### ISSUE TITLE
After login there is blank page with background color

### ISSUE THREAD

**Issue by cwchristerw** [mastodon/mastodon#10169]
I made test account that should show what I mean
tootctl accounts create test --email spam@cwinfo.net --confirmed

EMAIL: spam@cwinfo.net
PASSWORD: 21e51909a73c2a2098aa3fa5c1776836
https://mastodon.cwinfo.org

NOT IF THIS IS RELATED TO MY PROBLEM
FROM Sidekiq Docker Logs
docker logs mastodon-sidekiq
```
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/logging.rb:42:in `with_job_hash_context'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:124:in `dispatch'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:165:in `process'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:83:in `process_one'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:71:in `run'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:16:in `watchdog'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/util.rb:25:in `block in safe_thread'
2019-03-04T22:34:13.617Z 6 TID-gratghb16 BootstrapTimelineWorker JID-7203966168f7523c0a58e6e2 INFO: fail: 1.028 sec
2019-03-04T22:34:13.617Z 6 TID-gratghb16 WARN: {"context":"Job raised exception","job":{"class":"BootstrapTimelineWorker","args":[1],"retry":true,"queue":"default","jid":"7203966168f7523c0a58e6e2","created_at":1550062488.4661975,"enqueued_at":1551738852.5885026,"error_message":"ActiveRecord::RecordNotFound","error_class":"ActiveRecord::RecordNotFound","failed_at":1550062653.8337111,"retry_count":8,"retried_at":1550276774.7719498},"jobstr":"{\"class\":\"BootstrapTimelineWorker\",\"args\":[1],\"retry\":true,\"queue\":\"default\",\"jid\":\"7203966168f7523c0a58e6e2\",\"created_at\":1550062488.4661975,\"enqueued_at\":1551738852.5885026,\"error_message\":\"ActiveRecord::RecordNotFound\",\"error_class\":\"ActiveRecord::RecordNotFound\",\"failed_at\":1550062653.8337111,\"retry_count\":8,\"retried_at\":1550276774.7719498}"}
2019-03-04T22:34:13.617Z 6 TID-gratghb16 WARN: ActiveRecord::RecordNotFound: ActiveRecord::RecordNotFound
2019-03-04T22:34:13.617Z 6 TID-gratghb16 WARN: /mastodon/app/services/follow_service.rb:12:in `call'
/mastodon/app/services/bootstrap_timeline_service.rb:20:in `block in autofollow_bootstrap_timeline_accounts!'
/mastodon/app/services/bootstrap_timeline_service.rb:19:in `each'
/mastodon/app/services/bootstrap_timeline_service.rb:19:in `autofollow_bootstrap_timeline_accounts!'
/mastodon/app/services/bootstrap_timeline_service.rb:8:in `call'
/mastodon/app/workers/bootstrap_timeline_worker.rb:7:in `perform'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:185:in `execute_job'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/processor.rb:167:in `block (2 levels) in process'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/mastodon/app/lib/sidekiq_error_handler.rb:5:in `call'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-5.2.5/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/mastodon/vendor/bundle/ruby/2.6.0/gems/sidekiq-unique-jobs-6.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:23:in `call'
```

**Comment by Gargron** [comment]
I'd check which accounts are configured to be auto-followed and which of them are mistyped.

**Comment by cwchristerw** [comment]
Created two admin users from command line after installing Docker container.

**Comment by cwchristerw** [comment]
Havent logged in with these users before making them admin
