### ISSUE TITLE
Install fails  - http_parser.rb

### ISSUE THREAD

**Issue by mahescho** [mastodon/mastodon#10270]
I'm on Debian 9, no Docker.

I followed this: https://docs.joinmastodon.org/administration/installation/ and while doing:

`bundle install  -j$(getconf _NPROCESSORS_ONLN) --deployment --without development test`

I get:

     Using http_parser.rb 0.6.1 from https://github.com/tmm1/http_parser.rb (at 54b17ba@54b17ba)
     /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:183: warning: conflicting chdir during another chdir block
     /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:191: warning: conflicting chdir during another chdir block
     Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
     
         current directory: /home/mastodon/live/vendor/bundle/ruby/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser
     /home/mastodon/.rbenv/versions/2.6.0/bin/ruby -I /home/mastodon/.rbenv/versions/2.6.0/lib/ruby/site_ruby/2.6.0 -r
     ./siteconf20190314-4307-1occw9k.rb extconf.rb
     *** extconf.rb failed ***
     Could not create Makefile due to some reason, probably lack of necessary
     libraries and/or headers.  Check the mkmf.log file for more details.  You may
     need configuration options.
     
     Provided configuration options:
     	--with-opt-dir
     	--without-opt-dir
     	--with-opt-include
     	--without-opt-include=${opt-dir}/include
     	--with-opt-lib
     	--without-opt-lib=${opt-dir}/lib
     	--with-make-prog
     	--without-make-prog
     	--srcdir=.
     	--curdir
     	--ruby=/home/mastodon/.rbenv/versions/2.6.0/bin/$(RUBY_BASE_NAME)
     extconf.rb:17:in `read': No such file or directory @ rb_sysopen -
     /home/mastodon/live/vendor/bundle/ruby/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8/ext/ruby_http_parser/vendor/http-parser/http_parser.c
     (Errno::ENOENT)
     	from extconf.rb:17:in `block (2 levels) in <main>'
     	from extconf.rb:16:in `open'
     	from extconf.rb:16:in `block in <main>'
     	from extconf.rb:15:in `each'
     	from extconf.rb:15:in `<main>'
     
     extconf failed, exit code 1
     
     Gem files will remain installed in /home/mastodon/live/vendor/bundle/ruby/2.6.0/bundler/gems/http_parser.rb-54b17ba8c7d8 for inspection.
     Results logged to
     /home/mastodon/live/vendor/bundle/ruby/2.6.0/bundler/gems/extensions/x86_64-linux/2.6.0-static/http_parser.rb-54b17ba8c7d8/gem_make.out
     
     An error occurred while installing http_parser.rb (0.6.1), and Bundler cannot continue.
     
     
     In Gemfile:
       goldfinger was resolved to 2.1.0, which depends on
         http was resolved to 3.3.0, which depends on
           http_parser.rb

How to fix this?

TIA

**Comment by mahescho** [comment]
Duplicate of this issue:

https://github.com/tootsuite/mastodon/issues/7607

Why can't git just use HTTPS ?
