### ISSUE TITLE
docker-compose elasticsearch failed to start

### ISSUE THREAD

**Issue by thiras** [mastodon/mastodon#14482]
### Expected behaviour

Get elasticsearch up and running

### Actual behaviour

Crashes at the start

### Steps to reproduce the problem

Uncomment related elasticsearch lines at the `docker-compose.yml`

### Specifications

Mastodon 3.2.0

### Error log

Error log uses 6.8.11 but it throws exact same error on 6.8.10 too.

```
es_1         | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
es_1         | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
es_1         |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
es_1         |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
es_1         |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
es_1         |  at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
es_1         |  at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
es_1         |  at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]
es_1         |  at java.nio.file.Files.createDirectories(Files.java:787) ~[?:?]
es_1         |  at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  ... 6 more
es_1         | [2020-08-01T12:07:25,043][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]                                                                        
es_1         | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment                                                                                   
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                      
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                   
es_1         |  at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                      
es_1         |  at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.11.jar:6.8.11]                                                                                
es_1         |  at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.11.jar:6.8.11]                                                                                                     
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                      
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                       
es_1         | Caused by: java.lang.IllegalStateException: Failed to create node environment
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                          
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                             
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                              
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                      
es_1         |  ... 6 more
es_1         | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
es_1         |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
es_1         |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
es_1         |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
es_1         |  at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]                                                                                                      
es_1         |  at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
es_1         |  at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]
es_1         |  at java.nio.file.Files.createDirectories(Files.java:787) ~[?:?]
es_1         |  at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                
es_1         |  at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                             
es_1         |  at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                      
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.11.jar:6.8.11]
es_1         |  at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                          
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                             
es_1         |  at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                              
es_1         |  at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.11.jar:6.8.11]                                                                                      
es_1         |  ... 6 more
```

**Comment by shleeable** [comment]
You might need to investigate the UID/GID that runs locally vs inside the container.
might be worth trying to chmod 777 the folder and seeing if it's getting access denied after it mounted internally.
