### ISSUE TITLE
500 Internal Server Error: Using malformed token to access API endpoints

### ISSUE THREAD

**Issue by vatlidak** [mastodon/mastodon#14528]
500 Internal Server Error when using a malformed token to access API endpoints. Ideally, the controller's library should have been able to recover from such invalid characters.

### Expected behavior
400 Bad Request

### Actual behavior
500 Internal Server Error

### Steps to reproduce the problem
```
echo -e 'Authorization: Bearer [FILTERED_PART]_2ds_\xfeSsS_[FILTERED_PART]' | curl -v  --insecure -H @- -H "Content-Type: application/json" -X 'GET' 'https://localhost/api/v1/accounts/search?q=100anothe&resolve=true&following=true'
```

### Specifications
Version 3.1.1 running on local Ubuntu deployment.

### Stack traces
```
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] method=GET path=/api/v1/accounts/search format=*/* controller=Api::V1::Accounts::SearchController action=show status=500 error='ActiveRecord::StatementInvalid: PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xfe
Aug 08 11:42:40 server2-1 bundle[5102]: : SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2' duration=2.33 view=0.00 db=0.68
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433]
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] ActiveRecord::StatementInvalid (PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xfe
Aug 08 11:42:40 server2-1 bundle[5102]: : SELECT  "oauth_access_tokens".* FROM "oauth_access_tokens" WHERE "oauth_access_tokens"."token" = $1 LIMIT $2):
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433]
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] app/controllers/api/base_controller.rb:78:in `current_resource_owner'
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] app/controllers/api/base_controller.rb:82:in `current_user'
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] app/controllers/concerns/user_tracking_concern.rb:20:in `user_needs_sign_in_update?'
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] app/controllers/concerns/user_tracking_concern.rb:15:in `set_user_activity'
Aug 08 11:42:40 server2-1 bundle[5102]: [d32b3468-52ba-4cf2-b038-ff51c19b6433] app/middleware/handle_bad_encoding_middleware.rb:16:in `call'
```

### Comments

This bug was found using REST API fuzzing.

**Comment by mjankowski** [comment]
I think this can be closed for same reasons as https://github.com/mastodon/mastodon/issues/14533#issuecomment-1561700899

**Comment by ThisIsMissEm** [comment]
I believe this is now fixed, as I'm unable to reproduce it (mastodon returns a 401 for me on 4.2 / main), though, I'd suspect this would actually be a vulnerability in Doorkeeper if it exists still: https://github.com/doorkeeper-gem/doorkeeper/

cc @vmstan
