### ISSUE TITLE
500 Internal Server Error: Creating account with malformed email address

### ISSUE THREAD

**Issue by vatlidak** [mastodon/mastodon#14529]
500 Internal Server Error when creating a fresh mastodon account with malformed email address. Ideally, the controller's library should have been able to recover from such invalid characters.

### Expected behavior
400 Bad Request

### Actual behavior
500 Internal Server Error

### Steps to reproduce the problem
```
% echo -e '{"username":"aff5196738b0439a8368dd4","email":"/api/v1/accoun\xe7s/relationships@mastodon.com","password":"anotherString","agreement":true,"locale":"fr"}' | curl -v  --insecure -H 'Authorization: Bearer [FILTERED]' -H "Content-Type: application/json" -X 'POST' 'https://localhost/api/v1/accounts' -d @- -H "Host: localhost" -H "Accept: */*"
```

### Specifications
Version 3.1.1 running on local Ubuntu deployment.

### Stack traces
```
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3] method=POST path=/api/v1/accounts format=*/* controller=Api::V1::AccountsController action=create status=500 error='ArgumentError: input string invalid' duration=84.59 view=0.00 db=1.29
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3]
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3] ArgumentError (input string invalid):
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3]
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3] app/services/app_sign_up_service.rb:10:in `call'
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3] app/controllers/api/v1/accounts_controller.rb:24:in `create'
Aug 08 16:56:54 server2-1 bundle[5102]: [e5b0cbcc-be25-49f2-9740-ba02e05509a3] app/middleware/handle_bad_encoding_middleware.rb:16:in `call'
```

### Comments

This bug was found using REST API fuzzing.

**Comment by mjankowski** [comment]
I think this can be closed for same reasons as https://github.com/mastodon/mastodon/issues/14533#issuecomment-1561700899

**Comment by mjankowski** [comment]
Confirmed, this is a 400 bad request on latest.
