### ISSUE TITLE
500 Internal Server Error: Creating list with malformed title

### ISSUE THREAD

**Issue by vatlidak** [mastodon/mastodon#14530]
500 Internal Server Error when creating a list with malformed title. Ideally, the controller's library should have been able to recover from such invalid characters.

### Expected behavior
400 Bad Request

### Actual behavior
500 Internal Server Error

### Steps to reproduce the problem
```
echo -e '{"title":"Authorizati\xden: Bearer "}' | curl -v  --insecure -H 'Authorization: Bearer [FILTERED]' -H "Content-Type: application/json" -X 'POST' 'https://localhost/api/v1/lists' -d @- -H "Host: localhost" -H "Accept: */*"

```

### Specifications
Version 3.1.1 running on local Ubuntu deployment.

### Stack traces
```
Aug 08 17:11:54 server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444] method=POST path=/api/v1/lists format=*/* controller=Api::V1::ListsController action=create status=500 error='ActiveRecord::StatementInvalid: PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xde 0x6e
Aug 08 17:11:54 server2-1 bundle[5102]: : INSERT INTO "lists" ("account_id", "title", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"' duration=17.32 view=0.00 db=2.72
Aug 08 17:11:54 server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444]
Aug 08 17:11:54 server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444] ActiveRecord::StatementInvalid (PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xde 0x6e
Aug 08 17:11:54 server2-1 bundle[5102]: : INSERT INTO "lists" ("account_id", "title", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"):
Aug 08 17:11:54 server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444]
Aug 08 17:11:54 vaggelis-server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444] app/controllers/api/v1/lists_controller.rb:20:in `create'
Aug 08 17:11:54 server2-1 bundle[5102]: [52ba93da-fbec-4496-8caa-bddba4696444] app/middleware/handle_bad_encoding_middleware.rb:16:in `call'
```

### Comments

This bug was found using REST API fuzzing.

**Comment by mjankowski** [comment]
I think this can be closed for same reasons as https://github.com/mastodon/mastodon/issues/14533#issuecomment-1561700899
