### ISSUE TITLE
500 Internal Server Error: Post status update with malformed content

### ISSUE THREAD

**Issue by vatlidak** [mastodon/mastodon#14533]
500 Internal Server Error when posting a status update with malformed content

### Expected behavior
400 Bad Request

### Actual behavior
500 Internal Server Error

### Steps to reproduce the problem
```
echo -e '{"status":"ss\xf3anotherString","poll":{"options":["anotherString1","anotherString","cfrue"],"expires_in":1000}}' | curl -v  --insecure -H 'Authorization: Bearer [FILTERED]' -H "Content-Type: application/json" -X 'POST' 'https://localhost/api/v1/statuses' -d @- -H "Host: localhost" -H "Accept: */*"
```

### Specifications
Version 3.1.1 running on local Ubuntu deployment.

### Stack traces
```
Aug 08 17:30:01 server2-1 CRON[20847]: pam_unix(cron:session): session opened for user vatlidak by (uid=0)
Aug 08 17:30:01 server2-1 CRON[20846]: pam_unix(cron:session): session opened for user vatlidak by (uid=0)
Aug 08 17:30:01 server2-1 CRON[20848]: (vatlidak) CMD (touch /home/vatlidak/memory.txt)
Aug 08 17:30:01 server2-1 CRON[20849]: (vatlidak) CMD (free -mh >> /home/vatlidak/memory.txt)
Aug 08 17:30:01 server2-1 CRON[20847]: pam_unix(cron:session): session closed for user vatlidak
Aug 08 17:30:01 server2-1 CRON[20846]: pam_unix(cron:session): session closed for user vatlidak
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] method=POST path=/api/v1/statuses format=*/* controller=Api::V1::StatusesController action=create status=500 error='ArgumentError: invalid byte sequence in UTF-8' duration=33.42 view=0.00 db=2.65
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6]
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] ArgumentError (invalid byte sequence in UTF-8):
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6]
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/lib/language_detector.rb:89:in `remove_html'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/lib/language_detector.rb:69:in `simplify_text'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/lib/language_detector.rb:28:in `prepare_text'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/lib/language_detector.rb:14:in `detect'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/services/post_status_service.rb:161:in `status_attributes'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/services/post_status_service.rb:64:in `block in process_status!'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/services/post_status_service.rb:63:in `process_status!'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/services/post_status_service.rb:37:in `call'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/controllers/api/v1/statuses_controller.rb:37:in `create'
Aug 08 17:30:01 server2-1 bundle[5102]: [8197f7d7-2305-4956-804b-247e993d48d6] app/middleware/handle_bad_encoding_middleware.rb:16:in `call'
```

### Comments

This bug was found using REST API fuzzing.

**Comment by wildeng** [comment]
can this still be picked up?

**Comment by mjankowski** [comment]
I believe that in current Rails+Mastodon, this will result in an `ActionController::BadRequest` being raised, which Rails will catch and turn into a `400` http response.

If I'm misunderstanding, can you confirm that this is still an issue on current codebase, and if so, what mode you are running the server in to reproduce? (dev, test, production, etc)

Otherwise, this can probably be closed.
