### ISSUE TITLE
in Sidekiq 'pull' queue:  WARN: NameError: uninitialized constant Chewy::Strategy::CustomSidekiq::Worker

### ISSUE THREAD

**Issue by vincib** [mastodon/mastodon#15435]
### Expected behaviour

Sidekiq is launched on mamot.fr with multiple process for "default" queue, and a single process for the others (pull included) 

pull queue should treat all tasks properly

### Actual behaviour

sometimes (once every few seconds) sidekiq logs this (in the pull queue runner stderr) 

```
2020-12-27T09:21:46.683Z pid=96779 tid=3557 class=Chewy::Strategy::CustomSidekiq::Worker jid=55864a2c55588889e584daee INFO: start
2020-12-27T09:21:46.684Z pid=96779 tid=3557 class=Chewy::Strategy::CustomSidekiq::Worker jid=55864a2c55588889e584daee elapsed=0.001 INFO: fail
2020-12-27T09:21:46.683Z pid=96779 tid=32p3 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"pull","class":"Chewy::Strategy::CustomSidekiq::Worker","args":["StatusesIndex::Status",[101722820381080660]],"jid":"76dbc68cd123609a0bbb6289","created_at":1609060634.821905,"enqueued_at":1609060906.669719,"error_message":"uninitialized constant Chewy::Strategy::CustomSidekiq::Worker","error_class":"NameError","failed_at":1609060685.045495,"retry_count":2,"retried_at":1609060803.9283361},"jobstr":"{\"retry\":true,\"queue\":\"pull\",\"class\":\"Chewy::Strategy::CustomSidekiq::Worker\",\"args\":[\"StatusesIndex::Status\",[101722820381080660]],\"jid\":\"76dbc68cd123609a0bbb6289\",\"created_at\":1609060634.821905,\"enqueued_at\":1609060906.669719,\"error_message\":\"uninitialized constant Chewy::Strategy::CustomSidekiq::Worker\",\"error_class\":\"NameError\",\"failed_at\":1609060685.045495,\"retry_count\":2,\"retried_at\":1609060803.9283361}"}
2020-12-27T09:21:46.696Z pid=96779 tid=32p3 WARN: NameError: uninitialized constant Chewy::Strategy::CustomSidekiq::Worker
2020-12-27T09:21:46.696Z pid=96779 tid=3557 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"pull","class":"Chewy::Strategy::CustomSidekiq::Worker","args":["StatusesIndex::Status",[102910326623453500]],"jid":"55864a2c55588889e584daee","created_at":1609060639.1426873,"enqueued_at":1609060906.6709468,"error_message":"uninitialized constant Chewy::Strategy::CustomSidekiq::Worker","error_class":"NameError","failed_at":1609060686.1249163,"retry_count":2,"retried_at":1609060786.1044376},"jobstr":"{\"retry\":true,\"queue\":\"pull\",\"class\":\"Chewy::Strategy::CustomSidekiq::Worker\",\"args\":[\"StatusesIndex::Status\",[102910326623453500]],\"jid\":\"55864a2c55588889e584daee\",\"created_at\":1609060639.1426873,\"enqueued_at\":1609060906.6709468,\"error_message\":\"uninitialized constant Chewy::Strategy::CustomSidekiq::Worker\",\"error_class\":\"NameError\",\"failed_at\":1609060686.1249163,\"retry_count\":2,\"retried_at\":1609060786.1044376}"}
2020-12-27T09:21:46.696Z pid=96779 tid=32p3 WARN: /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:276:in `const_get'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:276:in `block in constantize'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:273:in `each'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:273:in `inject'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:273:in `constantize'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:132:in `block (5 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:14:in `block in call'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:73:in `block in wrap'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/execution_wrapper.rb:87:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/reloader.rb:72:in `wrap'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/rails.rb:13:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:257:in `stats'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:13:in `call'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_retry.rb:78:in `global'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/logger.rb:10:in `with'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/job_logger.rb:33:in `prepare'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:123:in `dispatch'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:162:in `process'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:78:in `process_one'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/processor.rb:68:in `run'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:15:in `watchdog'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.1.2/lib/sidekiq/util.rb:24:in `block in safe_thread'

```

### Steps to reproduce the problem

no idea, but we just upgraded from 3.2.0 to 3.3.0 when this happened.

### Specifications

mastodon v3.3.0, non docker, using ruby 2.7.2 via rbenv, nodejs 10.16.3, postgresql 9.6 and elasticsearch 6.8.12, debian stretch

**Comment by vincib** [comment]
I just found that the db:migrate post-restart was not entirely finished when we had those issues (I thought it was, sorry)

If it's likely due to that, feel free to delete this bug. Sorry.

(I don't see any new error in the "pull" queue worker now)

**Comment by JamesABDL** [comment]
I'm seeing the same, but did the pre / post migrations and restarted all processes in between. Seeing a few hundred thousand failed jobs now in Sidekiq and the same error as @vincib above

**Comment by JamesABDL** [comment]
I dumped everything in the pull and retry queue, was getting into the millions. Not seeing the error now, will check again in a hour

**Comment by ThibG** [comment]
Alright, pretty sure what's happening here is that #15387 dropped `Chewy::Strategy::CustomSidekiq::Worker` (we're using Chewy's stock one now), but there were jobs enqueued with it, meaning that after restarting sidekiq, those jobs wouldn't be able to be processed anymore.

This is an issue, as those jobs will clog the sidekiq queues, and will fail to update the ElasticSearch indexes… however, this will only be an issue with those jobs enqueued before the upgrade, anything after that will be fine.
