### ISSUE TITLE
"This page could not be displayed correctly"

### ISSUE THREAD

**Issue by cheeplusplus** [mastodon/mastodon#16530]
### Expected behaviour

Feed should have loaded

### Actual behaviour

Page crash

### Steps to reproduce the problem

1. Log in
2. View logged-in Mastodon feed (https://mastodon.social/web/getting-started)

Clearing site data and logging in again just shows error page again

### Specifications

Site was mastodon.social (live)

Error message:
```
Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.

Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.
```

Stacktrace from "copy stacktrace to clipboard":
```
TypeError: Cannot read property 'split' of null


TypeError: Cannot read property 'split' of null
    at f (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:296746)
    at https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:297282
    at https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:56296
    at jt.__iterate (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:50251)
    at o.Jt.r.__iterateUncached (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:56254)
    at fe (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:30837)
    at o.X.__iterate (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:29505)
    at o.toArray (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:74381)
    at jt [as constructor] (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:48368)
    at mn (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:62302)


split (webpack:///app/javascript/mastodon/components/attachment_list.js:7:28)
render (webpack:///app/javascript/mastodon/components/attachment_list.js:28:101)
iterable.__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:3155:25)
fn (webpack:///node_modules/immutable/dist/immutable.js:2266:10)
iterable.__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:3154:22)
fn (webpack:///node_modules/immutable/dist/immutable.js:590:15)
__iterate (webpack:///node_modules/immutable/dist/immutable.js:310:11)
this.valueSeq().__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:4547:22)
assertNotInfinite (webpack:///node_modules/immutable/dist/immutable.js:2114:59)
reify (webpack:///node_modules/immutable/dist/immutable.js:3804:36)
```

**Comment by ztauras** [comment]
Same bug only when loading notification panel, two different browsers same result

TypeError: Cannot read property 'split' of null


TypeError: Cannot read property 'split' of null
    at f (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:296746)
    at https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:297282
    at https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:56296
    at jt.__iterate (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:50251)
    at o.Jt.r.__iterateUncached (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:56254)
    at fe (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:30837)
    at o.X.__iterate (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:29505)
    at o.toArray (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:74381)
    at jt [as constructor] (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:48368)
    at mn (https://static-cdn.mastodon.social/packs/js/common-905928709a5e32e5a9d2.js:2:62302)


split (webpack:///app/javascript/mastodon/components/attachment_list.js:7:28)
render (webpack:///app/javascript/mastodon/components/attachment_list.js:28:101)
iterable.__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:3155:25)
fn (webpack:///node_modules/immutable/dist/immutable.js:2266:10)
iterable.__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:3154:22)
fn (webpack:///node_modules/immutable/dist/immutable.js:590:15)
__iterate (webpack:///node_modules/immutable/dist/immutable.js:310:11)
this.valueSeq().__iterate(function (webpack:///node_modules/immutable/dist/immutable.js:4547:22)
assertNotInfinite (webpack:///node_modules/immutable/dist/immutable.js:2114:59)
reify (webpack:///node_modules/immutable/dist/immutable.js:3804:36)

**Comment by ClearlyClaire** [comment]
This seems to occur because some status has an attachment with neither a `remote_url` nor a `url`. The fact that there's no `remote_url` means it's a local status, and for `url` to be null, it has to be marked as not processed… but I don't understand how a local media attachment could be attached to a status and not processed…

**Comment by cheeplusplus** [comment]
I've posted using Amaroq before, but the web interface was working fine, I posted something, then it stopped a bit after. It's still broken even now, so I suspect it's something in my notifications column.

**Comment by ClearlyClaire** [comment]
@cheeplusplus yes it is definitely from the notifications column, and it's a toot that contains media attachments that for some reason weren't processed. I have a hunch the iOS app may allow posting toots with media that have not been processed and that might explain it.

I'll write a fix for the crash itself.
