### ISSUE TITLE
Can't run configurator

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#16642]
### Expected behaviour

Should have run

### Actual behaviour

Error

### Steps to reproduce the problem

1. Follow install instructions up to `RAILS_ENV=production bundle exec rake mastodon:setup`
```
zotsocial@t1c:~/live$ RAILS_ENV=production bundle exec rake mastodon:setup

rake aborted!
LoadError: /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.so
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `require'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `require'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `block in <top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:44:in `rescue in with_gems'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:40:in `with_gems'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `require_relative'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `require_relative'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `<top (required)>'
/home/zotsocial/live/config/boot.rb:9:in `require'
/home/zotsocial/live/config/boot.rb:9:in `<top (required)>'
/home/zotsocial/live/config/application.rb:1:in `require_relative'
/home/zotsocial/live/config/application.rb:1:in `<top (required)>'
/home/zotsocial/live/Rakefile:4:in `require'
/home/zotsocial/live/Rakefile:4:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'

Caused by:
LoadError: /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.so
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `require'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `require'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `block in <top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `require_relative'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `require_relative'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `<top (required)>'
/home/zotsocial/live/config/boot.rb:9:in `require'
/home/zotsocial/live/config/boot.rb:9:in `<top (required)>'
/home/zotsocial/live/config/application.rb:1:in `require_relative'
/home/zotsocial/live/config/application.rb:1:in `<top (required)>'
/home/zotsocial/live/Rakefile:4:in `require'
/home/zotsocial/live/Rakefile:4:in `<top (required)>'
/home/zotsocial/live/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

### Specifications

Ubutnu 20.04 server

**Comment by ClearlyClaire** [comment]
I suppose you're not running out of memory? If not, it seems like it could be related to #15751

**Comment by ThatOneCalculator** [comment]
> I suppose you're not running out of memory? If not, it seems like it could be related to #15751

Plenty of memory to spare, Ill check that out
