### ISSUE TITLE
db:migrate fails with Mail::Field::IncompleteParseError on update to 3.4.1 in docker

### ISSUE THREAD

**Issue by thelarsh** [mastodon/mastodon#16672]
### Expected behaviour

the database migration should have ended without an error

### Actual behaviour

The database migration fails with a Mail::Field::IncompleteParseError

### Steps to reproduce the problem

1. when running: "docker-compose run --rm mastodon-web rails db:migrate", it generates this output:

```
Starting mastodon_mastodon-db_1    ... done
Starting mastodon_mastodon-redis_1 ... done
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/opt/ruby/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
rails aborted!
Mail::Field::IncompleteParseError: Mail::AddressList can not parse |'Mastodon <webmaster@mydomain.com>'|: Only able to parse up to "'Mastodon <webmaster@mydomain.com>"
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/parsers/address_lists_parser.rb:33230:in `parse'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/elements/address.rb:192:in `parse'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/elements/address.rb:30:in `initialize'
/opt/mastodon/config/environments/production.rb:94:in `new'
/opt/mastodon/config/environments/production.rb:94:in `block in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/railtie.rb:234:in `instance_eval'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/railtie.rb:234:in `configure'
/opt/mastodon/config/environments/production.rb:1:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:570:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/engine.rb:570:in `block in <class:Engine>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:32:in `run'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:384:in `initialize!'
/opt/mastodon/config/environment.rb:5:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:360:in `require_environment!'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/application.rb:526:in `block in run_tasks_blocks'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:281:in `execute'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:241:in `invoke_prerequisites'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/task.rb:188:in `invoke'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:160:in `invoke_task'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `each'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:116:in `block in top_level'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:125:in `run_with_threads'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:110:in `top_level'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/rake-13.0.3/lib/rake/rake_module.rb:59:in `with_application'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/command.rb:52:in `invoke'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/railties-6.1.3.2/lib/rails/commands.rb:18:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `block in require'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/dependencies.rb:332:in `require'
/opt/mastodon/bin/rails:4:in `<main>'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

### Specifications

docker-compose version 1.21.1, build 5a3f1a3
mastodon 3.4.1

**Comment by ClearlyClaire** [comment]
Can you give us the value of `SMTP_FROM_ADDRESS` in your `.env.production`?

**Comment by thelarsh** [comment]
Hi ClearyClaire,
this is in my  .env.production :
SMTP_FROM_ADDRESS='Mastodon <webmaster@mydomain.com>'

**Comment by ClearlyClaire** [comment]
I'm sorry, there has to be a typo or something in the real email address that you've fixed by changing it to `mydomain.com`…

**Comment by thelarsh** [comment]
Hi, I just checked and double checked the output from "docker-compose run --rm mastodon-web rails db:migrate" against the SMTP_FROM_ADDRESS in my .env.production but they are exactly the same.

One thing that I do notice is that the final single quote in the error is missing:
Mail::Field::IncompleteParseError: Mail::AddressList can not parse |'Mastodon <webmaster@zomaareenfeestje.org>'|: Only able to parse up to "'Mastodon <webmaster@zomaareenfeestje.org>"

**Comment by thelarsh** [comment]
Hi, I just checked and double checked the output from "docker-compose run --rm mastodon-web rails db:migrate" against the SMTP_FROM_ADDRESS in my .env.production but they are exactly the same.

One thing that I do notice is that the final single quote in the error is missing:
Mail::Field::IncompleteParseError: Mail::AddressList can not parse |'Mastodon webmaster@mydomain.com'|: Only able to parse up to "'Mastodon webmaster@mydomain.com"

**Comment by ClearlyClaire** [comment]
I'm sorry, but I really can't reproduce it, and I doubt your domain name is textually “mydomain.com”, which is why I suppose your issue is caused by the real, unedited value for `SMTP_FROM_ADDRESS` in your `.env.production` file, without anonymization. Unfortunately I'm not sure how to help you further without that real value.

**Comment by thelarsh** [comment]
OK... Here it is unedited... It is a webserver anyway....
unedited value for SMTP_FROM_ADDRESS in my .env.production file:
SMTP_FROM_ADDRESS='Mastodon <webmaster@zomaareenfeestje.org>'

and unedited error in the "docker-compose run --rm mastodon-web rails db:migrate" output:
Mail::Field::IncompleteParseError: Mail::AddressList can not parse |'Mastodon <webmaster@zomaareenfeestje.org>'|: Only able to parse up to "'Mastodon <webmaster@zomaareenfeestje.org>"

**Comment by ClearlyClaire** [comment]
Hmmm… still can't reproduce the issue… is that the `.env.production` line verbatim (is there only one `SMTP_FROM_ADDRESS` line)? or does the line look like `SMTP_FROM_ADDRESS="'Mastodon <webmaster@zomaareenfeestje.org>'"`?

Can you open a Rails console (`RAILS_ENV=production bundle exec rails c`) and check the output of `ENV.fetch('SMTP_FROM_ADDRESS', 'notifications@localhost')`?

**Comment by thelarsh** [comment]
Hi ClearlyClaire,
thanx for the effort so far ! To answer your questions:

There is only one SMTP_FROM_ADDRESS line in the .env.production and it has a single quotes around the address.

How do I open a Rails console ? I'm using a docker image...

**Comment by ClearlyClaire** [comment]
I think `docker-compose run --rm web rails c` is what you'd need to do to open a Rails console

**Comment by thelarsh** [comment]
I just found the problem... I looked closer at the .env.production file and noticed that none of the other entries have quotes.
I removed the single quotes around the mail address and... voila ! The migration ran without errors.
Thank you for your assistance ClearlyClaire !
