### ISSUE TITLE
Error when upload image

### ISSUE THREAD

**Issue by mashirozx** [mastodon/mastodon#16822]
### Expected behaviour

upload image

### Actual behaviour

422 error in front end, sidekiq logs below

### Steps to reproduce the problem

```

Aws::S3::Errors::BadRequest - cannot copy media_attachments/files/107/059/687/400/645/910/original/d99d1134c7dbbb92.png to local file /tmp/2cdf61393d07d0bab7a66d8fc2423c6d20211007-7-c3rnrm.png,
[paperclip] Trying to link /tmp/2cdf61393d07d0bab7a66d8fc2423c6d20211007-7-c3rnrm.png to /tmp/2cdf61393d07d0bab7a66d8fc2423c6d20211007-7-kgb2uz.png,
Command :: file -b --mime '/tmp/2cdf61393d07d0bab7a66d8fc2423c6d20211007-7-kgb2uz.png',
[paperclip] Content Type Spoof: Filename d99d1134c7dbbb92.png (image/png from Headers, ["image/png"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.,
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>,
2021-10-07T10:06:27.584Z pid=7 tid=4s3r class=PostProcessMediaWorker jid=bfce0295d100528d71ae9b1d elapsed=0.037 INFO: fail,
2021-10-07T10:06:27.584Z pid=7 tid=4s3r WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"class":"PostProcessMediaWorker","args":[107059687400645910],"jid":"bfce0295d100528d71ae9b1d","created_at":1633601187.5475914,"enqueued_at":1633601187.5476809},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"class\":\"PostProcessMediaWorker\",\"args\":[107059687400645910],\"jid\":\"bfce0295d100528d71ae9b1d\",\"created_at\":1633601187.5475914,\"enqueued_at\":1633601187.5476809}"},
2021-10-07T10:06:27.585Z pid=7 tid=4s3r WARN: NoMethodError: undefined method `start_with?' for nil:NilClass,
2021-10-07T10:06:27.585Z pid=7 tid=4s3r WARN: /opt/mastodon/vendor/bundle/ruby/2.7.0/gems/fastimage-2.2.5/lib/fastimage.rb:235:in `initialize',
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/fastimage-2.2.5/lib/fastimage.rb:140:in `size',
/opt/mastodon/vendor/bundle/ruby/2.7.0/gems/fastimage-2.2.5/lib/fastimage.rb:140:in `new',
[paperclip] copying media_attachments/files/107/059/687/400/645/910/original/d99d1134c7dbbb92.png to local file /tmp/2cdf61393d07d0bab7a66d8fc2423c6d20211007-7-c3rnrm.png,
2021-10-07T10:06:27.548Z pid=7 tid=4s3r class=PostProcessMediaWorker jid=bfce0295d100528d71ae9b1d INFO: start
```

### Specifications

Laste commit 900481b
Docker environment

**Comment by ClearlyClaire** [comment]
To process it?

**Comment by mashirozx** [comment]
Create a new toot, upload image attachment, it always fails. 
PS. The images from another sites checked successfully (remote media attachment download service works fine).

**Comment by mashirozx** [comment]
> To process it?

I think shouldn't it been processed locally and then upload to S3？😂

I seem something like handle thumbnail failure in front end's popup box 🤣

**Comment by mashirozx** [comment]
It's an old instance, problem occurs after switch from paperclip to kt-paperclip. Currently I've reverted the two commits about paperclip and it works fine now: https://github.com/mashirozx/mastodon/commits/main

**Comment by mashirozx** [comment]
> It is slightly surprising that the issue would occur with images but not video. I assume it's not a new instance, but the error is new?

Maybe it's just relevent to the image thumbnail as the error shows?
![image](https://user-images.githubusercontent.com/16148054/136640565-a5402b8d-5d10-4124-b279-2ba415bdfb43.png)

**Comment by ClearlyClaire** [comment]
Are you sure you properly applied the patch? I cannot reproduce this and can't understand how it could happen with the provided changes (it seems you removed the `Paperclip::Attachment.prepend(Paperclip::AttachmentExtensions)` line or something).

**Comment by ClearlyClaire** [comment]
> The logs below, let me know if something was missing.
> 
> ```
> Oct 10 18:51:25 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] [paperclip] Trying to link /tmp/RackMultipart20211010-3678160-16n9vj8.jpg to /tmp/8b830e20846a82fc8655baac0996e69520211010-3678160-n5dccn.jpg                      
> Oct 10 18:51:25 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] [paperclip] Trying to link /tmp/8b830e20846a82fc8655baac0996e69520211010-3678160-n5dccn.jpg to /tmp/8403a9cc9c131831f2d7d5298828bd2e20211010-3678160-1gf169m.jpg   
> Oct 10 18:51:25 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] Command :: file -b --mime '/tmp/8403a9cc9c131831f2d7d5298828bd2e20211010-3678160-1gf169m.jpg'                                                                      
> Oct 10 18:51:25 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] Command :: identify -format %m '/tmp/8b830e20846a82fc8655baac0996e69520211010-3678160-n5dccn.jpg[0]'                                                               
> Oct 10 18:51:25 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] Command :: convert '/tmp/8b830e20846a82fc8655baac0996e69520211010-3678160-n5dccn.jpg[0]' -auto-orient -resize "589x272>" -quality 90 -strip +set modify-date +set create-date '/tmp/2b570b8c34c1b57e4959f6e556b9030520211010-3678160-dyavtl'          
> Oct 10 18:51:26 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] Command :: convert '/tmp/2b570b8c34c1b57e4959f6e556b9030520211010-3678160-dyavtl' RGB:-                                                                            
> Oct 10 18:51:26 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] [paperclip] Trying to link /tmp/2b570b8c34c1b57e4959f6e556b9030520211010-3678160-dyavtl to /tmp/c92f7dc944241de2dc621adab4332a5c20211010-3678160-166ac0f           
> Oct 10 18:51:26 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] [paperclip] saving media_attachments/files/107/076/851/237/001/878/original/3bcf115c71b9a9a6.jpg                                                                   
> Oct 10 18:51:26 VM-0-7-ubuntu bundle[3678160]: [18bb82e2-d217-403f-a5a8-29cff0ba2b79] [paperclip] saving media_attachments/files/107/076/851/237/001/878/small/3bcf115c71b9a9a6.jpg
> ```

There should be lines with “copying media_attachments/[…]” and even the `Aws::S3::Errors::BadRequest` from earlier, that's what I'm interested in.

**Comment by mashirozx** [comment]
```
Oct 10 19:43:35 VM-0-7-ubuntu bundle[3706674]: [paperclip] Trying to link /tmp/215144d1765cb2f432afb33bd9b088cc20211010-3706674-autl7s.jpg to /tmp/215144d1765cb2f432afb33bd9b088cc20211010-3706674-75szms.jpg                                           
Oct 10 19:43:35 VM-0-7-ubuntu bundle[3706674]: Command :: file -b --mime '/tmp/215144d1765cb2f432afb33bd9b088cc20211010-3706674-75szms.jpg'                           
Oct 10 19:43:35 VM-0-7-ubuntu bundle[3706674]: Command :: identify -format %m '/tmp/215144d1765cb2f432afb33bd9b088cc20211010-3706674-autl7s.jpg[0]'                   
Oct 10 19:43:35 VM-0-7-ubuntu bundle[3706674]: Command :: convert '/tmp/215144d1765cb2f432afb33bd9b088cc20211010-3706674-autl7s.jpg[0]' -auto-orient -resize "2120x978>" -quality 90 -strip +set modify-date +set create-date '/tmp/86cfac260304b5a885e1b5742a562c3920211010-3706674-14ubusl'                                               
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.094Z pid=3706674 tid=2hqom class=ActivityPub::DeliveryWorker jid=5d9b3cc8400b4d4a10e7f7a1 INFO: start                                                                                 Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.098Z pid=3706674 tid=2hu5q class=ActivityPub::DeliveryWorker jid=d8478d86bfbaa0a4dfb31bce INFO: start                                                                                 
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.106Z pid=3706674 tid=2hqha class=ActivityPub::DeliveryWorker jid=8811899c860a448970558ebe INFO: start                                                                                 
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.138Z pid=3706674 tid=2htti class=ActivityPub::DeliveryWorker jid=18012b1be59072a906e3d977 INFO: start                                                                                 
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.140Z pid=3706674 tid=2htt6 class=ActivityPub::DeliveryWorker jid=9d7909abd65530d6e711ac1a INFO: start                                                                                 
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.145Z pid=3706674 tid=2htsu class=ActivityPub::DeliveryWorker jid=a57d3c99af5afbfa6636b65e INFO: start                                                                                 
Oct 10 19:43:36 VM-0-7-ubuntu bundle[3706674]: 2021-10-10T11:43:36.154Z pid=3706674 tid=2hu5q class=ActivityPub::DeliveryWorker jid=d8478d86bfbaa0a4dfb31bce elapsed=0.057 INFO: fail
```

**Comment by mashirozx** [comment]
Suspect it's my S3 provider's compatibility issue with `download_file` method, I'm now contacting their engineer

**Comment by ClearlyClaire** [comment]
Here are a few things to try out:
- revert to master and set `S3_REGION=ap-hongkong`
- revert to master, unset `S3_REGION`, and set `S3_SIGNATURE_VERSION=s3`
- revert to master, unset both `S3_REGION` and `S3_SIGNATURE_VERSION` and try with this patch:
```patch
diff --git a/lib/paperclip/attachment_extensions.rb b/lib/paperclip/attachment_extensions.rb
index 786f558e9..2fd34f566 100644
--- a/lib/paperclip/attachment_extensions.rb
+++ b/lib/paperclip/attachment_extensions.rb
@@ -90,6 +90,20 @@ module Paperclip
       end.run
     end
   end
+
+
+  module Storage
+    module S3Extensions
+      def copy_to_local_file(style, local_dest_path)
+        log("copying #{path(style)} to local file #{local_dest_path}")
+        s3_object(style).download_file(local_dest_path, { mode: 'single_request' })
+      rescue Aws::Errors::ServiceError => e
+        warn("#{e} - cannot copy #{path(style)} to local file #{local_dest_path}")
+        false
+      end
+    end
+  end
 end
 
 Paperclip::Attachment.prepend(Paperclip::AttachmentExtensions)
+Paperclip::Storage::S3.prepend(Paperclip::Storage::S3Extensions)
```

**Comment by ClearlyClaire** [comment]
The other changes did not do anything then?

**Comment by ClearlyClaire** [comment]
Alright… this is annoying, but I guess we will have to add code like this to support some S3-compatible services that do not handle that API…

**Comment by mashirozx** [comment]
Yes, I think so...

**Comment by fuomag9** [comment]
I confirm that adding `S3_FORCE_SINGLE_REQUEST` with `minio` as an s3 provider did indeed fix my issue. Maybe setting it as a default value with the autoconfig would be a good idea?

**Comment by rasos** [comment]
I had the problem the other way round on a k8s deployment with S3 on an extra minio server: image upload worked, but not video. Setting 

` S3_FORCE_SINGLE_REQUEST: "true"`

fixed the video upload.  That should be mentioned in the docs https://docs.joinmastodon.org/admin/optional/object-storage/#minio
