### ISSUE TITLE
Attempting to migrate DB to upgrade results in error.

### ISSUE THREAD

**Issue by ThatOneCalculator** [mastodon/mastodon#17017]
### Expected behaviour

RAILS_ENV=production bundle exec rails db:migrate should work

### Actual behaviour

It failed, spouting an error.

### Steps to reproduce the problem

1. `git fetch && git checkout v3.4.3`
2. `bundle install && yarn install`
3. `RAILS_ENV=production bundle exec rails db:migrate`
```
Traceback (most recent call last):
	13: from bin/rails:3:in `<main>'
	12: from bin/rails:3:in `require_relative'
	11: from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
	10: from /home/mastodon/live/config/boot.rb:9:in `require'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `<top (required)>'
	 8: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `require_relative'
	 7: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `<top (required)>'
	 6: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `require_relative'
	 5: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `<top (required)>'
	 4: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
	 3: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `block in <top (required)>'
	 2: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `require'
	 1: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.so (LoadError)
	14: from bin/rails:3:in `<main>'
	13: from bin/rails:3:in `require_relative'
	12: from /home/mastodon/live/config/boot.rb:9:in `<top (required)>'
	11: from /home/mastodon/live/config/boot.rb:9:in `require'
	10: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `<top (required)>'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap.rb:5:in `require_relative'
	 8: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `<top (required)>'
	 7: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache.rb:74:in `require_relative'
	 6: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `<top (required)>'
	 5: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:40:in `with_gems'
	 4: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/explicit_require.rb:44:in `rescue in with_gems'
	 3: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `block in <top (required)>'
	 2: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.6.0/lib/bootsnap/load_path_cache/store.rb:4:in `require'
	 1: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack.rb:8:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/msgpack-1.4.2/lib/msgpack/msgpack.so (LoadError)
```

### Specifications

Current ver is v3.4.1, not in Docker.

**Comment by ClearlyClaire** [comment]
Not an issue with Mastodon itself but something is wrong with the Ruby installation. Try the following:
1. `export LD_PRELOAD=/lib/x86_64-linux-gnu/libjemalloc.so.2` (there being an issue with libjemalloc makes me think of #15751)
2. `bundle install --force`
3. `RAILS_ENV=production bundle exec rails db:migrate` again

If this helps, you might need to add `LD_PRELOAD=/lib/x86_64-linux-gnu/libjemalloc.so.2` to the systemd service files (`/etc/systemd/system/mastodon-sidekiq.service` and `/etc/systemd/system/mastodon-web.service`).

I guess it's also possible, though unlikely, that you are simply running out of RAM?

**Comment by ThatOneCalculator** [comment]
Got stuck on step 2... [Log](https://ghostbin.com/loROr)

**Comment by ClearlyClaire** [comment]
Do you have `ruby2.7-dev` installed?

**Comment by ThatOneCalculator** [comment]
Sorry for the late reply, but that fixed it! Not sure why it wasn't installed earlier... anyways, thank you for the help!
