### ISSUE TITLE
Can't suspend users with + sign in their email address

### ISSUE THREAD

**Issue by rodti** [mastodon/mastodon#17033]
### Expected behaviour

Suspending a user with + sign in their email address leads to suspension of their account

### Actual behaviour

Suspending a user with + sign in their email address produces an error

### Steps to reproduce the problem

1. Encounter account with + sign in registered email address that requires moderation
2. Use Moderation > Accounts interface to choose account, and select 'Suspend'
3. Operation fails with 'We're sorry, but something went wrong on our end.' error
4. Account is not suspended.

### Specifications

Mastodon v3.4.3

This has been tried on multiple spam accounts, all with + in their email address (for example user+string@domain.tld), and all produce the same behaviour. Other spam accounts from the same IP but without + in the email address are suspended as expected.

**Comment by ClearlyClaire** [comment]
I am unable to reproduce this issue. Do you have server-side error logs? (`journalctl -u mastodon-web`)

**Comment by rodti** [comment]
This is the error produced for this activity:

```
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 12:03:08 mas bundle[257034]: ):
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8]
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/models/admin/account_action.rb:82:in `process_warning!'
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/models/admin/account_action.rb:34:in `save!'
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 12:03:08 mas bundle[257034]: [08b919fe-0f62-41ba-922a-5d7059c366d8] app/controllers/concerns/localized.rb:15:in `set_locale'
```

**Comment by rodti** [comment]
Interestingly, if I try to suspend the same user but untick 'Notify the user per e-mail' nothing happens. I get bounced back to the account screen, the user is not suspended, no error is produced.

**Comment by ClearlyClaire** [comment]
Are there errors in the log before this one?

**Comment by rodti** [comment]
Apologies for the dump, but here are all the more recent logs. Anything before that is from more than four hours ago, well before I tried to suspend these accounts:

```
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406]
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 11:21:48 mas bundle[257034]: ):
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406]
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/models/admin/account_action.rb:168:in `warning_preset'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/models/admin/account_action.rb:134:in `text_for_warning'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/models/admin/account_action.rb:85:in `process_warning!'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/models/admin/account_action.rb:34:in `save!'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 11:21:48 mas bundle[257034]: [719a2b6c-19ee-4488-8c4d-481754ce3406] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f]
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 11:22:10 mas bundle[257034]: ):
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f]
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/models/admin/account_action.rb:168:in `warning_preset'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/models/admin/account_action.rb:134:in `text_for_warning'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/models/admin/account_action.rb:85:in `process_warning!'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/models/admin/account_action.rb:34:in `save!'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 11:22:10 mas bundle[257034]: [3db60971-43c7-40a3-864a-3b5e4462430f] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def]
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 11:23:18 mas bundle[257034]: ):
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def]
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/models/admin/account_action.rb:168:in `warning_preset'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/models/admin/account_action.rb:134:in `text_for_warning'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/models/admin/account_action.rb:85:in `process_warning!'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/models/admin/account_action.rb:34:in `save!'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 11:23:18 mas bundle[257034]: [0bd9bfea-67fa-49ae-843c-7c6c26258def] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486]
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 11:23:24 mas bundle[257034]: ):
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486]
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/models/admin/account_action.rb:168:in `warning_preset'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/models/admin/account_action.rb:134:in `text_for_warning'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/models/admin/account_action.rb:85:in `process_warning!'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/models/admin/account_action.rb:34:in `save!'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 11:23:24 mas bundle[257034]: [4cabb26e-ce67-459b-b663-dfc4fbbdb486] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674]
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 12:02:21 mas bundle[257034]: ):
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674]
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/models/admin/account_action.rb:168:in `warning_preset'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/models/admin/account_action.rb:134:in `text_for_warning'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/models/admin/account_action.rb:85:in `process_warning!'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/models/admin/account_action.rb:34:in `save!'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 12:02:21 mas bundle[257034]: [9c931b83-71e2-4946-a504-5d8fb88f8674] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3]
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 12:02:26 mas bundle[257034]: ):
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3]
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/models/admin/account_action.rb:82:in `process_warning!'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/models/admin/account_action.rb:34:in `save!'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 12:02:26 mas bundle[257034]: [48585c71-4842-471a-885b-2cf616a26fe3] app/controllers/concerns/localized.rb:15:in `set_locale'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439]
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] ActiveRecord::StatementInvalid (PG::InFailedSqlTransaction: ERROR:  current transaction is aborted, commands ignored until end of transaction block
Nov 24 12:03:01 mas bundle[257034]: ):
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439]
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/models/admin/account_action.rb:82:in `process_warning!'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/models/admin/account_action.rb:36:in `block in save!'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/models/admin/account_action.rb:34:in `save!'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/controllers/admin/account_actions_controller.rb:17:in `create'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/controllers/concerns/localized.rb:16:in `block in set_locale'
Nov 24 12:03:01 mas bundle[257034]: [037083a8-9cfb-4d11-a358-eebb135ee439] app/controllers/concerns/localized.rb:15:in `set_locale'
```

**Comment by ClearlyClaire** [comment]
ok, I'm able to reproduce it, gonna try to fix it now

**Comment by ClearlyClaire** [comment]
@rodti #17036 should address your issue
