### ISSUE TITLE
Error fetching preview card

### ISSUE THREAD

**Issue by mashirozx** [mastodon/mastodon#17061]
### Steps to reproduce the problem

1. Post a took with a Github link who has og tags.

Sidekiq log:

```
^[[36msidekiq_1    |^[[0m 2021-11-26T15:20:50.329Z pid=8 tid=212uc class=LinkCrawlWorker jid=2bc30b24103f6ef56362b0b4 INFO: Adding dead LinkCrawlWorker job 2bc30b24103f6ef56362b0b4                
^[[36msidekiq_1    |^[[0m 2021-11-26T15:20:50.330Z pid=8 tid=212uc class=LinkCrawlWorker jid=2bc30b24103f6ef56362b0b4 elapsed=1.088 INFO: fail                                                      
^[[36msidekiq_1    |^[[0m 2021-11-26T15:20:50.331Z pid=8 tid=212uc WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"pull","class":"LinkCrawlWorker","args":[107344039066488505],"jid":"2bc30b24103f6ef56362b0b4","created_at":1637940049.2412744,"enqueued_at":1637940049.2418714},"jobstr":"{\"retry\":0,\"queue\":\"pull\",\"class\":\"LinkCrawlWorker\",\"args\":[107344039066488505],\"jid\":\"2bc30b24103f6ef56362b0b4\",\"created_at\":1637940049.2412744,\"enqueued_at\":1637940049.2418714}"}                                                                                      
^[[36msidekiq_1    |^[[0m 2021-11-26T15:20:50.331Z pid=8 tid=212uc WARN: ActiveModel::UnknownAttributeError: unknown attribute 'language' for PreviewCard.                                          
^[[36msidekiq_1    |^[[0m 2021-11-26T15:20:50.331Z pid=8 tid=212uc WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.4.1/lib/active_model/attribute_assignment.rb:51:in `_assign_attribute'                                                                                           
^[[36msidekiq_1    |^[[0m /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/attribute_assignment.rb:21:in `block in _assign_attributes'                            
^[[36msidekiq_1    |^[[0m /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.4.1/lib/active_record/attribute_assignment.rb:13:in `each'
```

### Expected behaviour

See a preview card

### Actual behaviour

Errors as above

### Specifications

12b3ff6c6d70df1ce34f4b103b519250c9e2d2c8

**Comment by ClearlyClaire** [comment]
Did you run the database migrations?

**Comment by mashirozx** [comment]
yeah
![IMG_20211127_005435](https://user-images.githubusercontent.com/16148054/143612323-5217437f-7526-4a5c-b60b-a81834a9424d.jpg)

**Comment by ClearlyClaire** [comment]
Did you restart the sidekiq processes after migrating the database? :thinking:

**Comment by mashirozx** [comment]
Oh, works after restarting, thanks
