### ISSUE TITLE
Bundler::GemNotFound occur when build docker in v3.4.4 

### ISSUE THREAD

**Issue by yuangezhizao** [mastodon/mastodon#17246]
### Steps to reproduce the problem

I checkout tag v3.4.4, and try to build docker image by Github Actions, but it seems occur GemNotFound.
I have spent two days in my spare time to trouble shooting, include using different CI/CD providers or update "Gemfile" and "Gemfile.lock" from the latest main branch, but it still build failed.
I really don't know how to solve it, anyone who knows? Sorry for bothering :)

P.S. I use v3.4.4 docker image in production environment, but needs to do custom modify so could not use out of the box docker image from Docker Hub

### Expected behaviour

docker build success

### Actual behaviour

docker build failed

### Specifications

```
#18 1.820 /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/definition.rb:489:in `materialize': Could not find pkg-config-1.4.6, puma-5.3.2, rails-6.1.3.2, sprockets-3.7.2, thor-1.1.0, rack-2.2.3, hamlit-rails-0.2.3, pg-1.2.3, makara-0.5.0, pghero-2.8.1, dotenv-rails-2.7.6, aws-sdk-s3-1.95.1, fog-core-2.1.0, fog-openstack-0.3.10, paperclip-6.0.0, blurhash-0.1.5, active_model_serializers-0.10.12, addressable-2.7.0, bootsnap-1.6.0, browser-4.2.0, charlock_holmes-0.7.7, iso-639-0.3.5, chewy-5.2.0, cld3-3.4.2, devise-4.8.0, devise-two-factor-4.0.0, net-ldap-0.17.0, omniauth-cas-2.0.0, omniauth-saml-1.10.3, omniauth-1.9.1, omniauth-rails_csrf_protection-0.1.2, color_diff-0.1, discard-1.2.0, doorkeeper-5.5.1, ed25519-1.2.4, fast_blank-1.0.0, fastimage-2.2.3, hiredis-0.6.3, redis-namespace-1.8.1, htmlentities-4.3.4, http-4.4.1, http_accept_language-2.1.1, httplog-1.5.0, idn-ruby-0.1.0, kaminari-1.2.1, link_header-0.0.8, mime-types-3.3.1, nokogiri-1.11.6, nsa-0.2.8, oj-3.11.5, ox-2.14.4, parslet-2.0.0, parallel-1.20.1, posix-spawn-0.3.15, pundit-2.1.0, premailer-rails-1.11.1, rack-attack-6.5.0, rack-cors-1.1.1, rails-i18n-6.0.0, rails-settings-cached-0.6.6, redis-4.2.5, mario-redis-lock-1.2.1, rqrcode-2.0.0, ruby-progressbar-1.11.0, sanitize-5.2.3, scenic-1.5.4, sidekiq-6.2.1, sidekiq-scheduler-3.0.1, sidekiq-unique-jobs-7.0.11, sidekiq-bulk-0.2.0, simple-navigation-4.3.0, simple_form-5.1.0, sprockets-rails-3.2.2, stoplight-2.2.1, strong_migrations-0.7.6, tty-prompt-0.23.1, twitter-text-3.1.0, tzinfo-data-1.2021.1, webpacker-5.4.0, webpush-0.3.8, webauthn-3.0.0.alpha1, json-ld-3.1.9, json-ld-preloaded-3.1.5, rdf-normalize-0.4.0, private_address_check-0.5.0, lograge-0.11.2, concurrent-ruby-1.1.8, connection_pool-2.2.5, xorcist-1.1.2, resolv-0.1.0, nio4r-2.5.7, actioncable-6.1.3.2, actionmailbox-6.1.3.2, actionmailer-6.1.3.2, actionpack-6.1.3.2, actiontext-6.1.3.2, actionview-6.1.3.2, activejob-6.1.3.2, activemodel-6.1.3.2, activerecord-6.1.3.2, activestorage-6.1.3.2, activesupport-6.1.3.2, railties-6.1.3.2, hamlit-2.13.0, dotenv-2.7.6, aws-sdk-core-3.114.0, aws-sdk-kms-1.43.0, aws-sigv4-1.2.3, builder-3.2.4, excon-0.76.0, formatador-0.2.5, fog-json-1.2.0, ipaddress-0.8.3, mimemagic-0.3.10, terrapin-0.6.0, ffi-1.15.0, case_transform-0.2, jsonapi-renderer-0.2.2, public_suffix-4.0.6, msgpack-1.4.2, elasticsearch-7.10.1, elasticsearch-dsl-0.1.9, bcrypt-3.1.16, orm_adapter-0.5.0, responders-3.0.1, warden-1.2.9, attr_encrypted-3.1.0, rotp-6.2.0, ruby-saml-1.11.0, hashie-4.1.0, http-cookie-1.0.3, http-form_data-2.3.0, http-parser-1.2.1, rainbow-3.0.0, kaminari-actionview-1.2.1, kaminari-activerecord-1.2.1, kaminari-core-1.2.1, mime-types-data-3.2020.0512, mini_portile2-2.5.2, racc-1.5.2, statsd-ruby-1.5.0, premailer-1.14.2, i18n-1.8.10, chunky_png-1.4.0, rqrcode_core-1.0.0, crass-1.0.6, nokogumbo-2.0.4, e2mmap-0.1.0, rufus-scheduler-3.6.0, thwait-0.2.0, tilt-2.0.10, brpoplpush-redis_script-0.1.2, pastel-0.8.0, tty-reader-0.9.0, unf-0.1.4, tzinfo-2.0.4, rack-proxy-0.6.5, semantic_range-3.0.0, hkdf-0.3.0, jwt-2.2.2, android_key_attestation-0.3.0, awrence-1.1.1, bindata-2.4.8, cbor-0.5.9.6, cose-1.0.0, openssl-2.2.0, safety_net_attestation-0.4.0, securecompare-1.0.0, tpm-key_attestation-0.9.0, json-canonicalization-0.2.1, multi_json-1.15.0, rdf-3.1.13, request_store-1.5.0, websocket-driver-0.7.3, mail-2.7.1, rails-dom-testing-2.0.3, rack-test-1.1.0, rails-html-sanitizer-1.3.0, erubi-1.10.0, globalid-0.4.2, marcel-1.0.1, mini_mime-1.0.3, minitest-5.14.4, zeitwerk-2.4.2, method_source-1.0.0, rake-13.0.3, temple-0.8.2, aws-eventstream-1.1.1, aws-partitions-1.465.0, jmespath-1.4.0, climate_control-0.2.0, elasticsearch-api-7.10.1, elasticsearch-transport-7.10.1, encryptor-3.0.0, domain_name-0.5.20190701, ffi-compiler-1.0.1, net-ftp-0.1.2, css_parser-1.7.1, fugit-1.3.9, tty-color-0.6.0, tty-cursor-0.7.1, tty-screen-0.8.1, wisper-2.0.1, unf_ext-0.0.7.7, openssl-signature_algorithm-0.4.0, hamster-3.0.0, websocket-extensions-0.1.5, loofah-2.9.1, faraday-1.3.0, net-protocol-0.1.0, time-0.1.0, et-orbi-1.2.4, raabro-1.3.3, faraday-net_http-1.0.1, multipart-post-2.1.1, ruby2_keywords-0.0.4 in any of the sources (Bundler::GemNotFound)
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/definition.rb:190:in `specs'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/definition.rb:238:in `specs_for'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/runtime.rb:18:in `setup'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler.rb:151:in `setup'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/ui/shell.rb:136:in `with_level'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/ui/shell.rb:88:in `silence'
#18 1.820 	from /opt/ruby/lib/ruby/gems/2.7.0/gems/bundler-2.3.4/lib/bundler/setup.rb:20:in `<top (required)>'
#18 1.820 	from /opt/ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
#18 1.820 	from /opt/ruby/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
#18 1.820 	from /opt/mastodon/config/boot.rb:8:in `<top (required)>'
#18 1.820 	from /opt/mastodon/bin/rails:3:in `require_relative'
#18 1.820 	from /opt/mastodon/bin/rails:3:in `<main>'
#18 ERROR: process "/bin/bash -o pipefail -c cd ~ && \tOTP_SECRET=precompile_placeholder SECRET_KEY_BASE=precompile_placeholder rails assets:precompile && \tyarn cache clean" did not complete successfully: exit code: 1
```

**Comment by EqualMa** [comment]
I found the reason is that `bundler`'s latest version has changed.

To fix this issue, just change `	gem install bundler && \` to 
```
gem install bundler -v 2.1.4 && \
```
in `Dockerfile`

**Comment by yuangezhizao** [comment]
> I found the reason is that `bundler`'s latest version has changed.
> 
> To fix this issue, just change ` gem install bundler && \` to
> 
> ```
> gem install bundler -v 2.1.4 && \
> ```
> 
> in `Dockerfile`

Thank you for your reply, but i used another way to fix this issue.

mastodon#17188，just add `--local` in `Dockerfile` really works.

By the way, it was resolved when reviewing the commit history on the third day.
