### ISSUE TITLE
Can't render profile after upgrading to v3.4.4 (ActionView::Template::Error)

### ISSUE THREAD

**Issue by sneak** [mastodon/mastodon#17263]
### Steps to reproduce the problem

upgraded dockerized server to v3.4.4.  Emptied cache and migrated database.

Single user-instance, now throws an error when loading the single user's profile:

```
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] method=GET path=/@arh format=html controller=AccountsController action=show status=500 error='ActionView::Template::Error: No route matches {:action=>"show", :controller=>"media", :id=>#<MediaAttachment status_id: 107565804198589103, file_file_name: "b6cc4094ca78e33d.jpg", file_content_type: "image/jpeg", file_file_size: 96493, file_updated_at: "2022-01-04 19:18:29.976377000 +0000", remote_url: "", created_at: "2022-01-04 19:18:30.950496000 +0000", updated_at: "2022-01-04 19:18:36.619189000 +0000", shortcode: nil, type: "image", file_meta: {"original"=>{"width"=>620, "height"=>700, "size"=>"620x700", "aspect"=>0.8857142857142857}, "small"=>{"width"=>376, "height"=>425, "size"=>"376x425", "aspect"=>0.8847058823529412}}, account_id: 107206281746114736, id: 107565803828243303, description: nil, scheduled_status_id: nil, blurhash: "ULIOhG~qj[9F4nM{xu%MWBD%Rjxu%M%MIURj", processing: "complete", file_storage_schema_version: 1, thumbnail_file_name: nil, thumbnail_content_type: nil, thumbnail_file_size: nil, thumbnail_updated_at: nil, thumbnail_remote_url: nil>}, possible unmatched constraints: [:id]
web_1        | Did you mean?  medium_path
web_1        |                medium_player_url
web_1        |                medium_player_path
web_1        |                api_v1_medium_url' duration=510.03 view=0.00 db=38.71
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] ActionView::Template::Error (No route matches {:action=>"show", :controller=>"media", :id=>#<MediaAttachment status_id: 107565804198589103, file_file_name: "b6cc4094ca78e33d.jpg", file_content_type: "image/jpeg", file_file_size: 96493, file_updated_at: "2022-01-04 19:18:29.976377000 +0000", remote_url: "", created_at: "2022-01-04 19:18:30.950496000 +0000", updated_at: "2022-01-04 19:18:36.619189000 +0000", shortcode: nil, type: "image", file_meta: {"original"=>{"width"=>620, "height"=>700, "size"=>"620x700", "aspect"=>0.8857142857142857}, "small"=>{"width"=>376, "height"=>425, "size"=>"376x425", "aspect"=>0.8847058823529412}}, account_id: 107206281746114736, id: 107565803828243303, description: nil, scheduled_status_id: nil, blurhash: "ULIOhG~qj[9F4nM{xu%MWBD%Rjxu%M%MIURj", processing: "complete", file_storage_schema_version: 1, thumbnail_file_name: nil, thumbnail_content_type: nil, thumbnail_file_size: nil, thumbnail_updated_at: nil, thumbnail_remote_url: nil>}, possible unmatched constraints: [:id]
web_1        | Did you mean?  medium_path
web_1        |                medium_player_url
web_1        |                medium_player_path
web_1        |                api_v1_medium_url):
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     40:     - elsif status.media_attachments.first.audio?
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     41:       = render_audio_component(status, width: 610, height: 343)
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     42:     - else
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     43:       = render_media_gallery_component(status, height: 343)
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     44:   - elsif status.preview_card
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     45:     = render_card_component(status)
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]     46:
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c]
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/serializers/rest/media_attachment_serializer.rb:43:in `text_url'
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/helpers/statuses_helper.rb:181:in `block in render_media_gallery_component'
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/helpers/statuses_helper.rb:181:in `map'
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/helpers/statuses_helper.rb:181:in `render_media_gallery_component'
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/views/statuses/_simple_status.html.haml:43
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/views/statuses/_status.html.haml:41
web_1        | [c25a9e00-0c52-4657-84e4-5a49e94c9e5c] app/views/accounts/show.html.haml:44

```

### Expected behaviour

not a 500, even if some file or record is missing

### Actual behaviour

500 server error

### Specifications

This is in the dockerized version tagged `v3.4.4`: 

https://hub.docker.com/layers/tootsuite/mastodon/v3.4.4/images/sha256-3c626cb9c4a9994cacf79aa268ef866909cd87338ffd1cf0b2f1717a920f534b?context=explore

**Comment by ClearlyClaire** [comment]
Did you accidentally switch to the development version before switching back to v3.4.4? If so, have a look at https://github.com/mastodon/mastodon/issues/16999#issuecomment-970742885

**Comment by mjankowski** [comment]
I think this was resolved by linked comment, but not auto-closed. Please reopen if still issue on 4.3
