### ISSUE TITLE
Elasticsearch v8

### ISSUE THREAD

**Issue by AnonymousWebHacker** [mastodon/mastodon#17537]
I was reading the documentation, and it uses v6 https://docs.joinmastodon.org/admin/optional/elasticsearch/#install
`deb https://artifacts.elastic.co/packages/6.x/apt stable main`

I decided to install from a deb package, in ubuntu 20.04 and install v 8 and it gave me this error
```
mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl search deploy
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Traceback (most recent call last):=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---|  ETA: ??:??:?? (0 docs/s)
	51: from bin/tootctl:8:in `<main>'
	50: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	49: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	48: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	47: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	46: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	45: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	44: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	43: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	42: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	41: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `deploy'
	40: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `select'
	39: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `block in deploy'
	38: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:56:in `changed?'
	37: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:37:in `locked'
	36: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:856:in `first'
	35: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:50:in `to_a'
	34: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:47:in `wrappers'
	33: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:115:in `response'
	32: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:979:in `perform'
	31: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
	30: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	29: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
	28: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:982:in `block in perform'
	27: from /home/mastodon/live/config/initializers/chewy.rb:41:in `search'
	26: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/search.rb:103:in `search'
	25: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
	24: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	23: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
	22: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
	21: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	20: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	19: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	18: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
	17: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	16: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	15: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
	14: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
	13: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:933:in `start'
	12: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:152:in `block in request_via_request_method'
	11: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:11:in `request'
	10: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:12:in `block in request'
	 8: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 7: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	 6: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	 5: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	 4: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	 3: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	 2: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	 1: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
	51: from bin/tootctl:8:in `<main>'
	50: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	49: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	48: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	47: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	46: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	45: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	44: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	43: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	42: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	41: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `deploy'
	40: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `select'
	39: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `block in deploy'
	38: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:56:in `changed?'
	37: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:37:in `locked'
	36: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:856:in `first'
	35: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:50:in `to_a'
	34: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:47:in `wrappers'
	33: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:115:in `response'
	32: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:979:in `perform'
	31: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
	30: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	29: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
	28: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:982:in `block in perform'
	27: from /home/mastodon/live/config/initializers/chewy.rb:41:in `search'
	26: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/search.rb:103:in `search'
	25: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
	24: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	23: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
	22: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:40:in `block in perform_request'
	21: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
	20: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
	19: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
	18: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
	17: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
	16: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
	15: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'
	14: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'
	13: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:933:in `start'
	12: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:152:in `block in request_via_request_method'
	11: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:11:in `request'
	10: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/benchmark.rb:308:in `realtime'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/httplog-1.5.0/lib/httplog/adapters/net_http.rb:12:in `block in request'
	 8: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	 7: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	 6: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	 5: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	 4: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	 3: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	 2: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	 1: from /home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (Faraday::ConnectionFailed)
```

My question, Mastodon is only compatible with v6 at the moment, or also with v8?

Anyway, I'm currently downloading v6 .

**Comment by ClearlyClaire** [comment]
For releases, v6 and v7 should be fine, as written in the release notes.

For `main`, v7 is needed.

**Comment by AnonymousWebHacker** [comment]
OS: Ubuntu Focal
mastodon: 3.4.6
yarn: 1.22.17
nodejs: 12
Elasticseach : 6

Step: `RAILS_ENV=production bin/tootctl search deploy`
URL DOC: https://docs.joinmastodon.org/admin/optional/elasticsearch/
```
mastodon@mastodon:~/live$ RAILS_ENV=production bin/tootctl search deploy
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:66: warning: previous definition of ProtocRetryError was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:206: warning: previous definition of BUFSIZE was here
/home/mastodon/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/net-protocol-0.1.0/lib/net/protocol.rb:503: warning: previous definition of Socket was here
Traceback (most recent call last):=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---=---|  ETA: ??:??:?? (0 docs/s)
	29: from bin/tootctl:8:in `<main>'
	28: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	27: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	26: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	25: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	24: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:243:in `block in subcommand'
	23: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:116:in `invoke'
	22: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	21: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	20: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	19: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `deploy'
	18: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `select'
	17: from /home/mastodon/live/lib/mastodon/search_cli.rb:50:in `block in deploy'
	16: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:56:in `changed?'
	15: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/index/specification.rb:37:in `locked'
	14: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:856:in `first'
	13: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:50:in `to_a'
	12: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:47:in `wrappers'
	11: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:115:in `response'
	10: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:979:in `perform'
	 9: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `instrument'
	 8: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	 7: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/activesupport-6.1.3.2/lib/active_support/notifications.rb:203:in `block in instrument'
	 6: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/chewy-5.2.0/lib/chewy/search/request.rb:982:in `block in perform'
	 5: from /home/mastodon/live/config/initializers/chewy.rb:41:in `search'
	 4: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.10.1/lib/elasticsearch/api/actions/search.rb:103:in `search'
	 3: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/client.rb:182:in `perform_request'
	 2: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	 1: from /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
/home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.10.1/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [400] {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/chewy_specifications/specification/_search] contains unrecognized parameter: [rest_total_hits_as_int]"}],"type":"illegal_argument_exception","reason":"request [/chewy_specifications/specification/_search] contains unrecognized parameter: [rest_total_hits_as_int]"},"status":400} (Elasticsearch::Transport::Transport::Errors::BadRequest)
```

**Comment by ClearlyClaire** [comment]
Are you using a release or `main`? Both will show 3.4.6 at the moment, but `main` requires ElasticSearch 7

**Comment by AnonymousWebHacker** [comment]
> ¿Estás usando una versión o `main`? Ambos mostrarán 3.4.6 en este momento, pero `main`requieren ElasticSearch 7



> Are you using a release or `main`? Both will show 3.4.6 at the moment, but `main` requires ElasticSearch 7

I just install using  https://docs.joinmastodon.org/admin/install/
```
git clone https://github.com/tootsuite/mastodon.git live && cd live
git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)
```
