### ISSUE TITLE
503 error when upload with S3

### ISSUE THREAD

**Issue by o3oicu** [mastodon/mastodon#17744]
### Steps to reproduce the problem

Upload any attachment would fail.

### Expected behaviour

image upload to s3

### Actual behaviour

503 error in front end

### Specifications

Here’s the log:
```
Mar 12 03:24:14 vmw54813 bundle[62225]: [paperclip] saving cache/media_attachments/files/107/941/190/316/391/916/original/90c4f2c6895d1734.jpeg
Mar 12 03:24:14 vmw54813 bundle[62225]: 2022-03-12T02:24:14.957Z pid=62225 tid=1xh9 class=DistributionWorker jid=e74c2d2803f1a591fadbbafe INFO: start
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.031Z pid=62225 tid=1etp class=ActivityPub::ProcessingWorker jid=2226cb8860b8502c8b4dfea8 elapsed=1.382 INFO: done
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.032Z pid=62225 tid=436t class=DistributionWorker jid=c9ad809a7472ce5f98717c6f INFO: start
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.034Z pid=62225 tid=1xh9 class=DistributionWorker jid=e74c2d2803f1a591fadbbafe elapsed=0.077 INFO: done
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.050Z pid=62225 tid=436t class=DistributionWorker jid=c9ad809a7472ce5f98717c6f elapsed=0.018 INFO: done
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.080Z pid=62225 tid=1w51 class=ActivityPub::ProcessingWorker jid=bddfc1676df70315914c5da4 elapsed=10.051 INFO: fail
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.080Z pid=62225 tid=1w51 WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"default","backtrace":true,"class":"ActivityPub::Process>Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.080Z pid=62225 tid=1w51 WARN: Mastodon::RaceConditionError: Mastodon::RaceConditionError
Mar 12 03:24:15 vmw54813 bundle[62225]: 2022-03-12T02:24:15.080Z pid=62225 tid=1w51 WARN: /home/mastodon/live/app/lib/activitypub/activity.rb:224:in `block in lock_or_fail'
Mar 12 03:24:15 vmw54813 bundle[62225]: /home/mastodon/live/vendor/bundle/ruby/2.7.0/gems/mario-redis-lock-1.2.1/lib/redis_lock.rb:49:in `acquire'
Mar 12 03:24:15 vmw54813 bundle[62225]: /home/mastodon/live/app/lib/activitypub/activity.rb:220:in `lock_or_fail'
```

s3 configuration here:
```
S3_ENABLED=true
S3_BUCKET=media
AWS_ACCESS_KEY_ID=*******
AWS_SECRET_ACCESS_KEY=******
S3_PROTOCOL=https
S3_REGION=fr-par
S3_HOSTNAME=s3.fr-par.scw.cloud
S3_ENDPOINT=https://s3.fr-par.scw.cloud
```
v3.4.6

It seems not only upload attachments failed, but all images fail to load or upload to s3.

**Comment by Gargron** [comment]
This is not the frontend log and there are no S3-related errors in it

**Comment by o3oicu** [comment]
```
Mar 12 04:03:08 vmw54813 bundle[64573]: [407c9f1a-1c4e-4a37-8ed5-162d63552da7] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=50.02 view=0.0>Mar 12 04:03:09 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] [paperclip] Trying to link /tmp/RackMultipart20220312-64573-11kqg99.png to /tmp/7311d6205dca665c4ad37c87ea7280f820220312-64573>Mar 12 04:03:09 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] [paperclip] Trying to link /tmp/7311d6205dca665c4ad37c87ea7280f820220312-64573-1890q8m.png to /tmp/a351a321ba539d2eb93e70e2ac3>Mar 12 04:03:09 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] Command :: file -b --mime '/tmp/a351a321ba539d2eb93e70e2ac30137f20220312-64573-tw83t0.png'
Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] Command :: identify -format %m '/tmp/7311d6205dca665c4ad37c87ea7280f820220312-64573-1890q8m.png[0]'
Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] Command :: convert '/tmp/7311d6205dca665c4ad37c87ea7280f820220312-64573-1890q8m.png[0]' -auto-orient -resize "400x400>" -quali>Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] Command :: convert '/tmp/6d5fa3cfafd33101fa19d5fb6028106c20220312-64573-xq4ayl' RGB:-
Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] [paperclip] Trying to link /tmp/6d5fa3cfafd33101fa19d5fb6028106c20220312-64573-xq4ayl to /tmp/36cdeec809f003d30c6efc21bcec161c>Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] [paperclip] Trying to link /tmp/7311d6205dca665c4ad37c87ea7280f820220312-64573-1890q8m.png to /tmp/a351a321ba539d2eb93e70e2ac3>Mar 12 04:03:10 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] Command :: file -b --mime '/tmp/a351a321ba539d2eb93e70e2ac30137f20220312-64573-1ik26w8.png'
Mar 12 04:03:11 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] [paperclip] saving media_attachments/files/107/941/343/454/772/667/original/2933f794dd9d1041.png
Mar 12 04:03:13 vmw54813 bundle[64573]: [1b56d151-670c-4f2c-ada8-aac86c8e7b99] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=32.42 view=0.0>Mar 12 04:03:16 vmw54813 bundle[64573]: [03bff26c-9fad-40c6-93a4-9515ea078884] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=503 duration=6331.36 view=>
```

**Comment by Gargron** [comment]
There is no error stacktrace so this is a 503 error returned by the S3 service itself.

**Comment by o3oicu** [comment]
I have tried uploading cache directly with aws after closing s3 and it is possible to upload. But I can't upload directly with front end in mastodon. Do you have any suggestions for a possible solution?

**Comment by o3oicu** [comment]
It seems that the problem occurred because s3 was not synchronized with the host. After asking the provider to rebuild the index and metadata the problem solved.

**Comment by twoheartliu** [comment]
@o3oicu sorry, how to [ the provider to rebuild the index and metadata ] ? I seem have the same problem.

**Comment by Gargron** [comment]
I guess you would need to contact their customer support and report the problem.
