### ISSUE TITLE
500 on admin API when filtering by `pending`

### ISSUE THREAD

**Issue by JamesABDL** [mastodon/mastodon#17870]
### Steps to reproduce the problem

HTTP GET to `/api/v1/admin/accounts?pending=True` with correct `admin:read:accounts` token.

### Expected behaviour

Should return a filtered list of pending approval accounts. As documented here: https://docs.joinmastodon.org/methods/admin/

### Actual behaviour

Returns no content and a 500 error

### Specifications

If you don't provide this query param it returns the normal un-filtered response.

This used to work fine on an older version (I think 3.3). Since upgrading to v3.4 this long running script has broken.

No combination of `pending`, `pending=True`, `pending=true`, `pending=1` works.

**Comment by JamesABDL** [comment]
Server logs:

```
[8560c577-4163-4f5c-8728-71c8b04c7fb6] method=GET path=/api/v1/admin/accounts format=*/* controller=Api::V1::Admin::AccountsController action=index status=500 error='RuntimeError: Unknown filter: pending' duration=3.27 view=0.00 db=0.55
[8560c577-4163-4f5c-8728-71c8b04c7fb6]
[8560c577-4163-4f5c-8728-71c8b04c7fb6] RuntimeError (Unknown filter: pending):
[8560c577-4163-4f5c-8728-71c8b04c7fb6]
[8560c577-4163-4f5c-8728-71c8b04c7fb6] app/models/account_filter.rb:60:in `scope_for'
[8560c577-4163-4f5c-8728-71c8b04c7fb6] app/models/account_filter.rb:29:in `block in results'
[8560c577-4163-4f5c-8728-71c8b04c7fb6] app/models/account_filter.rb:26:in `results'
[8560c577-4163-4f5c-8728-71c8b04c7fb6] app/controllers/api/v1/admin/accounts_controller.rb:107:in `filtered_accounts'
[8560c577-4163-4f5c-8728-71c8b04c7fb6] app/controllers/api/v1/admin/accounts_controller.rb:99:in `set_accounts'
```

**Comment by ClearlyClaire** [comment]
It appears it is an unwanted change from #17009 which changed the parameters for admin pages but did not update the admin API endpoints accordingly.
