### ISSUE TITLE
No Dashboard in v3.5.0

### ISSUE THREAD

**Issue by ingoj** [mastodon/mastodon#17924]
### Steps to reproduce the problem

Go to Setup -> Administration and there is no Dashboard anymore (it was in 3.4.7): 
![Bildschirmfoto 2022-03-31 um 16 04 06](https://user-images.githubusercontent.com/18173881/161139852-5f531357-6ab0-40c4-aa56-a7368bdc8090.png)

### Expected behaviour

working Dashboard ;)

### Actual behaviour

No Dashboard, no errors in log as far as I can tell... 

### Specifications

v3.5.0 non-docker with ruby 3.0.3
No dashboard with 2 different Admin accounts in 2 different browsers (FF & Chromium) on Mac OS

If I can provide some logs, please state how to do so. Thx!

**Comment by Gargron** [comment]
You likely missed the assets:precompile step

**Comment by ingoj** [comment]
Hmmm, according to my history file I did that step: 

```  992  git stash
  993  cd live
  994  git fetch && git checkout v3.5.0
  995  git stash
  996  git fetch && git checkout v3.5.0
  997  cd ~/.rbenv/plugins/ruby-build
  998  git pull
  999  RUBY_CONFIGURE_OPTS=--with-jemalloc rbenv install 3.0.3
 1000  cd ~/lice
 1001  cd ~/live
 1002  cat .ruby-version
 1003  bundle install
 1004  yarn install
 1005  yarn update
 1006  yarn upgrade
 1007  yarn install
 1008  yarn upgrade --latest
 1009  find .yarn/ iname yarn.lock
 1010  find .yarn/ -iname yarn.lock
 1011  find . -iname yarn.lock
 1012  mkdir ../live.bak
 1013  cp -a node_modules/ ../live.bak/
 1014  find ./node_modules/ -iname yarn.lock -exec rm {} \;
 1015  yarn install
 1016  yarn upgrade
 1017  yarn install @mastodon/mastodon
 1018  yarn install @mastodon
 1019  yarn install mastodon
 1020  yarn install
 1021  cp -a ../live.bak/node_modules/* node_modules/
 1022  yarn install
 1023  dir
 1024  ls -al
 1025  joe .nvmrc
 1026  yarn upgrade
 1027  yarn set version berry
 1028  yarn install
 1029  yarn upgrade
 1030  yarn install
 1031  cd live
 1032  yarn install
 1033  npm install --save emoji-mart
 1034  yarn install
 1035  yarn update
 1036  yarn upgrade
 1037  ls -l /home/mastodon/live/node_modules/humanize-ms/node_modules/ms
 1038  ls -l /home/mastodon/live/node_modules/humanize-ms/node_modules
 1039  ls -l /home/mastodon/live/node_modules/humanize-ms/
 1040  ls -l /home/mastodon/live/node_modules/
 1041  ls -l /home/mastodon/live/node_modules/human-signals/
 1042  yarn install
 1043  npm install --save humanize-ms
 1044  yarn install
 1045  npm install --save node-gyp
 1046  npm audit fix
 1047  yarn install
 1048  SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate
 1049  dir db/migrate/20 | grep RemoveUnused
 1050  dir db/migrate/20* | grep RemoveUnused
 1051  dir db/migrate/ | grep RemoveUnused
 1052  ls -l  db/migrate/20* | grep RemoveUnused
 1053  ls -l  db
 1054  ls -l  db/migrate/
 1055  ls -l  db/migrate/ | grep Unused
 1056  ls -l  db/migrate/ | grep -i Unused
 1057  rm db//migrate/20210725233041_remove_unused_indexes.rb
 1058  SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate
 1059  RAILS_ENV=production bundle exec rails assets:precompile
 1060  cd live
 1061  RAILS_ENV=production bin/tootctl cache clear
 1062  RAILS_ENV=production bundle exec rails db:migrate
 1063  joe live/.env.production
 1064  systemctl restart mastodon-web.service
 1065  joe live/.env.production
 1066  cd live
 1067  RAILS_ENV=production bin/tootctl cache clear
 1068  history | less```

See line/number 1059. But as you also can see I had to deal with some other stuff like needed to install some npm modules, because `yarn install` was giving me errors. After the installations and the removal of the older `db//migrate/20210725233041_remove_unused_indexes.rb` all errors were gone and only a ton auf warnings were left over.

**Comment by ingoj** [comment]
Here's the output from assets:precompile just executed again: 

```
mastodon@vserv1:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react-redux (p44d9c) with version 7.2.6, which doesn't satisfy what react-redux-loading-bar requests
➤ YN0002: │ react-swipeable-views-utils@npm:0.14.0 doesn't provide react (p74d53), requested by react-event-listener
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 1s 7ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 4s 35ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 5s 450ms
➤ YN0000: Done with warnings in 11s 90ms
Warning: you are using an unstable release of Node.js (v17.8.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Everything's up-to-date. Nothing to do
```

Hope that helps...

**Comment by ClearlyClaire** [comment]
It may have failed to compile the first time around, try `RAILS_ENV=production bundle exec rails assets:clobber && bundle exec rails assets:precompile`

**Comment by ingoj** [comment]
Ok, here is the output: 

```
mastodon@vserv1:~/live$ RAILS_ENV=production bundle exec rails assets:clobber
I, [2022-04-01T09:43:00.239750 #1409415]  INFO -- : Removed /home/mastodon/live/public/assets
Warning: you are using an unstable release of Node.js (v17.8.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Removed webpack output path directory /home/mastodon/live/public/packs
mastodon@vserv1:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react-redux (p44d9c) with version 7.2.6, which doesn't satisfy what react-redux-loading-bar requests
➤ YN0002: │ react-swipeable-views-utils@npm:0.14.0 doesn't provide react (p74d53), requested by react-event-listener
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 807ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 286ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 2s 549ms
➤ YN0000: Done with warnings in 4s 990ms
I, [2022-04-01T09:43:41.691041 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2022-04-01T09:43:41.691716 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2022-04-01T09:43:41.696919 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2022-04-01T09:43:41.697090 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2022-04-01T09:43:41.700438 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2022-04-01T09:43:41.715903 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2022-04-01T09:43:41.721136 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2022-04-01T09:43:41.731563 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2022-04-01T09:43:41.739465 #1413397]  INFO -- : Writing /home/mastodon/live/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Warning: you are using an unstable release of Node.js (v17.8.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Compiling...
Compilation failed:
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/mastodon/live/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/mastodon/live/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/mastodon/live/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/mastodon/live/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/mastodon/live/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/mastodon/live/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/mastodon/live/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/mastodon/live/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/mastodon/live/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/mastodon/live/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/mastodon/live/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.8.0

mastodon@vserv1:~/live$ 
```

**Comment by ClearlyClaire** [comment]
It seems that webpack could be using a hash algorithm with parameters that are no longer supported by OpenSSL 3.0.

As a workaround, either downgrade Node.js to the previous LTS, or set `export NODE_OPTIONS=--openssl-legacy-provider`

See https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported

**Comment by ClearlyClaire** [comment]
As for actually fixing the issue, we could either:
- use `sha256` instead of the default `md4` (probably significantly slower)
- update to a more recent version of webpack (not sure what the blockers for that are) and use `xxhash64`

**Comment by ingoj** [comment]
Ok, the first solution with export did work: 

```
mastodon@vserv1:~/live$ export NODE_OPTIONS=--openssl-legacy-provider
mastodon@vserv1:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @mastodon/mastodon@workspace:. provides react-redux (p44d9c) with version 7.2.6, which doesn't satisfy what react-redux-loading-bar requests
➤ YN0002: │ react-swipeable-views-utils@npm:0.14.0 doesn't provide react (p74d53), requested by react-event-listener
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 685ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 121ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 1s 920ms
➤ YN0000: Done with warnings in 4s 101ms
Warning: you are using an unstable release of Node.js (v17.8.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Compiling...
Compiled all packs in /home/mastodon/live/public/packs
```
... and after a restart of Mastodon the new Dashboard appeared now: 
![Bildschirmfoto 2022-04-01 um 17 21 36](https://user-images.githubusercontent.com/18173881/161293490-eb21be39-4468-4b4d-b5f1-6eae58f7030c.png)

Thanks for giving the pointers to fix it (temporarily)! :-)
