### ISSUE TITLE
Aws::S3::Errors::AccessControlListNotSupported with media uploading

### ISSUE THREAD

**Issue by everpcpc** [mastodon/mastodon#17978]
### Steps to reproduce the problem

1. use a s3 bucket with bucket owner enforced and ACLs disabled
2. check error log in sidekiq

### Expected behaviour

no errror

### Actual behaviour

error raised

### Specifications

```
[paperclip] Trying to link /tmp/ecdefcc8ed53a88723bfb0d40fcead3920220407-8-oglsak.jpeg to /tmp/00ff2bf852fe393ed6b144ba35acb84920220407-8-2b3dji.jpeg
Command :: file -b --mime '/tmp/00ff2bf852fe393ed6b144ba35acb84920220407-8-2b3dji.jpeg'
[paperclip] Trying to link /tmp/ecdefcc8ed53a88723bfb0d40fcead3920220407-8-oglsak.jpeg to /tmp/94321946b6334351809221ddcbab262c20220407-8-skc815.jpeg
Command :: identify -format %m '/tmp/94321946b6334351809221ddcbab262c20220407-8-skc815.jpeg[0]'
Command :: convert '/tmp/94321946b6334351809221ddcbab262c20220407-8-skc815.jpeg[0]' -auto-orient -resize "199x805>" -quality 90 -strip +set modify-date +set create-date '/tmp/8bb29737795c264a7358a681389c2caf20220407-8-vzojui'
Command :: convert '/tmp/8bb29737795c264a7358a681389c2caf20220407-8-vzojui' RGB:-
[paperclip] Trying to link /tmp/8bb29737795c264a7358a681389c2caf20220407-8-vzojui to /tmp/9cff3bf735a8b261d1dc0f571a95be5e20220407-8-w7im4d
[paperclip] saving cache/media_attachments/files/108/088/300/846/014/066/original/fa10103bbbd2d7b2.jpeg
2022-04-07T01:56:25.315Z pid=8 tid=2heo class=ActivityPub::ProcessingWorker jid=0457d6742c7a634edc5a574b elapsed=2.746 INFO: fail
2022-04-07T01:56:25.315Z pid=8 tid=2heo WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"default","backtrace":true,"args":[1768,"{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://m.cmx.im/users/hulifox/statuses/108088225641261334/activity\",\"type\":\"Announce\",\"actor\":\"https://m.cmx.im/users/hulifox\",\"published\":\"2022-04-07T01:37:15Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://mastodon.social/users/dearsadgirl\",\"https://m.cmx.im/users/hulifox/followers\"],\"object\":\"https://mastodon.social/users/dearsadgirl/statuses/108088021904664141\"}",null],"class":"ActivityPub::ProcessingWorker","jid":"0457d6742c7a634edc5a574b","created_at":1649295436.1555226,"enqueued_at":1649296582.5688381,"error_message":"The bucket does not allow ACLs","error_class":"Aws::S3::Errors::AccessControlListNotSupported","failed_at":1649295438.9123697,"retry_count":5,"error_backtrace":"eJy9z8EKwjAMBuBXkV282GZdhcFeRUS7NmhZ15akU3x7K4p69uAtJD98f3YN\npFxgNlySSxEuGF0iGJfoAgIt4w20bGULJ5wZzJUFu0nYRCi0VF1fL8GPwGjO\niRjBBo+xQA7LyUcGMp7xQMg5xTogUU1JGgfVDz6ujtaEsG42P5VgLZRUSr8q\nfNZvnStp8/Twuu0fPLeYwMXYp/j94f4OHq97NA==\n","retried_at":1649295930.1547594},"jobstr":"{\"retry\":8,\"queue\":\"default\",\"backtrace\":true,\"args\":[1768,\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://m.cmx.im/users/hulifox/statuses/108088225641261334/activity\\\",\\\"type\\\":\\\"Announce\\\",\\\"actor\\\":\\\"https://m.cmx.im/users/hulifox\\\",\\\"published\\\":\\\"2022-04-07T01:37:15Z\\\",\\\"to\\\":[\\\"https://www.w3.org/ns/activitystreams#Public\\\"],\\\"cc\\\":[\\\"https://mastodon.social/users/dearsadgirl\\\",\\\"https://m.cmx.im/users/hulifox/followers\\\"],\\\"object\\\":\\\"https://mastodon.social/users/dearsadgirl/statuses/108088021904664141\\\"}\",null],\"class\":\"ActivityPub::ProcessingWorker\",\"jid\":\"0457d6742c7a634edc5a574b\",\"created_at\":1649295436.1555226,\"enqueued_at\":1649296582.5688381,\"error_message\":\"The bucket does not allow ACLs\",\"error_class\":\"Aws::S3::Errors::AccessControlListNotSupported\",\"failed_at\":1649295438.9123697,\"retry_count\":5,\"error_backtrace\":\"eJy9z8EKwjAMBuBXkV282GZdhcFeRUS7NmhZ15akU3x7K4p69uAtJD98f3YN\\npFxgNlySSxEuGF0iGJfoAgIt4w20bGULJ5wZzJUFu0nYRCi0VF1fL8GPwGjO\\niRjBBo+xQA7LyUcGMp7xQMg5xTogUU1JGgfVDz6ujtaEsG42P5VgLZRUSr8q\\nfNZvnStp8/Twuu0fPLeYwMXYp/j94f4OHq97NA==\\n\",\"retried_at\":1649295930.1547594}"}
2022-04-07T01:56:25.315Z pid=8 tid=2heo WARN: Aws::S3::Errors::AccessControlListNotSupported: The bucket does not allow ACLs
2022-04-07T01:56:25.315Z pid=8 tid=2heo WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-core-3.127.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.113.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.113.0/lib/aws-sdk-s3/plugins/dualstack.rb:27:in `call'
```

**Comment by everpcpc** [comment]
also occurs when posting image on the web

```
[02e75ff4-0751-4b37-8202-2188dc0a87e3] [paperclip] Trying to link /tmp/RackMultipart20220407-9-sd8w6t.jpg to /tmp/ec22ee9c5ff178f6727db318e314260520220407-9-t8tnvn.jpg
[02e75ff4-0751-4b37-8202-2188dc0a87e3] [paperclip] Trying to link /tmp/ec22ee9c5ff178f6727db318e314260520220407-9-t8tnvn.jpg to /tmp/8e2e8f87dfc7de0c611c855fb9e44f2020220407-9-6lm23p.jpg
[02e75ff4-0751-4b37-8202-2188dc0a87e3] Command :: file -b --mime '/tmp/8e2e8f87dfc7de0c611c855fb9e44f2020220407-9-6lm23p.jpg'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] Command :: identify -format %m '/tmp/ec22ee9c5ff178f6727db318e314260520220407-9-t8tnvn.jpg[0]'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] Command :: convert '/tmp/ec22ee9c5ff178f6727db318e314260520220407-9-t8tnvn.jpg[0]' -auto-orient -resize "533x300>" -quality 90 -strip +set modify-date +set create-date '/tmp/bf58517553444abb541574b90c54d1bd20220407-9-sqfg4'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] Command :: convert '/tmp/bf58517553444abb541574b90c54d1bd20220407-9-sqfg4' RGB:-
[02e75ff4-0751-4b37-8202-2188dc0a87e3] [paperclip] Trying to link /tmp/bf58517553444abb541574b90c54d1bd20220407-9-sqfg4 to /tmp/99e25b71a51656cdba0c6cb7ed0bb87b20220407-9-sypsyp
[02e75ff4-0751-4b37-8202-2188dc0a87e3] [paperclip] saving media_attachments/files/108/088/727/359/314/311/original/511bec3b0a06271d.jpg
[02e75ff4-0751-4b37-8202-2188dc0a87e3] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 error='Aws::S3::Errors::AccessControlListNotSupported: The bucket does not allow ACLs' duration=2399.65 view=0.00 db=5.60
[02e75ff4-0751-4b37-8202-2188dc0a87e3]
[02e75ff4-0751-4b37-8202-2188dc0a87e3] Aws::S3::Errors::AccessControlListNotSupported (The bucket does not allow ACLs):
[02e75ff4-0751-4b37-8202-2188dc0a87e3]
[02e75ff4-0751-4b37-8202-2188dc0a87e3] lib/paperclip/attachment_extensions.rb:84:in `block in save'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] lib/paperclip/attachment_extensions.rb:90:in `save'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] app/controllers/api/v2/media_controller.rb:5:in `create'
[02e75ff4-0751-4b37-8202-2188dc0a87e3] app/controllers/concerns/localized.rb:11:in `set_locale'
```

**Comment by everpcpc** [comment]
It seems like a issue with paperclip.

**Comment by mjankowski** [comment]
This is very old, but -- did you ever sort this out?

**Comment by everpcpc** [comment]
Seems resolved.

**Comment by everpcpc** [comment]
Oh it's not, still errors
> 2024-12-05T00:54:55.378Z pid=7 tid=2puf class=ThreadResolveWorker jid=d7ea384d332195c2f79a860b elapsed=1.449 INFO: fail
2024-12-05T00:54:55.379Z pid=7 tid=2puf WARN: {"context":"Job raised exception","job":{"retry":3,"queue":"pull","args":[113590986802968989,"https://fedibird.com/users/yoshimi/statuses/113590985850722580",{"request_id":"1733360070-status-https://fedibird.com/users/yoshimi/statuses/113590986865729512"}],"class":"ThreadResolveWorker","jid":"d7ea384d332195c2f79a860b","created_at":1733360077.2029202,"enqueued_at":1733360093.92949,"error_message":"The bucket does not allow ACLs","error_class":"Aws::S3::Errors::AccessControlListNotSupported","failed_at":1733360078.3845696,"retry_count":0}}
2024-12-05T00:54:55.379Z pid=7 tid=2puf WARN: Aws::S3::Errors::AccessControlListNotSupported: The bucket does not allow ACLs

**Comment by everpcpc** [comment]
And another error
> 2024-12-05T01:01:46.202Z pid=7 tid=3shv WARN: Aws::S3::Errors::AccessDenied: User: arn:aws:sts::-:assumed-role/ec2-access-s3/i-- is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::-/cache/media_attachments/files/113/597/514/054/475/544/original/-.jpg" because public access control lists (ACLs) are blocked by the BlockPublicAcls block public access setting.
2024-12-05T01:01:46.202Z pid=7 tid=3shv WARN: /usr/local/bundle/gems/aws-sdk-core-3.209.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
/usr/local/bundle/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
/usr/local/bundle/gems/aws-sdk-s3-1.166.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'

**Comment by ClearlyClaire** [comment]
Does it not work if you set `S3_PERMISSION` to an empty value, as described in <https://docs.joinmastodon.org/admin/optional/object-storage/#cloudflare-r2>?

**Comment by everpcpc** [comment]
> Does it not work if you set `S3_PERMISSION` to an empty value, as described in https://docs.joinmastodon.org/admin/optional/object-storage/#cloudflare-r2?

Thanks, that seems working now.
