### ISSUE TITLE
This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile

### ISSUE THREAD

**Issue by Noirvent** [mastodon/mastodon#18107]
### Steps to reproduce the problem

I tried to install mastodon using this guide: https://docs.joinmastodon.org/admin/install/ on a fresh debian11 install.
Everything seems fine utile the setup phase which give me an error but still continue to the admin account creation.
Then I did the nginx & systemd parts, but when I try to open the page, I'm redirected to mastodon.mydomain.tld/about with a blank page.

journalctl -u mastodon-web give me the following error : 
```
Apr 26 17:26:10 isla-nublar bundle[1105]: [d1e5ebd6-9c52-416d-b785-298e65a2d6e7] method=GET path=/ format=html controller=HomeController action=index status=302 duration=4.16 view=0.00 location=https://mastodon.itopie.ch/about
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] method=GET path=/about format=html controller=AboutController action=show status=500 error='ActionView::Template::Error: Webpacker can't find media/images/preview.jpg in /home/mastodon/live/pu>
Apr 26 17:26:10 isla-nublar bundle[1105]: 1. You want to set webpacker.yml value of compile to true for your environment
Apr 26 17:26:10 isla-nublar bundle[1105]:    unless you are using the `webpack -w` or the webpack-dev-server.
Apr 26 17:26:10 isla-nublar bundle[1105]: 2. webpack has not yet re-run to reflect updates.
Apr 26 17:26:10 isla-nublar bundle[1105]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Apr 26 17:26:10 isla-nublar bundle[1105]: 4. Your webpack configuration is not creating a manifest.
Apr 26 17:26:10 isla-nublar bundle[1105]: Your manifest contains:
Apr 26 17:26:10 isla-nublar bundle[1105]: {
Apr 26 17:26:10 isla-nublar bundle[1105]: }
Apr 26 17:26:10 isla-nublar bundle[1105]: ' duration=9.30 view=0.00
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] ActionView::Template::Error (Webpacker can't find media/images/preview.jpg in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Apr 26 17:26:10 isla-nublar bundle[1105]: 1. You want to set webpacker.yml value of compile to true for your environment
Apr 26 17:26:10 isla-nublar bundle[1105]:    unless you are using the `webpack -w` or the webpack-dev-server.
Apr 26 17:26:10 isla-nublar bundle[1105]: 2. webpack has not yet re-run to reflect updates.
Apr 26 17:26:10 isla-nublar bundle[1105]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Apr 26 17:26:10 isla-nublar bundle[1105]: 4. Your webpack configuration is not creating a manifest.
Apr 26 17:26:10 isla-nublar bundle[1105]: Your manifest contains:
Apr 26 17:26:10 isla-nublar bundle[1105]: {
Apr 26 17:26:10 isla-nublar bundle[1105]: }
Apr 26 17:26:10 isla-nublar bundle[1105]: ):
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]      8: = opengraph 'og:type', 'website'
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]      9: = opengraph 'og:title', @instance_presenter.site_title
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]     10: = opengraph 'og:description', description
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]     11: = opengraph 'og:image', full_asset_url(thumbnail&.file&.url || asset_pack_path('media/images/preview.jpg', protocol: :request))
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]     12: = opengraph 'og:image:width', thumbnail ? thumbnail.meta['width'] : '1200'
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]     13: = opengraph 'og:image:height', thumbnail ? thumbnail.meta['height'] : '630'
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]     14: = opengraph 'twitter:card', 'summary_large_image'
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725]
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] app/views/shared/_og.html.haml:11
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] app/views/about/show.html.haml:6
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] app/views/about/show.html.haml:4
Apr 26 17:26:10 isla-nublar bundle[1105]: [fdc8e1ae-b03c-4ad5-9fc4-041b64bc8725] app/controllers/concerns/localized.rb:11:in `set_locale'
```
So after a bit of digging here and there on this repo, I tried to recompile the assets which give me another error : 
```
mastodon@isla-nublar:~/live$ RAILS_ENV=production bundle exec rails assets:precompile
➤ YN0000: ┌ Resolution step
➤ YN0032: │ bufferutil@npm:4.0.6: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ babel-eslint@npm:10.1.0 is deprecated: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
➤ YN0032: │ utf-8-validate@npm:5.0.9: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ babel-plugin-react-intl@npm:6.2.0 is deprecated: this package has been renamed to babel-plugin-formatjs
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ core-js@npm:2.6.11 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ intl-messageformat-parser@npm:4.1.4 is deprecated: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
➤ YN0061: │ intl-messageformat-parser@npm:1.4.0 is deprecated: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
➤ YN0061: │ intl-relativeformat@npm:2.2.0 is deprecated: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
➤ YN0061: │ source-map-resolve@npm:0.6.0 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ @formatjs/intl-unified-numberformat@npm:3.3.6 is deprecated: We have renamed the package to @formatjs/intl-numberformat
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0032: │ nan@npm:2.14.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ circular-json@npm:0.3.3 is deprecated: CircularJSON is in maintenance only, flatted is its successor.
➤ YN0061: │ source-map-url@npm:0.4.0 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ @formatjs/intl-utils@npm:2.2.5 is deprecated: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
➤ YN0001: │ Error: emoji-mart@npm:emoji-mart-lazyload: No candidates found
    at le (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:441:7865)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
➤ YN0000: └ Completed in 22s 646ms
➤ YN0000: Failed with errors in 22s 671ms
➤ YN0032: evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
Compiling...
Compilation failed:
Internal Error: @mastodon/mastodon@workspace:.: This package doesn't seem to be present in your lockfile; run "yarn install" to update the lockfile
    at tF.getCandidates (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:437:4480)
    at wd.getCandidates (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:395:1281)
    at /home/mastodon/.yarn/releases/yarn-3.2.0.cjs:441:7765
    at Pg (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:394:11098)
    at le (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:441:7745)
```
The I did yarn install as suggested (which was already done as per the guide):
```
mastodon@isla-nublar:~/live$ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0032: │ bufferutil@npm:4.0.6: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ babel-eslint@npm:10.1.0 is deprecated: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
➤ YN0032: │ utf-8-validate@npm:5.0.9: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ babel-plugin-react-intl@npm:6.2.0 is deprecated: this package has been renamed to babel-plugin-formatjs
➤ YN0061: │ core-js@npm:2.6.11 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ core-js@npm:2.6.12 is deprecated: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
➤ YN0061: │ resolve-url@npm:0.2.1 is deprecated: https://github.com/lydell/resolve-url#deprecated
➤ YN0061: │ uuid@npm:3.4.0 is deprecated: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
➤ YN0061: │ chokidar@npm:2.1.8 is deprecated: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
➤ YN0061: │ intl-messageformat-parser@npm:4.1.4 is deprecated: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
➤ YN0061: │ intl-messageformat-parser@npm:1.4.0 is deprecated: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
➤ YN0061: │ intl-relativeformat@npm:2.2.0 is deprecated: This package has been deprecated, please see migration guide at 'https://github.com/formatjs/formatjs/tree/master/packages/intl-relativeformat#migration-guide'
➤ YN0061: │ querystring@npm:0.2.0 is deprecated: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
➤ YN0032: │ fsevents@npm:2.3.2: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ fsevents@npm:1.2.13 is deprecated: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
➤ YN0061: │ source-map-resolve@npm:0.6.0 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ @formatjs/intl-unified-numberformat@npm:3.3.6 is deprecated: We have renamed the package to @formatjs/intl-numberformat
➤ YN0061: │ source-map-resolve@npm:0.5.3 is deprecated: See https://github.com/lydell/source-map-resolve#deprecated
➤ YN0061: │ svgo@npm:1.3.2 is deprecated: This SVGO version is no longer supported. Upgrade to v2.x.x.
➤ YN0061: │ circular-json@npm:0.3.3 is deprecated: CircularJSON is in maintenance only, flatted is its successor.
➤ YN0032: │ nan@npm:2.14.1: Implicit dependencies on node-gyp are discouraged
➤ YN0061: │ urix@npm:0.1.0 is deprecated: Please see https://github.com/lydell/urix#deprecated
➤ YN0061: │ source-map-url@npm:0.4.0 is deprecated: See https://github.com/lydell/source-map-url#deprecated
➤ YN0061: │ @formatjs/intl-utils@npm:2.2.5 is deprecated: the package is rather renamed to @formatjs/ecma-abstract with some changes in functionality (primarily selectUnit is removed and we don't plan to make any further changes to this package
➤ YN0001: │ Error: emoji-mart@npm:emoji-mart-lazyload: No candidates found
    at le (/home/mastodon/.yarn/releases/yarn-3.2.0.cjs:441:7865)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
➤ YN0000: └ Completed in 22s 316ms
➤ YN0000: Failed with errors in 22s 363ms
➤ YN0032: evp_bytestokey@npm:1.0.3: Implicit dependencies on node-gyp are discouraged
```

and I'm still stuck with the blank page. 

### Expected behaviour

Mastodon interface should show up

### Actual behaviour

Blank page when trying to access mastodon url

### Specifications

```
mastodon@isla-nublar:~/live$ git status
HEAD detached at v3.5.1
mastodon@isla-nublar:~/live$ npm --version
8.5.0
mastodon@isla-nublar:~/live$ node --version
v16.14.2
mastodon@isla-nublar:~/live$ ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x86_64-linux]
mastodon@isla-nublar:~/live$ yarn --version
3.2.0
mastodon@isla-nublar:~/live$ cat /etc/debian_version
11.3
```
Tried from firefox 99, which give a blank page
Chromium 100 straight up give me an Error 500

**Comment by ClearlyClaire** [comment]
This is apparently caused by a difference between yarn versions, https://github.com/mastodon/documentation/issues/931 has more information about this
