### ISSUE TITLE
RAILS_LOG_LEVEL=warning breaks

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#18121]
### Steps to reproduce the problem

As per ref: https://docs.joinmastodon.org/admin/config/
RAILS_LOG_LEVEL=warning breaks my instance.

```
sidekiq-push_1       | 2022-04-27T09:03:04.420Z pid=11 tid=6zz WARN: NameError: uninitialized constant ActiveSupport::Logger::WARNING
sidekiq-push_1       | Did you mean?  Warning
sidekiq-push_1       | 2022-04-27T09:03:04.420Z pid=11 tid=6zz WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/bootstrap.rb:53:in `const_get'
sidekiq-push_1       | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5/lib/rails/application/bootstrap.rb:53:in `block in <module:Bootstrap>'
```

### Expected behaviour

Less logs

### Actual behaviour

Crashed instance

### Specifications

3.5.1

**Comment by shleeable** [comment]
fixed in https://github.com/mastodon/documentation/pull/933
