### ISSUE TITLE
Image OCR feature is broken (since 3.5?)

### ISSUE THREAD

**Issue by claus** [mastodon/mastodon#18266]
### Steps to reproduce the problem

1. Upload an image
2. Click "Edit"
3. Click "Detect text from picture"

### Expected behaviour

Text is detected

### Actual behaviour

Gets stuck at "Preparing OCR"

### Specifications

Mastodon 3.5.1
Chrome Version 100.0.4896.127 (Official Build) (x86_64)
macOS Monterey 12.2.1

RTE in Dev Tools:
<img width="741" alt="Screen Shot 2022-05-02 at 16 33 45" src="https://user-images.githubusercontent.com/2277/166314108-268d16ae-230d-491e-9784-e009578fb2b0.png">

**Comment by Ember-Ember** [comment]
Can reproduce, with mastodon 3.5.3-glitch & firefox 104
![Screenshot from 2022-10-15 19-48-25](https://user-images.githubusercontent.com/48266942/196042689-2c8407b5-3fca-458b-822e-218f06e28730.png)

**Comment by claus** [comment]
This might be fixed with https://github.com/mastodon/mastodon/pull/18817

**Comment by dsmouse** [comment]
having the same symptoms with 
Chrome: 107.0.5304.87
OS: Ubuntu
Mastodon: 3.5.3

WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://social.redactedurl.com"

Uncaught (in promise) RuntimeError: abort(CompileError: WebAssembly.instantiate(): Refused to compile or instantiate WebAssembly module because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' https://social.redactedurl.com"). Build with -s ASSERTIONS=1 for more info.
    at sA (tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1:8515)
    at tesseract-core.wasm-e4db7f953ac7bcf9f67bd39031e42241.js:1:3634246

**Comment by KitKat31337** [comment]
Version 107.0.1418.35 (Official build) (64-bit) of Edge also still has this issue on 3.5.3
