### ISSUE TITLE
Running tootctl media mark-media-missing results in error

### ISSUE THREAD

**Issue by ErikLentz** [mastodon/mastodon#18469]
### Steps to reproduce the problem

1. Migrate instance from one server to another, exclude /public/system/cache directory
2. Run `RAILS_ENV=development bin/tootctl media mark-media-missing` to re-populate local cache
3. Error below
...

```
~/live$ RAILS_ENV=development bin/tootctl media mark-media-missing
/home/mastodon/live/config/environments/development.rb:90:in `<top (required)>': uninitialized constant ActiveRecordQueryTrace (NameError)
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:35:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/engine.rb:571:in `block (2 levels) in <class:Engine>'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/engine.rb:570:in `each'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/engine.rb:570:in `block in <class:Engine>'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `instance_exec'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:32:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:50:in `each'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:50:in `tsort_each_child'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `call'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:415:in `each_strongly_connected_component_from'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/initializable.rb:60:in `run_initializers'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/railties-6.1.5.1/lib/rails/application.rb:391:in `initialize!'
	from /home/mastodon/live/config/environment.rb:5:in `<top (required)>'
	from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `require_relative'
	from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `<top (required)>'
	from /home/mastodon/live/lib/cli.rb:4:in `require_relative'
	from /home/mastodon/live/lib/cli.rb:4:in `<top (required)>'
	from bin/tootctl:5:in `require_relative'
	from bin/tootctl:5:in `<main>'

```

### Expected behaviour

Re-retrieve remote media

### Actual behaviour

Error above

### Specifications

Mastodon v3.5.2
Debian 11

Fresh installation + migration following https://docs.joinmastodon.org/admin/migrating/

**Comment by ErikLentz** [comment]
When I try `RAILS_ENV=production bin/tootctl media mark-media-missing` I receive:
`Could not find command "mark_media_missing"
`

**Comment by Gargron** [comment]
I'm not aware of a command called mark-media-missing

**Comment by ErikLentz** [comment]
https://github.com/mastodon/mastodon/pull/16457

This PR makes me think the command exists.

**Comment by Gargron** [comment]
The PR has status "Closed" and not status "Merged". If you want to use the command from the PR you'll need to get the code from the PR.
