### ISSUE TITLE
New filter UI server error when adding mutliple new keywords

### ISSUE THREAD

**Issue by prplecake** [mastodon/mastodon#18742]
### Steps to reproduce the problem

1. **Edit** one of your filters by adding more than one new keyword
2. Observe server error
3. Edit same filter by adding exactly one new keyword
4. Observe no error

### Expected behaviour

All new keywords be added to the filter

### Actual behaviour

Server error; unique constraint violations

This doesn't appear to be an issue when creating a new filter with multiple keywords, but when editing a preexisting filter to consolidate multiple filters into one. 

### Specifications

Found in 02851848e964675bb59919fa5fd1bdee2c1c29db, https://github.com/mastodon/mastodon/pull/18058

**Comment by prplecake** [comment]
```
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8] method=PUT path=/filters/4 format=ht
ml controller=FiltersController action=update status=500 error='ActiveRecord::RecordNotUnique: PG::UniqueViolation: ER
ROR:  duplicate key value violates unique constraint "custom_filter_keywords_pkey"
Jun 30 03:29:16 mauve-aqua bundle[154455]: DETAIL:  Key (id)=(4) already exists.
Jun 30 03:29:16 mauve-aqua bundle[154455]: ' duration=19.00 view=0.00 db=3.41
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8]
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "custom_filter_keywords_pkey"
Jun 30 03:29:16 mauve-aqua bundle[154455]: DETAIL:  Key (id)=(4) already exists.
Jun 30 03:29:16 mauve-aqua bundle[154455]: ):
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8]
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8] app/controllers/filters_controller.rb:33:in `update'
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8] app/controllers/concerns/localized.rb:11:in `set_locale'
Jun 30 03:29:16 mauve-aqua bundle[154455]: [aa7c56c3-ffcd-4cb5-8143-519b1b40b1d8] lib/mastodon/rack_middleware.rb:9:in `call'                                                                                                               Jun 30 03:29:21 mauve-aqua bundle[154455]: [0ce7145a-dd5a-4230-b822-1a5dc90f92ed] method=PUT path=/filters/4 format=html controller=FiltersController action=update status=302 duration=16.96 view=0.00 db=3.17 location=https://compostintraining.club/filters
Jun 30 03:29:21 mauve-aqua bundle[154461]: [dd827cab-4a81-42bf-b046-c902bb48647f] method=GET path=/api/v1/filters format=html controller=Api::V1::FiltersController action=index status=200 duration=10.94 view=5.47 db=1.54                Jun 30 03:29:21 mauve-aqua bundle[154461]: [7f209c39-495e-4a84-b543-14629e66b295] method=GET path=/api/v1/filters format=html controller=Api::V1::FiltersController action=index status=200 duration=12.74 view=3.87 db=3.85                Jun 30 03:29:21 mauve-aqua bundle[154461]: [0a48e73d-2927-4fc6-a452-a8e4e8f3a2ca] method=GET path=/filters format=html controller=FiltersController action=index status=200 duration=75.09 view=47.80 db=12.30                              Jun 30 03:29:27 mauve-aqua bundle[154461]: [3097bbd6-46a0-4350-8e9d-93a293ef1e7e] method=GET path=/filters/4/edit format=html controller=FiltersController action=edit status=200 duration=56.01 view=45.67 db=2.71                         Jun 30 03:30:01 mauve-aqua bundle[154461]: [b6f8864e-3f73-4d8c-b4e3-2d1fd577195e] method=GET path=/api/v1/bookmarks format=html controller=Api::V1::BookmarksController action=index status=200 duration=319.69 view=134.40 db=17.22        Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d] method=PUT path=/filters/4 format=html controller=FiltersController action=update status=500 error='ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "custom_filter_keywords_pkey"                                    Jun 30 03:30:01 mauve-aqua bundle[154461]: DETAIL:  Key (id)=(6) already exists.
Jun 30 03:30:01 mauve-aqua bundle[154461]: ' duration=22.80 view=0.00 db=3.84                                         Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d]
Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d] ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "custom_filter_keywords_pkey"
Jun 30 03:30:01 mauve-aqua bundle[154461]: DETAIL:  Key (id)=(6) already exists.                                      Jun 30 03:30:01 mauve-aqua bundle[154461]: ):
Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d]                                     Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d] app/controllers/filters_controller.rb:33:in `update'                                                                                                      Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d] app/controllers/concerns/localized.rb:11:in `set_locale'
Jun 30 03:30:01 mauve-aqua bundle[154461]: [74729883-1e25-47e6-ae79-07ee1e8d608d] lib/mastodon/rack_middleware.rb:9:in `call'
```

**Comment by ClearlyClaire** [comment]
Thanks for reporting!

I haven't been able to reproduce it yet, and I'm unsure what could be happening, though.

**Comment by prplecake** [comment]
I haven't been able to repro this in my dev environment either - nor have I been able to repro it on my production instance (where the above logs are from).

**Comment by ClearlyClaire** [comment]
Someone else reported the same error to me, and although I still can't reproduce it, I think I know what is going on.

In the database migration script, I migrate existing filters to the new table, keeping their `id`. However, manually inserting items like that does not increment postgresql's sequence counter as far as I know, meaning that postgres may try to insert new filters using existing IDs.

I guess we need another migration to lock the table, get the maximum `id`, and set the sequence accordingly.
