### ISSUE TITLE
Unable to upload images and get 422 error

### ISSUE THREAD

**Issue by m0r016** [mastodon/mastodon#18778]
### Steps to reproduce the problem

The behavior on mastodon is
End-users cannot upload images.
I have confirmed that the images on the coalition are displayed from s3(minio).
On another server (v3.3.0) that I manage, the above `.env.production` works fine.

The actual configuration is
```
mastodon(serverA) <-> nginx(reverse proxy) <-> minio(serverB)
```

I followed the official documentation and set up minio in s3. Contents of `.env.production`.
```
S3_ENABLED=true
S3_PROTOCOL=https
S3_REGION=us-east-1
S3_ENDPOINT=https://s3.m0r016.net
S3_HOSTNAME=s3.m0r016.net
S3_BUCKET=bucket-name
AWS_ACCESS_KEY_ID=id
AWS_SECRET_ACCESS_KEY=password
S3_ALIAS_HOST=bucket.name
```

You will see this in the sidekiq error log.
```
Aws::S3::Errors::Forbidden - cannot copy media_attachments/files/108/596/331/498/656/502/original/95597d1241308ab0.jpeg to local file /tmp/960beb482a6bc8be02ec713f7a4aba8820220706-796433-8ptcn4.jpeg
```

The sidekiq output log (level: info) will show this
```
[paperclip] Content Type Spoof: Filename 95597d1241308ab0.jpeg (image/jpeg from Headers, ["image/jpeg"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
2022-07-05T19:15:42.411Z pid=796433 tid=j4n9 class=PostProcessMediaWorker jid=791b3d464093303611080048 ERROR: Processing media attachment 108596331498656502 failed with undefined method `start_with?' for nil:NilClass
2022-07-05T19:15:42.412Z pid=796433 tid=j4n9 class=PostProcessMediaWorker jid=791b3d464093303611080048 elapsed=0.077 INFO: fail
2022-07-05T19:15:42.412Z pid=796433 tid=j4n9 WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"args":[108596331498656502],"class":"PostProcessMediaWorker","jid":"791b3d464093303611080048","created_at":1657048515.455382,"enqueued_at":1657048542.3346841,"error_message":"undefined method `start_with?' for nil:NilClass","error_class":"NoMethodError","failed_at":1657048515.5296721,"retry_count":0},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"args\":[108596331498656502],\"class\":\"PostProcessMediaWorker\",\"jid\":\"791b3d464093303611080048\",\"created_at\":1657048515.455382,\"enqueued_at\":1657048542.3346841,\"error_message\":\"undefined method `start_with?' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1657048515.5296721,\"retry_count\":0}"}
2022-07-05T19:15:42.412Z pid=796433 tid=j4n9 WARN: NoMethodError: undefined method `start_with?' for nil:NilClass
2022-07-05T19:15:42.412Z pid=796433 tid=j4n9 WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/fastimage-2.2.6/lib/fastimage.rb:235:in `initialize'
```

### Expected behaviour

upload image

### Actual behaviour

image could not be uploaded.

### Specifications

mastodon v3.5.3
minio verision:RELEASE.2021-10-13T00-23-17Z

**Comment by tateisu** [comment]
まず
https://github.com/mastodon/mastodon/issues/16822#issuecomment-939527995
にある  http_wire_trace の指定を行ってリビルドしてから試してください。
すると 
https://github.com/mastodon/mastodon/issues/16822#issuecomment-940582302
にあるような、S3との間の通信の詳細が出てきます。

**Comment by tateisu** [comment]
https://github.com/mastodon/mastodon/issues/16822#issuecomment-1120313164

**Comment by m0r016** [comment]
@tateisu ありがとうございます。`S3_FORCE_SINGLE_REQUEST=true`で以下のようなログが出ました。
```
[paperclip] copying media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg to local file /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-fvx1hy.jpeg
opening connection to s3.m0r016.net:443...
opened
starting SSL for s3.m0r016.net:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384
<- "HEAD /media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg?partNumber=1 HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.127.0 ruby/3.0.3 aarch64-linux aws-sdk-s3/1.113.0\r\nHost: s3.m0r016.net\r\nX-Amz-Date: 20220709T161939Z\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=mastodon/20220709/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=9def0db58d1cc164c8d86564a2bc2d7259ad0c7a8f05686a10606844d3efaaf5\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Sat, 09 Jul 2022 16:19:39 GMT\r\n"
-> "Content-Type: application/xml\r\n"
-> "Content-Length: 559\r\n"
-> "Connection: keep-alive\r\n"
-> "content-security-policy: block-all-mixed-content\r\n"
-> "strict-transport-security: max-age=31536000; includeSubDomains\r\n"
-> "vary: Origin, Accept-Encoding\r\n"
-> "x-amz-request-id: 17003595B267C1ED\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "CF-Cache-Status: BYPASS\r\n"
-> "Expect-CT: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\n"
-> "Report-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=l%2FKkymdg%2FxqeMzeQhW62PVJh3H8TNx2R4yf8PiOQWlVZKff2RrfTUIYBgqTaNw6B5Uj2gING2elUtU506lapmRbSmMZcvyteqSQ3py6yOKlrYqmCmdijCd8GVA1cegHV\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "NEL: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "Server: cloudflare\r\n"
-> "CF-RAY: 728261ee69b81ed0-NRT\r\n"
-> "alt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400\r\n"
-> "\r\n"
Conn keep-alive
<- "HEAD /media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.127.0 ruby/3.0.3 aarch64-linux aws-sdk-s3/1.113.0\r\nHost: s3.m0r016.net\r\nX-Amz-Date: 20220709T161939Z\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=mastodon/20220709/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=f1f0619acab67a8f1936f55c792e8aba667f76ac6d2bb9fd76ee70181e6e1ffb\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Sat, 09 Jul 2022 16:19:39 GMT\r\n"
-> "Content-Type: application/xml\r\n"
-> "Content-Length: 559\r\n"
-> "Connection: keep-alive\r\n"
-> "content-security-policy: block-all-mixed-content\r\n"
-> "strict-transport-security: max-age=31536000; includeSubDomains\r\n"
-> "vary: Origin, Accept-Encoding\r\n"
-> "x-amz-request-id: 17003595B4218056\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "CF-Cache-Status: BYPASS\r\n"
-> "Expect-CT: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\n"
-> "Report-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=5IzH9EsVJ72%2B8HmLaL3ohxfYdZ54Tx6vklbmI3DW7q5wg2ivi%2FTR9yZqGBtzJYVefkS4VzjDGCqExSXHh9lUSfFcLHXnr4DWOgKDL4%2BjTwmztrMfdwlH5C7BlvftAgFs\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "NEL: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "Server: cloudflare\r\n"
-> "CF-RAY: 728261ee99f01ed0-NRT\r\n"
-> "alt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400\r\n"
-> "\r\n"
Conn keep-alive
[paperclip] Trying to link /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-fvx1hy.jpeg to /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-iqdscc.jpeg
Command :: file -b --mime '/tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-iqdscc.jpeg'
[paperclip] Content Type Spoof: Filename a0acf301430bd55e.jpeg (image/jpeg from Headers, ["image/jpeg"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
2022-07-09T16:19:39.973Z pid=890146 tid=h19a class=PostProcessMediaWorker jid=5402221b738db2e82d5aa7f8 elapsed=0.141 INFO: fail
2022-07-09T16:19:39.974Z pid=890146 tid=h19a WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"args":[108618290273346817],"class":"PostProcessMediaWorker","jid":"5402221b738db2e82d5aa7f8","created_at":1657383579.8313892,"enqueued_at":1657383579.831878},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"args\":[108618290273346817],\"class\":\"PostProcessMediaWorker\",\"jid\":\"5402221b738db2e82d5aa7f8\",\"created_at\":1657383579.8313892,\"enqueued_at\":1657383579.831878}"}
2022-07-09T16:19:39.974Z pid=890146 tid=h19a WARN: NoMethodError: undefined method `start_with?' for nil:NilClass
2022-07-09T16:19:39.974Z pid=890146 tid=h19a WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/fastimage-2.2.6/lib/fastimage.rb:235:in `initialize'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/fastimage-2.2.6/lib/fastimage.rb:140:in `new'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/fastimage-2.2.6/lib/fastimage.rb:140:in `size'
2022-07-09T16:19:43.832Z pid=890146 tid=hbxu INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2022-07-09T16:19:43.836Z pid=890146 tid=hbwm class=Scheduler::AccountsStatusesCleanupScheduler jid=3d91c16d85b4815063e051aa INFO: start
2022-07-09T16:19:43.846Z pid=890146 tid=hbwm class=Scheduler::AccountsStatusesCleanupScheduler jid=3d91c16d85b4815063e051aa elapsed=0.011 INFO: done
2022-07-09T16:19:56.466Z pid=890146 tid=hbwm class=PostProcessMediaWorker jid=5402221b738db2e82d5aa7f8 INFO: start
[paperclip] copying media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg to local file /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-sle5t6.jpeg
opening connection to s3.m0r016.net:443...
opened
starting SSL for s3.m0r016.net:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384
<- "HEAD /media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg?partNumber=1 HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.127.0 ruby/3.0.3 aarch64-linux aws-sdk-s3/1.113.0\r\nHost: s3.m0r016.net\r\nX-Amz-Date: 20220709T161956Z\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=mastodon/20220709/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=78de5770055880084254d376f4d09dc8f74941f50aa72d53937e3d423b925ad4\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Sat, 09 Jul 2022 16:19:56 GMT\r\n"
-> "Content-Type: application/xml\r\n"
-> "Content-Length: 559\r\n"
-> "Connection: keep-alive\r\n"
-> "content-security-policy: block-all-mixed-content\r\n"
-> "strict-transport-security: max-age=31536000; includeSubDomains\r\n"
-> "vary: Origin, Accept-Encoding\r\n"
-> "x-amz-request-id: 170035998EB750B7\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "CF-Cache-Status: BYPASS\r\n"
-> "Expect-CT: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\n"
-> "Report-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=AC%2BPe4bX%2BTKu4mx9NQ6xeawEpt5lB802XOwVktQkT8j36v9ktsoOGC6A771vDXcOt6YUQFcl6cJewuY1xfWB3N1e2ora98MJKwakBk6c4XhE9U%2FxjTzkJarO5lqHvw%2Fe\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "NEL: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "Server: cloudflare\r\n"
-> "CF-RAY: 728262560ffe80cf-NRT\r\n"
-> "alt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400\r\n"
-> "\r\n"
Conn keep-alive
<- "HEAD /media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg HTTP/1.1\r\nAccept-Encoding: \r\nUser-Agent: aws-sdk-ruby3/3.127.0 ruby/3.0.3 aarch64-linux aws-sdk-s3/1.113.0\r\nHost: s3.m0r016.net\r\nX-Amz-Date: 20220709T161956Z\r\nX-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\r\nAuthorization: AWS4-HMAC-SHA256 Credential=mastodon/20220709/us-east-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=25eaa71386c24f010b86ef5d89bc62a617a70f09f4b14509d90a7b8a4d11afcc\r\nAccept: */*\r\n\r\n"
-> "HTTP/1.1 403 Forbidden\r\n"
-> "Date: Sat, 09 Jul 2022 16:19:56 GMT\r\n"
-> "Content-Type: application/xml\r\n"
-> "Content-Length: 559\r\n"
-> "Connection: keep-alive\r\n"
-> "content-security-policy: block-all-mixed-content\r\n"
-> "strict-transport-security: max-age=31536000; includeSubDomains\r\n"
-> "vary: Origin, Accept-Encoding\r\n"
-> "x-amz-request-id: 170035998F9C7C50\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "x-xss-protection: 1; mode=block\r\n"
-> "CF-Cache-Status: BYPASS\r\n"
-> "Expect-CT: max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"\r\n"
-> "Report-To: {\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=XDvT7DTLPtK8y0GL5XR3gjnXGiZN5O1X4IKHmZsSdzR%2BnddJWwFk3rz1FalhBdQ21BQxZNd0vq00OSHQjkSqHbiYBv4tYeu5jagGQ4bnZXruQgoutcWAFwwIV6zkRL0%2F\"}],\"group\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "NEL: {\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}\r\n"
-> "Server: cloudflare\r\n"
-> "CF-RAY: 72826256384280cf-NRT\r\n"
-> "alt-svc: h3=\":443\"; ma=86400, h3-29=\":443\"; ma=86400\r\n"
-> "\r\n"
Conn keep-alive
[paperclip] Trying to link /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-sle5t6.jpeg to /tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-34vv3.jpeg
Command :: file -b --mime '/tmp/ec600e6700f594e47eb7f4fa2fbd950c20220710-890146-34vv3.jpeg'
[paperclip] Content Type Spoof: Filename a0acf301430bd55e.jpeg (image/jpeg from Headers, ["image/jpeg"] from Extension), content type discovered from file command: inode/x-empty. See documentation to allow this combination.
[paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
2022-07-09T16:19:56.546Z pid=890146 tid=hbwm class=PostProcessMediaWorker jid=5402221b738db2e82d5aa7f8 ERROR: Processing media attachment 108618290273346817 failed with undefined method `start_with?' for nil:NilClass
2022-07-09T16:19:56.547Z pid=890146 tid=hbwm class=PostProcessMediaWorker jid=5402221b738db2e82d5aa7f8 elapsed=0.081 INFO: fail
2022-07-09T16:19:56.547Z pid=890146 tid=hbwm WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"args":[108618290273346817],"class":"PostProcessMediaWorker","jid":"5402221b738db2e82d5aa7f8","created_at":1657383579.8313892,"enqueued_at":1657383596.4660213,"error_message":"undefined method `start_with?' for nil:NilClass","error_class":"NoMethodError","failed_at":1657383579.9733114,"retry_count":0},"jobstr":"{\"retry\":1,\"queue\":\"default\",\"dead\":false,\"args\":[108618290273346817],\"class\":\"PostProcessMediaWorker\",\"jid\":\"5402221b738db2e82d5aa7f8\",\"created_at\":1657383579.8313892,\"enqueued_at\":1657383596.4660213,\"error_message\":\"undefined method `start_with?' for nil:NilClass\",\"error_class\":\"NoMethodError\",\"failed_at\":1657383579.9733114,\"retry_count\":0}"}
2022-07-09T16:19:56.547Z pid=890146 tid=hbwm WARN: NoMethodError: undefined method `start_with?' for nil:NilClass
2022-07-09T16:19:56.547Z pid=890146 tid=hbwm WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/fastimage-2.2.6/lib/fastimage.rb:235:in `initialize'
```

**Comment by tateisu** [comment]
> HEAD /media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg 
> HTTP/1.1 403 Forbidden

認証に失敗しているようです。

**Comment by m0r016** [comment]
3.4.6までは動いていて3.5.0になるとこの症状が出てしまいます・・・。
ちなみにリンクの方は見れていますね・・・
https://s3.m0r016.net/media-mstdn-life/media_attachments/files/108/618/290/273/346/817/original/a0acf301430bd55e.jpeg

**Comment by m0r016** [comment]
本番環境に適用したところ、解決しました。

**Comment by filmaj** [comment]
FWIW I was getting Access Denied errors using programmatic API keys using AWS S3 as object storage in my instance. Using the keys with the `aws` CLI worked fine to upload objects to the bucket. After setting `S3_FORCE_SINGLE_REQUEST=true` in my `.env.production` file on my instance and restarting, the error went away and assets work great now!
