### ISSUE TITLE
User failed to get post archive

### ISSUE THREAD

**Issue by MamaShip** [mastodon/mastodon#18785]
### Steps to reproduce the problem

1. Click [**Preferences**] -> [**Import and export**] ->[**Data export**] -> [**Request your archive**] 
2. See [**Compiling your archive...**]
3. No email received. No archive generated. 
4. If user visit [**Data export**] page again, the [**Request your archive**] button is still there. User can click it again and still nothing happened.

### Expected behaviour

User can find [Download your archive] button on his [**Data export**] page

### Actual behaviour

Nothing happend

### Specifications

I can't reproduce this bug on my own account. The bug only happened on one specific user account.

Found a BackupWorker Error in Sidekiq soon after requesting archive : 
![图片](https://user-images.githubusercontent.com/7104870/177905212-2c189158-746e-4edc-a836-dccf75fa7ba6.png)

**Environment**:
Mastodon version:  v3.5.3
This instance is using S3 storage.

**Comment by rodti** [comment]
+1

**Comment by SouthFox-D** [comment]
Same problem here

my logs:

```
sidekiq_1    |#<Thread:0x00007f38baf9c230 /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_downloader.rb:123 run> terminated with exception (report_on_exception is true):
sidekiq_1    |/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write': undefined method `split' for nil:NilClass (NoMethodError)
sidekiq_1    |      from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
sidekiq_1    | 2022-09-07T12:35:52.221Z pid=7 tid=2ezvov class=BackupWorker jid=75f91e48f64b031d439944ed elapsed=334.717 INFO: fail
sidekiq_1    | 2022-09-07T12:35:52.221Z pid=7 tid=2ezvov WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"args":[4],"class":"BackupWorker","jid":"75f91e48f64b031d439944ed","created_at":1662553343.2498746,"enqueued_at":1662553817.5024946,"error_message":"undefined method `split' for nil:NilClass","error_class":"NoMethodError","failed_at":1662553580.390903,"retry_count":1,"error_backtrace":"eJy9zUEOwiAQAMCvkF6qiWWLaEz6FWMqdFdLugUDtMTf23jyBV7nMtcKwivD\nbFIOGDys5DFEsItHJoiLfYOWrWzhSXMCU1KTcGqSbpRU6rQ5O/vD8HBMPYbi\nORikKKPtlD53zot7iS5TXR3+MB4v39FyGCax04JpJU57sWEeIxnsrcnDSKmu\nbh8xG1cX\n","retried_at":1662553783.324919}}
sidekiq_1    | 2022-09-07T12:35:52.221Z pid=7 tid=2ezvov WARN: NoMethodError: undefined method `split' for nil:NilClass
sidekiq_1    | 2022-09-07T12:35:52.221Z pid=7 tid=2ezvov WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.114.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
```

**Comment by yingziwu** [comment]
Same problem on Mastodon v4.1.1

```
Mar 25 00:38:57 sidekiq.rel.bgme.org bundle[667539]: 2023-03-25T00:38:57.370Z pid=667539 tid=26phuz class=BackupWorker jid=be26e8ffae9275baa42494ce INFO: start
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: 2023-03-25T00:47:11.503Z pid=667539 tid=26phuz class=BackupWorker jid=be26e8ffae9275baa42494ce elapsed=494.133 INFO: fail
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: 2023-03-25T00:47:11.504Z pid=667539 tid=26phuz WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"args":[818],"class":"BackupWorker","jid":"be26e8ffae9275baa42494ce","created_at":1679704737.369699,"enqueued_at":1679704737.3698688}}
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: 2023-03-25T00:47:11.504Z pid=667539 tid=26phuz WARN: NoMethodError: undefined method `split' for nil:NilClass
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: 2023-03-25T00:47:11.504Z pid=667539 tid=26phuz WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write'
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: #<Thread:0x00007f629b6ec698 /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:123 run> terminated with exception (report_on_exception is true):
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Mar 25 00:47:11 sidekiq.rel.bgme.org bundle[667539]:         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: #<Thread:0x00007f629b6ece18 /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:123 run> terminated with exception (report_on_exception is true):
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]:         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: #<Thread:0x00007f629b6ecd28 /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:123 run> terminated with exception (report_on_exception is true):
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]:         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: #<Thread:0x00007f629b6ecc38 /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:123 run> terminated with exception (report_on_exception is true):
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:135:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Mar 25 00:47:12 sidekiq.rel.bgme.org bundle[667539]:         from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/aws-sdk-s3-1.119.0/lib/aws-sdk-s3/file_downloader.rb:127:in `block (3 levels) in thread_batches'
```

**Comment by cmx-im** [comment]
Same ```undefined method `split' for nil:NilClass``` error observed on Mastodon v4.1.5

Log:

```
WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"args":[1976],"class":"BackupWorker","jid":"85531b4c93eb06695dd4bcd8","created_at":1689969160.534509,"enqueued_at":1689969367.625099,"error_message":"undefined method `split' for nil:NilClass","error_class":"NoMethodError","failed_at":1689969345.3790998,"retry_count":0,...}}
```

**Comment by MamaShip** [comment]
@ClearlyClaire
This bug seems to be easily triggered in the S3 storage scenario, and our users really care about the **data export** feature. 
Can you help check it out?

**Comment by ClearlyClaire** [comment]
Try with `S3_FORCE_SINGLE_REQUEST=true`

**Comment by CurrentBias** [comment]
+1

**Comment by SarraceniaWilds** [comment]
this bug is present on every instance i have migrated to or from
