### ISSUE TITLE
Sidebar broken in latest commit

### ISSUE THREAD

**Issue by kescherCode** [mastodon/mastodon#18821]
### Steps to reproduce the problem

1. Open a profile page, a post, etc. on an instance that currently has a hashtag trending (not in the web UI for logged in users, but in *that other one*)
2. receive the following stacktrace:

```
ActionView::Template::Error (undefined local variable or method `current_user' for #<REST::TagSerializer:0x00007fd9edec51e8 @_routes=nil, @object=#<Tag id: 23, name: "Linux", created_at: "2022-04-15 19:25:06.077106000 +0000", updated_at: "2022-07-17 13:46:18.507623000 +0000", usable: true, trendable: true, listable: true, reviewed_at: "2022-04-27 02:58:41.021416000 +0000", requested_review_at: nil, last_status_at: "2022-07-17 13:46:12.000000000 +0000", max_score: 12.5, max_score_at: "2022-07-17 17:35:06.091199000 +0000", display_name: nil>, @instance_options={}, @root=nil, @scope=nil, @attributes=nil>
Did you mean?  current_user?):
    13:       %h4.emojify= t('footer.trending_now')
    14:
    15:       - trends.each do |tag|
    16:         = react_component :hashtag, hashtag: ActiveModelSerializers::SerializableResource.new(tag, serializer: REST::TagSerializer).as_json
[2bd82cf3-8a4f-4b84-af91-8ec50b62b3c1]
app/serializers/rest/tag_serializer.rb:27:in `current_user?'
app/views/application/_sidebar.html.haml:16
app/models/trends/query.rb:62:in `each'
app/models/trends/query.rb:62:in `each'
app/views/application/_sidebar.html.haml:15
app/views/accounts/show.html.haml:86
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

### Expected behaviour

The page should have loaded fine

### Actual behaviour

500 Internal Server Error

### Specifications

Commit c3f0621a59a74d0e20e6db6170894871c48e8f0f

**Comment by kescherCode** [comment]
[The issue is somewhere here](https://github.com/mastodon/mastodon/commit/c3f0621a59a74d0e20e6db6170894871c48e8f0f#diff-689e719539d117ba019272509e70f74ba64cbf78d9c15514922ba57b90c0a1bdR22)

**Comment by tribela** [comment]
I got `undefined local variable or method 'current_user'` on app/serializers/rest/tag_serializer.rbL27

**Comment by kescherCode** [comment]
Apparently, the cause of this was a missing scope for current_user in _sidebar.html.haml.
