### ISSUE TITLE
Unable to import an export from another mastodon server

### ISSUE THREAD

**Issue by kallisti5** [mastodon/mastodon#18891]
### Steps to reproduce the problem

```
[f89d5640-3683-4e27-9273-1c65393e115b] [paperclip] Trying to link /tmp/RackMultipart20220727-14-n66ev2.gz to /tmp/fabf7a8f4881a340f9b7093ac6b438ac20220727-14-djxwmk.gz
[f89d5640-3683-4e27-9273-1c65393e115b] [paperclip] Trying to link /tmp/fabf7a8f4881a340f9b7093ac6b438ac20220727-14-djxwmk.gz to /tmp/fabf7a8f4881a340f9b7093ac6b438ac20220727-14-1b50lv.gz
[f89d5640-3683-4e27-9273-1c65393e115b] Command :: file -b --mime '/tmp/fabf7a8f4881a340f9b7093ac6b438ac20220727-14-1b50lv.gz'
[f89d5640-3683-4e27-9273-1c65393e115b] method=POST path=/settings/import format=html controller=Settings::ImportsController action=create status=500 error='CSV::MalformedCSVError: Unquoted fields do not allow new line <"\n"> in line 2.' duration=210.47 view=0.00 db=1.10
[f89d5640-3683-4e27-9273-1c65393e115b]   
[f89d5640-3683-4e27-9273-1c65393e115b] CSV::MalformedCSVError (Unquoted fields do not allow new line <"\n"> in line 2.):
[f89d5640-3683-4e27-9273-1c65393e115b]   
[f89d5640-3683-4e27-9273-1c65393e115b] app/validators/import_validator.rb:18:in `validate'
[f89d5640-3683-4e27-9273-1c65393e115b] app/controllers/settings/imports_controller.rb:14:in `create'
[f89d5640-3683-4e27-9273-1c65393e115b] app/controllers/concerns/localized.rb:11:in `set_locale'
[f89d5640-3683-4e27-9273-1c65393e115b] lib/mastodon/rack_middleware.rb:9:in `call'
X-Accel-Mapping header missing
X-Accel-Mapping header missing
```

### Expected behaviour

Import to work

### Actual behaviour

Something went wrong error

### Specifications

Exporting from v3.5.3, importing to v3.5.3

**Comment by ClearlyClaire** [comment]
Can you share the first lines of the comment (anonymizing if necessary, but keeping any non-alphanumeric character if possible)?
