### ISSUE TITLE
remove-orphans Exception: No such file or directory

### ISSUE THREAD

**Issue by nixuno** [mastodon/mastodon#18928]
### Steps to reproduce the problem

1. Connect to mastodon-streaming container shell (Docker)
2. Run `tootctl media remove-orphans`
3. Get exception error message below:

```
tootctl media remove-orphans
/opt/ruby/lib/ruby/3.0.0/find.rb:43:in `block in find': No such file or directory - /opt/mastodon/public/system (Errno::ENOENT)---=---=---=---=---=---=---=---=---=-|  ETA: ??:??:??
        from /opt/ruby/lib/ruby/3.0.0/find.rb:43:in `collect!'
        from /opt/ruby/lib/ruby/3.0.0/find.rb:43:in `find'
        from /opt/mastodon/lib/mastodon/media_cli.rb:132:in `remove_orphans'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from /opt/mastodon/bin/tootctl:8:in `<main>'
```

### Expected behaviour

Orphaned files should have been removed

### Actual behaviour

An exception was thrown

### Specifications

Running version 3.5.3 on standard docker-compose stack.

**Comment by nixuno** [comment]
Running the command on the `mastodon-web` container was the solution. User error. Closing.
