### ISSUE TITLE
Cannot follow other instance users after instance rebuild

### ISSUE THREAD

**Issue by aaro-n** [mastodon/mastodon#19338]
### Steps to reproduce the problem

1.Build the instance normally, and pay attention to other instance users.
2.After the instance has been running for a period of time, delete the instance database and rerun the instance settings, save.
3.Follow other instance users again (before), prompt "Following verification", there is 401 in the log
4.You can follow other users normally by setting up a new domain name.
...

### Expected behaviour

After the database is reset, you can follow other instances with the old domain name

### Actual behaviour

A new domain name is required to follow other instance users.

### Specifications

```
mastodon-web-1        | [aca8029b-4915-4e6e-a472-66d455ff65d4] method=GET path=/users/aaron format=json controller=AccountsController action=show status=200 duration=21.75 view=7.06 db=3.83 key=https://mast.dragon-fly.club/actor#main-key
mastodon-sidekiq-1    | 2022-10-10T13:33:32.215Z pid=6 tid=2l3a class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d elapsed=1.502 INFO: fail
mastodon-sidekiq-1    | 2022-10-10T13:33:32.215Z pid=6 tid=2l3a WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\",\"type\":\"Follow\",\"actor\":\"https://me.its2.fun/users/aaron\",\"object\":\"https://mast.dragon-fly.club/users/SaBunnKi\"}",109138910118564175,"https://mast.dragon-fly.club/users/SaBunnKi/inbox"],"class":"ActivityPub::DeliveryWorker","jid":"eaf29bdee99699c056899f0d","created_at":1665408810.7118962,"enqueued_at":1665408810.7123432},"jobstr":"{\"retry\":16,\"queue\":\"push\",\"dead\":false,\"args\":[\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https://me.its2.fun/users/aaron\\\",\\\"object\\\":\\\"https://mast.dragon-fly.club/users/SaBunnKi\\\"}\",109138910118564175,\"https://mast.dragon-fly.club/users/SaBunnKi/inbox\"],\"class\":\"ActivityPub::DeliveryWorker\",\"jid\":\"eaf29bdee99699c056899f0d\",\"created_at\":1665408810.7118962,\"enqueued_at\":1665408810.7123432}"}
mastodon-sidekiq-1    | 2022-10-10T13:33:32.215Z pid=6 tid=2l3a WARN: Mastodon::UnexpectedResponseError: https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401
mastodon-sidekiq-1    | 2022-10-10T13:33:32.215Z pid=6 tid=2l3a WARN: /opt/mastodon/app/workers/activitypub/delivery_worker.rb:54:in `block (3 levels) in perform_request'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/request.rb:75:in `perform'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/activitypub/delivery_worker.rb:53:in `block (2 levels) in perform_request'
mastodon-web-1        | [7fb1aa07-d178-442e-8157-27ac6d95e511] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 duration=0.41 view=0.21 db=0.00
mastodon-sidekiq-1    | 2022-10-10T13:33:51.231Z pid=6 tid=2l6y INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
mastodon-sidekiq-1    | 2022-10-10T13:33:51.234Z pid=6 tid=2lee class=Scheduler::AccountsStatusesCleanupScheduler jid=8c837fe7df8e8e00b36b2b6a INFO: start
mastodon-sidekiq-1    | 2022-10-10T13:33:51.240Z pid=6 tid=2lee class=Scheduler::AccountsStatusesCleanupScheduler jid=8c837fe7df8e8e00b36b2b6a elapsed=0.006 INFO: done
mastodon-web-1        | [0f254636-bbab-4f4b-8dcf-f3d697c0f89a] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=6.80 view=0.44 db=1.34
mastodon-web-1        | [320772b6-e218-47f9-a646-8f05518e06b0] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=9.28 view=0.39 db=2.91
mastodon-web-1        | [3b7f48d4-9023-4898-b084-94bd0a2fbf12] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=7.11 view=0.93 db=2.80
mastodon-sidekiq-1    | 2022-10-10T13:33:58.263Z pid=6 tid=2lfi class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d INFO: start
mastodon-sidekiq-1    | 2022-10-10T13:33:58.827Z pid=6 tid=2lfi class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d elapsed=0.564 INFO: fail
mastodon-sidekiq-1    | 2022-10-10T13:33:58.827Z pid=6 tid=2lfi WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\",\"type\":\"Follow\",\"actor\":\"https://me.its2.fun/users/aaron\",\"object\":\"https://mast.dragon-fly.club/users/SaBunnKi\"}",109138910118564175,"https://mast.dragon-fly.club/users/SaBunnKi/inbox"],"class":"ActivityPub::DeliveryWorker","jid":"eaf29bdee99699c056899f0d","created_at":1665408810.7118962,"enqueued_at":1665408838.2630787,"error_message":"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401","error_class":"Mastodon::UnexpectedResponseError","failed_at":1665408812.2148535,"retry_count":0},"jobstr":"{\"retry\":16,\"queue\":\"push\",\"dead\":false,\"args\":[\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https://me.its2.fun/users/aaron\\\",\\\"object\\\":\\\"https://mast.dragon-fly.club/users/SaBunnKi\\\"}\",109138910118564175,\"https://mast.dragon-fly.club/users/SaBunnKi/inbox\"],\"class\":\"ActivityPub::DeliveryWorker\",\"jid\":\"eaf29bdee99699c056899f0d\",\"created_at\":1665408810.7118962,\"enqueued_at\":1665408838.2630787,\"error_message\":\"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401\",\"error_class\":\"Mastodon::UnexpectedResponseError\",\"failed_at\":1665408812.2148535,\"retry_count\":0}"}
mastodon-sidekiq-1    | 2022-10-10T13:33:58.827Z pid=6 tid=2lfi WARN: Mastodon::UnexpectedResponseError: https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401
mastodon-sidekiq-1    | 2022-10-10T13:33:58.827Z pid=6 tid=2lfi WARN: /opt/mastodon/app/workers/activitypub/delivery_worker.rb:54:in `block (3 levels) in perform_request'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/request.rb:75:in `perform'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/activitypub/delivery_worker.rb:53:in `block (2 levels) in perform_request'
mastodon-web-1        | [6de735ef-8caf-43df-b110-d258d34b814f] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=7.69 view=0.00 db=0.59 key=https://pawoo.net/users/Princess108#main-key
mastodon-web-1        | [b9b4bd2a-4542-4383-96e4-51df5daf4391] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 duration=0.50 view=0.28 db=0.00
mastodon-web-1        | [18de3a7c-35e0-406b-a167-9ba0409f6a5b] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=6.81 view=0.42 db=1.32
mastodon-web-1        | [304b6e19-e5ba-40b6-9b11-205ddca9f23e] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=8.43 view=0.40 db=2.15
mastodon-web-1        | [79ae2557-9f63-423b-9f43-ba3dc409a426] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=5.91 view=0.92 db=1.85
mastodon-sidekiq-1    | 2022-10-10T13:34:25.691Z pid=6 tid=2kz6 class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d INFO: start
mastodon-sidekiq-1    | 2022-10-10T13:34:26.294Z pid=6 tid=2kz6 class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d elapsed=0.602 INFO: fail
mastodon-sidekiq-1    | 2022-10-10T13:34:26.294Z pid=6 tid=2kz6 WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\",\"type\":\"Follow\",\"actor\":\"https://me.its2.fun/users/aaron\",\"object\":\"https://mast.dragon-fly.club/users/SaBunnKi\"}",109138910118564175,"https://mast.dragon-fly.club/users/SaBunnKi/inbox"],"class":"ActivityPub::DeliveryWorker","jid":"eaf29bdee99699c056899f0d","created_at":1665408810.7118962,"enqueued_at":1665408865.6913939,"error_message":"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401","error_class":"Mastodon::UnexpectedResponseError","failed_at":1665408812.2148535,"retry_count":1,"retried_at":1665408838.826508},"jobstr":"{\"retry\":16,\"queue\":\"push\",\"dead\":false,\"args\":[\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https://me.its2.fun/users/aaron\\\",\\\"object\\\":\\\"https://mast.dragon-fly.club/users/SaBunnKi\\\"}\",109138910118564175,\"https://mast.dragon-fly.club/users/SaBunnKi/inbox\"],\"class\":\"ActivityPub::DeliveryWorker\",\"jid\":\"eaf29bdee99699c056899f0d\",\"created_at\":1665408810.7118962,\"enqueued_at\":1665408865.6913939,\"error_message\":\"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401\",\"error_class\":\"Mastodon::UnexpectedResponseError\",\"failed_at\":1665408812.2148535,\"retry_count\":1,\"retried_at\":1665408838.826508}"}
mastodon-sidekiq-1    | 2022-10-10T13:34:26.294Z pid=6 tid=2kz6 WARN: Mastodon::UnexpectedResponseError: https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401
mastodon-sidekiq-1    | 2022-10-10T13:34:26.294Z pid=6 tid=2kz6 WARN: /opt/mastodon/app/workers/activitypub/delivery_worker.rb:54:in `block (3 levels) in perform_request'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/request.rb:75:in `perform'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/activitypub/delivery_worker.rb:53:in `block (2 levels) in perform_request'
mastodon-web-1        | [c30a743b-dc63-44b0-82a4-2aa54b0d06b4] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 duration=0.42 view=0.21 db=0.00
mastodon-sidekiq-1    | 2022-10-10T13:34:51.284Z pid=6 tid=2l6y INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
mastodon-sidekiq-1    | 2022-10-10T13:34:51.286Z pid=6 tid=2lee class=Scheduler::AccountsStatusesCleanupScheduler jid=68d27e8b997bdf15fa2c725e INFO: start
mastodon-sidekiq-1    | 2022-10-10T13:34:51.292Z pid=6 tid=2lee class=Scheduler::AccountsStatusesCleanupScheduler jid=68d27e8b997bdf15fa2c725e elapsed=0.006 INFO: done
mastodon-web-1        | [e94c3280-2677-4deb-b325-5efa126f4255] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=6.46 view=0.49 db=1.23
mastodon-web-1        | [0a5ce7f3-30eb-41cd-9a42-04fe0b3898f6] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=8.60 view=0.43 db=2.31
mastodon-web-1        | [0a3c765e-0646-40da-8675-f72180a64243] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=5.98 view=0.81 db=1.93
mastodon-sidekiq-1    | 2022-10-10T13:35:10.392Z pid=6 tid=2ljy class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d INFO: start
mastodon-sidekiq-1    | 2022-10-10T13:35:10.993Z pid=6 tid=2ljy class=ActivityPub::DeliveryWorker jid=eaf29bdee99699c056899f0d elapsed=0.601 INFO: fail
mastodon-sidekiq-1    | 2022-10-10T13:35:10.994Z pid=6 tid=2ljy WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\",\"type\":\"Follow\",\"actor\":\"https://me.its2.fun/users/aaron\",\"object\":\"https://mast.dragon-fly.club/users/SaBunnKi\"}",109138910118564175,"https://mast.dragon-fly.club/users/SaBunnKi/inbox"],"class":"ActivityPub::DeliveryWorker","jid":"eaf29bdee99699c056899f0d","created_at":1665408810.7118962,"enqueued_at":1665408910.3922791,"error_message":"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401","error_class":"Mastodon::UnexpectedResponseError","failed_at":1665408812.2148535,"retry_count":2,"retried_at":1665408866.2933004},"jobstr":"{\"retry\":16,\"queue\":\"push\",\"dead\":false,\"args\":[\"{\\\"@context\\\":\\\"https://www.w3.org/ns/activitystreams\\\",\\\"id\\\":\\\"https://me.its2.fun/e027e951-0f83-4bbe-8b8e-001404a014d8\\\",\\\"type\\\":\\\"Follow\\\",\\\"actor\\\":\\\"https://me.its2.fun/users/aaron\\\",\\\"object\\\":\\\"https://mast.dragon-fly.club/users/SaBunnKi\\\"}\",109138910118564175,\"https://mast.dragon-fly.club/users/SaBunnKi/inbox\"],\"class\":\"ActivityPub::DeliveryWorker\",\"jid\":\"eaf29bdee99699c056899f0d\",\"created_at\":1665408810.7118962,\"enqueued_at\":1665408910.3922791,\"error_message\":\"https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401\",\"error_class\":\"Mastodon::UnexpectedResponseError\",\"failed_at\":1665408812.2148535,\"retry_count\":2,\"retried_at\":1665408866.2933004}"}
mastodon-sidekiq-1    | 2022-10-10T13:35:10.994Z pid=6 tid=2ljy WARN: Mastodon::UnexpectedResponseError: https://mast.dragon-fly.club/users/SaBunnKi/inbox returned code 401
mastodon-sidekiq-1    | 2022-10-10T13:35:10.994Z pid=6 tid=2ljy WARN: /opt/mastodon/app/workers/activitypub/delivery_worker.rb:54:in `block (3 levels) in perform_request'
mastodon-sidekiq-1    | /opt/mastodon/app/lib/request.rb:75:in `perform'
mastodon-sidekiq-1    | /opt/mastodon/app/workers/activitypub/delivery_worker.rb:53:in `block (2 levels) in perform_request'
mastodon-web-1        | [1cc5bf60-9dc1-4474-96f4-7a612fc0ed53] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 duration=0.42 view=0.21 db=0.00
mastodon-web-1        | [8c48f275-1451-413b-b127-30062dc340ee] method=GET path=/api/v1/timelines/home format=html controller=Api::V1::Timelines::HomeController action=show status=200 duration=6.58 view=0.47 db=1.36
mastodon-web-1        | [925233f8-9f71-4bd7-9551-39022b72525e] method=GET path=/api/v1/notifications format=html controller=Api::V1::NotificationsController action=index status=200 duration=8.16 view=0.38 db=2.15
mastodon-web-1        | [cb01720a-447c-434c-b5ac-a656632dd94c] method=GET path=/api/v1/announcements format=html controller=Api::V1::AnnouncementsController action=index status=200 duration=6.61 view=0.84 db=2.37
mastodon-web-1        | [73032569-40ba-4c48-90da-d62f5b31e696] method=HEAD path=/health format=*/* controller=HealthController action=show status=200 duration=0.40 view=0.20 db=0.00
```

**Comment by BrianJKoopman** [comment]
I'm encountering the same issue while trying to stand up a new instance for the first time. I'm not sure what's causing the 401.

You said changing domain names fixed it for you. Is it sufficient to change `WEB_DOMAIN` or is a change of the `LOCAL_DOMAIN` needed as well? I'm wondering if I can just switch subdomains.

**Comment by cromulus** [comment]
I had the same error.

My setup: I have a personal domain, my-name.org and my mastodon instance lives on mastodon.my-name.org.

LOCAL_DOMAIN=my-name.org
WEB_DOMAIN=mastodon.my-name.org

The problem was that my webfinger redirect was failing.

`curl  https://my-name.org/.well-known/webfinger?resource=acct:me@my-name.org` should return:

```
{"subject":"acct:me@my-name.org","aliases":["https://mastodon.my-name.org/@me","https://mastodon.my-name.org/users/mel"],"links":[{"rel":"http://webfinger.net/rel/profile-page","type":"text/html","href":"https://mastodon.my-name.org/@me"},{"rel":"self","type":"application/activity+json","href":"https://mastodon.my-name.org/users/mel"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://mastodon.my-name.org/authorize_interaction?uri={uri}"}]}
```

`curl  https://my-name.org/.well-known/host-meta` returns 
```
<?xml version="1.0" encoding="UTF-8"?>
<XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
  <Link rel="lrdd" template="https://mastodon.my-name.org/.well-known/webfinger?resource={uri}"/>
</XRD>
```

@BrianJKoopman that's what fixed it for me!

**Comment by aaro-n** [comment]
@cromulus @BrianJKoopman Completely replace the new domain name.The domain name I used for the first time was `me.my-name.fun`, and then changed to `ce.my-name.fun` and `m.my-name.fun`, and the same error occurred, and the domain name was changed to `m.my-name.plus` to work normally.

```
# LOCAL_DOMAIN=me.my-name.fun
LOCAL_DOMAIN=m.my-name.plus
ALTERNATE_DOMAINS=me.my-name.fun
```

**Comment by BrianJKoopman** [comment]
@cromulus those examples were incredibly helpful in debugging this. Thanks! I appear to have things working now.

My issue was with my nginx config. I had a configuration for `.well-known` that I was carrying around thinking I needed it for Let's Encrypt, turns out I don't need it. Getting rid of it solved a 401 I was getting on `curl https://my-name.org/.well-known/host-meta`.

**Comment by aaro-n** [comment]
The domain name is mentioned in the documentation, the [documentation](https://docs.joinmastodon.org/admin/config/#local_domain)，I think it is the first time to create an instance and pay attention to users on other instances. Other instances should record the domain name and instance information of this instance. When deleting the database and rebuilding the instance, and following users of other instances again, due to the use of the same domain name, others The instance will be compared with the previous domain name information, and if there is a mismatch, it will refuse to follow.

**Comment by mazzy89** [comment]
I do get the same issue but in my case my `local_domain` and `web_domain` matches and are in the format local_domain=subdomain.mydomain.social and web_domain=subdomain.mydomain.social and  both of those two returns OK

```
https://subdomain.mydomain.social/.well-known/webfinger?resource=acct:user@subdomain.mydomain.social'
```

```
curl https://subdomain.mydomain.social/.well-known/host-meta
```

what else could be off?

**Comment by mazzy89** [comment]
For whoever will find this post, make sure also that your SSL certs are correctly set. In my case my servers were missing the intermediate certificate and while many browsers solve this issue, mastodon process could not do proper SSL validation.

**Comment by narcoticfresh** [comment]
@mazzy89 / @cromulus 

i'm also having the same issue; version 4.0.2..
`LOCAL_DOMAIN` and `ALTERNATE_DOMAINS` are identical, the `.well-known` responses look fine.. TLS/SSL is fine.. it's mysterious.. it's a fresh instance and i'm unable to follow anybody on another instance..

i'm always seeing this in the log.. 

```
mastodon/mastodon-web-756444585c-4xhkm[mastodon]: [2e346c1b-923c-4747-a733-65f86bc61789] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=401 duration=295.27 view=0.70 db=3.54 key=https://mastodon.social/users/sethcotlar#main-key
```

Has anybody any idea how to get more information what causes the `401` error? I already set `RAILS_LOG_LEVEL=debug`..

**Comment by mazzy89** [comment]
Unfortunately can't say what else could be. It would require some guidance by someone definitely more navigated than me into Mastodon internals. In my case was easy but here on yours seem less clear. I would try to replicate your issue. Check out extactly what http request Mastodon does and check to replicate on your side.

**Comment by tf-anguskong** [comment]
I'm currently having this issue using Linux Servers 4.0.2 docker image as well. Where I do have a separate mastodon domain of `domain.xyz` and the web domain of `mastodon.domain.xyz`

**Comment by jpescada** [comment]
I had the same issue and just fixed it. The solution for me was like @cromulus [mentioned above](https://github.com/mastodon/mastodon/issues/19338#issuecomment-1320361943). The domain (`LOCAL_DOMAIN`) should redirect/rewrite the `./well-known` path to the one in the subdomain (`WEB_DOMAIN`) where Mastodon is installed.

**Comment by tf-anguskong** [comment]
I'm having the issue with docker (from linux server) version 4.0.2 as well. 

My `WEB_DOMAIN` and `LOCAL_DOMAIN` are different, `mastodon.example.com` and `example.com` respectively. I've used multiple cert providers because my suspicions were with Namecheaps... SSL certificate at first. I am not able to get a response on my account's `./well-known` and `./well-known/host-meta` as well. Everything looks correct.

**Comment by tf-anguskong** [comment]
Rebuilt instance from scratch using a domain that was never used before. The `LOCAL_DOMAIN` and `WEB_DOMAIN` are identical, still running into the same error as before when try to @ anyone and/or follow anyone. 

![image](https://user-images.githubusercontent.com/48041768/208316541-9848b8b6-541f-4f60-bcb9-34a90e4edaef.png)

**Comment by tf-anguskong** [comment]
Like @mazzy89 said above... make sure the SSL certificate full chain is in there. I was using the .crt from Namecheap's SSL service and it was not working. Using let's encrypt certificate resolved the issue.

**Comment by alisyd** [comment]
this started showing up after I migrated my instance to another server, It doesn't happen on the old server. I have ssl configured, ```LOCAL_DOMAIN```  is the same as ```WEB_DOMAIN``` , I am behind a router which has static ip configure, I am changing servers internally, I don't think remote servers are blocking my IP/domain. I have no clue what could be wrong, any help would be appreciated.

**Comment by litvinovg** [comment]
In my case instance was behind proxy, so I had to set Host header in nginx proxy configuration to be the same as instance public domain name to fix signature verification. 
In my case I had requests like  /users/*username*/inbox HTTP/1.1 401 in access.log

**Comment by MrScopi** [comment]
I'm facing a similar issue as far as I can tell.
Running in Docker behind an nginx reverse proxy, and after updating the proxy container (SWAG) my feed stopped updating.  I tried updating everything, but the issue remains.  Logs show that attempts to POST to the /inbox fail with 401 error codes.  I'm out of my depth at this point, so any help would be greatly appreciated.  Thanks!

**Comment by andresdegante** [comment]
> I had the same error.
> 
> My setup: I have a personal domain, my-name.org and my mastodon instance lives on mastodon.my-name.org.
> 
> LOCAL_DOMAIN=my-name.org WEB_DOMAIN=mastodon.my-name.org
> 
> The problem was that my webfinger redirect was failing.
> 
> `curl https://my-name.org/.well-known/webfinger?resource=acct:me@my-name.org` should return:
> 
> ```
> {"subject":"acct:me@my-name.org","aliases":["https://mastodon.my-name.org/@me","https://mastodon.my-name.org/users/mel"],"links":[{"rel":"http://webfinger.net/rel/profile-page","type":"text/html","href":"https://mastodon.my-name.org/@me"},{"rel":"self","type":"application/activity+json","href":"https://mastodon.my-name.org/users/mel"},{"rel":"http://ostatus.org/schema/1.0/subscribe","template":"https://mastodon.my-name.org/authorize_interaction?uri={uri}"}]}
> ```
> 
> `curl https://my-name.org/.well-known/host-meta` returns
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <XRD xmlns="http://docs.oasis-open.org/ns/xri/xrd-1.0">
>   <Link rel="lrdd" template="https://mastodon.my-name.org/.well-known/webfinger?resource={uri}"/>
> </XRD>
> ```
> 
> @BrianJKoopman that's what fixed it for me!

Sorry, where can I made this change?
