### ISSUE TITLE
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:601:in `validate_secret_key_base': `secret_key_base` for production environment must be a type of String` (ArgumentError)

### ISSUE THREAD

**Issue by DocViper** [mastodon/mastodon#19586]
### Steps to reproduce the problem

1. Installation bis zum Punkt 

2. Keys mit nano eingetragen
root@ServerName ~/mastodon # nano .env.production

3. Admin Account erstellt
root@ServerName ~/mastodon # docker-compose run --rm web tootctl accounts create DocViper --email *@*.de --confirmed --role admin

4. Starting 

Ach ja, ich kann englisch leider nur mit Übersetzer.

### Expected behaviour

Ausgabe des Admin Passwortes

### Actual behaviour

Fehlermeldung

### Detailed description

```
docker-compose run --rm web tootctl accounts create DocViper --email *@*.de --confirmed --role admin
Starting mastodon_redis_1 ... done
Starting mastodon_db_1    ... done
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:601:in `validate_secret_key_base': `secret_key_base` for production environment must be a type of String` (ArgumentError)
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:437:in `secret_key_base'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/secret_key_finder.rb:24:in `key_exists?'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/secret_key_finder.rb:16:in `find'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/devise-4.8.1/lib/devise/rails.rb:37:in `block in <class:Engine>'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `instance_exec'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:32:in `run'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:347:in `call'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
	from /opt/ruby/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/initializable.rb:60:in `run_initializers'
	from /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7/lib/rails/application.rb:391:in `initialize!'
	from /opt/mastodon/config/environment.rb:5:in `<top (required)>'
	from /opt/mastodon/lib/mastodon/media_cli.rb:4:in `require_relative'
	from /opt/mastodon/lib/mastodon/media_cli.rb:4:in `<top (required)>'
	from /opt/mastodon/lib/cli.rb:4:in `require_relative'
	from /opt/mastodon/lib/cli.rb:4:in `<top (required)>'
	from /opt/mastodon/bin/tootctl:5:in `require_relative'
	from /opt/mastodon/bin/tootctl:5:in `<main>'
```

### Specifications

Debian 10.13
Mastodon latest
Docker 18.09.1
ruby 2.5.5p157

**Comment by DocViper** [comment]
Ich habs dran gegeben

**Comment by DocViper** [comment]
aufgegeben
