### ISSUE TITLE
tootctl search deploy fails with ruby 3.0.0

### ISSUE THREAD

**Issue by mgloec** [mastodon/mastodon#19741]
### Steps to reproduce the problem

1. Clean installation of mastodon
2. Create some posts
3. Install and enable elastic search
4. run /live$ RAILS_ENV=production bin/tootctl search deploy

### Expected behaviour

Indexing runs without errors

### Actual behaviour

Indexing does fail with error Connection refused

### **Connection test with curl to 172.0.0.1:9000 passed before run /live$ RAILS_ENV=production bin/tootctl search deploy:**

```
{
  "name" : "v220220837304199125",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "c-L7JudMQYyk8iEC-eYspg",
  "version" : {
    "number" : "7.17.7",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "78dcaaa8cee33438b91eca7f5c7f56a70fec9e80",
    "build_date" : "2022-10-17T15:29:54.167373105Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

### **Connection test with curl to 172.0.0.1:9200 after deploy failed:**

```
curl: (7) Failed to connect to localhost port 9200: Connection refused
```

### **Output after exec of /live$ RAILS_ENV=production bin/tootctl search deploy:**

```
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket': Connection refused - Connection refused - connect(2) for "localhost" port 9200 (localhost:9200) (Faraday::ConnectionFailed)
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:60:in `create_socket'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
        from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
        from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:13:in `block in do_get_block'
        from /home/mastodon/.rbenv/versions/3.0.3/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:11:in `do_get_block'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:47:in `block in call'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:46:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transpo
```

### Specifications

Mastodon 3.5.3
Ruby 3.0.3p157
Postgres 15
Redis 5.07
Ubuntu 20.04.5 LTS
openjdk version "17.0.4"

**Comment by ClearlyClaire** [comment]
Seems like ElasticSearch may have crashed, what's in ElasticSearch's logs?

Also, you seem to be mixing up ports 9000 and 9200 in the commands you are describing, might worth double-checking.

**Comment by mgloec** [comment]
Thank you! Port 9000 was a typo. Here the ElasticSearch log:

```
[2022-11-04T15:45:12,605][INFO ][o.e.n.Node               ] [v220220837304199125] initialized
[2022-11-04T15:45:12,606][INFO ][o.e.n.Node               ] [v220220837304199125] starting ...
[2022-11-04T15:45:12,624][INFO ][o.e.x.s.c.f.PersistentCache] [v220220837304199125] persistent cache index loaded
[2022-11-04T15:45:12,625][INFO ][o.e.x.d.l.DeprecationIndexingComponent] [v220220837304199125] deprecation component started
[2022-11-04T15:45:12,805][INFO ][o.e.t.TransportService   ] [v220220837304199125] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {12>[2022-11-04T15:45:13,357][WARN ][o.e.b.BootstrapChecks    ] [v220220837304199125] the default discovery settings are unsuitable for production use; a>
[2022-11-04T15:45:13,359][INFO ][o.e.c.c.Coordinator      ] [v220220837304199125] cluster UUID [c-L7JudMQYyk8iEC-eYspg]
[2022-11-04T15:45:13,379][INFO ][o.e.c.c.ClusterBootstrapService] [v220220837304199125] no discovery configuration found, will perform best-effort cl>[2022-11-04T15:45:13,536][INFO ][o.e.c.s.MasterService    ] [v220220837304199125] elected-as-master ([1] nodes joined)[{v220220837304199125}{-Ybh9mqO>[2022-11-04T15:45:13,641][INFO ][o.e.c.s.ClusterApplierService] [v220220837304199125] master node changed {previous [], current [{v220220837304199125>[2022-11-04T15:45:13,757][INFO ][o.e.h.AbstractHttpServerTransport] [v220220837304199125] publish_address {127.0.0.1:9200}, bound_addresses {[::1]:92>[2022-11-04T15:45:13,758][INFO ][o.e.n.Node               ] [v220220837304199125] started
[2022-11-04T15:45:14,383][INFO ][o.e.l.LicenseService     ] [v220220837304199125] license [a81e5f7b-23cb-4564-9871-a08789d805c0] mode [basic] - valid
[2022-11-04T15:45:14,385][INFO ][o.e.x.s.s.SecurityStatusChangeListener] [v220220837304199125] Active license is now [BASIC]; Security is disabled
[2022-11-04T15:45:14,386][WARN ][o.e.x.s.s.SecurityStatusChangeListener] [v220220837304199125] Elasticsearch built-in security features are not enabl>
[2022-11-04T15:45:14,400][INFO ][o.e.g.GatewayService     ] [v220220837304199125] recovered [5] indices into cluster_state
[2022-11-04T15:45:15,368][ERROR][o.e.i.g.GeoIpDownloader  ] [v220220837304199125] exception during geoip databases update
org.elasticsearch.ElasticsearchException: not all primary shards of [.geoip_databases] index are active
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.updateDatabases(GeoIpDownloader.java:137) ~[ingest-geoip-7.17.7.jar:7.17.7]
        at org.elasticsearch.ingest.geoip.GeoIpDownloader.runDownloader(GeoIpDownloader.java:284) [ingest-geoip-7.17.7.jar:7.17.7]
        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:100) [ingest-geoip-7.17.7.jar:7.>        at org.elasticsearch.ingest.geoip.GeoIpDownloaderTaskExecutor.nodeOperation(GeoIpDownloaderTaskExecutor.java:46) [ingest-geoip-7.17.7.jar:7.1>        at org.elasticsearch.persistent.NodePersistentTasksExecutor$1.doRun(NodePersistentTasksExecutor.java:42) [elasticsearch-7.17.7.jar:7.17.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:777) [elasticsearch-7.17>        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.17.7.jar:7.17.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.lang.Thread.run(Thread.java:1589) [?:?]
[2022-11-04T15:45:15,565][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] retrieve geoip database [GeoLite2-Country.mmdb] from [.geoip_data>[2022-11-04T15:45:15,569][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] retrieve geoip database [GeoLite2-City.mmdb] from [.geoip_databas>[2022-11-04T15:45:15,569][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] retrieve geoip database [GeoLite2-ASN.mmdb] from [.geoip_database>[2022-11-04T15:45:16,156][INFO ][o.e.c.r.a.AllocationService] [v220220837304199125] Cluster health status changed from [RED] to [YELLOW] (reason: [sh>[2022-11-04T15:45:16,444][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] successfully reloaded changed geoip database file [/tmp/elasticse>[2022-11-04T15:45:16,632][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] successfully reloaded changed geoip database file [/tmp/elasticse>[2022-11-04T15:45:18,073][INFO ][o.e.i.g.DatabaseNodeService] [v220220837304199125] successfully reloaded changed geoip database file [/tmp/elasticse>[2022-11-04T15:47:34,058][WARN ][o.e.t.ThreadPool         ] [v220220837304199125] execution of [ReschedulingRunnable{runnable=org.elasticsearch.watch>[2022-11-04T15:47:45,963][WARN ][o.e.t.ThreadPool         ] [v220220837304199125] execution of [ReschedulingRunnable{runnable=org.elasticsearch.watch>[2022-11-04T15:47:56,465][WARN ][o.e.t.ThreadPool         ] [v220220837304199125] execution of [ReschedulingRunnable{runnable=org.elasticsearch.watch>
```

**Comment by ClearlyClaire** [comment]
Unfortunately, I'm not knowledgeable enough about ElasticSearch to help you on this, but it definitely sounds like a deployment issue with ElasticSearch rather than a Mastodon issue. Updating the issue tags accordingly.

Hopefully someone more knowledgeable can chime in and help you with that.

**Comment by mgloec** [comment]
Thank you for your analysis! If it is a ElasticSearch issue, i will try to do a search within elastic search support pages. But if here someone can help, I would appreciate that.

**Comment by michaelyorkpa** [comment]
I was having a similar issue, with Mastodon 3.5.3 and 4.0.2, Ruby 3.0.3 and 3.0.4, so, logically, that isolated ElasticSearch config as the issue. The main issue I was seeing was a 503 connection refused error. I was able to get to ES with telnet without issue.

I finally figured out you need to name the cluster, the node, and specify the cluster.initial_master_nodes. I set the following and I was able to do the search deploy without a problem:

cluster.name: $unique-name
node.name: node-1
cluster.initial_master_nodes: ["node-1"]

Also, be sure to set your network.host to 127.0.0.1, your http.port to 9200, and discovery.seed_hosts to empty (just brackets [] ).

Feel free to follow me @mike@social.raytec.co if this worked for you!
