### ISSUE TITLE
Sidekiq does not stop searching for Elasticsearch when ES_ENABLED is changed from true to false

### ISSUE THREAD

**Issue by fuomag9** [mastodon/mastodon#19823]
### Steps to reproduce the problem

How to:
- install mastodon via docker compose
- use the following .env.production settings (among the ones you have already)
```
# Elasticsearch (optional)
# ------------------------
ES_ENABLED=true
ES_HOST={YOURIP}
ES_PORT=9200
# Authentication for ES (optional)
ES_USER={YOURUSER}
ES_PASS={YOURPASS}
```
- change `ES_ENABLED` to false after installing
- Sidekiq will sill try to connect to elasticsearch even when jobs to retry are deleted from the Sidekiq web interface

```
| 2022-11-06T00:37:41.762Z pid=7 tid=7mx7 class=Scheduler::ScheduledStatusesScheduler jid=851ef64349f7952ed911a8d1 elapsed=0.007 INFO: done
mastodon-sidekiq-1     | 2022-11-06T00:37:41.762Z pid=7 tid=7lab WARN: Faraday::ConnectionFailed: Connection refused - Connection refused - connect(2) for "{IP}" port 9200 ({IP}:9200)
mastodon-sidekiq-1     | 2022-11-06T00:37:41.762Z pid=7 tid=7lab WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:623:in `rescue in create_socket'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:607:in `create_socket'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:60:in `create_socket'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:755:in `block in connect'
mastodon-sidekiq-1     | /opt/ruby/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
mastodon-sidekiq-1     | /opt/ruby/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:748:in `connect'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:511:in `query'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:177:in `query'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1242:in `do_get_block'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:13:in `block in do_get_block'
mastodon-sidekiq-1     | /opt/ruby/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httplog-1.5.0/lib/httplog/adapters/httpclient.rb:11:in `do_get_block'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:47:in `block in call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:46:in `call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:48:in `block in perform_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/exists.rb:51:in `block in exists'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/utils.rb:219:in `__rescue_from_not_found'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/exists.rb:50:in `exists'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/actions.rb:15:in `exists?'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/import/routine.rb:70:in `create_indexes!'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/import.rb:133:in `import_routine'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/import.rb:87:in `import!'
mastodon-sidekiq-1     | /opt/mastodon/app/workers/scheduler/indexing_scheduler.rb:14:in `block (2 levels) in perform'
mastodon-sidekiq-1     | /opt/mastodon/app/lib/redis_configuration.rb:11:in `block in with'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:63:in `block (2 levels) in with'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `handle_interrupt'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:62:in `block in with'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
mastodon-sidekiq-1     | /opt/mastodon/app/lib/redis_configuration.rb:11:in `with'
mastodon-sidekiq-1     | /opt/mastodon/app/models/concerns/redisable.rb:9:in `with_redis'
mastodon-sidekiq-1     | /opt/mastodon/app/workers/scheduler/indexing_scheduler.rb:11:in `block in perform'
mastodon-sidekiq-1     | /opt/mastodon/app/workers/scheduler/indexing_scheduler.rb:10:in `each'
mastodon-sidekiq-1     | /opt/mastodon/app/workers/scheduler/indexing_scheduler.rb:10:in `perform'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:196:in `execute_job'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-unique-jobs-7.1.22/lib/sidekiq_unique_jobs/middleware.rb:36:in `call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
mastodon-sidekiq-1     | /opt/mastodon/lib/mastodon/sidekiq_middleware.rb:7:in `call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/middleware/chain.rb:143:in `invoke'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:163:in `block in process'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:114:in `local'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:14:in `block in call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:72:in `block in wrap'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/execution_wrapper.rb:91:in `wrap'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/reloader.rb:71:in `wrap'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/rails.rb:13:in `call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:257:in `stats'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:13:in `call'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/job_retry.rb:81:in `global'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:124:in `block in dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/job_logger.rb:39:in `prepare'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:123:in `dispatch'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:162:in `process'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:78:in `process_one'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/processor.rb:68:in `run'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:56:in `watchdog'
mastodon-sidekiq-1     | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.4.2/lib/sidekiq/util.rb:65:in `block in safe_thread'
```

### Expected behaviour

sidekiq should not be trying to use elasticsearch

### Actual behaviour

sidekiq keeps trying to use elasticsearch

### Specifications

Mastodon | 3.5.3
Ruby | 3.0.3p157
PostgreSQL | 14.5
Redis | 7.0.5

**Comment by ClearlyClaire** [comment]
Fixed by #19805.
