### ISSUE TITLE
hiredis does not support SSL (NotImplemented)

### ISSUE THREAD

**Issue by haydenwalker980** [mastodon/mastodon#19824]
### Steps to reproduce the problem

1. use an SSL redis server
2. try booting up Mastodon
3. profit

### Expected behaviour

Mastodon boots and works normally

### Actual behaviour

Fails to even start - you get "hiredis does not support SSL"

### Detailed description

I'm using Heroku with modifications in https://github.com/haydenwalker980/mastodon, premium 0 plan for Redis

Full traceback:
```
2022-11-06T01:27:18.771601+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e]   
2022-11-06T01:27:18.771616+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] NotImplementedError (SSL not supported by hiredis driver):
2022-11-06T01:27:18.771617+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e]   
2022-11-06T01:27:18.771618+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] app/models/ip_block.rb:38:in `blocked?'
2022-11-06T01:27:18.771619+00:00 app[web.1]: [b1dd536a-9b1a-4786-9d8a-34d6223d956e] config/initializers/rack_attack.rb:46:in `block in <class:Attack>'
```

### Specifications

Ruby 3.0.4
Mastodon [58fc889](https://github.com/mastodon/mastodon/commit/58fc889c6fe697da4f880cb43e75d97d3a604d79)

**Comment by SamStephens** [comment]
According to https://redis.com/lp/hiredis/#using-ssl-and-hiredis

> hiredis does not support SSL connections natively. For an added security measure, you can secure the connection using [stunnel](https://redis.com/blog/stunnel-secure-redis-ssl/).

So it looks like you're going to be setting up an stunnel. (Be warned, I have not done any of this, this is just from a quick web search).

**Comment by haydenwalker980** [comment]
Fun. Looks like I'm gonna need to change some things around

**Comment by ineffyble** [comment]
I think those docs are outdated, hiredis [has supported SSL as of version 1.0.0](https://github.com/redis/hiredis/blob/master/CHANGELOG.md). The issue is Mastodon is on version 0.6 which is quite old.

**Comment by zunda** [comment]
I tried to use redis-rb and saw a huge increase in memory consumption. I'll continue looking into this but I need to add memory or reduce concurrency...
https://github.com/zunda/mastodon/commit/0545a9da3a7455d7c58308e3ee3c2e6483559116

**Comment by zunda** [comment]
It looks like the memory problem was caused by the platform: https://status.heroku.com/incidents/2468. My production server has now been on redis-rb for 30 minutes (right half) and running fine as was on hiredis (left half) :)

![Screenshot_2022-11-16_10-04-22](https://user-images.githubusercontent.com/30968/202282886-ce4170ca-4e49-4036-b3d0-acc5a611b251.png)

**Comment by ineffyble** [comment]
@Gargron I think you were involved in the Redis config we have today. Do you know of a reason we can't deprecate hiredis and swap to native redis-rb driver? (See commit above for an example)

**Comment by zunda** [comment]
I'm actually noticing more frequent spikes in response time along with higher CPU load, once in a couple of hours. I'm currently using three of hobby-dev (free) Heroku Redis. I'll upgrade it to single Premium-0 and see what'd happen.

![Screenshot_2022-11-16_16-34-53](https://user-images.githubusercontent.com/30968/202340901-f9f4de2a-32fd-489a-9109-77e438ab4e25.png)

**Comment by lifeofguenter** [comment]
This means that unfortunately mastodon will not work with DigitalOceans Managed Redis (it forces TLS)

**Comment by Jorijn** [comment]
Mastodon itself does not. I use DO Managed Redis with HAProxy in between.

**Comment by goloroden** [comment]
@lifeofguenter Same problem on my site as well.

@Jorijn Yes, that's a viable option. However, I'd rather call it a "workaround" than a "solution" (I know that you didn't call it that either).

**Comment by MikeHuntington** [comment]
> 

Not by default. I had to use Stunnel to get it working (which was super easy to setup): https://www.digitalocean.com/community/tutorials/how-to-connect-to-managed-redis-over-tls-with-stunnel-and-redis-cli

**Comment by ChadOhman** [comment]
I'd just like to +1 this work, here using DO"s Managed Redis and Stunnel is probably our weakest point in the chain. If our instance goes down, 80% of the time it's Stunnel. Having Mastodon support Redis over TLS would be a complete game changer.

Thanks

**Comment by Jorijn** [comment]
> I'd just like to +1 this work, here using DO"s Managed Redis and Stunnel is probably our weakest point in the chain. If our instance goes down, 80% of the time it's Stunnel. Having Mastodon support Redis over TLS would be a complete game changer.
> 
> Thanks

We've been running HAProxy for this same reason but it's rock solid. Our config is a 1:1 steal should you want to experiment: https://github.com/toot-community/kubernetes/blob/main/haproxy-chart/templates/configmap.yaml

**Comment by ChadOhman** [comment]
@Jorijn I'll give it a shot but ultimately I'd prefer to avoid middleware altogether!

**Comment by jodok** [comment]
i'm running mastodon on AWS with elasticache. if one wants to use authentication, TLS is required. so +1
