### ISSUE TITLE
[rc2, omniauth]: SAML seems to return internal server error due to missing strategy.display_name

### ISSUE THREAD

**Issue by samip5** [mastodon/mastodon#19913]
### Steps to reproduce the problem

1. Checkouut v4.0.0rc2 version
2. Set it up like normal
3. Setup SAML
4. Try to use SAML
5. See that display name is not displayed correctly despite it being set and returning to Mastodon after SAML results in internal servver error (HTTP status 500).

### Expected behaviour

I would have expected to be logged in via SAML

### Actual behaviour

Error 500, aka something went wrong page was displayed

### Detailed description

```
Nov 06 23:34:40 bundle[262420]: [34eda713-86bf-4eb5-bf78-cfa84d747e85] method=GET path=/auth/sign_in format=html controller=Auth::SessionsController action=new status=200 duration=208.46 view=200.34 db=0.00
Nov 06 23:34:42 bundle[262420]: I, [2022-11-06T23:34:42.130818 #262420]  INFO -- omniauth: (saml) Request phase initiated.
Nov 06 23:34:44 bundle[262420]: I, [2022-11-06T23:34:44.395744 #262420]  INFO -- omniauth: (saml) Callback phase initiated.
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe] method=GET path=/auth/auth/saml/callback format=html controller=Auth::OmniauthCallbacksController action=saml status=500 error='NoMethodError: >
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe]
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe] NoMethodError (undefined method `capitalize' for nil:NilClass):
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe]
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe] app/controllers/auth/omniauth_callbacks_controller.rb:21:in `block in provides_callback_for'
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe] app/controllers/concerns/localized.rb:11:in `set_locale'
Nov 06 23:34:44 bundle[262420]: [1fb9eca5-a342-49b9-8daa-c08e4cfa6cbe] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

Mastodon v4.0.0rc2.

**Comment by ClearlyClaire** [comment]
Hi! Sorry about that. Can you give #19962 a try?
