### ISSUE TITLE
Redis connection error when running first time setup using Docker

### ISSUE THREAD

**Issue by BrianAllred** [mastodon/mastodon#20086]
### Steps to reproduce the problem

1. Proceed through standard Docker setup using `docker-compose run --rm web bundle exec rake mastodon:setup`
2. Use default values for postgres and redis
3. Proceed through setup, hitting enter after entering an email for the new admin user

### Expected behaviour

Setup continues successfully

### Actual behaviour

Stack trace

### Detailed description

Running the task with `--trace` yielded the following stack trace

```
rake aborted!
Redis::CannotConnectError: Error connecting to Redis on localhost:6379 (Errno::ECONNREFUSED)
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:398:in `rescue in establish_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:379:in `establish_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:234:in `call_pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:201:in `block in call_pipeline'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:199:in `call_pipeline'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:2671:in `block in pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
/opt/ruby/lib/ruby/3.0.0/monitor.rb:202:in `synchronize'
/opt/ruby/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:2667:in `pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:201:in `block in raw_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:198:in `raw_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:79:in `push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:360:in `client_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:198:in `perform_async'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:289:in `perform_async'
/opt/mastodon/app/models/user.rb:519:in `trigger_webhooks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:260:in `block in conditional'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `block in invoke_after'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `invoke_after'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:107:in `run_callbacks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:824:in `_run_commit_callbacks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:321:in `committed!'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:351:in `block in within_new_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:298:in `save'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:44:in `save'
/opt/mastodon/lib/tasks/mastodon.rake:438:in `block (2 levels) in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/bin/rake:25:in `load'
/opt/mastodon/vendor/bundle/ruby/3.0.0/bin/rake:25:in `<top (required)>'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
/opt/ruby/bin/bundle:23:in `load'
/opt/ruby/bin/bundle:23:in `<main>'

Caused by:
Errno::ECONNREFUSED: Connection refused
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/connection/hiredis.rb:20:in `connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/connection/hiredis.rb:20:in `connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:385:in `establish_connection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:117:in `block in connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:116:in `connect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:417:in `ensure_connected'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:269:in `block in process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:356:in `logging'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:268:in `process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:234:in `call_pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:201:in `block in call_pipeline'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:344:in `with_reconnect'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis/client.rb:199:in `call_pipeline'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:2671:in `block in pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `block in synchronize'
/opt/ruby/lib/ruby/3.0.0/monitor.rb:202:in `synchronize'
/opt/ruby/lib/ruby/3.0.0/monitor.rb:202:in `mon_synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:72:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/redis-4.5.1/lib/redis.rb:2667:in `pipelined'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:201:in `block in raw_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:65:in `block (2 levels) in with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:64:in `block in with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/connection_pool-2.3.0/lib/connection_pool.rb:61:in `with'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:198:in `raw_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/client.rb:79:in `push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:360:in `client_push'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:198:in `perform_async'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.7/lib/sidekiq/worker.rb:289:in `perform_async'
/opt/mastodon/app/models/user.rb:519:in `trigger_webhooks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:427:in `block in make_lambda'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:260:in `block in conditional'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `block in invoke_after'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:516:in `invoke_after'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:107:in `run_callbacks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:824:in `_run_commit_callbacks'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:321:in `committed!'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:155:in `commit_records'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:304:in `block in commit_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:294:in `commit_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:351:in `block in within_new_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/transactions.rb:298:in `save'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7/lib/active_record/suppressor.rb:44:in `save'
/opt/mastodon/lib/tasks/mastodon.rake:438:in `block (2 levels) in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.0.0/bin/rake:25:in `load'
/opt/mastodon/vendor/bundle/ruby/3.0.0/bin/rake:25:in `<top (required)>'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `load'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli/exec.rb:23:in `run'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:486:in `exec'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:31:in `dispatch'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/cli.rb:25:in `start'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:48:in `block in <top (required)>'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/opt/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.25/exe/bundle:36:in `<top (required)>'
/opt/ruby/bin/bundle:23:in `load'
/opt/ruby/bin/bundle:23:in `<main>'
Tasks: TOP => mastodon:setup
```

### Specifications

Mastodon 4.0.0rc2
Docker 20.10.21
Docker Compose 2.12.2
Arch Linux (linux kernel 5.15.77-1-lts)

**Comment by matthewford** [comment]
The defaults are assuming redis is running on your localhost, which in docker it is not, you would also need to run Redis in docker and pass in the env variables for the connection https://docs.joinmastodon.org/admin/config/

**Comment by BrianAllred** [comment]
The default docker-compose.yml has a redis service defined. According to the configuration, it should share the internal-network with the other services and be available at hostname `redis`, which the setup task looks for by default.

**Comment by BrianAllred** [comment]
Actually, upon further inspection, for some reason the setup task sets the correct hostname (`redis`) during setup, but uses `localhost` when attempting to connect. Something seems weird there.

**Comment by matthewford** [comment]
https://github.com/mastodon/mastodon/blob/main/lib/mastodon/redis_config.rb#L10

The first redis connection, by default tries to connection to localhost, not sure but this was introduced in https://github.com/mastodon/mastodon/blob/main/lib/mastodon/redis_config.rb#L25, the config file I think needs to be reworked, so that you can just set the CACHE_REDIS variables, but you try making the env variables for REDIS_HOST etc the same as the CACHE and that should then work.

**Comment by claudioc** [comment]
In your `env.production` set `REDIS_HOST=redis` 

Using docker-compose, the name of the "host" must match the name of the image running redis.

Same for the `DB_HOST=db`

**Comment by gmorenz** [comment]
I ran into what I think is the same issue. If so, it's user error, but user error that the tool could do a better job of avoiding.

In short, the issue is just not following the instruction to "save [the configuration] to an .env.production file outside Docker".

During setup it prints the following, I've added `$ ` in front of prompts that ask for user input even though they aren't there in the actual output

```
This configuration will be written to .env.production
$ Save configuration? Yes
Below is your configuration, save it to an .env.production file outside Docker:

# Generated with mastodon:setup on 2022-11-15 18:09:52 UTC

LOCAL_DOMAIN=test.political-cinema.droid.cafe
SINGLE_USER_MODE=true
SECRET_KEY_BASE=<removed>
OTP_SECRET=<removed>
VAPID_PRIVATE_KEY=<removed>
VAPID_PUBLIC_KEY=<removed>
DB_HOST=db
DB_PORT=5432
DB_NAME=postgres
DB_USER=postgres
DB_PASS=<removed>
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=<removed>
SMTP_SERVER=localhost
SMTP_PORT=25
SMTP_AUTH_METHOD=none
SMTP_OPENSSL_VERIFY_MODE=none
SMTP_ENABLE_STARTTLS=auto
SMTP_FROM_ADDRESS=<removed>

It is also saved within this container so you can proceed with this wizard.

Now that configuration is saved, the database schema must be loaded.
If the database already exists, this will erase its contents.
$ Prepare the database now? Yes
```

It's telling me to "Below is your configuration, save it to an .env.production file outside Docker:", but I (and I think OP) completely read over that this was an instruction that I was supposed to follow. I don't think it's that surprising that we read over this

 - I had just been told that "This configuration will be written to .env.production"
 - I had just been instructed that "<for reason> I can proceed with this wizard"
 - I had just instructed the install script to save the thing that I was then told to save by hand
 - The instruction to save the thing was "buried" at the top of a bunch of lines of terminal output.

I'd propose changing the "Save configuration" prompt so that it appears after the configuration is printed, and to be a prompt for the user to copy the configuration into `.env.production`. I'd also consider changing the "you can proceed with this wizard." text to "you can proceed with this wizard after copying the configuration to .env.production" - but that may be redundant with the first proposal.

**Comment by robconery** [comment]
I'm trying to troubleshoot the same issue and I think it's due to this:

```ruby
    # When the application code gets loaded, it runs `lib/mastodon/redis_configuration.rb`.
    # This happens before application environment configuration and sets REDIS_URL etc.
    # These variables are then used even when REDIS_HOST etc. are changed, so clear them
    # out so they don't interfere with our new configuration.
    ENV.delete('REDIS_URL')
    ENV.delete('CACHE_REDIS_URL')
    ENV.delete('SIDEKIQ_REDIS_URL')
```

The URLs for these things aren't being set, so when the default user is added, and error is thrown. This should be fixable by setting the URLs when the Redis dialogs are set.

**Comment by robconery** [comment]
OK I can confirm this. If you're using docker, your best choice is to set a REDIS_URL in the environment and things work nicely.

**Comment by shukriadams** [comment]
This still seems to be an issue. I'm getting it on the mastodon/mastodon:v4.2.5 container image.

When I set an env var on the mastadon web container in my docker-compose file ``REDIS_URL=redis` compose up fails immediately with 

#ArgumentError: invalid uri scheme ''

As .env.production is currently not working/used when running in docker, where exactly should we set the the redis url?

**Comment by shukriadams** [comment]
This still seems to be an issue, getting it on the latest container image (ghcr.io/mastodon/mastodon:v4.2.5), though it appears you can ignore the errors, ensure your settings are written to .env.production, restart your compose and your admin user is there. Sometimes.
