### ISSUE TITLE
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0

### ISSUE THREAD

**Issue by jamincollins** [mastodon/mastodon#20280]
### Steps to reproduce the problem

1. Install `mastodon` on Arch Linux
2. Attempt to run `RAILS_ENV=production bundle exec rails mastodon:setup`

### Expected behaviour

Setup should work

### Actual behaviour

Aborts with the above error and a stack trace

### Detailed description

```
[mastodon@mastodon ~]$ RAILS_ENV=production bundle exec rails mastodon:setup
Your instance is identified by its domain name. Changing it afterward will break things.
Domain name: ...

Single user mode disables registrations and redirects the landing page to your public profile.
Do you want to enable single user mode? No
rails aborted!
OpenSSL::PKey::PKeyError: pkeys are immutable on OpenSSL 3.0
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/webpush-0.3.8/lib/webpush/vapid_key.rb:33:in `generate_key!'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/webpush-0.3.8/lib/webpush/vapid_key.rb:33:in `initialize'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/webpush-0.3.8/lib/webpush.rb:52:in `new'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/webpush-0.3.8/lib/webpush.rb:52:in `generate_key'
/var/lib/mastodon/lib/tasks/mastodon.rake:37:in `block (2 levels) in <top (required)>'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/command.rb:50:in `invoke'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<top (required)>'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/var/lib/mastodon/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.11.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
Tasks: TOP => mastodon:setup
(See full trace by running task with --trace)
```

### Specifications

Mastodon 3.5.3
Ruby 3.0.4p208
Node.js 19.0.1

**Comment by ineffyble** [comment]
This is fixed in #18449.
