### ISSUE TITLE
SMTP Mailing not working with docker: SSL Error wrong version number

### ISSUE THREAD

**Issue by eitch** [mastodon/mastodon#20310]
### Steps to reproduce the problem

I've setup a new docker environment:
1. copy docker-compose.yml from v3.5.3
2. modified all images to use tootsuite/mastodon:v3.5.3
3. prepared a .env.production file
4. prepared the setup with `sudo docker-compose run --rm web bundle exec rake mastodon:setup`
5. Could not configure SMTP in the setup.
6. configured SMTP as follows:
```
SMTP_SERVER=smtp-relay.sendinblue.com
SMTP_PORT=587
SMTP_LOGIN=XXX@mydomain.ch
SMTP_PASSWORD=my-password-with-no-special-chars
SMTP_FROM_ADDRESS=XXX@mydomain.ch
SMTP_SSL=true
SMTP_TLS=true
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_AUTH_METHOD=plain
SMTP_OPENSSL_VERIFY_MODE=none
```
7. Updated and restarted the containers:
```bash
sudo docker compose stop
sudo docker compose rm
sudo docker compose up -d
```
8. follow logs and retry the job in sidekiq

### Expected behaviour

A mail is send to the SMTP server

### Actual behaviour

OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error:  wrong version number)

### Detailed description

```
mastodon-sidekiq  | 2022-11-10T08:33:05.764Z pid=7 tid=2drz class=ActionMailer::MailDeliveryJob jid=88f4821f92c539d9ab308e92 INFO: start
mastodon-sidekiq  | [ActiveJob] [ActionMailer::MailDeliveryJob] [12b72366-89b0-4088-8121-72a545d54594] Performing ActionMailer::MailDeliveryJob (Job ID: 12b72366-89b0-4088-8121-72a545d54594) from Sidekiq(default) enqueued at 2022-11-10T07:48:40Z with arguments: "UserMailer", "reset_password_instruct
ions", "deliver_now", {:args=>[#<GlobalID:0x00007f73db11eeb8 @uri=#<URI::GID gid://mastodon/User/1>>, "XXXXX"]}
mastodon-sidekiq  | [ActiveJob] [ActionMailer::MailDeliveryJob] [12b72366-89b0-4088-8121-72a545d54594] Delivered mail XXXX@mydomain.ch (135.1ms)
mastodon-sidekiq  | [ActiveJob] [ActionMailer::MailDeliveryJob] [12b72366-89b0-4088-8121-72a545d54594] Error performing ActionMailer::MailDeliveryJob (Job ID: 12b72366-89b0-4088-8121-72a545d54594) from Sidekiq(default) in 289.86ms: OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: 
wrong version number):
mastodon-sidekiq  | /opt/ruby/lib/ruby/3.0.0/net/protocol.rb:46:in `connect_nonblock'
mastodon-sidekiq  | /opt/ruby/lib/ruby/3.0.0/net/protocol.rb:46:in `ssl_socket_connect'
mastodon-sidekiq  | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:624:in `tlsconnect'
mastodon-sidekiq  | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:591:in `do_start'
mastodon-sidekiq  | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:557:in `start'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/base.rb:559:in `block in deliver_mail'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `block in instrument'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.6/lib/active_support/notifications.rb:203:in `instrument'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/base.rb:557:in `deliver_mail'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
mastodon-sidekiq  | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.6/lib/action_mailer/mail_delivery_job.rb:23:in `perform'

```

### Specifications

Mastodon docker container v3.5.3

**Comment by ineffyble** [comment]
Try this:
```
SMTP_SSL=false
SMTP_TLS=false
SMTP_ENABLE_STARTTLS_AUTO=true
```

The error suggests it's trying to negotiate an SSL/TLS connection and failing. Port 587 is often used for STARTTLS, and some other sources on the internet suggest that's what `smtp-relay.sendinblue.com` expects.

**Comment by eitch** [comment]
Thank you, thank you, thank you! This has been really annoying and your link was just what i needed!
