### ISSUE TITLE
sidekiq: errors found during processing

### ISSUE THREAD

**Issue by Izorkin** [mastodon/mastodon#20349]
### Steps to reproduce the problem

Run journalctl -f --unit=mastodon-sidekiq --unit=mastodon-streaming --unit=mastodon-web
There will be errors like this in log:

```
web sidekiq[83998]: 2022-11-10T18:45:33.809Z pid=83998 tid=2mxz6 class=ActivityPub::ProcessingWorker jid=4f9da5b1f99fc2694c75d5a6 INFO: start
web sidekiq[83998]: 2022-11-10T18:45:36.764Z pid=83998 tid=2f8vq class=ActivityPub::DeliveryWorker jid=8a2a82fa8e915ffbf2bd44ab INFO: start
web sidekiq[83998]: 2022-11-10T18:45:37.416Z pid=83998 tid=2fk7m class=ActivityPub::ProcessingWorker jid=39069d4290a1859f7761b4d6 INFO: start
web sidekiq[83998]: ERROR Statement #<RDF::Statement:0x42f5e0(<_site1_/activity/c8fb136a-8371-4bb1-ae80-c9ee3c73195f> <https://www.w3.org/ns/activitystreams#published> "2022-11-10 10:35:58"^^<http://www.w3.org/2001/XMLSchema#dateTime> .)> is invalid
web sidekiq[83998]: 2022-11-10T18:45:37.755Z pid=83998 tid=2fk7m class=ActivityPub::ProcessingWorker jid=39069d4290a1859f7761b4d6 INFO: Adding dead ActivityPub::ProcessingWorker job 39069d4290a1859f7761b4d6
web sidekiq[83998]: 2022-11-10T18:45:37.770Z pid=83998 tid=2fk7m class=ActivityPub::ProcessingWorker jid=39069d4290a1859f7761b4d6 elapsed=0.354 INFO: fail
web sidekiq[83998]: 2022-11-10T18:45:37.770Z pid=83998 tid=2fk7m WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"default","backtrace":true,"args":[109167144249698103,"{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\",\"_site1_/apschema/v1.10\"],\"type\":\"Like\",\"id\":\"_site1_/activity/...\",\"diaspora:guid\":\"...\",\"published\":\"2022-11-10 10:35:58\",\"inReplyTo\":\"https://_site2_/item/...\",\"actor\":\"_site1_/channel/_channel1_\",\"object\":{\"type\":\"Note\",\"id\":\"https://_site2_/item/...\",\"diaspora:guid\":\"...\",\"published\":\"2022-11-10T09:27:46Z\",\"commentPolicy\":\"authenticated\",\"attributedTo\":\"https://_site2_/followers/_name2_\",\"content\":\"...",\"source\":{\"content\":\"...",\"mediaType\":\"text/bbcode\"},\"actor\":\"https://_site2_/followers/_name2_\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[]},\"attachment\":[{\"type\":\"PropertyValue\",\"name\":\"zot.diaspora.fields\",\"value\":{\"positive\":\"true\",\"guid\":\"...\",\"author\":\"_name1_w@_site1_\",\"parent_type\":\"Post\",\"parent_guid\":\"...\",\"author_signature\":\"AWA8Jk...trv6Sis=\"}}],\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"_site1_/followers/_channel1_\",\"https://_site2_/followers/_name2_\"],\"signature\":{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://w3id.org/security/v1\"],\"type\":\"RsaSignature2017\",\"nonce\":\"49e17...29baf\",\"creator\":\"_site1_/channel/_channel1_\",\"created\":\"2022-11-10T10:35:58Z\",\"signatureValue\":\"XxV...i86RyY=\"}}",null,"Account"],"class":"ActivityPub::ProcessingWorker","jid":"39069...4d6","created_at":1668077037.7773259,"enqueued_at":1668105937.4160738,"error_message":"Errors found during processing","error_class":"RDF::WriterError","failed_at":1668077037.8977358,"retry_count":7,"error_backtrace":"eJzFk...PwOaEQ==\n","retried_at":1668082084.602896}}
web sidekiq[83998]: 2022-11-10T18:45:37.770Z pid=83998 tid=2fk7m WARN: RDF::WriterError: Errors found during processing
web sidekiq[83998]: 2022-11-10T18:45:37.770Z pid=83998 tid=2fk7m WARN: /nix/store/lq429vwxg8bv25wjr7faj2di6d8abiqf-mastodon-gems-4.0.0rc2/lib/ruby/gems/3.0.0/gems/rdf-3.2.9/lib/rdf/writer.rb:427:in `write_epilogue'
web sidekiq[83998]: /nix/store/lq429vwxg8bv25wjr7faj2di6d8abiqf-mastodon-gems-4.0.0rc2/lib/ruby/gems/3.0.0/gems/rdf-normalize-0.5.0/lib/rdf/normalize/writer.rb:64:in `write_epilogue'
web sidekiq[83998]: /nix/store/lq429vwxg8bv25wjr7faj2di6d8abiqf-mastodon-gems-4.0.0rc2/lib/ruby/gems/3.0.0/gems/rdf-3.2.9/lib/rdf/writer.rb:297:in `initialize'


```

### Expected behaviour

The log does not contain these errors

### Actual behaviour

There are errors in log

### Specifications

Mastodon 4.0.0rc2
Ruby 3.0.4
Nodejs 18.9.1

Vivaldi 5.5.2805.38 (Chrome/106.0.0.0)

**Comment by vmstan** [comment]
@Izorkin are you still having this issue or can it be closed?

**Comment by Izorkin** [comment]
I didn’t find this error in the logs.
