### ISSUE TITLE
Cannot get dev container running in windows

### ISSUE THREAD

**Issue by CEbbinghaus** [mastodon/mastodon#20466]
### Steps to reproduce the problem

1. Clone repository
2. Open in Visual Studio Code
3. Click on "Open workspace in container"
Crash.

### Expected behaviour

It opens a dev environment within the container

### Actual behaviour

It crashes

### Detailed description

Important messsage:
```
unable to prepare context: unable to get relative Dockerfile path: Rel: can't make C:\Users\CEbbi\AppData\Local\Temp\devcontainercli\container-features\0.23.2-1668215115076\Dockerfile-with-features relative to \\?\c:\Users\CEbbi\Projects\mastodon\.devcontainer
```
When searching for that error I came across only a single Github issue which doesn't outline how the problem was solved but rather that it was: https://github.com/dotnet/tye/issues/153

Would be nice to be able to work on Mastodon and having a dev container to manage the environment is crucial to being able to do that.

Full Logs:
```
[195 ms] Dev Containers 0.262.3 in VS Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075).
[195 ms] Start: Resolving Remote
[218 ms] Setting up container for folder or workspace: c:\Users\CEbbi\Projects\mastodon
[221 ms] Start: Check Docker is running
[221 ms] Start: Run: docker version --format {{.Server.APIVersion}}
[432 ms] Server API version: 1.41
[433 ms] Start: Run: docker volume ls -q
[622 ms] Start: Run: docker ps -q -a --filter label=vsch.local.folder=c:\Users\CEbbi\Projects\mastodon --filter label=vsch.quality=stable
[772 ms] Start: Run: docker ps -q -a --filter label=devcontainer.local_folder=c:\Users\CEbbi\Projects\mastodon
[912 ms] Start: Run: C:\Users\CEbbi\scoop\apps\vscode\1.72.2\Code.exe --ms-enable-electron-run-as-node c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\user-data\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\CEbbi\Projects\mastodon --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\CEbbi\Projects\mastodon --log-level debug --log-format json --config c:\Users\CEbbi\Projects\mastodon\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[1202 ms] (node:57740) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1202 ms] (Use `Code --trace-deprecation ...` to show where the warning was created)
[1202 ms] @devcontainers/cli 0.23.2. Node.js v16.14.2. win32 10.0.22621 x64.
[1202 ms] Start: Run: docker buildx version
[1440 ms] github.com/docker/buildx v0.8.2 6224def4dd2c3d347eee19db595348c50d7cb491
[1440 ms] 
[1440 ms] Start: Resolving Remote
[1443 ms] Start: Run: docker-compose version --short
[2417 ms] Docker Compose version: 1.29.2
[2417 ms] Start: Run: docker ps -q -a --filter label=com.docker.compose.project=mastodon_devcontainer --filter label=com.docker.compose.service=app
[2558 ms] Start: Run: docker-compose -f c:\Users\CEbbi\Projects\mastodon\.devcontainer\docker-compose.yml config
[3112 ms] networks:
  external_network: {}
  internal_network:
    internal: true
services:
  app:
    build:
      args:
        NODE_VERSION: '14'
        VARIANT: 3.0-bullseye
      context: c:\Users\CEbbi\Projects\mastodon\.devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      DB_HOST: db
      DB_PASS: postgres
      DB_PORT: '5432'
      DB_USER: postgres
      ES_ENABLED: "true"
      ES_HOST: es
      ES_PORT: '9200'
      LIBRE_TRANSLATE_ENDPOINT: http://libretranslate:5000
      NODE_ENV: development
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    networks:
      external_network: null
      internal_network: null
    user: vscode
    volumes:
    - c:\Users\CEbbi\Projects\mastodon:/workspaces/mastodon:cached
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:14-alpine
    networks:
      internal_network: null
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
  es:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
      cluster.name: es-mastodon
      discovery.type: single-node
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    networks:
      internal_network: null
    restart: unless-stopped
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - es-data:/usr/share/elasticsearch/data:rw
  libretranslate:
    image: libretranslate/libretranslate:v1.2.9
    networks:
      internal_network: null
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    networks:
      internal_network: null
    restart: unless-stopped
    volumes:
    - redis-data:/data:rw
version: '3'
volumes:
  es-data: {}
  postgres-data: {}
  redis-data: {}

[3115 ms] Start: Run: docker events --format {{json .}} --filter event=start
[3122 ms] PersistedPath=c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\user-data\User\globalStorage\ms-vscode-remote.remote-containers\data, ContainerHasLabels=false
[3122 ms] Start: Run: docker-compose -f c:\Users\CEbbi\Projects\mastodon\.devcontainer\docker-compose.yml config
[3642 ms] networks:
  external_network: {}
  internal_network:
    internal: true
services:
  app:
    build:
      args:
        NODE_VERSION: '14'
        VARIANT: 3.0-bullseye
      context: c:\Users\CEbbi\Projects\mastodon\.devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    environment:
      DB_HOST: db
      DB_PASS: postgres
      DB_PORT: '5432'
      DB_USER: postgres
      ES_ENABLED: "true"
      ES_HOST: es
      ES_PORT: '9200'
      LIBRE_TRANSLATE_ENDPOINT: http://libretranslate:5000
      NODE_ENV: development
      RAILS_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: '6379'
    networks:
      external_network: null
      internal_network: null
    user: vscode
    volumes:
    - c:\Users\CEbbi\Projects\mastodon:/workspaces/mastodon:cached
  db:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:14-alpine
    networks:
      internal_network: null
    restart: unless-stopped
    volumes:
    - postgres-data:/var/lib/postgresql/data:rw
  es:
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      bootstrap.memory_lock: "true"
      cluster.name: es-mastodon
      discovery.type: single-node
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    networks:
      internal_network: null
    restart: unless-stopped
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - es-data:/usr/share/elasticsearch/data:rw
  libretranslate:
    image: libretranslate/libretranslate:v1.2.9
    networks:
      internal_network: null
    restart: unless-stopped
  redis:
    image: redis:6-alpine
    networks:
      internal_network: null
    restart: unless-stopped
    volumes:
    - redis-data:/data:rw
version: '3'
volumes:
  es-data: {}
  postgres-data: {}
  redis-data: {}

[3648 ms] Start: Run: docker inspect --type image mcr.microsoft.com/vscode/devcontainers/ruby:3.0-bullseye
[4324 ms] local container features stored at: C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\node_modules\vscode-dev-containers\container-features
[4324 ms] Start: Run: tar --no-same-owner -x -f -
[4376 ms] Docker Compose override file for building image:
version: '3'

services:
  app:
    build:
      dockerfile: C:\Users\CEbbi\AppData\Local\Temp\devcontainercli\container-features\0.23.2-1668215115076\Dockerfile-with-features
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label

[4376 ms] Start: Run: docker-compose --project-name mastodon_devcontainer -f c:\Users\CEbbi\Projects\mastodon\.devcontainer\docker-compose.yml -f c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\user-data\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1668215115129.yml build
redis uses an image, skipping
libretranslate uses an image, skipping
db uses an image, skipping
es uses an image, skipping
Building app
unable to prepare context: unable to get relative Dockerfile path: Rel: can't ma
ke C:\Users\CEbbi\AppData\Local\Temp\devcontainercli\container-features\0.23.2-1
668215115076\Dockerfile-with-features relative to \\?\c:\Users\CEbbi\Projects\ma
stodon\.devcontainer
ERROR: Service 'app' failed to build : Build failed
[5216 ms] Error: Command failed: docker-compose --project-name mastodon_devcontainer -f c:\Users\CEbbi\Projects\mastodon\.devcontainer\docker-compose.yml -f c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\user-data\User\globalStorage\ms-vscode-remote.remote-containers\data\docker-compose\docker-compose.devcontainer.build-1668215115129.yml build
[5216 ms]     at cF (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1849:431)
[5217 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
[5217 ms]     at async eoe (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1849:2433)
[5217 ms]     at async Qse (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1831:2396)
[5217 ms]     at async voe (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1893:2222)
[5217 ms]     at async Xf (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:1893:3212)
[5217 ms]     at async Jae (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:2013:15058)
[5217 ms]     at async Wae (C:\Users\CEbbi\scoop\persist\vscode\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js:2013:14812)
[5226 ms] Exit code 1
[5229 ms] Command failed: C:\Users\CEbbi\scoop\apps\vscode\1.72.2\Code.exe --ms-enable-electron-run-as-node c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\extensions\ms-vscode-remote.remote-containers-0.262.3\dist\spec-node\devContainersSpecCLI.js up --user-data-folder c:\Users\CEbbi\scoop\apps\vscode\1.72.2\data\user-data\User\globalStorage\ms-vscode-remote.remote-containers\data --workspace-folder c:\Users\CEbbi\Projects\mastodon --workspace-mount-consistency cached --id-label devcontainer.local_folder=c:\Users\CEbbi\Projects\mastodon --log-level debug --log-format json --config c:\Users\CEbbi\Projects\mastodon\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root true
[5229 ms] Exit code 1
```

### Specifications

Branch: main@53817294f
OS: Win11 22H2 22621.674
VSCode: V1.72.2
Docker Engine v20.10.14

**Comment by mjankowski** [comment]
We did a bunch of updating to the devcontainers defs a few months ago -- I'm going to close this on assumption that is fixed now, but please re-open with logging (from current versions) if not!
