### ISSUE TITLE
S3 Bucket Can't attach files to posts... error log shows Aws::Sigv4::Errors::MissingCredentialsError

### ISSUE THREAD

**Issue by capcom1701** [mastodon/mastodon#20508]
### Steps to reproduce the problem

1. Attempt to attach an image to a toot.
2. Image attempts to load and throws a server 500 error.
3. Potentially related, I can't see emojis in the dropdown box on the post editor. I can click on an empty box, and the correct emoji will appear in the toot, but the icons aren't in the dropdown box. 
4. Potentially related, if I dump my browser cache, I cannot log in... the username/password works, but the 2FA returns mastodon pounding keyboard. I have to go into CLI, disable 2FA for the user, log in through the website, and reconnect 2FA.
...

Thanks in advance for any assistance you can provide.

### Expected behaviour

image should attach to post

### Actual behaviour

Server sends 500 error

### Detailed description

I'm using an S3 Bucket through Digitalocean. 

Once I enabled the bucket, my account seems to function normally, I see avatars, etc. But I cannot attach an image to a post. 

in the journalctl -u mastodon-web I see:

> "Aws::Sigv4::Errors::MissingCredentialsError (missing credentials, provide crede>
>- :access_key_id and :secret_access_key
>- :credentials
>- :credentials_provider):"

The journal lines leading into the error are:
`[903ea8c6-1750-4d3e-8617-8900b740b019] lib/paperclip/attachment_extensions.rb:84:in `block in save'
[903ea8c6-1750-4d3e-8617-8900b740b019] lib/paperclip/attachment_extensions.rb:90:in `save'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/models/account.rb:344:in `save_with_optional_media!'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/process_account_service.rb:76:in `update_account'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/process_account_service.rb:29:in `block in call'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/models/concerns/lockable.rb:12:in `block (2 levels) in with_lock'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/models/concerns/lockable.rb:10:in `block in with_lock'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/lib/redis_configuration.rb:11:in `block in with'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/lib/redis_configuration.rb:11:in `with'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/models/concerns/redisable.rb:9:in `with_redis'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/models/concerns/lockable.rb:9:in `with_lock'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/process_account_service.rb:21:in `call'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/fetch_remote_account_service.rb:31:in `call'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/fetch_remote_key_service.rb:39:in `find_account'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/services/activitypub/fetch_remote_key_service.rb:26:in `call'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/controllers/concerns/signature_verification.rb:222:in `block in account_from_key_id'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/controllers/concerns/signature_verification.rb:235:in `stoplight_wrap_request'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/controllers/concerns/signature_verification.rb:222:in `account_from_key_id'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/controllers/concerns/signature_verification.rb:81:in `signed_request_account'
[903ea8c6-1750-4d3e-8617-8900b740b019] app/controllers/concerns/signature_verification.rb:49:in `require_signature!'
[903ea8c6-1750-4d3e-8617-8900b740b019] lib/mastodon/rack_middleware.rb:9:in `call'`

My sanitized s3 bucket text in my .env.production file looks like this:

#S3 Bucket
S3_ENABLED=true
S3_PROTOCOL=https
S3_BUCKET=foo
S3_REGION=us-east-1
S3_HOSTNAME=foo.nyc3.digitaloceanspaces.com
S3_ENDPOINT=https://nyc3.digitaloceanspaces.com
S3_ACCESS_KEY_ID=Digitalocean key
S3_SECRET_ACCESS_KEY=Digitalocean secret
S3_ALIAS_HOST=images.foo.com
S3_FORCE_SINGLE_REQUEST=true

I should also point out that the setup tutorial I used had me use Cloudflare. 

### Specifications

Ubuntu 20.04.5 LTS
Mastodon 3.5.3
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]

**Comment by jaredallard** [comment]
I believe it's supposed to be `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`, right? Ref: https://docs.joinmastodon.org/admin/config/#s3

**Comment by capcom1701** [comment]
That was where it all went wrong. Changed Access key and Secret to AWS and it all works now. Thanks!
