### ISSUE TITLE
Importing followers CSV containing special characters causes error

### ISSUE THREAD

**Issue by skerit** [mastodon/mastodon#20571]
### Steps to reproduce the problem

1. Have a CSV of people you want to follow
2. Import it

### Expected behaviour

It should eventually import the accounts

### Actual behaviour

For an end user: nothing happens.

### Detailed description

So the list I was trying to import contained a user with a special domain name:

```
@username@թութ.հայ,true,false,
```

This failed. The following error is logged:

```
2022-11-13T15:23:15.595Z pid=6 tid=1m447u class=ImportWorker jid=e5a33421c9abbefd48310cbf INFO: start
[paperclip] copying imports/data/000/000/014/original/broken.csv to local file /tmp/54ddc3c7d064822eed932015d874033620221113-6-7n5fte.csv
[paperclip] copying imports/data/000/000/014/original/broken.csv to local file /tmp/54ddc3c7d064822eed932015d874033620221113-6-qg7tve.csv
[paperclip] deleting imports/data/000/000/014/original/broken.csv
2022-11-13T15:23:15.800Z pid=6 tid=1m447u class=ImportWorker jid=e5a33421c9abbefd48310cbf elapsed=0.205 INFO: fail
2022-11-13T15:23:15.800Z pid=6 tid=1m447u WARN: {"context":"Job raised exception","job":{"retry":false,"queue":"pull","args":[14],"class":"ImportWorker","jid":"e5a33421c9abbefd48310cbf","created_at":1668352995.5954869,"enqueued_at":1668352995.5956154}}
2022-11-13T15:23:15.801Z pid=6 tid=1m447u WARN: Encoding::UndefinedConversionError: "\xD5" from ASCII-8BIT to UTF-8
2022-11-13T15:23:15.801Z pid=6 tid=1m447u WARN: /opt/ruby/lib/ruby/3.0.0/json/common.rb:312:in `generate'
/opt/ruby/lib/ruby/3.0.0/json/common.rb:312:in `generate'
/opt/ruby/lib/ruby/3.0.0/json/common.rb:641:in `dump'
```

The log does not say which line fails, or what was in that line. But after creating a csv with just that one line, I managed to track it down.

The end-user will also not get any warnings: the import will just silently fail.

### Specifications

Mastodon v4.0.0-rc3
Using the docker image

**Comment by hcatlin** [comment]
I'm looking into this!

**Comment by HamptonMakes** [comment]
I'm looking into this!

**Comment by HamptonMakes** [comment]
PR OPEN!

**Comment by ineffyble** [comment]
PR merged!
