### ISSUE TITLE
admin dashboard page return 504 error

### ISSUE THREAD

**Issue by SouthFox-D** [mastodon/mastodon#20648]
### Steps to reproduce the problem

Try to view the dashboard page, but return 504 page.

### Expected behaviour

200 success

### Actual behaviour

504 error page

### Detailed description

```
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] method=GET path=/admin/dashboard format=html controller=Admin::DashboardController action=index status=500 error='Faraday::TimeoutError: execution expired' duration=60205.11 view=0.00 db=24.72
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd]   
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] Faraday::TimeoutError (execution expired):
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd]   
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check/elasticsearch_check.rb:26:in `running_version'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check/elasticsearch_check.rb:11:in `pass?'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check.rb:15:in `block in perform'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check.rb:12:in `each'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check.rb:12:in `each_with_object'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/lib/admin/system_check.rb:12:in `perform'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/controllers/admin/dashboard_controller.rb:10:in `index'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] app/controllers/concerns/localized.rb:11:in `set_locale'
web_1        | [1ad7cf8b-4dab-40ed-a91f-8e3784eeb0cd] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

Mastodon v4.0.0rc4

**Comment by SouthFox-D** [comment]
I think I know why.
My elasticsearch was deployed on another VPS (using WireGuard to connect), and it's offline now.

I guess a check is needed here rather than an error page?

**Comment by ineffyble** [comment]
The error is because it's trying to talk to ElasticSearch and giving up after 60 seconds. This probably means something is wrong with ElasticSearch but it could be any number of issues, including "ElasticSearch is under very heavy load and too slow to respond in time".

**Comment by vmstan** [comment]
Closing as fixed.
