### ISSUE TITLE
HEIC upload fails

### ISSUE THREAD

**Issue by tchorwat** [mastodon/mastodon#21157]
### Steps to reproduce the problem

1. Try to attach any image in heic format on fresh mastodon 4.0.2 install
2. After upload 500 error code is displayed
3. In server logs:
```
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] [paperclip] Trying to link /tmp/8c1086f0bdcb0a4fa6b3e2a04a5af62620221119-19507-g8tcpl.heic to /tmp/1c3811360466ea51ccb63441447e90a720221119-19507-ittywm.heic
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] Command :: file -b --mime '/tmp/1c3811360466ea51ccb63441447e90a720221119-19507-ittywm.heic'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] [paperclip] An error was received while processing: #<Paperclip::Errors::NotIdentifiedByImageMagickError: Paperclip::Errors::NotIdentifiedByImageMagickError>
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 error='IOError: closed stream' duration=50.45 view=0.00 db=1.77
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae]
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] IOError (closed stream):
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae]
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] app/lib/fast_geometry_parser.rb:5:in `from_file'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] lib/paperclip/attachment_extensions.rb:20:in `each'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] lib/paperclip/attachment_extensions.rb:20:in `inject'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] app/controllers/api/v2/media_controller.rb:5:in `create'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] app/controllers/concerns/localized.rb:11:in `set_locale'
Nov 19 22:44:43 localhost bundle[19507]: [7778a697-ff93-44bb-a495-2ccbe0a14bae] lib/mastodon/rack_middleware.rb:9:in `call'
```
Uplouding jpeg files works without any issue

### Expected behaviour

HEIC image should be converted to jpeg and successfully attached to tooth

### Actual behaviour

500 error

### Specifications

Mastodon 4.0.2
Ruby 3.0.4p208

**Comment by nmalcolm** [comment]
>Paperclip::Errors::NotIdentifiedByImageMagickError

This worked for me on Ubuntu 20.04:

```
sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
apt-get update
apt-get build-dep imagemagick libde265 libheif -y
cd /usr/src/
git clone https://github.com/strukturag/libde265.git 
git clone https://github.com/strukturag/libheif.git 
cd libde265/
./autogen.sh 
./configure 
make
make install
cd /usr/src/libheif/
./autogen.sh
./configure 
make
make install
cd /usr/src/
wget https://www.imagemagick.org/download/ImageMagick.tar.gz 
tar xf ImageMagick.tar.gz
cd ImageMagick-7*
./configure --with-heic=yes 
make
make install
ldconfig
```

**Comment by tchorwat** [comment]
@nmalcolm, thx but didn't help for my case
I would add that on my instance s3 storage backend for media attachments are enabled

**Comment by vmstan** [comment]
@tchorwat is this still an issue for you? It appears to be an ImageMagick problem that it's missing the proper support for HEIC files.
