### ISSUE TITLE
Can't follow on a other instance

### ISSUE THREAD

**Issue by duylong** [mastodon/mastodon#21268]
### Steps to reproduce the problem

1. Find a user to follow on another server
2. Click Follow

### Expected behaviour

I would like to successfully follow another user on another instance.

### Actual behaviour

Mastodon::UnexpectedResponseError: https://mastodon.social/users/**USER**/inbox returned code 401

### Detailed description

Hi,

I installed Mastodon on my server with 3 containers in Kubernetes (web, streaming, sidekiq). Everything works well. 
However, I'm trying to follow other users outside of my server, but when I click "follow", the status stays on "pending approval" indefinitely.

When I go to the sidekiq logs, I get this error:
```
2022-11-20T23:03:32.589Z pid=1 tid=2e1t class=ActivityPub::DeliveryWorker jid=****5fd9f53a1bee86fe**** INFO: start
2022-11-20T23:03:34.714Z pid=1 tid=2e1t class=ActivityPub::DeliveryWorker jid=****5fd9f53a1bee86fe**** elapsed=2.126 INFO: fail
2022-11-20T23:03:34.715Z pid=1 tid=2e1t WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"args":["{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://social.****.fr/2d761c29-ce5a-48d6-88ec-****\",\"type\":\"Follow\",\"actor\":\"https://social.****.fr/users/****\",\"object\":\"https://mastodon.social/users/****\"}",****6613261934****,"https://mastodon.social/users/****/inbox"],"class":"ActivityPub::DeliveryWorker","jid":"****5fd9f53a1bee86fe****","created_at":1668985412.5841987,"enqueued_at":1668985412.5851738}}
2022-11-20T23:03:34.715Z pid=1 tid=2e1t WARN: Mastodon::UnexpectedResponseError: https://mastodon.social/users/****/inbox returned code 401
2022-11-20T23:03:34.715Z pid=1 tid=2e1t WARN: /opt/mastodon/app/workers/activitypub/delivery_worker.rb:54:in `block (3 levels) in perform_request'
/opt/mastodon/app/lib/request.rb:72:in `perform'
```

I have delivery errors, I don't understand the origin of the problem...

* https://social.****.fr/actor is OK
* https://social.****.fr/.well-known/webfinger?resource=acct:test@****.fr is OK
* My LOCAL_DOMAIN and WEB_DOMAIN variables are well defined
* My server retrieves a list of users and federation

Do you have an idea of ​​the problem ? I don't see anything else in the logs.

### Specifications

Docker image : tootsuite/mastodon:v4.0.2

**Comment by aaro-n** [comment]
you can see #19338

**Comment by mazzy89** [comment]
I do get the same issue but in my case my `local_domain` and `web_domain`.
