### ISSUE TITLE
Trending posts not being populated and many object storage Stoplight::Error::RedLight errors in Sidekiq

### ISSUE THREAD

**Issue by richkershaw** [mastodon/mastodon#21482]
### Steps to reproduce the problem

1. Load the /explore or Preferences > Trends pages
2. No results displayed
3. Check Sidekiq listing and find many erorrs in retries list

### Expected behaviour

Trends displayed for moderation

### Actual behaviour

Empty lists

### Detailed description

Following job details appear in Sidekiq:

Queue | ingress
-- | --
ActivityPub::ProcessingWorker
109393241868759973, "{\"@context\": \"https://www.w3.org/ns/activitystreams\", \"type\": \"Announce\", \"to\": [\"https://relay.flm9.me/followers\"], \"actor\": \"https://relay.flm9.me/actor\", \"object\": \"https://social.vivaldi.net/users/jontromans/statuses/109392430960330685\", \"id\": \"https://relay.flm9.me/activities/e11918e7-ced9-45c1-8061-eacb43eb42f2\"}", nil, "Account"
daac98c261ab2d61627ac2d6
1 hour ago
29 minutes ago
5
11 minutes ago
just now

Queue	[ingress](https://civilians.social/sidekiq/queues/ingress)
Job	ActivityPub::ProcessingWorker
Arguments	
109393241868759973, "{\"@context\": \"https://www.w3.org/ns/activitystreams\", \"type\": \"Announce\", \"to\": [\"https://relay.flm9.me/followers\"], \"actor\": \"https://relay.flm9.me/actor\", \"object\": \"https://social.vivaldi.net/users/jontromans/statuses/109392430960330685\", \"id\": \"https://relay.flm9.me/activities/e11918e7-ced9-45c1-8061-eacb43eb42f2\"}", nil, "Account"
JID	daac98c261ab2d61627ac2d6
Created At	1 hour ago
Enqueued	29 minutes ago
Retry Count	5
Last Retry	11 minutes ago
Next Retry	just now

Error
Error Class	Stoplight::Error::RedLight
Error Message	object-storage
Error Backtrace	/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/stoplight-3.0.0/lib/stoplight/light/runnable.rb:46:in `run_red'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/stoplight-3.0.0/lib/stoplight/light/runnable.rb:25:in `run'
/home/mastodon/live/lib/paperclip/attachment_extensions.rb:93:in `save'

### Specifications

Mastodon v4.0.2 (though seen in v3.8.x
Ruby v3.0.4

**Comment by vmstan** [comment]
Hi @richkershaw are you still seeing this issue?
