### ISSUE TITLE
Failed to run `tootctl search deploy`

### ISSUE THREAD

**Issue by Surinrasu** [mastodon/mastodon#21834]
### Steps to reproduce the problem

1.Install Mastodon and ES as the guide
2.run `RAILS_ENV=production bin/tootctl search deploy`
```Shell
~/live$ RAILS_ENV=production bin/tootctl search deploy
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header': HTTPClient::KeepAliveDisconnected:  (HTTPClient::KeepAliveDisconnected)
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.0/lib/httplog/adapters/httpclient.rb:13:in `block in do_get_block'
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.0/lib/httplog/adapters/httpclient.rb:11:in `do_get_block'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1138:in `rescue in protect_keep_alive_disconnected'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1131:in `protect_keep_alive_disconnected'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:47:in `block in call'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:46:in `call'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:48:in `block in perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/search.rb:104:in `search'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:1003:in `block in perform'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:1002:in `perform'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:105:in `response'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:47:in `wrappers'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:50:in `to_a'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:875:in `first'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/specification.rb:37:in `locked'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/specification.rb:57:in `changed?'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `block in deploy'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `select'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `deploy'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:8:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header': HTTPClient::KeepAliveDisconnected:  (HTTPClient::KeepAliveDisconnected)
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.0/lib/httplog/adapters/httpclient.rb:13:in `block in do_get_block'
	from /home/mastodon/.rbenv/versions/3.0.4/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.0/lib/httplog/adapters/httpclient.rb:11:in `do_get_block'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:47:in `block in call'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-httpclient-1.0.1/lib/faraday/adapter/httpclient.rb:46:in `call'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:48:in `block in perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/search.rb:104:in `search'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:1003:in `block in perform'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:1002:in `perform'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:105:in `response'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:47:in `wrappers'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:50:in `to_a'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/search/request.rb:875:in `first'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/specification.rb:37:in `locked'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/index/specification.rb:57:in `changed?'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `block in deploy'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `select'
	from /home/mastodon/live/lib/mastodon/search_cli.rb:60:in `deploy'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:8:in `<main>'
```

### Expected behaviour

work normally

### Actual behaviour

not work

### Specifications

Mastodon 4.0.2
Ruby 3.0.4
Nodejs 16.18.1

**Comment by MrWazaby** [comment]
I have the same issue with the same configuration. 
The elasticsearch is working well, I can access it with curl. 

Here some additional infos : 

1. My ES is on a dedicated server 
2. It is using SSL (but I didn't see an option to specify that)
3. It is authenticated and configured with ES_USER and ES_PASS

**Comment by limdingwen** [comment]
I ran into this issue. Try running `curl localhost:9200` on your server. If it replies with "Empty reply from server", you may be running into [this issue](https://stackoverflow.com/questions/35921195/curl-52-empty-reply-from-server-timeout-when-querying-elastiscsearch). Just disable the security 😎 

Remember to restart elasticsearch.

It should return something like this:

```
{
  "name" : "[snip]",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "[snip]",
  "version" : {
    "number" : "8.5.3",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "[snip]",
    "build_date" : "[snip]",
    "build_snapshot" : false,
    "lucene_version" : "9.4.2",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by Joshix-1** [comment]
I solved it by setting the option to the following:
```
ES_HOST=https://example.org
```

**Comment by mackuba** [comment]
Thanks @Joshix-1 - this got me one step forward, but I was getting the "certificate verify failed" error since Elastic also generates its own self-signed local certificate that needs to be included, as they show in the curl test command in the [installation instructions](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/deb.html):

```
curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic https://localhost:9200
```

It seems to be working when I add this to the Chewy settings hash, as mentioned in that old Chewy issue that @mhkhung linked to (I had to copy the cert file to a user-accessible place):

```
transport_options: {
  ssl: {
    ca_file: './elasticsearch/http_ca.crt',
  }
}
```

**Comment by Joshix-1** [comment]
You could replace the certificat with a free one from Let's Encrypt then it isn't self-signed and Mastodon accepts it. That's what I'm doing and it works for me

**Comment by mackuba** [comment]
But it's a certificate for localhost, right? I don't want Elastic to be accessible from outside.

**Comment by Joshix-1** [comment]
Then you can just run elasticsearch without tls. Just make sure it isn't accessible from the outside and it's fine.

**Comment by mjankowski** [comment]
Seems like this was diagnosed/resolved in comments, closing ... if not, please comment.
