### ISSUE TITLE
Uploading invalid GIFs cause various Internal Server Errors (500)

### ISSUE THREAD

**Issue by mmnmnnmnmm** [mastodon/mastodon#22028]
### Steps to reproduce the problem

Can be minimally reproduced by uploading a single byte file ending in .gif.
(e.g. a file called g.gif containing a single letter 'G')

1. Go to account settings.
2. Upload any of the below gif as either your avatar or header background.
3. Save changes.
4. "We're sorry, but something went wrong on our end." Internal Server Error (500)

Attempting to post any of these gifs results all with the same error, with a "500 Internal Server Error" pop up without otherwise affecting the post.

1. Attach media
2. Choose any of the below gifs.
3. "500 Internal Server Error"

### Expected behaviour

Mastodon warns the user that the image is invalid like it does for other images (too large, etc).

### Actual behaviour

For uploading on account settings: Displays: "We're sorry, but something went wrong on our end." Internal Server Error (500) Page has to be reloaded. No changes made.

For attempting to post: "500 Internal Server Error" Pop up is displayed, media is not attached, the post is otherwise unchanged.

### Detailed description

Debug output from different tested gifs (long):

A single byte file:
```
xxd g.gif
00000000: 47                                       G
```

<details>
<summary>Debug output:</summary>
<br>

```
IOError in Settings::ProfilesController#update
closed stream
Extracted source (around line #5):

3 class FastGeometryParser
4   def self.from_file(file)
5     width, height = FastImage.size(file)
6
7     raise Paperclip::Errors::NotIdentifiedByImageMagickError if width.nil?
8

Rails.root: /vagrant
Application Trace | Framework Trace | Full Trace
app/lib/fast_geometry_parser.rb:5:in `from_file'
lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
lib/paperclip/attachment_extensions.rb:20:in `each'
lib/paperclip/attachment_extensions.rb:20:in `inject'
lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
app/services/update_account_service.rb:8:in `call'
app/controllers/settings/profiles_controller.rb:11:in `update'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
Exception Causes
IOError: closed stream
Request

Parameters:

{"button"=>"",
 "_method"=>"put",
 "authenticity_token"=>"GFsXo2JLrhwYVlm-7gIjQ4cRmy4k13j8YkEPHlv6vLeIJX8IbRQMpGKK0d4kby-byi_7kXBUpsyyOby0eVQz7Q",
 "account"=>
  {"display_name"=>"",
   "note"=>"",
   "avatar"=>
    #<ActionDispatch::Http::UploadedFile:0x00007fe1d48d7378
     @content_type="image/gif",
     @headers="Content-Disposition: form-data; name=\"account[avatar]\"; filename=\"g.gif\"\r\n" + "Content-Type: image/gif\r\n",
     @original_filename="g.gif",
     @tempfile=#<File:/tmp/RackMultipart20221130-5961-761smk.gif>>,
   "locked"=>"0",
   "bot"=>"0",
   "discoverable"=>"0",
   "hide_collections"=>"0",
   "fields_attributes"=>{"0"=>{"name"=>"", "value"=>""}, "1"=>{"name"=>"", "value"=>""}, "2"=>{"name"=>"", "value"=>""}, "3"=>{"name"=>"", "value"=>""}}}}

Toggle session dump
Toggle env dump
Response

Headers:

None
```
</details>

<hr>

Smallest questionably valid gif file:
```
xxd small.gif
00000000: 4749 4638 3961 0100 0100 00ff 002c 0000  GIF89a.......,..
00000010: 0000 0100 0100 0002 003b                 .........;
```

<details>
<summary>Debug output:</summary>
<br>

```
Paperclip::Error in Settings::ProfilesController#update
There was an error processing the thumbnail for a9a92beab8ebfcf1e557fbf7fdaee92820221130-7150-c8q5og:
Command 'convert '/tmp/a9a92beab8ebfcf1e557fbf7fdaee92820221130-7150-c8q5og.gif' -coalesce -auto-orient -resize "1x" -crop "1x1+0+0" +repage -layers "optimize" +profile "!icc,*" +set modify-date +set create-date '/tmp/1ff2c526c0aaa3d2e8ee12436b28271c20221130-7150-wujt16'' returned 1. Expected 0
Here is the command output: STDOUT:
STDERR:
convert-im6.q16: corrupt image `/tmp/a9a92beab8ebfcf1e557fbf7fdaee92820221130-7150-c8q5og.gif' @ error/gif.c/ReadGIFImage/1390.
convert-im6.q16: no images defined `/tmp/1ff2c526c0aaa3d2e8ee12436b28271c20221130-7150-wujt16' @ error/convert.c/ConvertImageCommand/3258.
Extracted source (around line #17):

15       end
16
17       Paperclip::Thumbnail.make(file, options, attachment)
18     end
19
20     private

Rails.root: /vagrant
Application Trace | Framework Trace | Full Trace
lib/paperclip/lazy_thumbnail.rb:17:in `make'
lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
lib/paperclip/attachment_extensions.rb:20:in `each'
lib/paperclip/attachment_extensions.rb:20:in `inject'
lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
app/services/update_account_service.rb:8:in `call'
app/controllers/settings/profiles_controller.rb:11:in `update'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
Exception Causes
Terrapin::ExitStatusError: Command 'convert '/tmp/a9a92beab8ebfcf1e557fbf7fdaee92820221130-7150-c8q5og.gif' -coalesce -auto-orient -resize "1x" -crop "1x1+0+0" +repage -layers "optimize" +profile "!icc,*" +set modify-date +set create-date '/tmp/1ff2c526c0aaa3d2e8ee12436b28271c20221130-7150-wujt16'' returned 1. Expected 0 Here is the command output: STDOUT: STDERR: convert-im6.q16: corrupt image `/tmp/a9a92beab8ebfcf1e557fbf7fdaee92820221130-7150-c8q5og.gif' @ error/gif.c/ReadGIFImage/1390. convert-im6.q16: no images defined `/tmp/1ff2c526c0aaa3d2e8ee12436b28271c20221130-7150-wujt16' @ error/convert.c/ConvertImageCommand/3258.
Request

Parameters:

{"button"=>"",
 "_method"=>"put",
 "authenticity_token"=>"KHqMDgeF3juDRadTwOt3BqV424ObhUdcuWp2XwXUQyawrksv8nVdr47ZKYOpFlllW0DBRWYQdSXQU6E_qOXdxw",
 "account"=>
  {"display_name"=>"",
   "note"=>"",
   "avatar"=>
    #<ActionDispatch::Http::UploadedFile:0x000055ac5d0b1800
     @content_type="image/gif",
     @headers="Content-Disposition: form-data; name=\"account[avatar]\"; filename=\"small.gif\"\r\n" + "Content-Type: image/gif\r\n",
     @original_filename="small.gif",
     @tempfile=#<File:/tmp/RackMultipart20221130-7150-81it07.gif>>,
   "locked"=>"0",
   "bot"=>"0",
   "discoverable"=>"0",
   "hide_collections"=>"0",
   "fields_attributes"=>{"0"=>{"name"=>"", "value"=>""}, "1"=>{"name"=>"", "value"=>""}, "2"=>{"name"=>"", "value"=>""}, "3"=>{"name"=>"", "value"=>""}}}}

Toggle session dump
Toggle env dump
Response

Headers:

None
```
</details>

<hr>

A gif with no size:
```
xxd no_size.gif
00000000: 4749 4638 3961 0000 0000 00ff 002c 0000  GIF89a.......,..
00000010: 0000 0100 0100 0002 003b                 .........;
```

<details>
<summary>Debug output:</summary>
<br>

```
FloatDomainError in Settings::ProfilesController#update
NaN
Extracted source (around line #17):

15       end
16
17       Paperclip::Thumbnail.make(file, options, attachment)
18     end
19
20     private

Rails.root: /vagrant
Application Trace | Framework Trace | Full Trace
lib/paperclip/lazy_thumbnail.rb:17:in `make'
lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
lib/paperclip/attachment_extensions.rb:20:in `each'
lib/paperclip/attachment_extensions.rb:20:in `inject'
lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
app/services/update_account_service.rb:8:in `call'
app/controllers/settings/profiles_controller.rb:11:in `update'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
Request

Parameters:

{"button"=>"",
 "_method"=>"put",
 "authenticity_token"=>"PnvFsE81u6R-A2cRrnAzhnJQSAVCvGkBUYAgEqDxUBqmrwKRusU4MHOf6cHHjR3ljGhSw78pW3g4ufdyDcDO-w",
 "account"=>
  {"display_name"=>"",
   "note"=>"",
   "avatar"=>
    #<ActionDispatch::Http::UploadedFile:0x00007f8fb412a980
     @content_type="image/gif",
     @headers="Content-Disposition: form-data; name=\"account[avatar]\"; filename=\"no_size.gif\"\r\n" + "Content-Type: image/gif\r\n",
     @original_filename="no_size.gif",
     @tempfile=#<File:/tmp/RackMultipart20221130-7152-gwsnps.gif>>,
   "locked"=>"0",
   "bot"=>"0",
   "discoverable"=>"0",
   "hide_collections"=>"0",
   "fields_attributes"=>{"0"=>{"name"=>"", "value"=>""}, "1"=>{"name"=>"", "value"=>""}, "2"=>{"name"=>"", "value"=>""}, "3"=>{"name"=>"", "value"=>""}}}}

Toggle session dump
Toggle env dump
Response

Headers:

None
```
</details>

<hr>

Just a gif header and trailer:
```
xxd smallest.gif
00000000: 4749 4638 3961 0100 0100 0000 003b       GIF89a.......;
```

<details>
<summary>Debug output:</summary>
<br>

```
Paperclip::Error in Settings::ProfilesController#update
There was an error running `identify` for d38252762d3d4fd229faae637fd13f4e20221201-4329-360ssx
Extracted source (around line #17):

15       end
16
17       Paperclip::Thumbnail.make(file, options, attachment)
18     end
19
20    private

Rails.root: /vagrant
Application Trace | Framework Trace | Full Trace
lib/paperclip/lazy_thumbnail.rb:17:in `make'
lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
lib/paperclip/attachment_extensions.rb:20:in `each'
lib/paperclip/attachment_extensions.rb:20:in `inject'
lib/paperclip/attachment_extensions.rb:20:in `post_process_style'
app/services/update_account_service.rb:8:in `call'
app/controllers/settings/profiles_controller.rb:11:in `update'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
Exception Causes
Terrapin::ExitStatusError: Command 'identify -format %m '/tmp/d38252762d3d4fd229faae637fd13f4e20221201-4329-360ssx.gif[0]'' returned 1. Expected 0 Here is the command output: STDOUT: STDERR: identify-im6.q16: negative or zero image size `/tmp/d38252762d3d4fd229faae637fd13f4e20221201-4329-360ssx.gif' @ error/gif.c/ReadGIFImage/1406.
Request

Parameters:

{"button"=>"",
 "_method"=>"put",
 "authenticity_token"=>"HnhNSPBUERG_p8fTkRwStf_KgoOcA8d1R-QNYR7VZxI4aIg9fGn2sHRLq4xod_3R49HH_d7fb514yUq2D05jXQ",
 "account"=>
  {"display_name"=>"",
   "note"=>"",
   "avatar"=>
    #<ActionDispatch::Http::UploadedFile:0x00007fb09821a980
     @content_type="image/gif",
     @headers="Content-Disposition: form-data; name=\"account[avatar]\"; filename=\"gif.gif\"\r\n" + "Content-Type: image/gif\r\n",
     @original_filename="gif.gif",
     @tempfile=#<File:/tmp/RackMultipart20221201-4329-51mtxr.gif>>,
   "locked"=>"0",
   "bot"=>"0",
   "discoverable"=>"0",
   "hide_collections"=>"0",
   "fields_attributes"=>{"0"=>{"name"=>"", "value"=>""}, "1"=>{"name"=>"", "value"=>""}, "2"=>{"name"=>"", "value"=>""}, "3"=>{"name"=>"", "value"=>""}}}}

Toggle session dump
Toggle env dump
Response

Headers:

None
```
</details>

### Specifications

Tested on mastodon git: 1122697b375da82cbb156b73eb1015ae066fc6ee

Affects v4.0.2 instances.

**Comment by mjankowski** [comment]
I believe this is resolved on 4.3 and this specific error will be more gracefully caught with validation error message on the form.
