### ISSUE TITLE
Some rspec tests fail when ran as a group, succeed when ran individually

### ISSUE THREAD

**Issue by petecheslock** [mastodon/mastodon#22136]
### Steps to reproduce the problem

1. Clone the latest 4.x release tag for Mastodon  (v4.0.2 is the latest i've tried)
2. Setup the environment with an updated [docker compose](https://github.com/land-of-apps/mastodon/blob/appmap-v4/docker-compose.yml)
3. Source environment variables to setup dev environment [source .env-rspec](https://github.com/land-of-apps/mastodon/blob/appmap-v4/.env-rspec)
4. Set custom [webpacker.yml](https://github.com/land-of-apps/mastodon/blob/appmap-v4/config/webpacker.yml#L74-L81) to support running rspec locally.
5. Run webpack `RAILS_ENV=test ./bin/webpack`
6. Run tests `RAILS_ENV=test bundle exec rspec`

### Expected behaviour

Tests that fail togeather fail individually and tests that pass together pass individually

### Actual behaviour

Tests that failed when running as a group will pass when running individually

### Detailed description

While working on some [Mastodon tutorial content for onboarding new engineers](https://dev.to/appmap/the-fastest-way-to-run-mastodon-tests-5g03) I ran across a problem where running all the rspec tests will have a series of about 54 tests fail - it does not seem like the same group of tests each time although I'm going to do a few more tests to confirm.  

For example - when running `RAILS_ENV=test bundle exec rspec` I'll get the following error:

```
 621) ActivityPub::RepliesController GET #index with signature behaves like allowed access when status is public behaves like cacheable response returns public Cache-Control header
       Failure/Error: object.active_mentions.to_a.sort_by(&:id) + object.tags + object.emojis
       
       TypeError:
         no implicit conversion of nil into String
       Shared Example Group: "cacheable response" called from ./spec/controllers/activitypub/replies_controller_spec.rb:96
       Shared Example Group: "allowed access" called from ./spec/controllers/activitypub/replies_controller_spec.rb:193
       # ./app/serializers/activitypub/note_serializer.rb:116:in `+'
       # ./app/serializers/activitypub/note_serializer.rb:116:in `virtual_tags'
       # ./app/lib/activitypub/serializer.rb:36:in `serializable_hash'
       # ./app/lib/activitypub/serializer.rb:36:in `serializable_hash'
       # ./app/lib/activitypub/adapter.rb:19:in `serializable_hash'
       # ./app/controllers/activitypub/replies_controller.rb:17:in `index'
       # ./spec/controllers/activitypub/replies_controller_spec.rb:183:in `block (3 levels) in <top (required)>'
       # ./spec/controllers/activitypub/replies_controller_spec.rb:23:in `block (3 levels) in <top (required)>'


       rspec './spec/controllers/activitypub/replies_controller_spec.rb[1:1:2:1:3:3:3]' # ActivityPub::RepliesController GET #index with signature behaves like allowed access when status is public behaves like cacheable response returns public Cache-Control header
```

But when I run this test by itself it will pass.
```
$ RAILS_ENV=test bundle exec rspec ./spec/controllers/activitypub/replies_controller_spec.rb                                                                                     INT ✘  3.0.4   13:29:51  
    
Randomized with seed 23157
warning: tag 'v0.1.2' is externally known as '0.1.2'                                                                                                                                                                                         |  ETA: ??:??:?? 
 40/40 |=============================================================================================================== 100 ================================================================================================================>| Time: 00:00:19 

Finished in 20 seconds (files took 3.48 seconds to load)
40 examples, 0 failures

Randomized with seed 23157
```

When looking at all the failed tests after a full run will show 82 failures
```
$ cat tmp/rspec/examples.txt  | grep failed | sed 's/\[.*//g' | uniq | wc -l    
82
```

When iterating thru the list and re-running individually many will succeed. 

```
$ for i in `cat tmp/rspec/examples.txt  | grep failed | sed 's/\[.*//g' | uniq`;do RAILS_ENV=test bundle exec rspec $i;done

<tests run>

cat tmp/rspec/examples.txt  | grep failed | sed 's/\[.*//g' | uniq | wc -l
28
```

A list of the tests that are failed after running together: 
[failed-tests.txt](https://github.com/mastodon/mastodon/files/10179528/failed-tests.txt)

A list of the tests that are failed after re-running all the previously failed tests individually.
[after-individual-runs.txt](https://github.com/mastodon/mastodon/files/10179532/after-individual-runs.txt)

Is there a setup command I'm missing or some other setting that needs to be in place?

### Specifications

Mastodon 4.0.2
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [arm64-darwin21]

**Comment by petecheslock** [comment]
Going to close this issue for now as I can't get enough consistency to repeat the problem and will continue to look and see if it's a local environment issue.
