### ISSUE TITLE
`tootctl domains crawl` terminates with unhandled errors and no result

### ISSUE THREAD

**Issue by selfawaresoup** [mastodon/mastodon#22180]
### Steps to reproduce the problem

1. run `tootctl domains crawl`, no options

### Expected behaviour

puts out a list on domains

### Actual behaviour

terminates with NoMethodError and RegexError

### Detailed description

Example output:
```
$ bin/tootctl domains crawl
/home/mastodon/live/lib/mastodon/domains_cli.rb:147:in `ensure in crawl': undefined method `finish' for nil:NilClass (NoMethodError)
	from /home/mastodon/live/lib/mastodon/domains_cli.rb:156:in `crawl'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:8:in `<main>'
/home/mastodon/live/lib/mastodon/domains_cli.rb:100:in `initialize': target of repeat operator is not specified: /\\.?bitcoinhackers.org|bae.st|beefyboys.club|dobbs.town|freeatlantis.com|freecumextremist.com|freesoftwareextremist.com|freespeechextremist.com|freewahaextremist.com|gab.ai|gab.best|gab.com|gearlandia.haus|gleasonator.com|kiwifarms.net|kiwifarms.is|kiwifarms.cc|iddqd.social|leafposter.club|letsalllovela.in|mastodon.green|noagendasocial.com|outerheaven.club|poa.st|quote.org|drama.cc|shitposter.club|spinster.xyz|truthsocial.com|yggdrasil.social|cum.salon|daishouri.moe|varishangout.net|wolfgirl.bar|ryona.agency|pl.natehiggers.online|pl.info.natehiggers.online|pleroma.nobodyhasthe.biz|lolison.top|lolicon.rocks|rapemeat.solutions|shota.house|*.activitypub-troll.cf|*.repl.co|*.misskey-forkbomb.cf$/ (RegexpError)
	from /home/mastodon/live/lib/mastodon/domains_cli.rb:100:in `new'
	from /home/mastodon/live/lib/mastodon/domains_cli.rb:100:in `crawl'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:8:in `<main>'
```

### Specifications

Mastodon | 4.0.2
Ruby | 3.0.4p208
PostgreSQL | 12.12
Redis | 5.0.7

**Comment by selfawaresoup** [comment]
Same result with `tootctl domains crawl --exclude-suspended`

**Comment by mjankowski** [comment]
The CLI area has changed a bit in last few releases -- is this still an issue on 4.3?
