### ISSUE TITLE
sidekiq incorrectly flags mails as delivered when network is not available.

### ISSUE THREAD

**Issue by Flightkick** [mastodon/mastodon#22496]
### Steps to reproduce the problem

1. Use the docker configuration
2. Disable sidekiq's public network access by removing
https://github.com/mastodon/mastodon/blob/2bad619d171f8516137725c83878cdf5f6f61aa9/docker-compose.yml#L106
3. Trigger something that sends an email
4. Check the sidekiq logs
...

### Expected behaviour

ActionMailer::MailDeliveryJob should report a delivery failure

### Actual behaviour

ActionMailer::MailDeliveryJob reports 'Delivered mail'

### Detailed description

I encountered this issue while setting up Mastodon as I accidentally didn't grant sidekiq access to the external network.
The logs seem to indicate that this issue may be caused by [rails actionmailer](https://github.com/rails/rails/tree/main/actionmailer).
Just reporting this inconsistency, I don't need assistance.

### Logs
```
sidekiq_1    | [ActiveJob] [ActionMailer::MailDeliveryJob] [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Performing ActionMailer::MailDeliveryJob (Job ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) from Sidekiq(mailers) enqueued at 2022-12-19T14:24:51Z with arguments: "UserMailer", "confirmation_instructions", "deliver_now", {:args=>[#<GlobalID:0x0000xxxxxxxxxxxx @uri=#<URI::GID gid://mastodon/User/xxxxx>>, "xxxxxxxxxxxxxxxxxxxx"]}
sidekiq_1    | [ActiveJob] [ActionMailer::MailDeliveryJob] [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Delivered mail xxxxxxxxxxxx_xxxxxxxxxxx@mail.xxxxxxxxxxxx.xxx (10029.8ms)
sidekiq_1    | [ActiveJob] [ActionMailer::MailDeliveryJob] [xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx] Error performing ActionMailer::MailDeliveryJob (Job ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx) from Sidekiq(mailers) in 10297.96ms: SocketError (getaddrinfo: Temporary failure in name resolution):
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:578:in `initialize'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:578:in `open'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:578:in `tcp_socket'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:588:in `block in do_start'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/timeout.rb:107:in `timeout'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:587:in `do_start'
sidekiq_1    | /opt/ruby/lib/ruby/3.0.0/net/smtp.rb:557:in `start'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:559:in `block in deliver_mail'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/base.rb:557:in `deliver_mail'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/message_delivery.rb:119:in `block in deliver_now'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/actionmailer-6.1.7/lib/action_mailer/mail_delivery_job.rb:23:in `perform'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/execution.rb:48:in `block in perform_now'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/i18n-1.12.0/lib/i18n.rb:322:in `with_locale'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:21:in `block in instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `block in instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/notifications.rb:203:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:31:in `instrument'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `instance_exec'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activejob-6.1.7/lib/active_job/logging.rb:22:in `block in tag_logger'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `block in tagged'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:37:in `tagged'
sidekiq_1    | /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7/lib/active_support/tagged_logging.rb:99:in `tagged'
```

### Specifications

Docker: tootsuite/mastodon
Digest:sha256:21c20181a5d44ff553e9e8f7d8d2e53b2551cc8c7ac900760e056445b88e7438

**Comment by nightpool** [comment]
I'm not sure I quite understand your bug report—is the job being marked as "completed" or is it retrying as normal, but with a slightly misleading log message? You only mention the log message, but it's hard for me to tell whether or not this is a bug without knowing whether the job actually gets marked correctly by sidekiq as "retrying" or not.

**Comment by Flightkick** [comment]
It took a little while before the mails arrived so it seems that only the logs are misleading luckily.
