### ISSUE TITLE
`tootctl accounts migrate`: undefined method `target_acount_id'

### ISSUE THREAD

**Issue by Saiv46** [mastodon/mastodon#23548]
### Steps to reproduce the problem

1. Make migration for (username)
2. Cancel migration
3. Run `tootctl accounts migrate (username) --replay`

### Expected behaviour

Migration would be retried with last one

### Actual behaviour

Error occurs, need to specify `--target` to make it work

### Detailed description

```
$ RAILS_ENV=production ./live/bin/tootctl accounts migrate saiv46 --replay
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activemodel-6.1.7.2/lib/active_model/attribute_methods.rb:469:in `method_missing': undefined method `target_acount_id' for #<AccountMigration id: 39, account_id: 109114091988624483, acct: "saiv46@c.im", followers_count: 138, target_account_id: 107893189472315579, created_at: "2023-01-07 20:22:27.792487000 +0000", updated_at: "2023-01-07 20:22:27.792487000 +0000"> (NoMethodError)
Did you mean?  target_account_id
               target_account_id?
               target_account_id=
               target_account
               target_account=
	from /home/mastodon/live/lib/mastodon/accounts_cli.rb:634:in `migrate'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from ./live/bin/tootctl:8:in `<main>'
```

### Specifications

Mastodon v4.1.0

**Comment by ClearlyClaire** [comment]
Hi! Thank you for your report.

There's a typo indeed in that file, and #23567 should fix it. In the meantime you should be able to get past this by using `--force`.

**Comment by Saiv46** [comment]
Thank you!
