### ISSUE TITLE
Marking trending post as "disallowed" breaks moderation interface for said post

### ISSUE THREAD

**Issue by smiba** [mastodon/mastodon#23573]
### Steps to reproduce the problem

1. Mark trending post as "Disallow post"
2. Open the post and press "Open this post in the moderation interface"
3. 500 error is thrown 

### Expected behaviour

Moderation interface should've opened

### Actual behaviour

500 error is shown

### Detailed description

Opening the post throws the following error:

```
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700] method=GET path=/admin/accounts/109552402632649346/statuses/109855755827007172 format=html controller=Admin::StatusesController action=show status=500 error='ActionView::Template::Error: undefined method `requires_review?' for #<StatusTrend id: 35247, status_id: 109855755827007172, account_id: 109552402632649346, score: 0.8788198703741205, rank: 1, allowed: false, language: "en">
Did you mean?  require_dependency' duration=39.37 view=0.00 db=6.37
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700] ActionView::Template::Error (undefined method `requires_review?' for #<StatusTrend id: 35247, status_id: 109855755827007172, account_id: 109552402632649346, score: 0.8788198703741205, rank: 1, allowed: false, language: "en">
Did you mean?  require_dependency):
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     34:           %td
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     35:             - if @status.trend.allowed?
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     36:               %abbr{ title: t('admin.trends.tags.current_score', score: @status.trend.score) }= t('admin.trends.tags.trending_rank', rank: @status.trend.rank)
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     37:             - elsif @status.trend.requires_review?
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     38:               = t('admin.trends.pending_review')
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     39:             - else
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]     40:               = t('admin.trends.not_allowed_to_trend')
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700]
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700] app/views/admin/statuses/show.html.haml:37
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700] app/controllers/concerns/localized.rb:11:in `set_locale'
[4e11d1ef-e4b9-43d9-98c5-4aeec1c18700] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

Mastodon 4.1.0
Ruby 3.0.4p208

**Comment by ClearlyClaire** [comment]
That seem to occur to the history view of any trending-but-not-approved-to-trend post. This only affects the view of the post's history.

**Comment by smiba** [comment]
Unfortunately it causes the entire request to come back as "Sorry something went wrong", meaning I can't access the interface for the post 

I may have missed it before, as trending posts on my instance are approved by default.

**Comment by ClearlyClaire** [comment]
> Unfortunately it causes the entire request to come back as "Sorry something went wrong", meaning I can't access the interface for the post

Yes, but I mean the entire request is just here to display the edit log in the first place.

**Comment by smiba** [comment]
> > Unfortunately it causes the entire request to come back as "Sorry something went wrong", meaning I can't access the interface for the post
> 
> Yes, but I mean the entire request is just here to display the edit log in the first place.

Oh like that, got it :) 

Thanks for looking into it by the way!
