### ISSUE TITLE
Scheduler::Trends::RefreshScheduler getting stuck

### ISSUE THREAD

**Issue by StreamOfRon** [mastodon/mastodon#23590]
### Steps to reproduce the problem

Unknown

### Expected behaviour

Scheduler::Trends::RefreshScheduler tasks should complete quickly

### Actual behaviour

Scheduler::Trends::RefreshScheduler tasks block threads on the scheduler instance

### Detailed description

I was troubleshooting why my sidekiq queues backed up overnight and found that all of the worker threads were running "Scheduler::Trends::RefreshScheduler" tasks.  Some of them had been running for several hours at that point.  I've continued to monitor the situation and periodically these tasks start accumulating again.  If I restart the scheduler worker, I see them retry and usually clear within seconds.  

### Specifications

Mastodon 4.1 running from official docker images

**Comment by StreamOfRon** [comment]
As an example of how this exhibits, 10 of the 16 threads on my scheduler are currently blocked with jobs that never seem to finish unless I restart the scheduler (sometimes more than once): 
<img width="1182" alt="Screenshot 2023-02-15 at 2 46 43 PM" src="https://user-images.githubusercontent.com/643717/219206015-acafecf3-b917-4d57-9831-45c7c0d88267.png">

**Comment by StreamOfRon** [comment]
There's nothing in the sidekiq logs when this is happening.  Is there a way to increase verbosity to get visibility into what they're doing that's getting stuck like this?

**Comment by StreamOfRon** [comment]
I sent a kill -s TTIN to the scheduler process (per the sidekiq docs) to get a stack trace while one task was "stuck":
```
2023-02-15T23:53:15.537Z pid=1 tid=76d WARN: Thread TID-2hll processor
2023-02-15T23:53:15.537Z pid=1 tid=76d WARN: /opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `exec_params'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:672:in `block (2 levels) in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:671:in `block in exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:696:in `block (2 levels) in log'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:695:in `block in log'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract_adapter.rb:687:in `log'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:670:in `exec_no_cache'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec_query'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:532:in `select'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:69:in `select_all'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `block in select_all'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:118:in `block in cache_sql'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:109:in `cache_sql'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/query_cache.rb:101:in `select_all'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/querying.rb:47:in `find_by_sql'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:843:in `block in exec_queries'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:828:in `exec_queries'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:631:in `load'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader/association.rb:118:in `records_for'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader/association.rb:45:in `load_records'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader/association.rb:27:in `records_by_owner'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader/association.rb:17:in `run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:151:in `block in preloaders_for_reflection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:150:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:150:in `map'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:150:in `preloaders_for_reflection'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:145:in `block in preloaders_for_one'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:144:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:144:in `flat_map'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:144:in `preloaders_for_one'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:110:in `preloaders_on'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:94:in `block in preload'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:93:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:93:in `flat_map'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/associations/preloader.rb:93:in `preload'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:763:in `block in preload_associations'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:761:in `each'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:761:in `preload_associations'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:846:in `block in exec_queries'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:861:in `skip_query_cache_if_necessary'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:828:in `exec_queries'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:631:in `load'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation.rb:249:in `records'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.2/lib/active_record/relation/delegation.rb:88:in `each'
/opt/mastodon/app/models/trends/statuses.rb:98:in `map'
/opt/mastodon/app/models/trends/statuses.rb:98:in `calculate_scores'
/opt/mastodon/app/models/trends/statuses.rb:62:in `refresh'
/opt/mastodon/app/models/trends.rb:25:in `each'
/opt/mastodon/app/models/trends.rb:25:in `refresh!'
/opt/mastodon/app/workers/scheduler/trends/refresh_scheduler.rb:9:in `perform'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:202:in `execute_job'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:177:in `block in invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-unique-jobs-7.1.29/lib/sidekiq_unique_jobs/middleware.rb:36:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
/opt/mastodon/lib/mastodon/sidekiq_middleware.rb:7:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:179:in `block in invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/middleware/chain.rb:182:in `invoke'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:169:in `block in process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_retry.rb:113:in `local'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:14:in `block in call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/execution_wrapper.rb:91:in `wrap'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/reloader.rb:72:in `block in wrap'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/execution_wrapper.rb:91:in `wrap'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/reloader.rb:71:in `wrap'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/rails.rb:13:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:263:in `stats'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:13:in `call'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_retry.rb:80:in `global'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:124:in `block in dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/job_logger.rb:39:in `prepare'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:123:in `dispatch'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:168:in `process'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:78:in `process_one'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/processor.rb:68:in `run'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:8:in `watchdog'
/opt/mastodon/vendor/bundle/ruby/3.0.0/gems/sidekiq-6.5.8/lib/sidekiq/component.rb:17:in `block in safe_thread'
```

**Comment by ElanHasson** [comment]
I have no errors in the log for me..

I do have this though:

![image](https://github.com/mastodon/mastodon/assets/234704/9810cb88-cfc7-4096-ab72-3ef80e8a35c9)

![image](https://github.com/mastodon/mastodon/assets/234704/7e51d6ce-ea26-4d35-ad35-957cca3ccdaf)

**Comment by ElanHasson** [comment]
@renchap advised me to move my sidekiq workers closer to my redis instance. 

Removing latency here solved the problem for me.

**Comment by mjankowski** [comment]
Still an issue on 4.3?

If so, did you review the prior comment re: sidekiq/redis proximity?

**Comment by ElanHasson** [comment]
sidekiq and redis are now co-located, postgres is far away :)
