### ISSUE TITLE
v4.1.1: Compilation failed "digital envelope routines::unsupported"

### ISSUE THREAD

**Issue by memo-567** [mastodon/mastodon#24141]
### Steps to reproduce the problem

Updating from 4.1.0 to 4.1.1 shows an error message, but Mastodon is running as 4.1.1 without recognizable errors.

### Expected behaviour

Upgrade without error message

### Actual behaviour

See error message in description

### Detailed description

```
Compilation failed:
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mastodon/live/node_modules/webpack/lib/util/createHash.js:135:53)
    at ConcatenatedModule._createIdentifier (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:563:16)
    at new ConcatenatedModule (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:445:27)
    at /home/mastodon/live/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:250:26
    at SyncBailHook.eval [as call] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1351:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1342:27)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:675:18
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1185:12
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

### Specifications

Mastodon 4.1.1
Node.js v18.15.0

**Comment by memo-567** [comment]
Thanks for the hint.

So `RAILS_ENV=production bundle exec rails assets:precompile NODE_OPTIONS=--openssl-legacy-provider`  is the solution?

**Comment by memo-567** [comment]
@fsLeg 

So 

`RAILS_ENV=production bundle exec rails assets:precompile NODE_OPTIONS=--openssl-legacy-provider`

is the solution?

**Comment by fsLeg** [comment]
One might think a few days was enough to learn how environment variables work and to test the suggestion.

No, the correct command is

`NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production bundle exec rails assets:precompile`

And it is not a solution, it's a workaround. The solution would be to make Mastodon support Node.js v18 which is the current LTS release, but a quick search in the issues shows that it's a much more complicated task than one might initially think.

**Comment by memo-567** [comment]
Thanks for the corrected version of the SSH command.

**Comment by poitch** [comment]
The official "Installing from Source" documentation doesn't seem to specify which version of node is supported, and following the steps to install node will land you with node version 18.

**Comment by renchap** [comment]
Closing, as this is an issue with your setup, you need Node 16, or to use the `NODE_OPTIONS` above.

**Comment by alarig** [comment]
Just an info if someone comes here looking for this error, even on node 16 I had to use the workaround. I think that’s is more likely to using openssl 3.0 instead of 1.1.1
