### ISSUE TITLE
Random errors caugh in web

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#24173]
### Steps to reproduce the problem

```
ActionController::BadRequest (Invalid request parameters: Invalid encoding for parameter: �������������):
actionpack (6.1.7.2) lib/action_dispatch/request/utils.rb:39:in `check_param_encoding'
actionpack (6.1.7.2) lib/action_dispatch/request/utils.rb:34:in `block in check_param_encoding'
actionpack (6.1.7.2) lib/action_dispatch/request/utils.rb:34:in `each_value'
actionpack (6.1.7.2) lib/action_dispatch/request/utils.rb:34:in `check_param_encoding'
actionpack (6.1.7.2) lib/action_dispatch/http/request.rb:403:in `block in POST'
rack (2.2.6.2) lib/rack/request.rb:69:in `fetch'
rack (2.2.6.2) lib/rack/request.rb:69:in `fetch_header'
actionpack (6.1.7.2) lib/action_dispatch/http/request.rb:398:in `POST'
actionpack (6.1.7.2) lib/action_dispatch/http/parameters.rb:55:in `parameters'
actionpack (6.1.7.2) lib/action_dispatch/http/filter_parameters.rb:43:in `filtered_parameters'
actionpack (6.1.7.2) lib/action_controller/metal/instrumentation.rb:24:in `process_action'
```

```
EOFError (EOFError):
rack (2.2.6.2) lib/rack/multipart/parser.rb:360:in `handle_empty_content!'
rack (2.2.6.2) lib/rack/multipart/parser.rb:186:in `on_read'
rack (2.2.6.2) lib/rack/multipart/parser.rb:77:in `block in parse'
rack (2.2.6.2) lib/rack/multipart/parser.rb:75:in `loop'
rack (2.2.6.2) lib/rack/multipart/parser.rb:75:in `parse'
rack (2.2.6.2) lib/rack/multipart.rb:53:in `extract_multipart'
rack (2.2.6.2) lib/rack/request.rb:594:in `parse_multipart'
rack (2.2.6.2) lib/rack/request.rb:446:in `POST'
rack (2.2.6.2) lib/rack/request.rb:469:in `params'
rack (2.2.6.2) lib/rack/request.rb:32:in `params'
config/initializers/rack_attack.rb:57:in `paging_request?'
```

### Expected behaviour

no error

### Actual behaviour

error

### Specifications

4.1.0

**Comment by mjankowski** [comment]
Actual app issue, or just noisy logs?

This is probably automated activity getting rejected by rails?

**Comment by mjankowski** [comment]
Separately, does this still happen on 4.3, and do you have more logs to show whether this is app-generated traffic, or random internet noise?
