### ISSUE TITLE
Precompile yields `Psych::BadAlias: Unknown alias: defaults`

### ISSUE THREAD

**Issue by Preskton** [mastodon/mastodon#24455]
### Steps to reproduce the problem

1. Followed 4.1.1 upgrade instructions up to the `precompile` step
2. Ran `sudo -u mastodon NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production bundle exec rails assets:precompile`

### Expected behaviour

Precompilation succeeds

### Actual behaviour

Precompilation fails with messages stating that `ActionView::Template::Error: Unknown alias: defaults` and `Psych::BadAlias: Unknown alias: defaults`

### Detailed description

Full exception message:

```
$ sudo -u mastodon NODE_OPTIONS=--openssl-legacy-provider RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 13.33s.
I, [2023-04-07T15:55:15.267950 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css
I, [2023-04-07T15:55:15.268742 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/doorkeeper/admin/application-a644908e7bab54fb749be0f59fb64a7480bbf9c4c2b79d4a65791cb7ab4d8730.css.gz
I, [2023-04-07T15:55:15.283708 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css
I, [2023-04-07T15:55:15.283825 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/doorkeeper/application-c93dac2ad9d65e3393e0e2c958481e86ef7a5e5b0f6ce406842a7b99b25a4850.css.gz
I, [2023-04-07T15:55:15.286327 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/pghero/favicon-db10337a56c45eb43c22ff5019546b520fa22c7281d4d385f235cbca67ed26bb.png
I, [2023-04-07T15:55:15.655702 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js
I, [2023-04-07T15:55:15.655894 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/pghero/application-a60bf0a452ed064fef3594cf52a4c998712da7c76150f890f4eaa644f59671e4.js.gz
I, [2023-04-07T15:55:15.678266 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css
I, [2023-04-07T15:55:15.678434 #1375823]  INFO -- : Writing /var/lib/mastodon-versions/v4.1.1/public/assets/pghero/application-c31338f656687c1d733bb0f48d40acd076e24060f3dcff83b34870e4ccc2789d.css.gz
Warning: you are using an unstable release of Node.js (v19.1.0). If you encounter issues with Node.js, consider switching to an Active LTS release. More info: https://docs.npmjs.com/try-the-latest-stable-version-of-node
Compiling...
Compiled all packs in /var/lib/mastodon-versions/v4.1.1/public/packs
Browserslist: caniuse-lite is outdated. Please run:
  npx update-browserslist-db@latest
  Why you should do it regularly: https://github.com/browserslist/update-db#readme

rails aborted!
ActionView::Template::Error: Unknown alias: defaults
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:41:in `initialize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:34:in `new'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:34:in `instance'
/var/lib/mastodon-versions/v4.1.1/app/models/setting.rb:54:in `default_settings'
/var/lib/mastodon-versions/v4.1.1/app/views/layouts/error.html.haml:6:in `_app_views_layouts_error_html_haml___1465707382931673492_68600'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:247:in `public_send'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:247:in `_run'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:154:in `block in render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:345:in `instrument_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:152:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:11:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:117:in `block in _render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:273:in `in_rendering_context'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:116:in `_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/streaming.rb:218:in `_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:103:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/abstract_controller/rendering.rb:47:in `render_to_string'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:41:in `render_to_string'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/renderer.rb:100:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:11:in `render'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:4:in `render_static_page'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:11:in `block (2 levels) in <top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:18:in `block in <top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/command.rb:50:in `invoke'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands.rb:18:in `<top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'

Caused by:
Psych::BadAlias: Unknown alias: defaults
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:41:in `initialize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:34:in `new'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rails-settings-cached-0.6.6/lib/rails-settings/default.rb:34:in `instance'
/var/lib/mastodon-versions/v4.1.1/app/models/setting.rb:54:in `default_settings'
/var/lib/mastodon-versions/v4.1.1/app/views/layouts/error.html.haml:6:in `_app_views_layouts_error_html_haml___1465707382931673492_68600'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:247:in `public_send'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:247:in `_run'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:154:in `block in render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:345:in `instrument_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/template.rb:152:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:72:in `block in render_with_layout'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:205:in `instrument'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:70:in `render_with_layout'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:55:in `render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/template_renderer.rb:11:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/renderer/renderer.rb:29:in `render_to_object'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:117:in `block in _render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/base.rb:273:in `in_rendering_context'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:116:in `_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/streaming.rb:218:in `_render_template'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionview-6.1.7.2/lib/action_view/rendering.rb:103:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/renderers.rb:142:in `render_to_body'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/abstract_controller/rendering.rb:47:in `render_to_string'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:41:in `render_to_string'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/renderer.rb:100:in `render'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/actionpack-6.1.7.2/lib/action_controller/metal/rendering.rb:11:in `render'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:4:in `render_static_page'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:11:in `block (2 levels) in <top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/lib/mastodon-versions/v4.1.1/lib/tasks/assets.rake:18:in `block in <top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/command.rb:50:in `invoke'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/commands.rb:18:in `<top (required)>'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/var/lib/mastodon-versions/v4.1.1/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Tasks: TOP => assets:generate_static_pages
(See full trace by running task with --trace)
```

### Specifications

Mastodon 4.1.1 and 4.1.2
ruby 3.0.4p208 (2022-04-12 revision 3fa771dded) [x86_64-linux]
node v19.1.0
Operating System: Arch Linux
Kernel: Linux 6.0.9-arch1-1
Architecture: x86-64

**Comment by Preskton** [comment]
Seems similar to https://github.com/mastodon/mastodon/issues/17681.

**Comment by ClearlyClaire** [comment]
Do you perhaps have any local change to Mastodon? Especially regarding dependencies (check `Gemfile` and `Gemfile.lock`)

**Comment by Preskton** [comment]
Howdy, @ClearlyClaire - thanks for responding. I totally wiped stuff out and started over, and this cleared things up. What I noticed is that we *might* have had a local change in our `Gemfile` to try to constrain `psych` to `<4` -- that was the only thing I found out of place.

**Comment by Trumeet** [comment]
Hi, I experienced this issue as well, after switching Ruby from `rbenv` to Arch repo's version. This is a issue related to Arch's packaging. Last year, Arch splited the Ruby package into lots of ruby stdlib packages, including a separate `ruby-psych` package. However, Ruby `3.0.5` ships with a `3.x` version of Psych, while Arch's `ruby-psych` is `4.x`. The `4.x` psych has a breaking change that does not allow using aliases by default, which caused the issue.

If you really want to use Arch's ruby (like me), you can temporarily use an old archive (I tested and found that the latest working date was 2022-07-15) to downgrade Ruby and wait for the issue to be fixed.

Related Arch ticket: https://bugs.archlinux.org/task/76004

Breaking change: https://bugs.ruby-lang.org/issues/17866 https://my.diffend.io/gems/psych/3.3.2/4.0.0
