### ISSUE TITLE
Having issues after upgrade to 4.1.2

### ISSUE THREAD

**Issue by sfunk1x** [mastodon/mastodon#24522]
### Steps to reproduce the problem

1. Execute `RAILS_ENV=production bin/tootctl`

### Expected behaviour

Expected tootctl to execute

### Actual behaviour

Crashed with error libidn.so.11: cannot open shared object file: No such file or directory

### Detailed description

After upgrading to Mastodon 4.1.2, I encountered the following error:

```
mastodon@tusk:~/live$ RAILS_ENV=production bin/tootctl
<internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require': libidn.so.11: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/idn-ruby-0.1.5/lib/idn.so (LoadError)
	from <internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `each'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:55:in `block in require'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `each'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler/runtime.rb:44:in `require'
	from /home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/bundler.rb:196:in `require'
	from /home/mastodon/live/config/application.rb:22:in `<top (required)>'
	from /home/mastodon/live/config/environment.rb:2:in `require_relative'
	from /home/mastodon/live/config/environment.rb:2:in `<top (required)>'
	from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `require_relative'
	from /home/mastodon/live/lib/mastodon/media_cli.rb:4:in `<top (required)>'
	from /home/mastodon/live/lib/cli.rb:4:in `require_relative'
	from /home/mastodon/live/lib/cli.rb:4:in `<top (required)>'
	from bin/tootctl:5:in `require_relative'
	from bin/tootctl:5:in `<main>'
```

Additionally, `mastodon-sidekiq` continually crashes after about 1 second. I don't know for sure if it's related to the same issue, as there don't appear to be any logs and journalctl isn't showing anything of value, but this started occuring after the upgrade to 4.1.2. Things had been operating smoothly post-Ubuntu upgrade (from 20.04 to 22.04) for several days.

Attempting to clear bundle cache:

```
mastodon@tusk:~/live$ RAILS_ENV=production bundle exec rake tmp:cache:clear
rake aborted!
LoadError: libidn.so.11: cannot open shared object file: No such file or directory - /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/idn-ruby-0.1.5/lib/idn.so
<internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/mastodon/live/config/application.rb:22:in `<top (required)>'
<internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/home/mastodon/.rbenv/versions/3.0.6/lib/ruby/site_ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/mastodon/live/Rakefile:4:in `<top (required)>'
/home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/mastodon/.rbenv/versions/3.0.6/bin/bundle:25:in `load'
/home/mastodon/.rbenv/versions/3.0.6/bin/bundle:25:in `<main>'
(See full trace by running task with --trace)
```

Checking for file that is allegedly missing:
```
mastodon@tusk:~$ ls -lah /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/idn-ruby-0.1.5/lib/idn.so
-rwxr-xr-x 1 mastodon mastodon 132K Mar 20 21:08 /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/idn-ruby-0.1.5/lib/idn.so
```

Output of `sudo journalctl -u mastodon-sidekiq`:
```
...
-- Boot b66e636302be4135ae0519b8da7099ab --
Nov 08 18:55:28 tusk systemd[1]: Started mastodon-sidekiq.
Nov 08 19:06:59 tusk systemd[1]: Stopping mastodon-sidekiq...
Nov 08 19:07:14 tusk systemd[1]: mastodon-sidekiq.service: State 'stop-sigterm' timed out. Killing.
Nov 08 19:07:14 tusk systemd[1]: mastodon-sidekiq.service: Killing process 750 (bundle) with signal SIGKILL.
Nov 08 19:07:14 tusk systemd[1]: mastodon-sidekiq.service: Killing process 2049 (connection_poo*) with signal SIGKILL.
Nov 08 19:07:14 tusk systemd[1]: mastodon-sidekiq.service: Killing process 2101 (scheduler.rb:6*) with signal SIGKILL.
Nov 08 19:07:14 tusk systemd[1]: mastodon-sidekiq.service: Killing process 2102 (heartbeat) with signal SIGKILL.
```

### Specifications

Mastodon 4.1.2
Ruby 3.0.6
NodeJS 14.21.3
Ubuntu 22.04
Elasticsearch 7.x
Pgsql 12.x

Running a bare metal install - Should note that this also included an upgrade for Ruby via rbenv.

**Comment by ClearlyClaire** [comment]
Try `bundle install --force`

**Comment by vmstan** [comment]
@sfunk1x has your issue been resolved?

**Comment by fishcharlie** [comment]
> Try `bundle install --force`

This worked for me. Thanks so much @ClearlyClaire!
