### ISSUE TITLE
`tootctl`: FrozenError when using `tootctl accounts create` with `--reattach --force` options

### ISSUE THREAD

**Issue by danielmbrasil** [mastodon/mastodon#24540]
### Steps to reproduce the problem

1. Create a new user using `tootctl`, as shown in: 
```
RAILS_ENV=development bin/tootctl accounts create example_username --email example@email.com
```
2. Try creating a new user with the same USERNAME, but using the `--reattach --force` options to delete the previous user, as shown in:
```
RAILS_ENV=development bin/tootctl accounts create example_username --email example2@email.com --reattach --force
```

### Expected behaviour

Creates new account and user, deleting the previous ones

### Actual behaviour

Throws uncaught `FrozenError`

### Detailed description

While trying to create a new account with an old USERNAME using the CLI, I'm getting a `FrozenError`. 

If I delete the account on the web UI, I can use the `tootctl accounts create` with the `--reattach` option and it works fine. However, when trying to get rid of a user attached to the account using the `--force` option, I'm getting an unexpected error.

Line causing the error:
https://github.com/mastodon/mastodon/blob/f05fb51ecb34fd5ef86fad861e16cfc959fe0b27/lib/mastodon/accounts_cli.rb#L109

Full error log:
```
/home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-6.1.7.3/lib/active_model/attribute_set.rb:50:in `write_from_user': can't modify frozen attributes (FrozenError)
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activerecord-6.1.7.3/lib/active_record/attribute_methods/write.rb:40:in `_write_attribute'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/activemodel-6.1.7.3/lib/active_model/attribute_methods.rb:254:in `suspended_at='
	from /home/daniel/CM42/giving_back/mastodon/lib/mastodon/accounts_cli.rb:110:in `create'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
	from bin/tootctl:9:in `block in <main>'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/chewy-7.3.0/lib/chewy/strategy.rb:60:in `wrap'
	from /home/daniel/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/chewy-7.3.0/lib/chewy.rb:154:in `strategy'
	from bin/tootctl:8:in `<main>'
```

Am I missing something?

### Specifications

Mastodon 4.1.2
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]

**Comment by ClearlyClaire** [comment]
This is indeed a bug, and it should be addressed by #24557
