### ISSUE TITLE
Uploading Avatar Gives Error - Errno::EPERM (Operation not permitted - when spawning '/bin/sh')

### ISSUE THREAD

**Issue by RyanBlakeIT** [mastodon/mastodon#25109]
### Steps to reproduce the problem

1. Try to upload an avatar
2. Receive error message saying something went wrong on the web ui
3. Look at logs and see error message.

### Expected behaviour

Avatar uploaded successfully

### Actual behaviour

Error thrown

### Detailed description

```
May 24 01:51:20 cyberdeath bundle[2570129]: [091373c1-1325-4723-9ad6-134fb33a688e] method=GET path=/settings/profile format=html controller=Settings::ProfilesController action=show status=200 duration=66.73 view=54.81 db=5.72
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] [paperclip] Trying to link /tmp/RackMultipart20230524-2570121-gkaugc.jpg to /tmp/8da48df0d93c06af59f465c5475b84e820230524-2570121-9rb6hv.jpg
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] [paperclip] Trying to link /tmp/8da48df0d93c06af59f465c5475b84e820230524-2570121-9rb6hv.jpg to /tmp/c121ffb8c4c740a9e619e9997e059a8e20230524-2570121-ubnlw9.jpg
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] Command :: file -b --mime '/tmp/c121ffb8c4c740a9e619e9997e059a8e20230524-2570121-ubnlw9.jpg'
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] method=PUT path=/settings/profile format=html controller=Settings::ProfilesController action=update status=500 error='Errno::EPERM: Operation not permitted - when spawning '/bin/sh'' duration=23.75 view=0.00 db=1.47
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca]
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] Errno::EPERM (Operation not permitted - when spawning '/bin/sh'):
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca]
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] app/models/concerns/attachmentable.rb:33:in `block in has_attached_file'
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] app/services/update_account_service.rb:8:in `call'
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] app/controllers/settings/profiles_controller.rb:11:in `update'
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] app/controllers/concerns/localized.rb:11:in `set_locale'
May 24 01:51:22 cyberdeath bundle[2570121]: [faf3812d-0584-4b1b-8bba-67d3088ee5ca] lib/mastodon/rack_middleware.rb:9:in `call'
```

Originally the environment variables were not set but I manually set these in hopes it would work:
PAPERCLIP_ROOT_PATH=~/live/public/system
PAPERCLIP_ROOT_URL=https://site.tld/system

Reinstalled ImageMagick and set this under all of the mastodon-* systemd:
ReadWritePaths=/home/mastodon/live/public /home/mastodon/live/tmp

### Specifications

Mastodon v4.1.2
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
Node.js v16.20.0

**Comment by renchap** [comment]
This seems to be related to some Ruby/system config not allowing your Rails process to start external shell commands.

Can you details your server environment a bit?

**Comment by RyanBlakeIT** [comment]
> Replying to https://github.com/mastodon/mastodon/issues/25109#issuecomment-1570937149

Running Debian 11 in a hosted VM environment where I have full control of the instance (& root).

nginx version: nginx/1.18.0

Server version: Apache/2.4.56 (Debian)
Server built:   2023-04-02T03:06:01

**Comment by mjankowski** [comment]
Did this get resolved?
