### ISSUE TITLE
Migration from mastodon to calckey

### ISSUE THREAD

**Issue by Ciechom** [mastodon/mastodon#25373]
### Steps to reproduce the problem

Hello, I'm trying to migrate from mastodon to calckey. Both servers are on the same machine.

When I try to migrate, I get an error: 
![Migration error](https://github.com/mastodon/mastodon/assets/6024778/6b1d6f75-0321-4ba5-a827-169d6caa100d)

Also, I have an issue where from calckey I can't follow an account on mastodon (the hosted on the same machine) but I guess it's more a calckey issue.

### Expected behaviour

The account should migrate.

### Actual behaviour

I get an error that doesn't explain anything.

### Specifications

Mastodon v4.1.2
Calckey 13.1.4.1

Both deployed by YunoHost. (On mastodon, I changed the account I try to migrate from LDAP to manually configured.)

**Comment by Ciechom** [comment]
I forgot to add that I can't redirect to that account as well.

**Comment by Ciechom** [comment]
/var/www/mastodon/live/app/lib/request.rb:278:in `check_private_address': Mastodon::PrivateNetworkAddressError (Mastodon::PrivateNetworkAddressError)
/var/www/mastodon/live/app/lib/request.rb:278:in `check_private_address': Mastodon::PrivateNetworkAddressError (Mastodon::PrivateNetworkAddressError)
        from /var/www/mastodon/live/app/lib/request.rb:219:in `block in open'
        from /var/www/mastodon/live/app/lib/request.rb:217:in `each'
        from /var/www/mastodon/live/app/lib/request.rb:217:in `open'
        from /var/www/mastodon/live/app/lib/request.rb:12:in `connect'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/http-5.1.1/lib/http/connection.rb:42:in `initialize'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.2/lib/httplog/adapters/http.rb:49:in `initialize'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/http-5.1.1/lib/http/client.rb:70:in `new'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/http-5.1.1/lib/http/client.rb:70:in `perform'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.2/lib/httplog/adapters/http.rb:12:in `block (2 levels) in <class:Client>'
        from /opt/rbenv/versions/3.0.6/lib/ruby/3.0.0/benchmark.rb:308:in `realtime'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/httplog-1.6.2/lib/httplog/adapters/http.rb:11:in `block in <class:Client>'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/http-5.1.1/lib/http/client.rb:31:in `request'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/http-5.1.1/lib/http/chainable.rb:20:in `get'
        from /var/www/mastodon/live/app/lib/request.rb:60:in `public_send'
        from /var/www/mastodon/live/app/lib/request.rb:60:in `perform'
        from /var/www/mastodon/live/app/lib/webfinger.rb:56:in `body_from_webfinger'
        from /var/www/mastodon/live/app/lib/webfinger.rb:46:in `perform'
        from /var/www/mastodon/live/app/helpers/webfinger_helper.rb:5:in `webfinger!'
        from /var/www/mastodon/live/app/services/resolve_account_service.rb:86:in `process_webfinger!'
        from /var/www/mastodon/live/app/services/resolve_account_service.rb:34:in `call'
        from /var/www/mastodon/live/lib/mastodon/accounts_cli.rb:647:in `migrate'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:116:in `invoke'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:243:in `block in subcommand'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from bin/tootctl:9:in `block in <main>'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/strategy.rb:57:in `wrap'
        from /var/www/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy.rb:154:in `strategy'
        from bin/tootctl:8:in `<main>'


That's an error from tootctl.

**Comment by Ciechom** [comment]
Setting:
ALLOWED_PRIVATE_ADDRESSES=127.0.0.1
in .env.production allowed me to migrate.
