### ISSUE TITLE
Error processing when trying to refresh a remote media

### ISSUE THREAD

**Issue by nicdex** [mastodon/mastodon#25574]
### Steps to reproduce the problem

1. RAILS_ENV=production bin/tootctl media refresh --status 110601479058494581 --verb
ose

### Expected behaviour

It should refresh (redownload and process) the remote media

### Actual behaviour

It gives me an error

### Detailed description

Processing 110601478791203062
Error processing 110601478791203062: undefined method `+' for nil:NilClass
1/1 |=================================================================================| Time: 00:00:00
Downloaded 1 media attachments (approx. 0 Bytes)

### Specifications

Mastodon 4.1.2 (patched to allow 1000 characters instead of 500)
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
Node v16.20.0
ffmpeg version 4.4.2-0ubuntu0.22.04.1

**Comment by renchap** [comment]
It would help to have more details about where this happens exactly, but I am not sure if we have a way to display a full trace here.

**Comment by amorgner** [comment]
I had the same issue (probably broken images where `file_file_size` is `nil`) and fixed it in a similar way as it was fixed in `tootctl media remove`, see https://github.com/mastodon/mastodon/pull/14657/commits/091fa08fc1104d3c4a2a5c4f27076121e6a5b95d.

**Comment by sbug0** [comment]
I'm getting this also.

Error processing 111032033952961182: undefined method `+' for nil:NilClass

Mastodon 4.1.7
ffmpeg version 4.3.6-0+deb11u1
Nove v16.20.2
ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]

**Comment by sbug0** [comment]
I've have some more information.

When I right click and copy the video url on a video that does work, I get an url like the following:
https://social.sinnesro.se/system/cache/media_attachments/files/111/037/518/635/807/630/original/e4a654f75ff02844.mp4

When I right click and copy the video url on a video that does NOT work, I get an url like the following:
https://social.sinnesro.se/media_proxy/111037433816824162/original

Have the media somehow got stucked between the proxy, and being processed and stored?

**Comment by Lynnesbian** [comment]
This is happening for me too.

Example broken post: See [here](https://botsin.space/@rain/111662283965473172). The original video file is available [here](https://files.botsin.space/media_attachments/files/111/662/283/948/929/767/original/e794d436ff610f6d.mp4), and my server links to it [here](https://fedi.lynnesbian.space/media_proxy/111662284083611454/original). This seems to be happening for me with *all* videos and GIFs.

**Comment by ClearlyClaire** [comment]
@Lynnesbian can you try the following in a Rails console? (`RAILS_LOG_LEVEL=debug RAILS_ENV=production bundle exec rails c`)

```ruby
MediaAttachment.where(status_id: 111662284185412725).find_each do |media|
  media.reset_file!
  media.reset_thumbnail!
  media.save
  puts "file size: #{media.file_file_size}\n"
end
```

**Comment by Lynnesbian** [comment]
Ah, that answers the problem!

```ruby
irb(main):001* MediaAttachment.where(status_id: 111662284185412725).find_each do |media|
irb(main):002*   media.reset_file!
irb(main):003*   media.reset_thumbnail!
irb(main):004*   media.save
irb(main):005*   puts "file size: #{media.file_file_size}\n"
irb(main):006> end
D, [2024-01-04T21:07:06.616741 #648648] DEBUG -- :   MediaAttachment Load (0.7ms)  SELECT "media_attachments".* FROM "media_attachments" WHERE "media_attachments"."status_id" = $1 ORDER BY "media_attachments"."id" ASC LIMIT $2  [["status_id", 111662284185412725], ["LIMIT", 1000]]
D, [2024-01-04T21:07:06.669630 #648648] DEBUG -- : [httplog] GET https://files.botsin.space/media_attachments/files/111/662/283/948/929/767/original/e794d436ff610f6d.mp4 completed with status code 200 in 0.026423 seconds
I, [2024-01-04T21:07:06.689717 #648648]  INFO -- : [paperclip] Trying to link /tmp/4a13a47fead4a77dfc03c4ec607f213320240104-648648-dznmpq.mp4 to /tmp/8ea5e4f315d13abc5a20872f7a541d9f20240104-648648-kq22bh.mp4
I, [2024-01-04T21:07:06.690520 #648648]  INFO -- : Command :: file -b --mime '/tmp/8ea5e4f315d13abc5a20872f7a541d9f20240104-648648-kq22bh.mp4'
D, [2024-01-04T21:07:06.696868 #648648] DEBUG -- : Error fetching remote file: Could not run the `ffprobe` command. Please install ffmpeg.
D, [2024-01-04T21:07:07.666852 #648648] DEBUG -- : [httplog] HEAD http://s3.us-west-1.wasabisys.com:443/the-slum-bucket/cache/media_attachments/files/111/662/284/083/611/454/original/ceb788e627f27ec9.mp4 completed with status code 404 in 0.382908 seconds
D, [2024-01-04T21:07:07.843774 #648648] DEBUG -- : [httplog] HEAD http://s3.us-west-1.wasabisys.com:443/the-slum-bucket/cache/media_attachments/files/111/662/284/083/611/454/small/ceb788e627f27ec9.png completed with status code 404 in 0.172858 seconds
D, [2024-01-04T21:07:07.847457 #648648] DEBUG -- :   TRANSACTION (0.2ms)  BEGIN
D, [2024-01-04T21:07:07.849495 #648648] DEBUG -- :   Account Load (1.2ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."sensitized_at", "accounts"."suspension_origin", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at", "accounts"."indexable" FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 890], ["LIMIT", 1]]
D, [2024-01-04T21:07:07.882292 #648648] DEBUG -- :   TRANSACTION (0.3ms)  COMMIT
D, [2024-01-04T21:07:07.882656 #648648] DEBUG -- : Cache delete: cache:v3:statuses/111662284185412725
file size: 
=> nil
```

My server doesn't have `ffmpeg` for some reason. I must have uninstalled it at some point, maybe due to using `apt autoremove` without reading the output. Thank you so much for pointing me in the right direction! 

```
RAILS_ENV=production bin/tootctl media refresh --status 111662388166727816 --force
1/1 |=============================================================================================================================================================================================| Time: 00:00:02
Downloaded 1 media attachments (approx. 674 Bytes)
```

**Comment by renchap** [comment]
Maybe we should have something validating that `ffmpeg` and `imagemagick` are properly installed somewhere (admin panel? Or in the sidekiq jobs, and fail with a proper exception?).

**Comment by sbug0** [comment]
Hum, but I'm having ffmpeg installed so in my case it can't be that issue.

However, I can't recall having this issue lately.

**Comment by smiba** [comment]
Same error here (with e.full_message):

Error processing 111833607848737555: /home/mastodon/live/lib/mastodon/media_cli.rb:294:in `block in refresh': undefined method `+' for nil:NilClass (NoMethodError)
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:58:in `block (5 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:57:in `block (4 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/strategy.rb:57:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy.rb:154:in `strategy'
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:56:in `block (3 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'

Has been a thing as long as I can remember, which has been at least a year or so. Only recently started looking into these.

**Comment by smiba** [comment]
More verbose logging + http_wire_trace on S3

```
# RAILS_LOG_LEVEL=debug RAILS_ENV=production /home/mastodon/live/bin/tootctl media refresh --status=<post ID with issue> --verbose
Processing <image ID with issue>
opening connection to s3.nl-ams.scw.cloud:443...
opened
starting SSL for s3.nl-ams.scw.cloud:443...
SSL established, protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384
<- "HEAD /files-woof-tech/cache/media_attachments/files/111/825/490/143/618/491/original/674a7f9dc45c23c5.jpeg HTTP/1.1<Request headers etc>
-> "HTTP/1.1 404 Not Found\r\n"
-> "content-type: application/xml\r\n"
-> "date: Sun, 28 Jan 2024 15:23:47 GMT\r\n"
-> "x-amz-id-2: txg42d18ddf8f274b739528-0065b67183\r\n"
-> "x-amz-request-id: txg42d18ddf8f274b739528-0065b67183\r\n"
-> "\r\n"
Conn keep-alive
<- "HEAD /files-woof-tech/cache/media_attachments/files/111/825/490/143/618/491/small/674a7f9dc45c23c5.jpeg HTTP/1.1<Request headers etc>
-> "HTTP/1.1 404 Not Found\r\n"
-> "content-type: application/xml\r\n"
-> "date: Sun, 28 Jan 2024 15:23:47 GMT\r\n"
-> "x-amz-id-2: txgd7493d56c4114203a4aa-0065b67183\r\n"
-> "x-amz-request-id: txgd7493d56c4114203a4aa-0065b67183\r\n"
-> "\r\n"
Conn keep-alive
Cache delete: cache:statuses/<post ID with issue>
Error processing <image ID with issue>: /home/mastodon/live/lib/mastodon/media_cli.rb:294:in `block in refresh': undefined method `+' for nil:NilClass (NoMethodError)
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:58:in `block (5 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.7.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:462:in `with_connection'
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:57:in `block (4 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy/strategy.rb:57:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/chewy-7.2.4/lib/chewy.rb:154:in `strategy'
        from /home/mastodon/live/lib/mastodon/cli_helper.rb:56:in `block (3 levels) in parallelize_with_progress'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:24:in `block in execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `block in synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/synchronization/mutex_lockable_object.rb:48:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/safe_task_executor.rb:22:in `execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/ivar.rb:170:in `safe_execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/future.rb:55:in `block in execute'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `run_task'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:343:in `block (3 levels) in create_worker'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `loop'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block (2 levels) in create_worker'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `catch'
        from /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/concurrent-ruby-1.2.2/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:333:in `block in create_worker'

```

**Comment by smiba** [comment]
Ah: `Error fetching remote file: 6308x4205 images are not supported`

Found the source of the issue :)
