### ISSUE TITLE
BackupWorker fails: ActiveRecord::RecordInvalid: Validation failed: Dump has contents that are not what they are reported to be

### ISSUE THREAD

**Issue by DRKSLV** [mastodon/mastodon#25750]
### Steps to reproduce the problem

1. I was trying to export my archive
2. Export fails over and over in the queue until the Job dies

### Expected behaviour

The backup should successfully complete

### Actual behaviour

It didn't

### Detailed description

Sidekiq Logs: 
You can see the backup worker starting, while other jobs get qued, and then failing on some content type thing

```
Jul 06 01:24:22 server3 bundle[1206573]: 2023-07-05T23:24:22.763Z pid=1206573 tid=18kl class=BackupWorker jid=84c4247a160c90cabe3575c0 INFO: start
Jul 06 01:24:59 server3 bundle[1206573]: 2023-07-05T23:24:59.299Z pid=1206573 tid=rn7d INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
Jul 06 01:25:54 server3 bundle[1206573]: 2023-07-05T23:25:54.574Z pid=1206573 tid=orjl INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuses_scheduler)
Jul 06 01:25:54 server3 bundle[1206573]: 2023-07-05T23:25:54.575Z pid=1206573 tid=rn7d INFO: queueing Scheduler::Trends::RefreshScheduler (trends_refresh_scheduler)
Jul 06 01:25:54 server3 bundle[1206573]: 2023-07-05T23:25:54.941Z pid=1206573 tid=rrjx uniquejobs=reaper INFO: Nothing to delete; exiting.
Jul 06 01:25:59 server3 bundle[1206573]: 2023-07-05T23:25:59.512Z pid=1206573 tid=orjl INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
Jul 06 01:26:55 server3 bundle[1206573]: [paperclip] Trying to link /tmp/archive20230706-1206573-nplo3e.tar.gz to /tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-1bz0pl.gz
Jul 06 01:26:55 server3 bundle[1206573]: [paperclip] Trying to link /tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-1bz0pl.gz to /tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-olyk4w.gz
Jul 06 01:26:55 server3 bundle[1206573]: Command :: file -b --mime '/tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-olyk4w.gz'
Jul 06 01:26:55 server3 bundle[1206573]: [paperclip] Content Type Spoof: Filename archive-20230705232655-f72b79cbe5d581efafb29d9068cec9f7.tar.gz (application/gzip from Headers, ["application/gzip", "application/x-gzip"] from Extension), content type discovered from file command: . See documentation to allow this combination.
Jul 06 01:26:55 server3 bundle[1206573]: [paperclip] Trying to link /tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-1bz0pl.gz to /tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-vbdex5.gz
Jul 06 01:26:55 server3 bundle[1206573]: Command :: file -b --mime '/tmp/ea8b74ecf3adeba82f77c3500a6b297620230706-1206573-vbdex5.gz'
Jul 06 01:26:55 server3 bundle[1206573]: [paperclip] Content Type Spoof: Filename archive-20230705232655-f72b79cbe5d581efafb29d9068cec9f7.tar.gz (application/gzip from Headers, ["application/gzip", "application/x-gzip"] from Extension), content type discovered from file command: . See documentation to allow this combination.
Jul 06 01:26:55 server3 bundle[1206573]: 2023-07-05T23:26:55.378Z pid=1206573 tid=18kl class=BackupWorker jid=84c4247a160c90cabe3575c0 elapsed=152.615 INFO: fail
Jul 06 01:26:55 server3 bundle[1206573]: 2023-07-05T23:26:55.379Z pid=1206573 tid=18kl WARN: {"context":"Job raised exception","job":{"retry":5,"queue":"pull","backtrace":true,"dead":false,"args":[7],"class":"BackupWorker","jid":"84c4247a160c90cabe3575c0","created_at":1688598570.355898,"enqueued_at":1688599462.7629762,"error_message":"Validation failed: Dump has contents that are not what they are reported to be","error_class":"ActiveRecord::RecordInvalid","failed_at":1688598740.414231,"retry_count":3,"error_backtrace":"eJy9jlEKwjAMQK8y9+OPNp1jIruKSE3XoMWugbQreHvnHHgC/Qt5Ce+da7jz\nSDBiyuw4QvCFoFB0LGCn6AKBTPYJrdJKw43GBDjk+UhoYHH7o2pUp5r5z67A\nfAgUDN5h9hyTEtufdO9jdRX0icyXGRJh2da7v4V07RKSsNDmp94sGNN7tYpb\nfVjMNvDwqOZpTbi8AADZiJE=\n","retried_at":1688599357.2457922},"jobstr":"{\"retry\":5,\"queue\":\"pull\",\"backtrace\":true,\"dead\":false,\"args\":[7],\"class\":\"BackupWorker\",\"jid\":\"84c4247a160c90cabe3575c0\",\"created_at\":1688598570.355898,\"enqueued_at\":1688599462.7629762,\"error_message\":\"Validation failed: Dump has contents that are not what they are reported to be\",\"error_class\":\"ActiveRecord::RecordInvalid\",\"failed_at\":1688598740.414231,\"retry_count\":3,\"error_backtrace\":\"eJy9jlEKwjAMQK8y9+OPNp1jIruKSE3XoMWugbQreHvnHHgC/Qt5Ce+da7jz\\nSDBiyuw4QvCFoFB0LGCn6AKBTPYJrdJKw43GBDjk+UhoYHH7o2pUp5r5z67A\\nfAgUDN5h9hyTEtufdO9jdRX0icyXGRJh2da7v4V07RKSsNDmp94sGNN7tYpb\\nfVjMNvDwqOZpTbi8AADZiJE=\\n\",\"retried_at\":1688599357.2457922}"}
Jul 06 01:26:55 server3 bundle[1206573]: 2023-07-05T23:26:55.379Z pid=1206573 tid=18kl WARN: ActiveRecord::RecordInvalid: Validation failed: Dump has contents that are not what they are reported to be
Jul 06 01:26:55 server3 bundle[1206573]: 2023-07-05T23:26:55.379Z pid=1206573 tid=18kl WARN: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5.1/lib/active_record/validations.rb:80:in `raise_validation_error'
Jul 06 01:26:55 server3 bundle[1206573]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5.1/lib/active_record/validations.rb:53:in `save!'
Jul 06 01:26:55 server3 bundle[1206573]: /home/mastodon/live/vendor/bundle/ruby/3.0.0/gems/activerecord-6.1.5.1/lib/active_record/transactions.rb:302:in `block in save!'
Jul 06 01:26:55 server3 bundle[1206573]: 2023-07-05T23:26:55.380Z pid=1206573 tid=6tdh class=Scheduler::AccountsStatusesCleanupScheduler jid=fb4bfe8ba9f29b8f47ae2a0e INFO: start
```

Does anyone know how i can fix this issue with my instance? 

### Specifications

Mastodon v3.5.2
Bundler version 2.3.15
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [aarch64-linux]
node v16.20.0

**Comment by DRKSLV** [comment]
i may have to apply the patch to my running instance - i don't think i can upgrade the server version easily, because i have tinkered too much

i kinda just want to save my data
