### ISSUE TITLE
Latest Nightly breaks

### ISSUE THREAD

**Issue by bentasker** [mastodon/mastodon#25761]
### Steps to reproduce the problem

Switch to latest nightly to get security fix

### Expected behaviour

Mastodon should work

### Actual behaviour

The interface throws an error

### Detailed description

Logs contain the following
```

[649a79e0-887a-4a65-8643-054b8b076492] method=GET path=/notifications format=html controller=HomeController action=index status=500 error='ActionView::Template::Error: undefined method `[]' for nil:NilClass' duration=10.60 view=0.00 db=1.66
[649a79e0-887a-4a65-8643-054b8b076492]   
[649a79e0-887a-4a65-8643-054b8b076492] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
[649a79e0-887a-4a65-8643-054b8b076492]      6: 
[649a79e0-887a-4a65-8643-054b8b076492]      7:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
[649a79e0-887a-4a65-8643-054b8b076492]      8: 
[649a79e0-887a-4a65-8643-054b8b076492]      9:   = render_initial_state
[649a79e0-887a-4a65-8643-054b8b076492]     10:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
[649a79e0-887a-4a65-8643-054b8b076492]     11: 
[649a79e0-887a-4a65-8643-054b8b076492]     12: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
[649a79e0-887a-4a65-8643-054b8b076492]   
[649a79e0-887a-4a65-8643-054b8b076492] app/models/concerns/has_user_settings.rb:107:in `setting_default_privacy'
[649a79e0-887a-4a65-8643-054b8b076492] app/helpers/application_helper.rb:191:in `render_initial_state'
[649a79e0-887a-4a65-8643-054b8b076492] app/views/shared/_web_app.html.haml:9
[649a79e0-887a-4a65-8643-054b8b076492] app/views/shared/_web_app.html.haml:1
[649a79e0-887a-4a65-8643-054b8b076492] app/views/home/index.html.haml:7
[649a79e0-887a-4a65-8643-054b8b076492] app/controllers/concerns/localized.rb:11:in `set_locale'
[649a79e0-887a-4a65-8643-054b8b076492] lib/mastodon/rack_middleware.rb:9:in `call'
[649a79e0-887a-4a65-8643-054b8b076492] lib/public_file_server_middleware.rb:18:in `call'
[1552c700-dcb2-494f-9cfa-056a149320af] method=POST path=/inbox format=html controller=ActivityPub::InboxesController action=create status=202 duration=15.44 view=0.00 db=1.27 key=https://mastodon.social/users/skaly#main-key
```

### Specifications

 ghcr.io/mastodon/mastodon:nightly-2023-07-06

**Comment by bentasker** [comment]
Nope, there wasn't a note in the release notes indicating it was needed so I'd skipped it.

Have rolled back, run the migrations, and looking good.

Thanks! I had a feeling this was going to be PEBKAC

**Comment by bentasker** [comment]
Ah that'll do it - I was on the releases and have switched to nightly just for this fix.

Thanks again

**Comment by kypeli** [comment]
I faced the same issue (with Docker). Where can I find the documentation about the said DB migration step that I need to run? And is it applicable also when running in Docker?

**Comment by kypeli** [comment]
Thanks! I am running 4.1.2 which is pulled by the default image from the docker-compose.yml file. I think I can try that by defining the nightly build as the image version and rebuilding the image.

**Comment by kypeli** [comment]
I ran update to `image: ghcr.io/mastodon/mastodon:nightly-2023-07-06` and run the migration command. Now getting

```
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]      6:
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]      7:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]      8:
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]      9:   = render_initial_state
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]     10:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]     11:
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]     12: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2]
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/models/concerns/has_user_settings.rb:107:in `setting_default_privacy'
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/helpers/application_helper.rb:191:in `render_initial_state'
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/views/shared/_web_app.html.haml:9
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/views/shared/_web_app.html.haml:1
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/views/home/index.html.haml:7
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] app/controllers/concerns/localized.rb:11:in `set_locale'
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] lib/mastodon/rack_middleware.rb:9:in `call'
[2851f838-fa69-4ce8-b645-68c9b7fd4ab2] lib/public_file_server_middleware.rb:18:in `call'

```
I'll just recreate my instance from backup and wait for the official Docker image to appear.

**Comment by ClearlyClaire** [comment]
`ghcr.io/mastodon/mastodon:v4.1.3` has been published!

**Comment by bentasker** [comment]
Awesome thanks! I can get back off the nightly track :D
