### ISSUE TITLE
Issue upgrading to 4.1.3 - Incompatible library version error on mastodon-web startup 

### ISSUE THREAD

**Issue by sethpjohnson** [mastodon/mastodon#25784]
### Steps to reproduce the problem

Preface this to say I started from 4.1.1 because I couldn't get Ruby 3.0.6 to install. I finally did... maybe. `rbenv` is installed under the mastodon user and `ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]` is the version I see when I run `ruby -v`

1. Update using rbenv -- 3.0.6 running
2. Follow instructions to pull 4.1.3 
3. run `build install` and `yarn install`
4. Restart services and error page only loads
5. Followed many troubleshooting steps from the documents site and various web searches. 
...

### Expected behaviour

website should start up 

### Actual behaviour

Error page -- something went wrong page shows

### Detailed description

when tailing journalctl and starting the -web service I see this:

```
Jul 07 06:27:27 hometech.social systemd[1]: Started mastodon-web.
Jul 07 06:27:27 hometech.social bundle[46139]: bundler: failed to load command: puma (/var/www/mastodon/vendor/bundle/ruby/3.0.0/bin/puma)
Jul 07 06:27:27 hometech.social bundle[46139]: /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/date-3.3.3/lib/date.rb:4:in `require': incompatible library version - /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/date-3.3.3/lib/date_core.so (LoadError)
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/date-3.3.3/lib/date.rb:4:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /usr/lib/ruby/3.0.0/time.rb:3:in `require'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /usr/lib/ruby/3.0.0/time.rb:3:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/lib/puma.rb:6:in `require'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/lib/puma.rb:6:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/lib/puma/cli.rb:6:in `require'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/lib/puma/cli.rb:6:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/bin/puma:6:in `require'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/gems/puma-5.6.5/bin/puma:6:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/bin/puma:25:in `load'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/www/mastodon/vendor/bundle/ruby/3.0.0/bin/puma:25:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `load'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:58:in `kernel_load'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli/exec.rb:23:in `run'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:486:in `exec'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:31:in `dispatch'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/cli.rb:25:in `start'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/exe/bundle:48:in `block in <top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /var/lib/gems/3.0.0/gems/bundler-2.3.26/exe/bundle:36:in `<top (required)>'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /usr/local/bin/bundle:25:in `load'
Jul 07 06:27:27 hometech.social bundle[46139]:         from /usr/local/bin/bundle:25:in `<main>'
Jul 07 06:27:27 hometech.social systemd[1]: mastodon-web.service: Main process exited, code=exited, status=1/FAILURE
```

### Specifications

Mastodon 4.1.3 
Ubuntu 22.04.2
Ruby 3.0.6p216 (2023-03-30 revision 23a532679b) [x86_64-linux]
Bundler 2.2.33
Yarn 1.22.19

Not sure there is anything else but if more info is needed I will post it.

**Comment by ClearlyClaire** [comment]
This does not look related to 4.1.3 specifically, but to a system update you did since last time you restarted the services.

You need to rebuild gems that depend on those updated system libraries. To do so, you can do `bundle install --force`

**Comment by sethpjohnson** [comment]
Hmm, I've done that a few times already. But I agree it's not an update issue. I tried rolling back to 4.1.1 and receive the same error.

**Comment by ClearlyClaire** [comment]
In that case, I wonder if your `mastodon-web.service` and `mastodon-sidekiq.service` files perhaps use a different version of Ruby than the one you use to install dependencies build the assets.

Check the `ExecStart` line of `/etc/systemd/system/mastodon-web.service` and `/etc/systemd/system/mastodon-sidekiq.service` and check whether it's not hardcoded to a particular Ruby version, and if it is, whether that's the same that you use when you manually issue commands.

**Comment by sethpjohnson** [comment]
It shows `ExecStart=/usr/local/bin/bundle exec puma -C config/puma.rb` but shouldn't that be `/home/mastodon/.rbenv/shims/bundle` ?

**Comment by sethpjohnson** [comment]
That seems to have done it

**Comment by sethpjohnson** [comment]
update complete 🎉Thanks for your help.
