### ISSUE TITLE
Error when viewing a remote account with verified links in the admin panel

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#25795]
### Steps to reproduce the problem

In the admin panel, access a remote account with at least one verified link (like `/admin/accounts/109310454390129092`).

### Expected behaviour

The page shows

### Actual behaviour

It results in a Ruby error

### Detailed description

Stacktrace:

```
ActionView::Template::Error (ArgumentError):
    21:                 - if field.verified?
    22:                   %span.verified__mark{ title: t('accounts.link_verified_on', date: l(field.verified_at)) }
    23:                     = fa_icon 'check'
    24:                 = prerender_custom_emojis(account_field_value_format(field, with_rel_me: false), account.emojis)
    25:
    26:     - if account.note.present?
    27:       %div

app/lib/emoji_formatter.rb:16:in `initialize'
app/helpers/application_helper.rb:245:in `new'
app/helpers/application_helper.rb:245:in `prerender_custom_emojis'
app/views/admin/accounts/show.html.haml:24
app/views/admin/accounts/show.html.haml:17:in `each'
app/views/admin/accounts/show.html.haml:17
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

### Specifications

Mastodon 4.1.3

**Comment by ClearlyClaire** [comment]
This is caused by one of our mitigations outputting a string that is not marked `html_safe`
