### ISSUE TITLE
tootctl statuses remove fails in nightly

### ISSUE THREAD

**Issue by tabletcorry** [mastodon/mastodon#26171]
### Steps to reproduce the problem

1. Run `tootctl statuses remove --days=5`
2. Observe immediate failure

### Expected behaviour

Old statuses removed

### Actual behaviour

Immediate crash

### Detailed description

Command executed and output:
```
~$ RAILS_ENV=production nice /home/mastodon/live/bin/tootctl statuses remove --days=5
Creating temporary database indices...
Extract the deletion target from statuses... This might take a while...
Removing temporary database indices to restore write performance...
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast': can't cast Array (TypeError)

        else raise TypeError, "can't cast #{value.class.name}"
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/quoting.rb:142:in `type_cast'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:220:in `block in type_casted_binds'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:216:in `map'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/quoting.rb:216:in `type_casted_binds'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:765:in `exec_no_cache'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:132:in `exec_insert'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:88:in `exec_insert'
	from /home/mastodon/live/lib/mastodon/cli/statuses.rb:64:in `remove_statuses'
	from /home/mastodon/live/lib/mastodon/cli/statuses.rb:34:in `remove'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /home/mastodon/live/bin/tootctl:9:in `block in <main>'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/strategy.rb:60:in `wrap'
	from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy.rb:154:in `strategy'
	from /home/mastodon/live/bin/tootctl:8:in `<main>'
```

### Mastodon instance

mastodon.sharpletters.net

### Mastodon version

v4.1.5+nightly-2023-07-25
v4.1.5+nightly-2023-07-26

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
- Node.js version: v16.20.1

**Comment by kevintraver** [comment]
Is there a reason the *bind* parameter is double wrapped in an array with `nil`?

https://github.com/mastodon/mastodon/blob/6781dc6462b0511a2d3e6e08c965b7006ffd3331/lib/mastodon/cli/statuses.rb#L64

Should it be something like this?

`ActiveRecord::Base.connection.exec_insert(<<-SQL.squish, 'SQL', [max_id])`

**Comment by ClearlyClaire** [comment]
Thanks for the report! This most likely broke when updating to Rails 7, I'll investigate the issue.
