### ISSUE TITLE
Missing attribute: `published_at` after updating to a recent nightly

### ISSUE THREAD

**Issue by renchap** [mastodon/mastodon#26229]
### Steps to reproduce the problem

When a nightly/`main` update containing https://github.com/mastodon/mastodon/pull/26153, timeline request result in 500 errors:

```
ActiveModel::MissingAttributeError (missing attribute: published_at):
app/controllers/api/v1/favourites_controller.rb:10:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
lib/public_file_server_middleware.rb:18:in `call'

ActiveModel::MissingAttributeError (missing attribute: published_at):
app/controllers/api/v1/notifications_controller.rb:17:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'

ActiveModel::MissingAttributeError (missing attribute: published_at):
app/controllers/api/v1/trends/statuses_controller.rb:12:in `index'
app/controllers/concerns/localized.rb:11:in `set_locale'
lib/mastodon/rack_middleware.rb:9:in `call'
```

### Expected behaviour

The update does not cause errors

### Actual behaviour

We get 500 errors on timelines

### Detailed description

Purging the Rails cache fixes the issues, there are most probably items in cache without this new `published_at` attribute, and rendering those fail until the cache expires.

### Mastodon version

`nightly`

**Comment by ClearlyClaire** [comment]
Something like the following should fix it, but I wonder if there's a cleaner solution:

```patch
diff --git a/app/serializers/rest/preview_card_serializer.rb b/app/serializers/rest/preview_card_serializer.rb
index cf700ff24e..2eb67214c9 100644
--- a/app/serializers/rest/preview_card_serializer.rb
+++ b/app/serializers/rest/preview_card_serializer.rb
@@ -15,4 +15,8 @@ class REST::PreviewCardSerializer < ActiveModel::Serializer
   def html
     Sanitize.fragment(object.html, Sanitize::Config::MASTODON_OEMBED)
   end
+
+  def published_at
+    object.published_at if object.respond_to?(:created_at)
+  end
 end
```
