### ISSUE TITLE
`tootctl search deploy` crashes on the latest nightly: PG::UndefinedColumn: ERROR:  column "id" does not exist (ActiveRecord::StatementInvalid) LINE 1: SELECT "id" FROM "instances" WHERE "instances"."id" IN ($1, ...

### ISSUE THREAD

**Issue by ronilaukkarinen** [mastodon/mastodon#26246]
### Steps to reproduce the problem

1. Pull the latest main up until [74903af](https://github.com/mastodon/mastodon/commit/74903af7ce6a0622752e19b1e0b326ecfa0463cb)
2. Rebuild assets
3. Restart server
4. Run `RAILS_ENV=production /home/mastodon/live/bin/tootctl search deploy;`
5. Get error on "Importing InstancesIndex"

### Expected behaviour

The command should run through

### Actual behaviour

Crashes on error

### Detailed description

I first thought this is about my fork but then pulled the clean main and it does the same:

```
RAILS_ENV=production /home/mastodon/live/bin/tootctl search deploy;
```

This (at the first part _Importing InstancesIndex 2700/6715551 |                  |  ETA: 00:26:11_)

```
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': PG::UndefinedColumn: ERROR:  column "id" does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT "id" FROM "instances" WHERE "instances"."id" IN ($1, ...
               ^

        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation/calculations.rb:250:in `block in pluck'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation.rb:962:in `skip_query_cache_if_necessary'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation/calculations.rb:246:in `pluck'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:49:in `block in clean_up!'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:40:in `block in scroll_batches'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:36:in `loop'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:36:in `scroll_batches'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search.rb:61:in `method_missing'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:47:in `clean_up!'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:83:in `block in deploy'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:61:in `each'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:61:in `deploy'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /home/mastodon/live/bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/strategy.rb:60:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy.rb:154:in `strategy'
        from /home/mastodon/live/bin/tootctl:8:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `exec_params': ERROR:  column "id" does not exist (PG::UndefinedColumn)
LINE 1: SELECT "id" FROM "instances" WHERE "instances"."id" IN ($1, ...
               ^

        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:768:in `block (2 levels) in exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:767:in `block in exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:769:in `block in log'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract_adapter.rb:760:in `log'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:766:in `exec_no_cache'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql_adapter.rb:745:in `execute_and_clear'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/postgresql/database_statements.rb:54:in `exec_query'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:560:in `select'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/database_statements.rb:66:in `select_all'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/connection_adapters/abstract/query_cache.rb:110:in `select_all'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation/calculations.rb:250:in `block in pluck'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation.rb:962:in `skip_query_cache_if_necessary'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.6/lib/active_record/relation/calculations.rb:246:in `pluck'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:49:in `block in clean_up!'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:40:in `block in scroll_batches'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:36:in `loop'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search/scrolling.rb:36:in `scroll_batches'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/search.rb:61:in `method_missing'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:47:in `clean_up!'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:83:in `block in deploy'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:61:in `each'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:61:in `deploy'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /home/mastodon/live/bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy/strategy.rb:60:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.3/lib/chewy.rb:154:in `strategy'
        from /home/mastodon/live/bin/tootctl:8:in `<main>'

```

These two commands go through fine:

```
RAILS_ENV=production bin/tootctl search deploy --only accounts
RAILS_ENV=production bin/tootctl search deploy --only statuses
```

Any ideas? It seems [InstanceIndex](https://github.com/mastodon/mastodon/commit/b4e739ff0f64c601973762ac986c0e63092d2d7e) was introduced two days ago. Some migration missing?

### Mastodon instance

mementomori.social

### Mastodon version

v4.1.5+nightly-2023-07-28~mementomori-social-mods

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v16.20.1

**Comment by supernovae** [comment]
Confirmed on universeodon.com

This index rebuild worked from main from about ~2 days ago, but is broken as of 7/29/23

Exact same error message.

**Comment by D-side** [comment]
Most likely the cleanup procedure (that runs last) being hardcoded to using ids:

https://github.com/mastodon/mastodon/blob/74903af7ce6a0622752e19b1e0b326ecfa0463cb/app/lib/importer/base_importer.rb#L46-L61

…and in case of instances should be using domains instead.

**Comment by ronilaukkarinen** [comment]
> Most likely the cleanup procedure (that runs last) being hardcoded to using ids:
> 
> https://github.com/mastodon/mastodon/blob/74903af7ce6a0622752e19b1e0b326ecfa0463cb/app/lib/importer/base_importer.rb#L46-L61
> 
> …and in case of instances should be using domains instead.

That's it! Tested it with changing ids to domains on a local environment. After the change it works:

```$ RAILS_ENV=production bin/tootctl search deploy --only instances --concurrency 16 --batch_size 4096;
Done! 18407/18407 |=================================================================================================================================================================================| Time: 00:00:01 (18407 docs/s)
Indexed 18373 records, de-indexed 0
```

There's no id column indeed:

```
mastodon_production-# \d+ instances
                                           Materialized view "public.instances"
     Column     |       Type        | Collation | Nullable | Default | Storage  | Compression | Stats target | Description 
----------------+-------------------+-----------+----------+---------+----------+-------------+--------------+-------------
 domain         | character varying |           |          |         | extended |             |              | 
 accounts_count | bigint            |           |          |         | plain    |             |              | 
Indexes:
    "index_instances_on_domain" UNIQUE, btree (domain)
    "index_instances_on_reverse_domain" btree (reverse('.'::text || domain::text), domain)
View definition:
 WITH domain_counts(domain, accounts_count) AS (
         SELECT accounts.domain,
            count(*) AS accounts_count
           FROM accounts
          WHERE accounts.domain IS NOT NULL
          GROUP BY accounts.domain
        )
 SELECT domain_counts.domain,
    domain_counts.accounts_count
   FROM domain_counts
UNION
 SELECT domain_blocks.domain,
    COALESCE(domain_counts.accounts_count, 0::bigint) AS accounts_count
   FROM domain_blocks
     LEFT JOIN domain_counts ON domain_counts.domain::text = domain_blocks.domain::text
UNION
 SELECT domain_allows.domain,
    COALESCE(domain_counts.accounts_count, 0::bigint) AS accounts_count
   FROM domain_allows
     LEFT JOIN domain_counts ON domain_counts.domain::text = domain_allows.domain::text;
Access method: heap
```

**Comment by renchap** [comment]
I think this comes from the introduction of `app/chewy/instances_index.rb` in #26075.
