### ISSUE TITLE
v4.2.0 raises more bad URI error due to encoding/decoding

### ISSUE THREAD

**Issue by xmflsct** [mastodon/mastodon#26494]
### Steps to reproduce the problem

Say when a remote URI includes some special characters, like `example.com/path[addition]` and in there `[` and `]` would break. Previously it was fine.

This is observed by https://github.com/tooot-app/app as above characters are used as push endpoints.

### Expected behaviour

Treat URI encoding/decoding more relax

### Actual behaviour

Throws error "URI::InvalidURIError: bad URI(is not URI?)"

### Mastodon version

v4.2.0-beta1

### Technical details

Running official Docker image of ARM64 build

**Comment by Gargron** [comment]
Potentially related changes: #24932 #26219

**Comment by xmflsct** [comment]
Thanks @Gargron. Just to be clear, versions prior to v4.2.0 works fine with brackets.

**Comment by xmflsct** [comment]
Thanks @Gargron. Just to be clear, versions prior to v4.2.0 works fine with brackets.

**Comment by c960657** [comment]
This URL is not RFC 3986-compliant. Which software generates such URLs?

The URL is passed from Mastodon to [http.rb](https://github.com/httprb/http) to [http-cookie](https://github.com/sparklemotion/http-cookie) to [URI](https://github.com/ruby/uri) which raises on the invalid URL.

Stacktrace below.
```
/usr/local/rvm/gems/default/gems/uri-0.12.2/lib/uri/rfc3986_parser.rb:72:in `parse'
/usr/local/rvm/gems/default/gems/uri-0.12.2/lib/uri/common.rb:193:in `parse'
/usr/local/rvm/gems/default/gems/uri-0.12.2/lib/uri/common.rb:722:in `URI'
/usr/local/rvm/gems/default/gems/http-cookie-1.0.5/lib/http/cookie.rb:278:in `parse'
/usr/local/rvm/gems/default/gems/http-cookie-1.0.5/lib/http/cookie_jar.rb:191:in `parse'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/response.rb:142:in `block in cookies'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/response.rb:141:in `each'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/response.rb:141:in `each_with_object'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/response.rb:141:in `cookies'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/redirector.rb:107:in `collect_cookies_from_response'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/redirector.rb:54:in `perform'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/client.rb:34:in `request'
/usr/local/rvm/gems/default/gems/http-5.1.1/lib/http/chainable.rb:20:in `get'
/workspaces/mastodon/app/lib/request.rb:127:in `public_send'
/workspaces/mastodon/app/lib/request.rb:127:in `perform'
```

**Comment by c960657** [comment]
One possible fix is this monkey-patch:
```ruby
class HTTP::Cookie
  class << self
    alias_method :original_parse, :parse

    def parse(set_cookie, origin, options = nil)
      origin = Addressable::URI.parse(origin).normalize.to_s
      original_parse(set_cookie, origin, options = nil)
    end
  end
end
```

I still think it was the right decision to remove the call to `Addressable::URI#normalize` for all URLs before fetching them (in #26219). But it is a problem that http.rb allows fetching “raw” URLs but uses a cookie library which insists on RFC 3986-compliant URLs. I'll make a PR for http.rb.

I wont have time to look further into this today.

But for the record, the URL in question is not RFC 3986-compliant, so whichever software is generating them ought to change them into e.g. https://api.tooot.app/push/send/ExponentPushToken%5BctjpgWOIfKWL3sUeSZX1qc%5D/social.xmflsct.com/1/z8v5iy83po. For such “system URLs” which are not supposed to be read/typed by humans, there is not really a reason to deviate from RFC 3986.

**Comment by xmflsct** [comment]
Yep not to suggest the example URL is the _correct_ one. Just to report a behaviour change due to the upgrade.

**Comment by ShadowJonathan** [comment]
> This URL is not RFC 3986-compliant. Which software generates such URLs?

Tooot

**Comment by c960657** [comment]
I have created a PR for http-cookie that will make it less strict when parsing URLs.
https://github.com/sparklemotion/http-cookie/pull/44

I have made a workaround for Mastodon (#26515), though I am not convinced this needs fixing. AFAICT this issue only affects machine-generated URLs provided in ActivityPub and other APIs. Any URLs entered into a status are subject to additional normalisation and wont trigger this issue. Also, the issue only occurs on URLs that set cookies _and_ are redirecting.

**Comment by c960657** [comment]
A fix for this has been committed to http-cookie (but not yet released):
https://github.com/sparklemotion/http-cookie/commit/8930674adf5b80c93e889bc2350d0a65f251fb5d

**Comment by renchap** [comment]
Closing this as I think it has been fixed
