### ISSUE TITLE
422 error when upload video

### ISSUE THREAD

**Issue by tribela** [mastodon/mastodon#26560]
### Steps to reproduce the problem

1. Upload a video
2. Wait for processed
3. Got a 422 error
...

### Expected behaviour

Processed well and get a thumbnail on compose box

### Actual behaviour

Failed with 422 error

### Detailed description

ffmpeg processing is failed on sidekiq. Further informations are below

### Mastodon instance

qdon.space

### Mastodon version

v4.2.0-beta1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.2.2
- Node.js version: 16.20

<details>
<summary>Error log from sidekiq</summary>

```
23:45:16 sidekiq.1 | Command :: ffmpeg -nostdin -i '/tmp/74a4c6a340ef33eadf25ca00c8d1aa0b20230820-210934-m0uepf.mp4' -loglevel 'fatal' -movflags 'faststart' -pix_fmt 'yuv420p' -vf 'scale='\''trunc(min(8294400, iw*ih) / ih / 2)*2:-2'\''' -vsync 'vfr' -c:v 'h264' -maxrate '1300K' -bufsize '1300K' -b:v '1300K' -frames:v '10800' -crf '18' -map_metadata '-1' -acodec 'aac' -strict 'experimental' -r '120' -y '/tmp/74a4c6a340ef33eadf25ca00c8d1aa0b20230820-210934-m0uepf20230820-210934-gze0l0.mp4'
23:45:16 sidekiq.1 | 2023-08-20T14:45:16.409Z pid=210934 tid=31wa class=PostProcessMediaWorker jid=d3b4c006e185ba552da974e3 elapsed=0.233 INFO: fail
23:45:16 sidekiq.1 | 2023-08-20T14:45:16.409Z pid=210934 tid=31wa WARN: {"context":"Job raised exception","job":{"retry":1,"queue":"default","dead":false,"args":[110922479446467329],"class":"PostProcessMediaWorker","jid":"d3b4c006e185ba552da974e3","created_at":1692542716.175338,"enqueued_at":1692542716.1757054}}
23:45:16 sidekiq.1 | 2023-08-20T14:45:16.409Z pid=210934 tid=31wa WARN: Paperclip::Error: Error while transcoding 74a4c6a340ef33eadf25ca00c8d1aa0b20230820-210934-m0uepf: Command 'ffmpeg -nostdin -i '/tmp/74a4c6a340ef33eadf25ca00c8d1aa0b20230820-210934-m0uepf.mp4' -loglevel 'fatal' -movflags 'faststart' -pix_fmt 'yuv420p' -vf 'scale='\''trunc(min(8294400, iw*ih) / ih / 2)*2:-2'\''' -vsync 'vfr' -c:v 'h264' -maxrate '1300K' -bufsize '1300K' -b:v '1300K' -frames:v '10800' -crf '18' -map_metadata '-1' -acodec 'aac' -strict 'experimental' -r '120' -y '/tmp/74a4c6a340ef33eadf25ca00c8d1aa0b20230820-210934-m0uepf20230820-210934-gze0l0.mp4'' returned 1. Expected 0
23:45:16 sidekiq.1 | Here is the command output: STDOUT:
23:45:16 sidekiq.1 |
23:45:16 sidekiq.1 |
23:45:16 sidekiq.1 |
23:45:16 sidekiq.1 | STDERR:
23:45:16 sidekiq.1 |
23:45:16 sidekiq.1 | [vost#0:0/libx264 @ 0x56190a1eeb80] One of -r/-fpsmax was specified together a non-CFR -vsync/-fps_mode. This is contradictory.
23:45:16 sidekiq.1 |
23:45:16 sidekiq.1 | 2023-08-20T14:45:16.409Z pid=210934 tid=31wa WARN: /home/jarm/git/qdon.space/lib/paperclip/transcoder.rb:57:in `rescue in make'
23:45:16 sidekiq.1 | /home/jarm/git/qdon.space/lib/paperclip/transcoder.rb:53:in `make'
23:45:16 sidekiq.1 | /home/jarm/git/qdon.space/vendor/bundle/ruby/3.2.0/gems/kt-paperclip-7.2.0/lib/paperclip/processor.rb:33:in `make'
23:45:33 sidekiq.1 | 2023-08-20T14:45:33.985Z pid=210934 tid=2xi2 class=PostProcessMediaWorker jid=d3b4c006e185ba552da974e3 INFO: start
```

</details>

Maybe related with this ffmpeg commit: https://github.com/FFmpeg/FFmpeg/commit/260f3918937463f1b90e1b77cba80b917f3cb8c1

And, related mastodon commit is: https://github.com/mastodon/mastodon/pull/17619

**Comment by selfawaresoup** [comment]
I'm having the same issue. 422 errors on GIFs and videos

**Comment by selfawaresoup** [comment]
Following the steps here fixed it for us: https://github.com/mastodon/mastodon/issues/26402

**Comment by tribela** [comment]
> Following the steps here fixed it for us: #26402

That issue is from CloudFlare's R2 storage
But this issue is comming from ffmpeg's deprecation of encoding parameters

**Comment by Gargron** [comment]
Does the issue still exist after changed encoding parameters in #26631?

**Comment by tribela** [comment]
> Does the issue still exist after changed encoding parameters in #26631?

Tested on local dev env, It seems to be fixed after 26631
