### ISSUE TITLE
Elasticsearch: no such index [statuses]

### ISSUE THREAD

**Issue by kotori2** [mastodon/mastodon#27024]
### Steps to reproduce the problem

* Upgrade to v4.2.0
* Apply patches at https://docs.joinmastodon.org/admin/elasticsearch/#chinese-search-optimization
* `RAILS_ENV=production bin/tootctl search deploy --reset-chewy`

### Expected behaviour

Indexes rebuild successfully

### Actual behaviour

Got the errors. 

### Detailed description

I'm upgrading from v4.1.8 to v4.2.0 with the help of the upgrade guide on [this page](https://github.com/mastodon/mastodon/releases/tag/v4.2.0) and the [Chinese search optimization patch on this page](https://docs.joinmastodon.org/admin/elasticsearch/#chinese-search-optimization).
I got some issues when applying this patch, see https://github.com/mastodon/documentation/issues/1306. 
When I was trying to rebuild the ES index with `RAILS_ENV=production bin/tootctl search deploy --reset-chewy`, I got the error:
```
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [statuses]","resource.type":"index_or_alias","resource.id":"statuses","index_uuid":"_na_","index":"statuses"}],"type":"index_not_found_exception","reason":"no such index [statuses]","resource.type":"index_or_alias","resource.id":"statuses","index_uuid":"_na_","index":"statuses"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/put_settings.rb:55:in `put_settings'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:31:in `optimize_for_search!'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:90:in `ensure in block in deploy'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:90:in `block in deploy'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:65:in `each'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:65:in `deploy'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from bin/tootctl:8:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index [statuses]","resource.type":"index_or_alias","resource.id":"statuses","index_uuid":"_na_","index":"statuses"}],"type":"index_not_found_exception","reason":"no such index [statuses]","resource.type":"index_or_alias","resource.id":"statuses","index_uuid":"_na_","index":"statuses"},"status":404} (Elasticsearch::Transport::Transport::Errors::NotFound)
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/put_settings.rb:55:in `put_settings'
        from /home/mastodon/live/app/lib/importer/base_importer.rb:26:in `optimize_for_import!'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:67:in `block in deploy'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:65:in `each'
        from /home/mastodon/live/lib/mastodon/cli/search.rb:65:in `deploy'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from bin/tootctl:8:in `<main>'
```

### Mastodon instance

m.0x.mk

### Mastodon version

v4.2.0 release

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]`
- Node.js version: `v18.17.1`

**Comment by mtfront** [comment]
I'm seeing the same error

**Comment by Tyketc** [comment]
The reason for this is that v4.2.0 has made significant changes to the search index, and the documentation's patch for Chinese search optimization has not been updated in a while.

Similar modifications need to be made to the newly added `public_statuses_index.rb` file, just like what was done with `status_index.rb`.

```
From fd90b1e59a4bf5cdc3dd7e1c500f9337386015a6 Mon Sep 17 00:00:00 2001
From: TykeTC <dev@uestc.social>
Date: Sat, 23 Sep 2023 08:00:00 +0000
Subject: [PATCH] Apply Chinese search optimization

---
 app/chewy/accounts_index.rb        |  2 +-
 app/chewy/public_statuses_index.rb | 12 +++++++++++-
 app/chewy/statuses_index.rb        | 12 +++++++++++-
 app/chewy/tags_index.rb            | 11 ++++++++++-
 4 files changed, 33 insertions(+), 4 deletions(-)

diff --git a/app/chewy/accounts_index.rb b/app/chewy/accounts_index.rb
index 00db257ac..ea308c8de 100644
--- a/app/chewy/accounts_index.rb
+++ b/app/chewy/accounts_index.rb
@@ -34,7 +34,7 @@ class AccountsIndex < Chewy::Index
       },
 
       verbatim: {
-        tokenizer: 'standard',
+        tokenizer: 'ik_max_word',
         filter: %w(lowercase asciifolding cjk_width),
       },
 
diff --git a/app/chewy/public_statuses_index.rb b/app/chewy/public_statuses_index.rb
index 4be204d4a..7db283f1e 100644
--- a/app/chewy/public_statuses_index.rb
+++ b/app/chewy/public_statuses_index.rb
@@ -19,6 +19,15 @@ class PublicStatusesIndex < Chewy::Index
       },
     },
 
+    char_filter: {
+      tsconvert: {
+        type: 'stconvert',
+        keep_both: false,
+        delimiter: '#',
+        convert_type: 't2s',
+      },
+    },
+
     analyzer: {
       verbatim: {
         tokenizer: 'uax_url_email',
@@ -26,7 +35,7 @@ class PublicStatusesIndex < Chewy::Index
       },
 
       content: {
-        tokenizer: 'standard',
+        tokenizer: 'ik_max_word',
         filter: %w(
           lowercase
           asciifolding
@@ -36,6 +45,7 @@ class PublicStatusesIndex < Chewy::Index
           english_stop
           english_stemmer
         ),
+        char_filter: %w(tsconvert),
       },
 
       hashtag: {
diff --git a/app/chewy/statuses_index.rb b/app/chewy/statuses_index.rb
index 6b25dc9df..b1e04c4da 100644
--- a/app/chewy/statuses_index.rb
+++ b/app/chewy/statuses_index.rb
@@ -19,6 +19,15 @@ class StatusesIndex < Chewy::Index
       },
     },
 
+    char_filter: {
+      tsconvert: {
+        type: 'stconvert',
+        keep_both: false,
+        delimiter: '#',
+        convert_type: 't2s',
+      },
+    },
+
     analyzer: {
       verbatim: {
         tokenizer: 'uax_url_email',
@@ -26,7 +35,7 @@ class StatusesIndex < Chewy::Index
       },
 
       content: {
-        tokenizer: 'standard',
+        tokenizer: 'ik_max_word',
         filter: %w(
           lowercase
           asciifolding
@@ -36,6 +45,7 @@ class StatusesIndex < Chewy::Index
           english_stop
           english_stemmer
         ),
+        char_filter: %w(tsconvert),
       },
 
       hashtag: {
diff --git a/app/chewy/tags_index.rb b/app/chewy/tags_index.rb
index 5b6349a96..5b5f0c6ab 100644
--- a/app/chewy/tags_index.rb
+++ b/app/chewy/tags_index.rb
@@ -2,15 +2,24 @@
 
 class TagsIndex < Chewy::Index
   settings index: index_preset(refresh_interval: '30s'), analysis: {
+    char_filter: {
+      tsconvert: {
+        type: 'stconvert',
+        keep_both: false,
+        delimiter: '#',
+        convert_type: 't2s',
+      },
+    },
     analyzer: {
       content: {
-        tokenizer: 'keyword',
+        tokenizer: 'ik_max_word',
         filter: %w(
           word_delimiter_graph
           lowercase
           asciifolding
           cjk_width
         ),
+        char_filter: %w(tsconvert),
       },
 
       edge_ngram: {
-- 
2.40.1


```
