### ISSUE TITLE
Upgrade procedure from 4.1.9 to 4.2.0 Fails

### ISSUE THREAD

**Issue by pulsar256** [mastodon/mastodon#27030]
### Steps to reproduce the problem

1. Pull new images
2. Run pre-deployment migration: `docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate`
3. Restart all services `docker-compose up -d --force-recreate`
4. Run post-deployment migration: `docker-compose run --rm web bundle exec rails db:migrate`

```
docker-compose run --rm web bundle exec rails db:migrate
WARNING: Some networks were defined but are not used by any service: external_network
Creating mastodon_web_run ... done
I, [2023-09-21T18:29:57.847943 #7]  INFO -- : Migrating to DropFollowRecommendations (20230818142253)
== 20230818142253 DropFollowRecommendations: migrating ========================
[strong_migrations] DANGER: No lock timeout set
-- drop_view(:follow_recommendations, {:materialized=>true})
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::InternalError: ERROR:  cache lookup failed for relation 18586
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:47:in `block in execute'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract_adapter.rb:752:in `block in log'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/abstract_adapter.rb:743:in `log'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql/database_statements.rb:46:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/scenic-1.7.0/lib/scenic/adapters/postgres.rb:228:in `execute'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/scenic-1.7.0/lib/scenic/adapters/postgres.rb:183:in `drop_materialized_view'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/scenic-1.7.0/lib/scenic/statements.rb:65:in `drop_view'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:965:in `block in method_missing'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:935:in `block in say_with_time'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:935:in `say_with_time'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/migration.rb:954:in `method_missing'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/strong_migrations-0.8.0/lib/strong_migrations/migration.rb:16:in `block in method_missing'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/strong_migrations-0.8.0/lib/strong_migrations/checker.rb:322:in `perform'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/strong_migrations-0.8.0/lib/strong_migrations/migration.rb:15:in `method_missing'
/opt/mastodon/db/post_migrate/20230818142253_drop_follow_recommendations.rb:5:in `up'
(...)
```

### Expected behaviour

Migration does not fail with an exception

### Actual behaviour

Migration fails with an exception

### Mastodon version

v4.2.0

**Comment by pulsar256** [comment]
solved by dropping the corresponding row in the `pg_depend` table.

```sql
delete from pg_depend where objid  = 18586;
```
