### ISSUE TITLE
Latest docker build errors

### ISSUE THREAD

**Issue by ssimpson89** [mastodon/mastodon#27065]
### Steps to reproduce the problem

Updated to the latest docker build and it looks like the web page now errors with "We're sorry, but something went wrong on our end." Here is the error in the log

```
mastodon-web-1        | I, [2023-09-22T14:46:01.921331 #19]  INFO -- : [feebb376-ce8d-4a8a-af78-8daddd409c23] method=GET path=/ format=html controller=HomeController action=index status=500 allocations=7224 duration=35.51 view=0.00 db=24.44
mastodon-web-1        | F, [2023-09-22T14:46:01.922828 #19] FATAL -- : [feebb376-ce8d-4a8a-af78-8daddd409c23]   
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] ActionView::Template::Error (undefined method `[]' for nil:NilClass):
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]      7: 
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]      8:   %meta{ name: 'applicationServerKey', content: Rails.configuration.x.vapid_public_key }
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]      9: 
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]     10:   = render_initial_state
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]     11:   = javascript_pack_tag 'application', crossorigin: 'anonymous'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]     12: 
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]     13: .notranslate.app-holder#mastodon{ data: { props: Oj.dump(default_props) } }
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23]   
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/models/concerns/has_user_settings.rb:15:in `prefers_noindex?'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/models/account.rb:139:in `user_prefers_noindex?'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/serializers/rest/account_serializer.rb:146:in `noindex'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/helpers/application_helper.rb:210:in `render_initial_state'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/views/shared/_web_app.html.haml:10
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/views/shared/_web_app.html.haml:1
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/views/home/index.html.haml:7
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] app/controllers/concerns/localized.rb:11:in `set_locale'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] lib/mastodon/rack_middleware.rb:9:in `call'
mastodon-web-1        | [feebb376-ce8d-4a8a-af78-8daddd409c23] lib/public_file_server_middleware.rb:18:in `call'

```

### Expected behaviour

Should show the timeline

### Actual behaviour

Shows an error

### Mastodon instance

private instance

### Mastodon version

ghcr.io/mastodon/mastodon:latest

### Browser name and version

Chrome 117.0.5938.88

### Operating system

Manjaro

**Comment by wolfmic** [comment]
Hello @ssimpson89 I updated the same way, and I saw you closed this issue. May I ask how did you solve it? I encountered the same problem by doing the same steps.
