### ISSUE TITLE
 Failed to start mastodon-web after upgrading to 4.2.0

### ISSUE THREAD

**Issue by cklokmose** [mastodon/mastodon#27074]
### Steps to reproduce the problem

1. Upgrade from 4.1.9 to 4.2.0 following the instructions
2. Start mastodon-web

### Expected behaviour

mastodon-web should start

### Actual behaviour

mastodon-web failed to start

### Detailed description

```
Sep 22 22:56:05 - bundle[2655766]: [2655766] ! Unable to load application: NameError: uninitialized constant Makara
Sep 22 22:56:05 - bundle[2655766]: bundler: failed to load command: puma (/home/mastodon/live/vendor/bundle/ruby/3.2.0/bin/puma)
Sep 22 22:56:05 - bundle[2655766]: /home/mastodon/live/config/initializers/makara.rb:1:in `<main>': uninitialized constant Makara (NameError)
Sep 22 22:56:05 - bundle[2655766]: Makara::Cookie::DEFAULT_OPTIONS[:same_site] = :lax
Sep 22 22:56:05 - bundle[2655766]:               ^^^^^^^^^^^^^^^^^
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `load'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `block in load_config_initializer'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/notifications.rb:208:in `instrument'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:666:in `load_config_initializer'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `block in <class:Engine>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `tsort_each_child'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `call'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `call'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/config/environment.rb:7:in `<top (required)>'
Sep 22 22:56:05 - bundle[2655766]:         from <internal:/home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Sep 22 22:56:05 - bundle[2655766]:         from <internal:/home/mastodon/.rbenv/versions/3.2.2/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
Sep 22 22:56:05 - bundle[2655766]:         from config.ru:5:in `block in <main>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `eval'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:116:in `new_from_string'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:105:in `load_file'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rack-2.2.8/lib/rack/builder.rb:66:in `parse_file'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/configuration.rb:366:in `load_rackup'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/configuration.rb:288:in `app'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/runner.rb:158:in `load_and_bind'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/cluster.rb:359:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/launcher.rb:194:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/lib/puma/cli.rb:75:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/puma-6.3.1/bin/puma:10:in `<top (required)>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/bin/puma:25:in `load'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/bin/puma:25:in `<top (required)>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `load'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:23:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:492:in `exec'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
Sep 22 22:56:05 - bundle[2655766]:         from /home/mastodon/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'
Sep 22 22:56:05 - systemd[1]: mastodon-web.service: Main process exited, code=exited, status=1/FAILURE
Sep 22 22:56:05 - systemd[1]: mastodon-web.service: Failed with result 'exit-code'.
```

### Mastodon instance

social.multiverset.net

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v3.2.2
- Node.js version: v16.18.0

**Comment by cklokmose** [comment]
I realize that this error already happens when I run the database migration:  ` SKIP_POST_DEPLOYMENT_MIGRATIONS=true RAILS_ENV=production bundle exec rails db:migrate`

This results in the error:
```
rails aborted!
NameError: uninitialized constant Makara
/home/mastodon/live/config/initializers/makara.rb:1:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `load'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:667:in `block in load_config_initializer'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/notifications.rb:208:in `instrument'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:666:in `load_config_initializer'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/engine.rb:619:in `block in <class:Engine>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `instance_exec'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:32:in `run'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:61:in `block in run_initializers'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:50:in `tsort_each_child'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/initializable.rb:60:in `run_initializers'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:372:in `initialize!'
/home/mastodon/live/config/environment.rb:7:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.6.11/lib/zeitwerk/kernel.rb:38:in `require'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:348:in `require_environment!'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/application.rb:506:in `block in run_tasks_blocks'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/command.rb:51:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/railties-7.0.8/lib/rails/commands.rb:18:in `<main>'
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
Tasks: TOP => db:migrate => db:load_config => environment
(See full trace by running task with --trace)
```

**Comment by cklokmose** [comment]
It seemed that my `live` folder was in a broken state.
I fixed the issue by:
 - `git stash`
 - `git checkout main`
 - `git pull`
 - ` git checkout v4.2.0`
 - Follow the upgrade instructions again.

**Comment by jkjoy** [comment]
same error
