### ISSUE TITLE
Compiling assets with Node 20 can fail sometimes

### ISSUE THREAD

**Issue by gunchleoc** [mastodon/mastodon#27114]
### Steps to reproduce the problem

On some (not all) installations, when running `RAILS_ENV=production bundle exec rails assets:precompile`, there will be the following error:

```
Compilation failed:
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/mastodon/live/node_modules/webpack/lib/util/createHash.js:135:53)
    at ConcatenatedModule._createIdentifier (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:563:16)
    at new ConcatenatedModule (/home/mastodon/live/node_modules/webpack/lib/optimize/ConcatenatedModule.js:445:27)
    at /home/mastodon/live/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:250:26
    at SyncBailHook.eval [as call] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:16)
    at SyncBailHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1351:37
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1342:27)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:675:18
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1261:4
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook (/home/mastodon/live/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (/home/mastodon/live/node_modules/webpack/lib/Compilation.js:1253:28)
    at /home/mastodon/live/node_modules/webpack/lib/Compiler.js:672:17
    at eval (eval at create (/home/mastodon/live/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1185:12
    at /home/mastodon/live/node_modules/webpack/lib/Compilation.js:1097:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

This can be fixed by running:

`RAILS_ENV=production bundle exec rails assets:precompile NODE_OPTIONS=--openssl-legacy-provider`

I know of at least 3 admins who have had this problem.

I propose editing the release notes to add this information as a first step and then changing the encryption algorithm in the future.

### Expected behaviour

Assets will compile

### Actual behaviour

Assets won't compile

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v20.7.0

Running on Debian 11

**Comment by ClearlyClaire** [comment]
Is this actually happening with v4.2.0, or with earlier versions? This shouldn't occur with v4.2.0

**Comment by renchap** [comment]
This is not expected, and we included a code change that removes the need for changing `NODE_OPTIONS`.

Can you check that you correctly have `const CompressionPlugin = require('@renchap/compression-webpack-plugin');` in `config/webpack/production.js`?

Also, did you run `yarn install`?

**Comment by gunchleoc** [comment]
I did run bundle install && yarn install as far as I remember, and it was definitely on 4.2.0. The error didn't reoccur for me though, so I'd have to set up a brand new server to see if I can reproduce this. I'll post into the chat to see if we can get more info fro the other admins.

**Comment by vmstan** [comment]
@gunchleoc can you verify this issue can be closed?

**Comment by gunchleoc** [comment]
I haven't heard back from anybody else and I haven't had time to try to reproduce.

I'd be fine with closing this - we can always open a new one if this should happen again.
