### ISSUE TITLE
500 Error when upload a GIF

### ISSUE THREAD

**Issue by nyansen** [mastodon/mastodon#27126]
### Steps to reproduce the problem

1. Upload a GIF

### Expected behaviour

See a GIF 

### Actual behaviour

Get a 500 error

### Detailed description

When I upload a GIF I get a 500er error without any Information at the Frontend

### Mastodon instance

elbmatsch.de

### Mastodon version

v4.2.0

### Browser name and version

Chrome

### Operating system

osx 14

### Technical details

journalctl -u mastodon-web:
```
INFO -- : method=POST path=/api/v2/media format=html controller=Api::V2::MediaController action=create status=500 allocations=4162 duration=120.28 view=0.00 db=1.05
FATAL -- :
 FloatDomainError (Infinity): 

 lib/paperclip/transcoder.rb:46:in 'floor'
 lib/paperclip/transcoder.rb:46:in 'make'
 lib/paperclip/gif_transcoder.rb:109:in 'make'
 lib/paperclip/attachment_extensions.rb:21:in 'block in post_process_style'
 lib/paperclip/attachment_extensions.rb:20:in 'each'
 lib/paperclip/attachment_extensions.rb:20:in 'inject'
 lib/paperclip/attachment_extensions.rb:20:in 'post_process_style'
 app/controllers/api/v2/media_controller.rb:5:in 'create'
 app/controllers/concerns/localized.rb:11:in 'set_locale'
 lib/mastodon/rack_middleware.rb:9:in 'call'
```

All versions are the required according to the changelog

**Comment by nyansen** [comment]
> Thanks for your report! This sounds like `ffprobe` is reporting the file to have a 0 seconds duration. Would it be possible to share the GIF file for investigation? (I believe I have a fix, but I am curious to see a file that causes this issue)

I have add a gif but all gifs are not working. and we try a lot of gifs.
![test](https://github.com/mastodon/mastodon/assets/156637/09d6e3d0-d7b6-4897-acf2-4d3145e9ac60)

**Comment by nyansen** [comment]
> Thanks! Can you run `ffprobe -i file.gif -print_format json -show_format -show_streams -show_error -loglevel fatal` directly on your server?

[result.txt](https://github.com/mastodon/mastodon/files/12715460/result.txt)

**Comment by ClearlyClaire** [comment]
Thanks! It indeed does not report a duration… not sure why. This appears to depend on the `ffprobe` version.

**Comment by nyansen** [comment]
> Thanks! It indeed does not report a duration… not sure why. This appears to depend on the `ffprobe` version.

Maybe my version of ffmpeg is too old but before the 4.2.0 update everything worked fine. Had also installed the betas and RC1 before and it worked fine.

**Comment by ClearlyClaire** [comment]
Yeah, taking the duration of the media for input is new.

**Comment by nyansen** [comment]
> Yeah, taking the duration of the media for input is new.

If you need it I can install the fix at my system and test it live.

**Comment by ClearlyClaire** [comment]
> > Yeah, taking the duration of the media for input is new.
> 
> If you need it I can install the fix at my system and test it live.

I'm confident this fixes the issue, but you're welcome to test it anyway!

**Comment by nyansen** [comment]
> > > Yeah, taking the duration of the media for input is new.
> > 
> > 
> > If you need it I can install the fix at my system and test it live.
> 
> I'm confident this fixes the issue, but you're welcome to test it anyway!

Fix is working :)

**Comment by claus** [comment]
I had the same issue and the patch fixed it.

If it helps, my `ffprobe` version is 3.4.11, which seems old.

```
root@mastodon-com-br:~# ffprobe -v
ffprobe version 3.4.11-0ubuntu0.1 Copyright (c) 2007-2022 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
```
