### ISSUE TITLE
tootctl search deploy throws exception

### ISSUE THREAD

**Issue by jgillich** [mastodon/mastodon#27241]
### Steps to reproduce the problem

1. Run `tootctl search deploy` - probably using an incorrect Elasticsearch config?

### Expected behaviour

It should deploy search indexes or return an error

### Actual behaviour

It throws an unrelated exception

### Detailed description

```
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/ruby-progressbar-1.13.0/lib/ruby-progressbar/progress.rb:66:in `total=': You can't set the item's total value to less than the current progress. (ProgressBar::InvalidProgressError)
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/ruby-progressbar-1.13.0/lib/ruby-progressbar/base.rb:228:in `block in update_progress'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/ruby-progressbar-1.13.0/lib/ruby-progressbar/output.rb:46:in `with_refresh'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/ruby-progressbar-1.13.0/lib/ruby-progressbar/base.rb:227:in `update_progress'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/ruby-progressbar-1.13.0/lib/ruby-progressbar/base.rb:150:in `total='
        from /opt/mastodon/lib/mastodon/cli/search.rb:58:in `deploy'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from /opt/mastodon/bin/tootctl:9:in `block in <main>'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from /opt/mastodon/bin/tootctl:8:in `<main>'
```

### Mastodon version

4.2.0 (official container image)

**Comment by jgillich** [comment]
Duplicate of #18625
