### ISSUE TITLE
Not possible to send direct messages 

### ISSUE THREAD

**Issue by olemara** [mastodon/mastodon#27243]
### Steps to reproduce the problem

1. Installed Mastodon from
2. Create users
3. Try sending direct message to another user
4. Check to see if the message appears under "direct messages", check whether the user that should have received the message gets notified.

### Expected behaviour

Messages en up as direct messages and user is notified

### Actual behaviour

Nothing happens.

### Detailed description

I have tried this both using the UI, and the API:

Sending the following request to another instance that was installed long ago (same version) works as expected:

https://{{mastodon_url}}/api/v1/statuses

{
"spoiler_text":"postman spoiler_text",
"status":"postman status @abc_3_serpentine",
"visibility":"direct"
}

But not to the instance I just installed.

The logs show me that a request is being made, and answered with 200 OK. No error messages are to be found. Also checking the actual request being sent from the front-end is answered with 200 OK.

Please advice if more information is needed, and some guide to debug this properly.

### Mastodon version

v4.0.11

### Technical details

I have tried this both using the UI, and the API:

Sending the following request to another instance that was installed long ago (same version) works as expected:

https://{{mastodon_url}}/api/v1/statuses

{
"spoiler_text":"postman spoiler_text",
"status":"postman status @abc_3_serpentine",
"visibility":"direct"
}

But not to the instance I just installed.

The logs show me that a request is being made, and answered with 200 OK. No error messages are to be found. Also checking the actual request being sent from the front-end is answered with 200 OK.

Please advice if more information is needed, and some guide to debug this properly.

**Comment by olemara** [comment]
Same thing happening with v4.0.7, v4.0.11, and v4.0.1.

Clearing all client side data when testing of course.

**Comment by ClearlyClaire** [comment]
I am not sure I fully understand the situation. Does the issue occur when the sender and recipient are on the same server? Is the DM listed in the sender's interface?

In your example, you are sending the exact same request to two different servers, without changing the mentioned user's handle. Are you actually mentioning a user that exists, or did you forget the `@server` part? (e.g. `@abc_3_serpentine@example.com`)

**Comment by olemara** [comment]
Sorry, I'll try to be more specific. The two examples are just one by the way.

Locally on my development machine I have installed v4.0.0, which works as expected, both via API and UI. I have set this up to use the hostname localtest.me, and I just use the @username to direct messages to that user. 

I have also installed that version to other servers with fully qualified domain names, and things have been working.

It seems something broke a couple of weeks ago. I can no longer send direct messages to user via UI or API. This made me also try v4.0.7, v4.0.11, and v4.1.0. So after sending a direct message it is only listed as regular toot(?). The receiving user is not notified of the message, and the message does not appear in the DM inbox. Here is how it looks:

file:///somulatorDocs/mastodon-bug.png

**Comment by olemara** [comment]
![mastodon-bug](https://github.com/mastodon/mastodon/assets/3372111/82e3e56d-8337-47aa-805d-c50fe2550d07)

**Comment by olemara** [comment]
I also try with @username@server, but the error still prevails.

**Comment by olemara** [comment]
I can add that I have tried installing on a fresh machine as well, and on multiple browsers to make sure nothing is cached.

**Comment by ClearlyClaire** [comment]
> ![mastodon-bug](https://user-images.githubusercontent.com/3372111/271951557-82e3e56d-8337-47aa-805d-c50fe2550d07.png)

That screenshot appears to be showing properly-working DMs. Are `admin` and `abc_1_posting` on the same server? If so, is `admin` actually an admin? What about `abc_1_bustling`? If the screenshot is supposed to show that something is not working, I suppose the post does not appear in “Notifications” or “Direct messages” even if you refresh?

Is `admin` perhaps “limited” server-side?

On the server with a strange behavior, is `mastodon-sidekiq` running? Is there anything in its logs?

**Comment by olemara** [comment]
![mast-1](https://github.com/mastodon/mastodon/assets/3372111/750ba4d2-59e9-488f-990b-7748277d5b5e)

**Comment by olemara** [comment]
![mast-2](https://github.com/mastodon/mastodon/assets/3372111/98263a3c-c1ed-4e8f-9f20-efc771e94ad0)

**Comment by olemara** [comment]
Yes, they are on the same server. admin is an admin user yes. I have also tried between "regular" users, and from admin to abc_1_bustling.

How can admin or other users be "limited"?

Sidekiq container is running.

I cannot find anything in the logs of interest except that posting to the "statuses" gives me 200 OK.

I do get alot of "X-Accel-Mapping header missing" in the logs, but that is not related I think (serving of static files).

**Comment by olemara** [comment]
Can I somehow turn on more logging? I have only found the output from "docker logs" command.

**Comment by olemara** [comment]
2023-10-02T11:22:49.704Z pid=7 tid=2nzr class=TriggerWebhookWorker jid=03c8439f50edc48b3f042850 INFO: start
2023-10-02T11:22:49.752Z pid=7 tid=2nzr class=TriggerWebhookWorker jid=03c8439f50edc48b3f042850 elapsed=0.048 INFO: fail
2023-10-02T11:22:49.752Z pid=7 tid=2nzr WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":["account.approved","Account",111164132015613633],"class":"TriggerWebhookWorker","jid":"03c8439f50edc48b3f042850","created_at":1696230042.0824564,"enqueued_at":1696245769.7025704,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230042.4459107,"retry_count":9,"retried_at":1696239182.6452758}}
2023-10-02T11:22:49.752Z pid=7 tid=2nzr WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:22:49.752Z pid=7 tid=2nzr WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:15:in `prefers_noindex?'
/opt/mastodon/app/models/account.rb:139:in `user_prefers_noindex?'
/opt/mastodon/app/serializers/rest/account_serializer.rb:146:in `noindex'
2023-10-02T11:23:12.989Z pid=7 tid=2o0v class=LocalNotificationWorker jid=fadbce600250d115383c3ae3 INFO: start
2023-10-02T11:23:13.030Z pid=7 tid=2o0v class=LocalNotificationWorker jid=fadbce600250d115383c3ae3 elapsed=0.04 INFO: fail
2023-10-02T11:23:13.030Z pid=7 tid=2o0v WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111164107377203638,1,"Follow","follow"],"class":"LocalNotificationWorker","jid":"fadbce600250d115383c3ae3","created_at":1696230050.1788175,"enqueued_at":1696245792.9878793,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230050.2837956,"retry_count":9,"retried_at":1696239182.6547418}}
2023-10-02T11:23:13.030Z pid=7 tid=2o0v WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:23:13.030Z pid=7 tid=2o0v WARN: /opt/mastodon/app/services/notify_service.rb:47:in `optional_non_follower?'
/opt/mastodon/app/services/notify_service.rb:120:in `blocked?'
/opt/mastodon/app/services/notify_service.rb:19:in `call'
2023-10-02T11:23:22.192Z pid=7 tid=2jkv INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:23:22.193Z pid=7 tid=2jl7 INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:23:22.195Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:23:22.206Z pid=7 tid=2nuj class=Scheduler::SuspendedUserCleanupScheduler jid=6f97d789ed44b94b15b18567 INFO: start
2023-10-02T11:23:22.209Z pid=7 tid=2mrb class=Scheduler::IndexingScheduler jid=063c68c3cbcb7502b027c12e INFO: start
2023-10-02T11:23:22.212Z pid=7 tid=2nr7 class=Scheduler::AccountsStatusesCleanupScheduler jid=a6398e9a92047fa774f6cf07 INFO: start
2023-10-02T11:23:22.224Z pid=7 tid=2mrb class=Scheduler::IndexingScheduler jid=063c68c3cbcb7502b027c12e elapsed=0.015 INFO: done
2023-10-02T11:23:22.229Z pid=7 tid=2nuj class=Scheduler::SuspendedUserCleanupScheduler jid=6f97d789ed44b94b15b18567 elapsed=0.023 INFO: done
2023-10-02T11:23:22.244Z pid=7 tid=2nr7 class=Scheduler::AccountsStatusesCleanupScheduler jid=a6398e9a92047fa774f6cf07 elapsed=0.032 INFO: done
2023-10-02T11:23:35.578Z pid=7 tid=2nxj class=TriggerWebhookWorker jid=d7f2333ef7aad8d54b2c686e INFO: start
2023-10-02T11:23:35.613Z pid=7 tid=2nxj class=TriggerWebhookWorker jid=d7f2333ef7aad8d54b2c686e elapsed=0.035 INFO: fail
2023-10-02T11:23:35.613Z pid=7 tid=2nxj WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":["account.created","Account",111164132015613633],"class":"TriggerWebhookWorker","jid":"d7f2333ef7aad8d54b2c686e","created_at":1696230042.0525916,"enqueued_at":1696245815.576454,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230042.21361,"retry_count":9,"retried_at":1696239217.2200124}}
2023-10-02T11:23:35.613Z pid=7 tid=2nxj WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:23:35.613Z pid=7 tid=2nxj WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:15:in `prefers_noindex?'
/opt/mastodon/app/models/account.rb:139:in `user_prefers_noindex?'
/opt/mastodon/app/serializers/rest/account_serializer.rb:146:in `noindex'
2023-10-02T11:23:45.716Z pid=7 tid=2nr7 class=LocalNotificationWorker jid=d5e1b8932b6a850740c6d412 INFO: start
2023-10-02T11:23:45.748Z pid=7 tid=2nr7 class=LocalNotificationWorker jid=d5e1b8932b6a850740c6d412 elapsed=0.032 INFO: fail
2023-10-02T11:23:45.748Z pid=7 tid=2nr7 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111164107377203638,111164132015613633,"Account","admin.sign_up"],"class":"LocalNotificationWorker","jid":"d5e1b8932b6a850740c6d412","created_at":1696230042.438557,"enqueued_at":1696245825.714782,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230042.4800127,"retry_count":9,"retried_at":1696239176.0695987}}
2023-10-02T11:23:45.748Z pid=7 tid=2nr7 WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:23:45.748Z pid=7 tid=2nr7 WARN: /opt/mastodon/app/services/notify_service.rb:47:in `optional_non_follower?'
/opt/mastodon/app/services/notify_service.rb:120:in `blocked?'
/opt/mastodon/app/services/notify_service.rb:19:in `call'
2023-10-02T11:24:22.309Z pid=7 tid=2jkv INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:24:22.312Z pid=7 tid=2jl7 INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:24:22.312Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:24:22.320Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=f966153ec079b9ada9234180 INFO: start
2023-10-02T11:24:22.324Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=9101d612234d206f1b14fda4 INFO: start
2023-10-02T11:24:22.327Z pid=7 tid=2o33 class=Scheduler::IndexingScheduler jid=2b0397b51502058ab09b808d INFO: start
2023-10-02T11:24:22.336Z pid=7 tid=2o33 class=Scheduler::IndexingScheduler jid=2b0397b51502058ab09b808d elapsed=0.008 INFO: done
2023-10-02T11:24:22.343Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=9101d612234d206f1b14fda4 elapsed=0.02 INFO: done
2023-10-02T11:24:22.355Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=f966153ec079b9ada9234180 elapsed=0.034 INFO: done
2023-10-02T11:24:24.130Z pid=7 tid=2o33 class=DistributionWorker jid=c371065f3eeccb9f0a046808 INFO: start
2023-10-02T11:24:24.176Z pid=7 tid=2o33 class=DistributionWorker jid=c371065f3eeccb9f0a046808 elapsed=0.046 INFO: fail
2023-10-02T11:24:24.177Z pid=7 tid=2o33 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111164139632248028],"class":"DistributionWorker","jid":"c371065f3eeccb9f0a046808","created_at":1696230158.1713312,"enqueued_at":1696245864.129295,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230158.2971094,"retry_count":9,"retried_at":1696239232.3775904}}
2023-10-02T11:24:24.177Z pid=7 tid=2o33 WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:24:24.177Z pid=7 tid=2o33 WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:127:in `shows_application?'
/opt/mastodon/app/models/account.rb:139:in `user_shows_application?'
/opt/mastodon/app/serializers/rest/status_serializer.rb:50:in `show_application?'
2023-10-02T11:24:48.759Z pid=7 tid=2jkv INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuses_scheduler)
2023-10-02T11:24:48.759Z pid=7 tid=2jl7 INFO: queueing Scheduler::Trends::RefreshScheduler (trends_refresh_scheduler)
2023-10-02T11:24:48.764Z pid=7 tid=2o47 class=Scheduler::Trends::RefreshScheduler jid=e72bd785473a07d619c01ade INFO: start
2023-10-02T11:24:48.773Z pid=7 tid=2o4j class=Scheduler::ScheduledStatusesScheduler jid=b79fe3349cc52a7680bad3be INFO: start
2023-10-02T11:24:48.805Z pid=7 tid=2o47 class=Scheduler::Trends::RefreshScheduler jid=e72bd785473a07d619c01ade elapsed=0.041 INFO: done
2023-10-02T11:24:48.808Z pid=7 tid=2o4j class=Scheduler::ScheduledStatusesScheduler jid=b79fe3349cc52a7680bad3be elapsed=0.035 INFO: done
2023-10-02T11:24:48.925Z pid=7 tid=2ijf uniquejobs=reaper INFO: Nothing to delete; exiting.
2023-10-02T11:24:48.926Z pid=7 tid=2ijf uniquejobs=reaper INFO: Nothing to delete; exiting.
2023-10-02T11:24:50.561Z pid=7 tid=2jlz INFO: queueing Scheduler::SoftwareUpdateCheckScheduler (software_update_check_scheduler)
2023-10-02T11:24:50.569Z pid=7 tid=2o47 class=Scheduler::SoftwareUpdateCheckScheduler jid=65c49bc6404bd8bdd96bd25c INFO: start
2023-10-02T11:24:50.578Z pid=7 tid=2o47 class=Scheduler::SoftwareUpdateCheckScheduler jid=65c49bc6404bd8bdd96bd25c INFO: Adding dead Scheduler::SoftwareUpdateCheckScheduler job 65c49bc6404bd8bdd96bd25c
2023-10-02T11:24:50.580Z pid=7 tid=2o47 class=Scheduler::SoftwareUpdateCheckScheduler jid=65c49bc6404bd8bdd96bd25c INFO: delete_by_digest(uniquejobs:587492945364d44effd7969941ad0c75) completed in 1ms
2023-10-02T11:24:50.582Z pid=7 tid=2o47 class=Scheduler::SoftwareUpdateCheckScheduler jid=65c49bc6404bd8bdd96bd25c elapsed=0.013 INFO: fail
2023-10-02T11:24:50.582Z pid=7 tid=2o47 WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"scheduler","lock":"until_executed","lock_ttl":3600,"class":"Scheduler::SoftwareUpdateCheckScheduler","args":[],"jid":"65c49bc6404bd8bdd96bd25c","created_at":1696245890.5619514,"lock_timeout":0,"lock_prefix":"uniquejobs","lock_args":[],"lock_digest":"uniquejobs:587492945364d44effd7969941ad0c75","enqueued_at":1696245890.5672157}}
2023-10-02T11:24:50.582Z pid=7 tid=2o47 WARN: ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "software_updates" does not exist
LINE 1: SELECT "software_updates".* FROM "software_updates" ORDER BY...
                                         ^

2023-10-02T11:24:50.582Z pid=7 tid=2o47 WARN: /opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `prepare'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:837:in `block in prepare_statement'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/activesupport-7.0.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
2023-10-02T11:25:22.422Z pid=7 tid=2jkv INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:25:22.423Z pid=7 tid=2jl7 INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:25:22.423Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:25:22.434Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=e7193a0d639c2dae334de9d6 INFO: start
2023-10-02T11:25:22.442Z pid=7 tid=2mrb class=Scheduler::IndexingScheduler jid=89d8b091026a2b1f62dcf840 INFO: start
2023-10-02T11:25:22.435Z pid=7 tid=2o6r class=Scheduler::SuspendedUserCleanupScheduler jid=69f638a96af3c2d3d5bda0e6 INFO: start
2023-10-02T11:25:22.453Z pid=7 tid=2mrb class=Scheduler::IndexingScheduler jid=89d8b091026a2b1f62dcf840 elapsed=0.011 INFO: done
2023-10-02T11:25:22.458Z pid=7 tid=2o6r class=Scheduler::SuspendedUserCleanupScheduler jid=69f638a96af3c2d3d5bda0e6 elapsed=0.024 INFO: done
2023-10-02T11:25:22.471Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=e7193a0d639c2dae334de9d6 elapsed=0.037 INFO: done
2023-10-02T11:25:33.605Z pid=7 tid=2o6r class=LocalNotificationWorker jid=ed73fca98e9ca530da73b09c INFO: start
2023-10-02T11:25:33.636Z pid=7 tid=2o6r class=LocalNotificationWorker jid=ed73fca98e9ca530da73b09c elapsed=0.031 INFO: fail
2023-10-02T11:25:33.636Z pid=7 tid=2o6r WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111164107377203638,2,"Follow","follow"],"class":"LocalNotificationWorker","jid":"ed73fca98e9ca530da73b09c","created_at":1696230050.187023,"enqueued_at":1696245933.6035917,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230050.281629,"retry_count":9,"retried_at":1696239266.9759672}}
2023-10-02T11:25:33.636Z pid=7 tid=2o6r WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:25:33.636Z pid=7 tid=2o6r WARN: /opt/mastodon/app/services/notify_service.rb:47:in `optional_non_follower?'
/opt/mastodon/app/services/notify_service.rb:120:in `blocked?'
/opt/mastodon/app/services/notify_service.rb:19:in `call'
2023-10-02T11:26:22.540Z pid=7 tid=2jl7 INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:26:22.541Z pid=7 tid=2jkv INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:26:22.543Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:26:22.554Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=d7c12cbf0f681fa97f99a019 INFO: start
2023-10-02T11:26:22.555Z pid=7 tid=2o7v class=Scheduler::IndexingScheduler jid=2a8e848a721d143299a7549e INFO: start
2023-10-02T11:26:22.556Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=2cd653dd78931b770a66c061 INFO: start
2023-10-02T11:26:22.576Z pid=7 tid=2o7v class=Scheduler::IndexingScheduler jid=2a8e848a721d143299a7549e elapsed=0.02 INFO: done
2023-10-02T11:26:22.581Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=d7c12cbf0f681fa97f99a019 elapsed=0.027 INFO: done
2023-10-02T11:26:22.594Z pid=7 tid=2nuj class=Scheduler::AccountsStatusesCleanupScheduler jid=2cd653dd78931b770a66c061 elapsed=0.038 INFO: done
2023-10-02T11:27:22.657Z pid=7 tid=2jl7 INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:27:22.656Z pid=7 tid=2jlz INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:27:22.662Z pid=7 tid=2jkv INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:27:22.673Z pid=7 tid=2o7v class=Scheduler::SuspendedUserCleanupScheduler jid=ea8be98e55e8a34b7ebef23d INFO: start
2023-10-02T11:27:22.677Z pid=7 tid=2nuj class=Scheduler::IndexingScheduler jid=c90fcf193b7c10210660c10e INFO: start
2023-10-02T11:27:22.678Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=d341dc18ad96e45f6faded10 INFO: start
2023-10-02T11:27:22.693Z pid=7 tid=2nuj class=Scheduler::IndexingScheduler jid=c90fcf193b7c10210660c10e elapsed=0.016 INFO: done
2023-10-02T11:27:22.700Z pid=7 tid=2o7v class=Scheduler::SuspendedUserCleanupScheduler jid=ea8be98e55e8a34b7ebef23d elapsed=0.027 INFO: done
2023-10-02T11:27:22.713Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=d341dc18ad96e45f6faded10 elapsed=0.035 INFO: done
2023-10-02T11:28:22.771Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:28:22.772Z pid=7 tid=2jkv INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:28:22.773Z pid=7 tid=2jl7 INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:28:22.784Z pid=7 tid=2o7v class=Scheduler::IndexingScheduler jid=31001688d906f2964060163b INFO: start
2023-10-02T11:28:22.792Z pid=7 tid=2nuj class=Scheduler::SuspendedUserCleanupScheduler jid=bee869f0b62fbe5a4bbef415 INFO: start
2023-10-02T11:28:22.794Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=0a9ec6d63e4ca571be966030 INFO: start
2023-10-02T11:28:22.798Z pid=7 tid=2o7v class=Scheduler::IndexingScheduler jid=31001688d906f2964060163b elapsed=0.014 INFO: done
2023-10-02T11:28:22.818Z pid=7 tid=2nuj class=Scheduler::SuspendedUserCleanupScheduler jid=bee869f0b62fbe5a4bbef415 elapsed=0.026 INFO: done
2023-10-02T11:28:22.824Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=0a9ec6d63e4ca571be966030 elapsed=0.03 INFO: done
2023-10-02T11:29:22.888Z pid=7 tid=2jlz INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:29:22.888Z pid=7 tid=2jkv INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:29:22.891Z pid=7 tid=2jl7 INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:29:22.901Z pid=7 tid=2o8n class=Scheduler::IndexingScheduler jid=4d9968dd15a397c6680960b4 INFO: start
2023-10-02T11:29:22.902Z pid=7 tid=2o7v class=Scheduler::AccountsStatusesCleanupScheduler jid=d99952f25119d3c5f58eac56 INFO: start
2023-10-02T11:29:22.913Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=961cf4fc3e0d05d2339bf1c8 INFO: start
2023-10-02T11:29:22.916Z pid=7 tid=2o8n class=Scheduler::IndexingScheduler jid=4d9968dd15a397c6680960b4 elapsed=0.015 INFO: done
2023-10-02T11:29:22.931Z pid=7 tid=2mrb class=Scheduler::SuspendedUserCleanupScheduler jid=961cf4fc3e0d05d2339bf1c8 elapsed=0.019 INFO: done
2023-10-02T11:29:22.946Z pid=7 tid=2o7v class=Scheduler::AccountsStatusesCleanupScheduler jid=d99952f25119d3c5f58eac56 elapsed=0.044 INFO: done
2023-10-02T11:29:48.734Z pid=7 tid=2jkv INFO: queueing Scheduler::ScheduledStatusesScheduler (scheduled_statuses_scheduler)
2023-10-02T11:29:48.735Z pid=7 tid=2jlz INFO: queueing Scheduler::Trends::RefreshScheduler (trends_refresh_scheduler)
2023-10-02T11:29:48.739Z pid=7 tid=2mrb class=Scheduler::Trends::RefreshScheduler jid=6eac9fd18e55de477020d7f4 INFO: start
2023-10-02T11:29:48.754Z pid=7 tid=2o8n class=Scheduler::ScheduledStatusesScheduler jid=67bff0a6cb075624d4f68039 INFO: start
2023-10-02T11:29:48.781Z pid=7 tid=2mrb class=Scheduler::Trends::RefreshScheduler jid=6eac9fd18e55de477020d7f4 elapsed=0.041 INFO: done
2023-10-02T11:29:48.785Z pid=7 tid=2o8n class=Scheduler::ScheduledStatusesScheduler jid=67bff0a6cb075624d4f68039 elapsed=0.031 INFO: done
2023-10-02T11:30:23.002Z pid=7 tid=2jl7 INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)
2023-10-02T11:30:23.002Z pid=7 tid=2jkv INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)
2023-10-02T11:30:23.003Z pid=7 tid=2jlz INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)
2023-10-02T11:30:23.016Z pid=7 tid=2o8n class=Scheduler::IndexingScheduler jid=c7bb95c605e5ff7b85235526 INFO: start
2023-10-02T11:30:23.018Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=0a09161193af111be24675b8 INFO: start
2023-10-02T11:30:23.020Z pid=7 tid=2o7v class=Scheduler::SuspendedUserCleanupScheduler jid=f20742eafab6c72e5a7e7169 INFO: start
2023-10-02T11:30:23.032Z pid=7 tid=2o8n class=Scheduler::IndexingScheduler jid=c7bb95c605e5ff7b85235526 elapsed=0.016 INFO: done
2023-10-02T11:30:23.043Z pid=7 tid=2o7v class=Scheduler::SuspendedUserCleanupScheduler jid=f20742eafab6c72e5a7e7169 elapsed=0.023 INFO: done
2023-10-02T11:30:23.051Z pid=7 tid=2mrb class=Scheduler::AccountsStatusesCleanupScheduler jid=0a09161193af111be24675b8 elapsed=0.033 INFO: done
2023-10-02T11:30:31.982Z pid=7 tid=2o4j class=DistributionWorker jid=081415f91a79efd474cfe5b1 INFO: start
2023-10-02T11:30:32.035Z pid=7 tid=2o4j class=DistributionWorker jid=081415f91a79efd474cfe5b1 elapsed=0.052 INFO: fail
2023-10-02T11:30:32.035Z pid=7 tid=2o4j WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[111164154982728378],"class":"DistributionWorker","jid":"081415f91a79efd474cfe5b1","created_at":1696230392.3975906,"enqueued_at":1696246231.9820514,"error_message":"undefined method `[]' for nil:NilClass","error_class":"NoMethodError","failed_at":1696230392.4712636,"retry_count":9,"retried_at":1696239573.8266609}}
2023-10-02T11:30:32.035Z pid=7 tid=2o4j WARN: NoMethodError: undefined method `[]' for nil:NilClass
2023-10-02T11:30:32.036Z pid=7 tid=2o4j WARN: /opt/mastodon/app/models/concerns/has_user_settings.rb:127:in `shows_application?'
/opt/mastodon/app/models/account.rb:139:in `user_shows_application?'
/opt/mastodon/app/serializers/rest/status_serializer.rb:50:in `show_application?'

**Comment by olemara** [comment]
One error in the postgres container:

ERROR:  relation "software_updates" does not exist at character 34
STATEMENT:  SELECT "software_updates".* FROM "software_updates" ORDER BY "software_updates"."id" ASC LIMIT $1

**Comment by ClearlyClaire** [comment]
Your issue seems to be that you are running 4.2.0 code on a pre-4.2.0 database. Since you're saying you're running v4.0.11, please double-check that *all* containers are running that version.

**Comment by olemara** [comment]
Seems like everything works as expected now.

Thanks for the quick and responsive help, really appreciate it!
