### ISSUE TITLE
Wayback archival broken

### ISSUE THREAD

**Issue by Ry3yr** [mastodon/mastodon#27405]
### Steps to reproduce the problem

1. Try backing up any mastodon post url with waybackmachines "savex feature

### Expected behaviour

Proper archival that renders as thge original post did

### Actual behaviour

Empty page with no entry

### Detailed description

Attempoting to save a mastodon post since mastodons 4.2.0 upodate results in an empty result archival.
Archive.ph still manages to backup fine.

The wayback archive was also informed:
https://pb.todon.de/@alcea/111153855622668345

All mastodon instances running 4.2.x+ are affected

### Mastodon instance

pb.todon.de

### Mastodon version

v4.2

### Browser name and version

Firefox 105.0.3

### Operating system

Android 13

**Comment by Ry3yr** [comment]
Example of bad snapshot:

![Screenshot_20231014-163304_Opera](https://github.com/mastodon/mastodon/assets/17431197/55ce2c5e-85b0-4b01-87ad-d109d1a62f61)

**Comment by ShadowJonathan** [comment]
After doing `git bisect` between tags `v4.1.9` (good) and `v4.2.0` (bad), it found the commit responsible for this;

https://github.com/mastodon/mastodon/commit/8d6aea33260dedeacb3d22ac1a6d2f9cc3856a5e

**Comment by Ry3yr** [comment]
Nice ! :)

I hope this can be resolved, it has been quite some time after all.

**Comment by 0xErnie** [comment]
I just stubled over this bug and found #27196 which has less information, but was created first.
One of them should be closed as a duplicate of the other.

**Comment by ShadowJonathan** [comment]
For anyone who wishes to work on this, https://webrecorder.net/ appears to have the exact same bug as the internet archive, in not properly replaying mastodon, with the exact same behaviour.

Webrecorder is open source, and can be traced to figure out where this is going wrong.

**Comment by Ry3yr** [comment]
Shame Gargron seems disinterested ...

Archive.ph is fine.
If we had a contact...

**Comment by liberaldev** [comment]
The primary reason for this is that the Wayback Machine is not properly archiving pages that are rendered client-side.

To solve this problem on our end, we need to ensure that our frontend renders server-side.

**Comment by Ry3yr** [comment]
Then why did it work in the old version ?
Something changed towards version 4.2.0 and it did not keep archive.ph from still saving properly.

Waybackarchive saves js and dependencies properly afaik.
I don't see why it should fail here

**Comment by ShadowJonathan** [comment]
WBA saves javascript properly, but possibly does a bit of post-processing to make them work properly within an archival context.

The commit above, https://github.com/mastodon/mastodon/commit/8d6aea33260dedeacb3d22ac1a6d2f9cc3856a5e, is the first bad commit. *All* that this commit did, was update to react 18. The commit right before that *will* work on the internet archive.

The problem is **not** that mastodon does client-side rendering, the problem is that **client-side rendering breaks with react 18, in an archival context**. Client-side rendering works perfectly fine otherwise.

**Comment by liberaldev** [comment]
> WBA saves javascript properly, but possibly does a bit of post-processing to make them work properly within an archival context.
> 
> The commit above, [8d6aea3](https://github.com/mastodon/mastodon/commit/8d6aea33260dedeacb3d22ac1a6d2f9cc3856a5e), is the first bad commit. _All_ that this commit did, was update to react 18. The commit right before that _will_ work on the internet archive.
> 
> The problem is **not** that mastodon does client-side rendering, the problem is that **client-side rendering breaks with react 18, in an archival context**. Client-side rendering works perfectly fine otherwise.

Sometimes the Wayback Machine does a good job of saving sites that do client-side rendering, but sometimes it doesn't. Here's an example.

https://web.archive.org/web/20240804091154/https://misskey.io/notes/9p6sdhbhuf4500sz (This site is powered by Vue.js.)
https://web.archive.org/web/20240804092238/https://meta.discourse.org/t/setup-discourseconnect-official-single-sign-on-for-discourse-sso/13045 (In the case of this link, the Wayback Machine was only saving the server-side rendered part and not the client-side rendered part. Compare this to the original page (https://meta.discourse.org/t/setup-discourseconnect-official-single-sign-on-for-discourse-sso/13045). As far as I know, discourse doesn't use React.)
https://web.archive.org/web/20240803173105/https://www.reddit.com/r/react/comments/1d6kntr/are_npm_i_react_and_npm_createreactapp_the_same/?rdt=47546

Archiving sites like Wayback Machine use bots to archive sites. The problem is that bots don't natively read client-side rendered pages well.

Wayback Machine can archive client-side rendered pages, but it's not perfect, so the problem lies primarily with Wayback Machine. What we can do before the Wayback Machine solves this problem is to introduce SSR.

**Comment by ShadowJonathan** [comment]
Please do not pollute this issue with unrelated and vague assertions on how the internet archive works.

We know what commit broke it, https://github.com/mastodon/mastodon/commit/8d6aea33260dedeacb3d22ac1a6d2f9cc3856a5e, and we have some methods of fixing it.

This is not helpful.

SSR had already been done in Mastodon, and the devs are unlikely to change it back. React worked fine before, but it doesn't now.

Going forward, the best solution would be to fix the bug in react (in its interaction with internet archival), so that this issue can be fixed for *any* react-18-using website.

**Comment by Ry3yr** [comment]
Both the retakes from today
https://web.archive.org/web/20250129104627/https://pb.todon.de/@alcea/111233466321909950 https://web.archive.org/save/https://pb.todon.de/@alcea/111153855622668345

Aswell as the wayback archives old one from the op post render fine now...

Did the waybackarchive refine their rendering to fix this issue on their side ?
(Must be, as the old 2023 has not gained infos over the course of over a year obvpiously, right ?)

Any info ?

**Comment by grahamperrin** [comment]
From <https://mastodon.bsd.cafe/@grahamperrin/115351453279704101> (2025-10-10): 

> - <https://web.archive.org/web/20251010183709/https://mastodon.bsd.cafe/@grahamperrin/115340325050785172> is empty.

**Comment by ShadowJonathan** [comment]
mastodon.bsd.cafe is running v4.4.7

**Comment by lindawagner** [comment]
mastodon.archive.org is running v4.2.17 and the following successsfully replays: https://web.archive.org/web/20250913002458/https://mastodon.archive.org/@brewsterkahle/

I have several non-mastodon.archive.org examples that don't successfully replay, but this calls into question "All mastodon instances running 4.2.x+ are affected"

**Comment by ShadowJonathan** [comment]
Unsure if the internet archive fixed something where it works with newer versions than v4.2

Does it work with a post on 4.4 / 4.5? If not, then I could do another git-bisect, and see where it ends up.

**Comment by grahamperrin** [comment]
Maybe off-topic, for <https://mastodon.bsd.cafe/@stefano/115503281047094432> (announcing the BSD Cafe Mastodon instances upgraded to v.4.5.0): 

A) an attempt at <https://web.archive.org/save> seemed to fail as pictured below,

<img width="851" height="551" alt="Image" src="https://github.com/user-attachments/assets/56b8e5ee-fc3c-4af4-bd90-d7fc0d681e9b" />

- the attempt had requested a screenshot
- I accepted the invitation to send an error report

B) an attempt with version 3.2 of the Wayback Machine also _apparently_ failed, 

> Error
> 
> https://mastodon.bsd.cafe/@stefano/115503281047094432
> 
> An Error Occurred. Please Try Again.
> 
> Save Page Now browser crashed on https://mastodon.bsd.cafe/@stefano/115503281047094432.

----

I reloaded the page then retried the extension, I was notified that capture had been taken a few minutes earlier. Found: 

<https://web.archive.org/web/20251108123248/https://mastodon.bsd.cafe/@stefano/115503281047094432>

> Due to a bug in our code or a browser compatibility issue, this page could not be displayed correctly.
> 
> Try refreshing the page. If that does not help, you may still be able to use Mastodon through a different browser or native app.
> 
> Mastodon v4.5.0 · Report issue · Copy stacktrace to clipboard

<details>
<summary>The stacktrace</summary>

```
TypeError: can't access property "location", ue(...) is undefined


Gt@https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22428
Te@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313
ju@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455
ma@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713
ca@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112396
mf@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112324
gl@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176
ao@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522
oa@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470
qe@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1605
st@https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1980
@https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26365
T@https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26126
P@https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26186



Gt (https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22428)
Te (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313)
ju (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455)
ma (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713)
ca (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112396)
mf (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112324)
gl (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176)
ao (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522)
oa (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470)
qe (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1605)
st (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1980)
https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26365
T (https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26126)
P (https://web.archive.org/web/20251108123248jm_/https://mastodon.bsd.cafe/packs/assets/polyfills-DouhSJ4p.js:1:26186)
```

</details>

**Comment by grahamperrin** [comment]
With a subsequent view of <https://web.archive.org/web/20251108123248/https://mastodon.bsd.cafe/@stefano/115503281047094432> in qutebrowser, the stacktrace is different: 

```
TypeError: Cannot read properties of undefined (reading 'location')


TypeError: Cannot read properties of undefined (reading 'location')
    at Gt (https://web.archive.org/web/20251108123251jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22433)
    at Te (https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313)
    at ju (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455)
    at ma (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713)
    at ca (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112394)
    at mf (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112322)
    at gl (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176)
    at ao (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522)
    at oa (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470)
    at qe (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1604)


ve (https://web.archive.org/web/20251108123251jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22433)
t (https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112394)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112322)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522)
Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470)
unstable_now (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1604)
```

**Comment by liberaldev** [comment]
> With a subsequent view of https://web.archive.org/web/20251108123248/https://mastodon.bsd.cafe/@stefano/115503281047094432 in qutebrowser, the stacktrace is different:
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'location')
> 
> 
> TypeError: Cannot read properties of undefined (reading 'location')
>     at Gt (https://web.archive.org/web/20251108123251jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22433)
>     at Te (https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313)
>     at ju (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455)
>     at ma (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713)
>     at ca (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112394)
>     at mf (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112322)
>     at gl (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176)
>     at ao (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522)
>     at oa (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470)
>     at qe (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1604)
> 
> 
> ve (https://web.archive.org/web/20251108123251jm_/https://mastodon.bsd.cafe/packs/short_number-CtfW0nug.js:1:22433)
> t (https://web.archive.org/web/20251108123253jm_/https://mastodon.bsd.cafe/packs/scroll_context-CFwUZHAE.js:14:10313)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:61455)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:116713)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112394)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112322)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:112176)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:108522)
> Ff (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:33:107470)
> unstable_now (https://web.archive.org/web/20251108123250jm_/https://mastodon.bsd.cafe/packs/client-DZIGVCsa.js:25:1604)
> ```

Given that the Wayback Machine is a long-standing service, it seems to misread websites that use modern JavaScript and client-side rendering.

**Comment by grahamperrin** [comment]
For my most recent attempt: 

- the traditional capture is bugged at https://web.archive.org/web/20260319065927/https://mastodon.bsd.cafe/@grahamperrin/116127306722990113
- the coincidental **screenshot is OK** at https://web.archive.org/web/20260319065948/http://web.archive.org/screenshot/https://mastodon.bsd.cafe/@grahamperrin/116127306722990113
