### ISSUE TITLE
LinkCrawlWorker NoMethodError undefined method 'to_sym'

### ISSUE THREAD

**Issue by vmstan** [mastodon/mastodon#27401]
### Steps to reproduce the problem

Starting about one week ago, noticed these types of errors appearing in Sidekiq dead queue.

```
NoMethodError: undefined method `to_sym' for [{"@type"=>"Language", "name"=>"Dutch"}]:Array
NoMethodError: undefined method `to_sym' for {"@type"=>"Language", "name"=>"Indonesian", "alternateName"=>"id"}:Hash
NoMethodError: undefined method `to_sym' for {"@type"=>"Language", "name"=>"Russian", "alternateName"=>"ru"}:Hash
```

![image](https://github.com/mastodon/mastodon/assets/3002053/fb435620-d815-45ea-a2cd-e989a9a9af0b)

![CleanShot 2023-10-13 at 11 48 45@2x](https://github.com/mastodon/mastodon/assets/3002053/3ab07212-cab8-403a-a33b-c0acb29d3c97)

### Expected behaviour

No errors

### Actual behaviour

These errors

### Mastodon instance

vmst.io

### Mastodon version

main

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.2.2 +YJIT)
- Node.js version: (from `node --version`, eg. v20)

**Comment by vmstan** [comment]
```
2023-10-13T17:03:51.913945255Z stdout F /opt/mastodon/app/lib/link_details_extractor.rb:201:in `language'
2023-10-13T17:03:51.913939195Z stdout F /opt/mastodon/app/helpers/languages_helper.rb:275:in `valid_locale_or_nil'
2023-10-13T17:03:51.913925726Z stdout F 2023-10-13T17:03:51.913Z pid=6 tid=3spca WARN: /opt/mastodon/app/helpers/languages_helper.rb:294:in `valid_locale?'
2023-10-13T17:03:51.913861126Z stdout F 2023-10-13T17:03:51.913Z pid=6 tid=3spca WARN: NoMethodError: undefined method `to_sym' for {"@type"=>"Language", "name"=>"Russian", "alternateName"=>"ru"}:Hash
2023-10-13T17:03:51.913165094Z stdout F 2023-10-13T17:03:51.912Z pid=6 tid=3spca WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"pull","class":"LinkCrawlWorker","args":[111228775663160661],"jid":"221921c619acc84970e6f092","created_at":1697216473.6776083,"enqueued_at":1697216527.578844}}
2023-10-13T17:03:51.898356342Z stdout F 2023-10-13T17:03:51.898Z pid=6 tid=3spca class=LinkCrawlWorker jid=221921c619acc84970e6f092 elapsed=4.528 INFO: fail
```

**Comment by ClearlyClaire** [comment]
This is caused by Mastodon not handling https://schema.org/Language values for the `inLanguage` attribute of JSON-LD documents in `app/lib/link_details_extractor.rb`

**Comment by jfrede** [comment]
Same problem @ https://radiosocial.de/
