### ISSUE TITLE
docker compose deploies Mastodon,web and sidekiq all the time restarting

### ISSUE THREAD

**Issue by jkjoy** [mastodon/mastodon#27594]
### Steps to reproduce the problem

1.docker
2.
3.
...

### Expected behaviour

docker compose deploies Mastodon

### Actual behaviour

docker compose deploies Mastodon,web and sidekiq all the time restarting

### Mastodon instance

so.so4.us

### Mastodon version

v4.2.1

### Browser name and version

GoogleChrome

### Operating system

Ubuntu22.0.4

### Technical details

```
/opt/mastodon/vendor/bundle/ruby/3.2.0/bin/sidekiq:25:in `load'
/opt/mastodon/vendor/bundle/ruby/3.2.0/bin/sidekiq:25:in `<top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `load'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli/exec.rb:23:in `run'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:492:in `exec'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:34:in `dispatch'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/cli.rb:28:in `start'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/exe/bundle:45:in `block in <top (required)>'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/opt/mastodon/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/exe/bundle:33:in `<top (required)>'
/opt/ruby/bin/bundle:25:in `load'
/opt/ruby/bin/bundle:25:in `<main>'
```

**Comment by vmstan** [comment]
Is this a new installation?

**Comment by jkjoy** [comment]
> Is this a new installation?

yes
