### ISSUE TITLE
Opening the profile link from the opened-post view doesn't

### ISSUE THREAD

**Issue by nabijaczleweli** [mastodon/mastodon#27614]
### Steps to reproduce the problem

1. open a post
2. click the profile imagus or nick or ID

### Expected behaviour

the bottom-left-corner link preview thing says it points to the profile, so "profile opens"

### Actual behaviour

nothing

### Mastodon instance

101010.pl

### Mastodon version

v4.3.0-alpha.0

### Browser name and version

firefox deved 87.0b9

### Operating system

windows 10

### Technical details

regression against 4.2

clicking on profiles on other posts in the view (thread or timeline) works

**Comment by vmstan** [comment]
I'm not able to reproduce this on my 4.3.0 instance, at least not in Safari or Firefox, but I do see the behavior directly on 101010.pl so is it possible you have modifications that would be impacting it?

**Comment by nabijaczleweli** [comment]
Ugh. Naturally, the source is a fork of a fork and maintained by merge commit with upstream instead of rebase, so it's annoying to find out what's actually changed.

The source is https://github.com/101010pl/Mastodon; the HEAD is at 83b382cc0b6c726cf204959d5927509bd7ee3883, corresponding to https://github.com/101010pl/Mastodon/pull/157 (note the commit message being "Update") which matches upstream mastodon 9a3d047f3e604e581e18346424569e28fc9c5b96.

This brings the diffstat to 
```
$ git diff 9a3d047f3e604e581e18346424569e28fc9c5b96 --stat
 .github/ISSUE_TEMPLATE/1.web_bug_report.yml                          |  76 -----------------------
 .github/ISSUE_TEMPLATE/2.server_bug_report.yml                       |  65 -------------------
 .github/ISSUE_TEMPLATE/3.feature_request.yml                         |  22 -------
 .github/ISSUE_TEMPLATE/config.yml                                    |   5 --
 .github/renovate.json5                                               | 123 ------------------------------------
 .github/stale.yml                                                    |  10 ---
 .github/stylelint-matcher.json                                       |  21 -------
 .github/workflows/build-container-image.yml                          |  99 -----------------------------
 .github/workflows/build-nightly.yml                                  |  43 -------------
 .github/workflows/build-push-pr.yml                                  |  41 ------------
 .github/workflows/build-releases.yml                                 |  29 ---------
 .github/workflows/bundler-audit.yml                                  |  34 ----------
 .github/workflows/check-i18n.yml                                     |  48 --------------
 .github/workflows/codeql.yml                                         |  62 ------------------
 .github/workflows/crowdin-download.yml                               |  71 ---------------------
 .github/workflows/crowdin-upload.yml                                 |  35 -----------
 .github/workflows/haml-lint-problem-matcher.json                     |  17 -----
 .github/workflows/lint-css.yml                                       |  46 --------------
 .github/workflows/lint-haml.yml                                      |  39 ------------
 .github/workflows/lint-js.yml                                        |  49 ---------------
 .github/workflows/lint-json.yml                                      |  38 ------------
 .github/workflows/lint-md.yml                                        |  38 ------------
 .github/workflows/lint-ruby.yml                                      |  45 --------------
 .github/workflows/lint-yml.yml                                       |  40 ------------
 .github/workflows/rebase-needed.yml                                  |  27 --------
 .github/workflows/test-image-build.yml                               |  21 -------
 .github/workflows/test-js.yml                                        |  42 -------------
 .github/workflows/test-migrations-one-step.yml                       | 103 ------------------------------
 .github/workflows/test-migrations-two-step.yml                       | 111 ---------------------------------
 .github/workflows/test-ruby.yml                                      | 324 -----------------------------------------------------------------------------------------------
 Gemfile                                                              |   1 +
 Gemfile.lock                                                         |   1 +
 app/javascript/mastodon/features/compose/components/compose_form.jsx |   5 +-
 app/javascript/styles/application.scss                               |   3 +
 app/javascript/styles/custom.scss                                    |   4 ++
 app/javascript/styles/mastodon/components.scss                       |   1 +
 app/validators/status_length_validator.rb                            |   2 +-
 config/environments/production.rb                                    |   1 +
 config/initializers/content_security_policy.rb                       |   1 +
 lib/mastodon/version.rb                                              |   2 +-
 40 files changed, 17 insertions(+), 1728 deletions(-)
```
and the actual diff is:
```diff
diff --git a/Gemfile b/Gemfile
index c935b5410..518e421ad 100644
--- a/Gemfile
+++ b/Gemfile
@@ -64,6 +64,7 @@ gem 'nokogiri', '~> 1.15'
 gem 'nsa', github: 'jhawthorn/nsa', ref: 'e020fcc3a54d993ab45b7194d89ab720296c111b'
 gem 'oj', '~> 3.14'
 gem 'ox', '~> 2.14'
+gem 'parallel', '~> 1.22'
 gem 'parslet'
 gem 'posix-spawn'
 gem 'public_suffix', '~> 5.0'
diff --git a/Gemfile.lock b/Gemfile.lock
index 33e355a06..5e2a6c8ba 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -894,6 +894,7 @@ DEPENDENCIES
   omniauth-saml (~> 2.0)
   omniauth_openid_connect (~> 0.6.1)
   ox (~> 2.14)
+  parallel (~> 1.22)
   parslet
   pg (~> 1.5)
   pghero
diff --git a/app/javascript/mastodon/features/compose/components/compose_form.jsx b/app/javascript/mastodon/features/compose/components/compose_form.jsx
index 60fb6b7e1..50ad77cd9 100644
--- a/app/javascript/mastodon/features/compose/components/compose_form.jsx
+++ b/app/javascript/mastodon/features/compose/components/compose_form.jsx
@@ -98,9 +98,10 @@ class ComposeForm extends ImmutablePureComponent {
     const fulltext = this.getFulltextForCharacterCounting();
     const isOnlyWhitespace = fulltext.length !== 0 && fulltext.trim().length === 0;
 
-    return !(isSubmitting || isUploading || isChangingUpload || length(fulltext) > 500 || (isOnlyWhitespace && !anyMedia));
+    return !(isSubmitting || isUploading || isChangingUpload || length(fulltext) > 2048 || (isOnlyWhitespace && !anyMedia));
   };
 
+
   handleSubmit = (e) => {
     if (this.props.text !== this.autosuggestTextarea.textarea.value) {
       // Something changed the text inside the textarea (e.g. browser extensions like Grammarly)
@@ -295,7 +296,7 @@ class ComposeForm extends ImmutablePureComponent {
             </div>
 
             <div className='character-counter__wrapper'>
-              <CharacterCounter max={500} text={this.getFulltextForCharacterCounting()} />
+              <CharacterCounter max={2048} text={this.getFulltextForCharacterCounting()} />
             </div>
           </div>
         </div>
diff --git a/app/javascript/styles/application.scss b/app/javascript/styles/application.scss
index 0dd573da9..a598e8678 100644
--- a/app/javascript/styles/application.scss
+++ b/app/javascript/styles/application.scss
@@ -21,5 +21,8 @@
 @import 'mastodon/admin';
 @import 'mastodon/dashboard';
 @import 'mastodon/rtl';
+div.column {
+	          flex-grow: 1;
+}
 @import 'mastodon/accessibility';
 @import 'mastodon/rich_text';
diff --git a/app/javascript/styles/custom.scss b/app/javascript/styles/custom.scss
new file mode 100644
index 000000000..a5c012a58
--- /dev/null
+++ b/app/javascript/styles/custom.scss
@@ -0,0 +1,4 @@
+@import 'application';
+div.column {
+  flex-grow: 1;
+}
diff --git a/app/javascript/styles/mastodon/components.scss b/app/javascript/styles/mastodon/components.scss
index 417f262a2..988c87f01 100644
--- a/app/javascript/styles/mastodon/components.scss
+++ b/app/javascript/styles/mastodon/components.scss
@@ -1555,6 +1555,7 @@ body > [data-popper-placement] {
   display: flex;
   gap: 10px;
   align-items: center;
+  flex-wrap: wrap;
 }
 
 .account__avatar {
diff --git a/app/validators/status_length_validator.rb b/app/validators/status_length_validator.rb
index dc841ded3..f5e2e3f35 100644
--- a/app/validators/status_length_validator.rb
+++ b/app/validators/status_length_validator.rb
@@ -1,7 +1,7 @@
 # frozen_string_literal: true
 
 class StatusLengthValidator < ActiveModel::Validator
-  MAX_CHARS = 500
+  MAX_CHARS = 2048
   URL_PLACEHOLDER_CHARS = 23
   URL_PLACEHOLDER = 'x' * 23
 
diff --git a/config/environments/production.rb b/config/environments/production.rb
index 94e74699f..ad502417c 100644
--- a/config/environments/production.rb
+++ b/config/environments/production.rb
@@ -43,6 +43,7 @@ Rails.application.configure do
   # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
   config.force_ssl = true
   config.ssl_options = {
+    hsts: { preload: true },
     redirect: {
       exclude: ->request { request.path.start_with?('/health') || request.headers["Host"].end_with?('.onion') || request.headers["Host"].end_with?('.i2p') }
     }
diff --git a/config/initializers/content_security_policy.rb b/config/initializers/content_security_policy.rb
index e5e672f2c..9b043c7f1 100644
--- a/config/initializers/content_security_policy.rb
+++ b/config/initializers/content_security_policy.rb
@@ -17,6 +17,7 @@ end
 base_host = Rails.configuration.x.web_domain
 
 assets_host   = Rails.configuration.action_controller.asset_host
+assets_host ||= "www.comperialead.pl"
 assets_host ||= host_to_url(base_host)
 
 media_host   = host_to_url(ENV['S3_ALIAS_HOST'])
diff --git a/lib/mastodon/version.rb b/lib/mastodon/version.rb
index 587e89303..89ab54c36 100644
--- a/lib/mastodon/version.rb
+++ b/lib/mastodon/version.rb
@@ -44,7 +44,7 @@ module Mastodon
     end
 
     def repository
-      ENV.fetch('GITHUB_REPOSITORY', 'mastodon/mastodon')
+      ENV.fetch('GITHUB_REPOSITORY', '101010pl/Mastodon')
     end
 
     def source_base_url
```
which I don't see how it could be affecting anything (half of these are "different upstream", half of these are "2kB posts", half of these are style and deployment config).

Assuming of course the version that's live actually matches the repo, but seeing as the diff isn't anything revolutionary and the update process, it's a good assumption it's just this.

**Comment by vmstan** [comment]
I see www.comperialead.pl hard coded as an asset host, is it possible that you have outdated JS on that repo?

**Comment by nabijaczleweli** [comment]
that's an affiliate program vendor (the server announcement has affiliate links in it, supposedly), but nothing from there is loaded accd'g to my network tab anyway

I'm not discounting "outdated js" given
![](https://github.com/mastodon/mastodon/assets/6709544/27acd092-db8a-4380-a4a0-e144110fa1a2)
but the Date header on all the .js files appears to be 2023-10-03 around 2pm so if it *is* that, it's not glaring

The operator doesn't have publicly-findable github account so I'm tagging @101010pl, maybe someone reads the notifications there (unlikely)

**Comment by 101010pl** [comment]
Jup. I see problem and reproduce it.
In dev console is JS error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'push')
    at Dt.handleAccountClick (detailed_status.jsx:61:20)
    at Object.Le (react-dom.production.min.js:761:7)
    at ze (react-dom.production.min.js:779:6)
    at react-dom.production.min.js:782:6
    at Rr (react-dom.production.min.js:1938:3)
    at Dr (react-dom.production.min.js:1963:9)
    at react-dom.production.min.js:2249:5
    at uc (react-dom.production.min.js:5899:12)
    at Ie (react-dom.production.min.js:712:12)
    at $r (react-dom.production.min.js:2039:3)
Dt.handleAccountClick @ detailed_status.jsx:61
Le @ react-dom.production.min.js:761
ze @ react-dom.production.min.js:779
(anonymous) @ react-dom.production.min.js:782
Rr @ react-dom.production.min.js:1938
Dr @ react-dom.production.min.js:1963
(anonymous) @ react-dom.production.min.js:2249
uc @ react-dom.production.min.js:5899
Ie @ react-dom.production.min.js:712
$r @ react-dom.production.min.js:2039
Vt @ react-dom.production.min.js:1251
Wt @ react-dom.production.min.js:1233`

**Comment by 101010pl** [comment]
@nabijaczleweli please check now. We update site.

**Comment by nabijaczleweli** [comment]
wfm 👍
