### ISSUE TITLE
Regression in emoji picker: Selecting an emoji does not output the emoji to textarea

### ISSUE THREAD

**Issue by ronilaukkarinen** [mastodon/mastodon#27643]
### Steps to reproduce the problem

1. Pull latest main to 277e696
2. Rebuild and restart
3. See emoji not outputting to textarea after selecting an emoji
...

### Expected behaviour

Emoji code should appear to textarea

### Actual behaviour

Nothing happens

### Detailed description

I may have been too hasty since this was introduced [8 hours ago](https://github.com/mastodon/mastodon/commit/9c8891b39a2d04898880f4bd0754a52739ada30a#diff-b407b14e1a5570dfc879754f8669660ee64065027c51912f5061726fe1679b4f)... sorry for that, if it should be this way and is acknowledged. Maybe @ClearlyClaire has a clue?

### Mastodon instance

mementomori.social

### Mastodon version

v4.3.0-alpha.0-2023-10-31

### Browser name and version

Google Chrome 118.0.5993.70 (Official Build) (64-bit)

### Operating system

Pop!_OS 22.04 LTS

### Technical details

DevTools Console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'selectionStart')
    at compose_form.jsx:219:40
    at Object.onPickEmoji [as onPick] (emoji_picker_dropdown_container.js:80:7)
    at Object.onClick (emoji_picker_dropdown.jsx:236:16)
    at a.value (nimble-picker.js:315:18)
    at nimble-emoji.js:46:23
    at onClick (nimble-emoji.js:220:16)
    at Object.Ae (react-dom.production.min.js:54:317)
    at ze (react-dom.production.min.js:54:471)
    at react-dom.production.min.js:55:35
    at Rr (react-dom.production.min.js:105:68)
```

**Comment by ronilaukkarinen** [comment]
Reverting these two files `compose_form.jsx` and `autosuggest_textarea.jsx` fixes it for now.
