### ISSUE TITLE
After upgrade to 4.2.1 the service "mastodon-streaming" can no longer be started

### ISSUE THREAD

**Issue by m0urs** [mastodon/mastodon#27657]
### Steps to reproduce the problem

Start the service "mastodon-streaming" with the following command:

`systemctl mastodon-streaming`

### Expected behaviour

Service should start

### Actual behaviour

Service cannot be started because of a syntax error

### Detailed description

After upgrade to 4.2.1 (from 4.1.6) the service "mastodon-streaming" ca no longer be started. In SYSLOG the following error appears:

```
Nov  2 16:15:06 vs1 systemd[1]: Started mastodon-streaming.
Nov  2 16:15:06 vs1 node[45119]: /home/mastodon/live/node_modules/jsdom/lib/jsdom/living/nodes/HTMLInputElement-impl.js:583
Nov  2 16:15:06 vs1 node[45119]:       this[filesSymbol] ||= FileList.createImpl(this._globalObject);
Nov  2 16:15:06 vs1 node[45119]:                         ^^^
Nov  2 16:15:06 vs1 node[45119]: SyntaxError: Unexpected token '||='
Nov  2 16:15:06 vs1 node[45119]:     at wrapSafe (internal/modules/cjs/loader.js:1029:16)
Nov  2 16:15:06 vs1 node[45119]:     at Module._compile (internal/modules/cjs/loader.js:1078:27)
Nov  2 16:15:06 vs1 node[45119]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Nov  2 16:15:06 vs1 node[45119]:     at Module.load (internal/modules/cjs/loader.js:979:32)
Nov  2 16:15:06 vs1 node[45119]:     at Function.Module._load (internal/modules/cjs/loader.js:819:12)
Nov  2 16:15:06 vs1 node[45119]:     at Module.require (internal/modules/cjs/loader.js:1003:19)
Nov  2 16:15:06 vs1 node[45119]:     at require (internal/modules/cjs/helpers.js:107:18)
Nov  2 16:15:06 vs1 node[45119]:     at Object.<anonymous> (/home/mastodon/live/node_modules/jsdom/lib/jsdom/living/generated/HTMLInputElement.js:1875:14)
Nov  2 16:15:06 vs1 node[45119]:     at Module._compile (internal/modules/cjs/loader.js:1114:14)
Nov  2 16:15:06 vs1 node[45119]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
Nov  2 16:15:06 vs1 systemd[1]: mastodon-streaming.service: Main process exited, code=exited, status=1/FAILURE
```

### Mastodon instance

social.urspringer.de

### Mastodon version

v4.2.1

### Technical details

If this is happening on your own Mastodon server, please fill out those:

- Ruby version:  ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
- Node.js version: v20.9.0 (tried also: 16.16.0 and 21.1.0 with same result)

-

**Comment by m0urs** [comment]
Sorry, my fault. The new NODE version have been installed in "/usr/local/bin/node" and the streaming service has been called with "/usr/bin/node". This version was still the version 14.x. I deleted "/usr/bin/node" and made a symbolic link to "/usr/local/bin/node" with "ln -s /usr/local/bin/node /usr/bin/node" and now the service starts correctly.
