### ISSUE TITLE
Error 500 when trying to enable 2FA

### ISSUE THREAD

**Issue by KDederichs** [mastodon/mastodon#27921]
### Steps to reproduce the problem

Enable 2FA, type in the verification code

### Expected behaviour

No error

### Actual behaviour

Error 500

### Detailed description

Getting this while trying to enable 2FA, I recently moved the server to a different machine, maybe something is missing?

```
Nov 17 13:33:58 mastodon bundle[1082]: F, [2023-11-17T13:33:58.033531 #1082] FATAL -- : [972ba856-fc75-4a57-aa2c-916f661f69a6]
Nov 17 13:33:58 mastodon bundle[1082]: [972ba856-fc75-4a57-aa2c-916f661f69a6] OpenSSL::Cipher::CipherError ():
Nov 17 13:33:58 mastodon bundle[1082]: [972ba856-fc75-4a57-aa2c-916f661f69a6]
Nov 17 13:33:58 mastodon bundle[1082]: [972ba856-fc75-4a57-aa2c-916f661f69a6] app/controllers/settings/two_factor_authentication/confirmations_controller.rb:18:in `create'
Nov 17 13:33:58 mastodon bundle[1082]: [972ba856-fc75-4a57-aa2c-916f661f69a6] app/controllers/concerns/localized.rb:11:in `set_locale'
Nov 17 13:33:58 mastodon bundle[1082]: [972ba856-fc75-4a57-aa2c-916f661f69a6] lib/mastodon/rack_middleware.rb:9:in `call'
```

### Mastodon instance

It's my private instance :)

### Mastodon version

4.2.1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
- Node.js version: v18.17.1

**Comment by vmstan** [comment]
What the underlying OS and specifically OpenSSL version?

**Comment by KDederichs** [comment]
> What the underlying OS and specifically OpenSSL version?

Ubuntu 22.04.3 LTS and OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)

**Comment by ClearlyClaire** [comment]
Is `OTP_SECRET` set in your `.env.production`?

**Comment by KDederichs** [comment]
> Is `OTP_SECRET` set in your `.env.production`?

Yup, it's set, SECRET_KEY_BASE as well

**Comment by KDederichs** [comment]
Any news on this?

**Comment by KDederichs** [comment]
sure, here you go @ClearlyClaire:
```
Dec 01 12:13:37 mastodon bundle[388951]: I, [2023-12-01T12:13:37.055819 #388951]  INFO -- : [242bac08-bf76-4701-bcaa-e820aa5170d9] method=POST path=/settings/two_factor_authentication/confirmation format=html controller=Settings::TwoFactorAuthentication::ConfirmationsController action=create status=500 allocations=1978 duration=25.03 view=0.00 db=2.03
Dec 01 12:13:37 mastodon bundle[388951]: F, [2023-12-01T12:13:37.056342 #388951] FATAL -- : [242bac08-bf76-4701-bcaa-e820aa5170d9]
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] OpenSSL::Cipher::CipherError ():
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9]
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] encryptor (3.0.0) lib/encryptor.rb:98:in `final'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] encryptor (3.0.0) lib/encryptor.rb:98:in `crypt'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] encryptor (3.0.0) lib/encryptor.rb:49:in `decrypt'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] attr_encrypted (4.0.0) lib/attr_encrypted.rb:242:in `attr_encrypted_decrypt'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] attr_encrypted (4.0.0) lib/attr_encrypted.rb:331:in `attr_encrypted_decrypt'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] attr_encrypted (4.0.0) lib/attr_encrypted.rb:163:in `block (2 levels) in attr_encrypted'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] devise-two-factor (4.1.0) lib/devise_two_factor/models/two_factor_authenticatable.rb:51:in `otp'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] devise-two-factor (4.1.0) lib/devise_two_factor/models/two_factor_authenticatable.rb:41:in `validate_and_consume_otp!'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] app/controllers/settings/two_factor_authentication/confirmations_controller.rb:18:in `create'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/abstract_controller/base.rb:215:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/rendering.rb:165:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] i18n (1.14.1) lib/i18n.rb:322:in `with_locale'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] app/controllers/concerns/localized.rb:11:in `set_locale'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/callbacks.rb:138:in `run_callbacks'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/abstract_controller/callbacks.rb:233:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/rescue.rb:23:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `block in instrument'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/notifications.rb:206:in `instrument'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activerecord (7.0.8) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/abstract_controller/base.rb:151:in `process'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionview (7.0.8) lib/action_view/rendering.rb:39:in `process'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal.rb:188:in `dispatch'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_controller/metal.rb:251:in `dispatch'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:32:in `serve'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:50:in `block in serve'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:32:in `each'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/journey/router.rb:32:in `serve'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/routing/route_set.rb:852:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] omniauth (2.1.1) lib/omniauth/builder.rb:44:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack-attack (6.7.0) lib/rack/attack.rb:103:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] http_accept_language (2.1.1) lib/http_accept_language/middleware.rb:14:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] lib/mastodon/rack_middleware.rb:9:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack-attack (6.7.0) lib/rack/attack.rb:127:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] warden (1.2.9) lib/warden/manager.rb:34:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/tempfile_reaper.rb:15:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/etag.rb:27:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/conditional_get.rb:40:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/head.rb:12:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/session/abstract/id.rb:266:in `context'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/session/abstract/id.rb:260:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/cookies.rb:704:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/callbacks.rb:99:in `run_callbacks'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] chewy (7.3.4) lib/chewy/railtie.rb:21:in `block in call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] chewy (7.3.4) lib/chewy/strategy.rb:60:in `wrap'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] chewy (7.3.4) lib/chewy.rb:154:in `strategy'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] chewy (7.3.4) lib/chewy/railtie.rb:21:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] lograge (0.13.0) lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] railties (7.0.8) lib/rails/rack/logger.rb:25:in `block in call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `block in tagged'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/tagged_logging.rb:37:in `tagged'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/tagged_logging.rb:99:in `tagged'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] railties (7.0.8) lib/rails/rack/logger.rb:25:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/request_id.rb:26:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/method_override.rb:24:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/runtime.rb:22:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] activesupport (7.0.8) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/executor.rb:14:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack (2.2.8) lib/rack/sendfile.rb:110:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/ssl.rb:77:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] actionpack (7.0.8) lib/action_dispatch/middleware/host_authorization.rb:138:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] rack-cors (2.0.1) lib/rack/cors.rb:102:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] railties (7.0.8) lib/rails/engine.rb:530:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/configuration.rb:270:in `call'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/request.rb:100:in `block in handle_request'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/thread_pool.rb:344:in `with_force_shutdown'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/request.rb:99:in `handle_request'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/server.rb:443:in `process_client'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/server.rb:245:in `block in run'
Dec 01 12:13:37 mastodon bundle[388951]: [242bac08-bf76-4701-bcaa-e820aa5170d9] puma (6.3.1) lib/puma/thread_pool.rb:151:in `block in spawn_thread'
```

**Comment by ClearlyClaire** [comment]
How long are the values of `SECRET_KEY_BASE` and `OTP_SECRET`?

**Comment by KDederichs** [comment]
@ClearlyClaire 
I generated them with your secret generate command, which seems to spit out 128 character keys

**Comment by ClearlyClaire** [comment]
Good. I'm asking because I've seen a couple people accidentally truncate them while copying/editing their config file.

**Comment by KDederichs** [comment]
Gotcha, both of mine have the 128 though so no issues there

**Comment by KDederichs** [comment]
@ClearlyClaire any news yet?
Sorry for the periodic pings btw.

**Comment by darnfish** [comment]
Hi, have you checked that the `encrypted_otp_secret*` values in your `users` table are empty? I just cleared them and it fixed this error for me.

**Comment by KDederichs** [comment]
@darnfish That does indeed fix it, thanks.

**Comment by ClearlyClaire** [comment]
Hmmm have you perhaps changed your `.env.production` secrets while keeping the same database?

**Comment by KDederichs** [comment]
@ClearlyClaire Yeah, I did move servers and didn't think about copying the .env.production file.

If that can be detected it might be a good idea to reset those in cases like that.

**Comment by ClearlyClaire** [comment]
Interesting, that probably explains it. Clearing those values automatically is a no-go as that would be a security downgrade, but surfacing the issue to admins and providing guidance to admins would be helpful. We will have to think on how to do that.

**Comment by KDederichs** [comment]
Yeah that'd also work, since currently you don't really have a clue what's going on.
