### ISSUE TITLE
Unable to search for a user via user@host - webfinger seems broken

### ISSUE THREAD

**Issue by ElanHasson** [mastodon/mastodon#28012]
### Steps to reproduce the problem

1. Follow a user on my instance  locally or remote
2.
3.
...

### Expected behaviour

I should be able to locate the user

### Actual behaviour

I get a 500 error

### Detailed description

This is as of the nightly and v4.2.1

```
023-11-20T21:08:50.319420414Z [d62150dd0a2ef6e9757c8140f713b10b] NoMethodError (undefined method `casecmp' for nil:NilClass):
[d62150dd0a2ef6e9757c8140f713b10b]   
2023-11-20T21:08:50.319465476Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/resolve_account_service.rb:87:in `process_webfinger!'
[d62150dd0a2ef6e9757c8140f713b10b] app/services/resolve_account_service.rb:34:in `call'
2023-11-20T21:08:50.319507383Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/account_search_service.rb:172:in `exact_match'
2023-11-20T21:08:50.319528033Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/account_search_service.rb:163:in `search_service_results'
2023-11-20T21:08:50.319549412Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/account_search_service.rb:155:in `call'
2023-11-20T21:08:50.319570147Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/search_service.rb:31:in `perform_accounts_search!'
2023-11-20T21:08:50.319616214Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/search_service.rb:21:in `block in call'
2023-11-20T21:08:50.319637546Z [d62150dd0a2ef6e9757c8140f713b10b] app/services/search_service.rb:15:in `call'
[d62150dd0a2ef6e9757c8140f713b10b] app/controllers/api/v2/search_controller.rb:33:in `search_results'
2023-11-20T21:08:50.319678016Z [d62150dd0a2ef6e9757c8140f713b10b] app/controllers/api/v2/search_controller.rb:12:in `index'
2023-11-20T21:08:50.319698481Z [d62150dd0a2ef6e9757c8140f713b10b] app/controllers/concerns/localized.rb:11:in `set_locale'
2023-11-20T21:08:50.319718803Z [d62150dd0a2ef6e9757c8140f713b10b] lib/mastodon/rack_middleware.rb:9:in `call'
[d62150dd0a2ef6e9757c8140f713b10b] lib/public_file_server_middleware.rb:18:in `call'

```

### Mastodon instance

an internal test instance

### Mastodon version

nightly 2023-11-20, confirmed on v4.2.1

### Technical details

I use the containers.

**Comment by ThisIsMissEm** [comment]
What does the `/.well-known/webfinger?resource=acct:@user@foo.example` return?

**Comment by ElanHasson** [comment]
Turns out it was because of `LOCAL_DOMAIN` being unset. Webfinger returned `subject:user@` missing the domain.
