### ISSUE TITLE
502 Bad Gateway on nginx/1.18.0 (Ubuntu)

### ISSUE THREAD

**Issue by MarkMicallef** [mastodon/mastodon#28073]
### Steps to reproduce the problem

1. Create mastodon user and switch to it.
2. Clone repo.
3. Bundle and install.
4. RAILS_ENV=production bundle exec rake mastodon:setup. Successfully complete db install and site configuration.
5. Copy nginx config file from mastodor directory to websites-active and make necessary changes.
6. Get certbot certificates.
7. Start mastodon-* services.
8. Go to my Mastodon domain.
9. See 502 Bad Gateway error.
...

### Expected behaviour

Expected to see Mastodon landing page.

### Actual behaviour

Got 502 Bad Gateway error.

### Detailed description

Hello. I am setting up a private instance to use amongst a few fellow creatives. Everything seemed to work until I tried visiting the URL we set up for Mastodon. Basically everything went fine (or seemed to) with the installation. I configured the server, created the database, sent the test email, started the mastodon-* services. But when I try to connect via the browser I am getting the message "502 bad gateway".

As far as I can tell, I am doing everything pretty much the default way. I am using an account called mastodon and running postgresql at the backend which I let the setup create the database.

I've done some research and someone suggesting posting the result of journalctl -xe -u mastodon-* so I will repost it here. I hope this is useful:

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.355Z pid=71153 tid=1799 INFO: queueing Scheduler::IndexingScheduler (indexing_scheduler)

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.356Z pid=71153 tid=1781 INFO: queueing Scheduler::AccountsStatusesCleanupScheduler (accounts_statuses_cleanup_scheduler)

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.356Z pid=71153 tid=177p INFO: queueing Scheduler::SuspendedUserCleanupScheduler (suspended_user_cleanup_scheduler)

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.359Z pid=71153 tid=12vh class=Scheduler::IndexingScheduler jid=0203885ec8803689284ead74 INFO: start

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.366Z pid=71153 tid=12vh class=Scheduler::IndexingScheduler jid=0203885ec8803689284ead74 elapsed=0.007 INFO: done

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.364Z pid=71153 tid=12wh class=Scheduler::SuspendedUserCleanupScheduler jid=49628727a7164ad1b6b0603d INFO: start

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.361Z pid=71153 tid=12zx class=Scheduler::AccountsStatusesCleanupScheduler jid=dbe3bd832acbe5e4fe36cec2 INFO: start

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.373Z pid=71153 tid=12wh class=Scheduler::SuspendedUserCleanupScheduler jid=49628727a7164ad1b6b0603d INFO: Adding dead Scheduler::SuspendedUserCleanupScheduler job 49628727a7164ad1b6b0603d

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.374Z pid=71153 tid=12wh class=Scheduler::SuspendedUserCleanupScheduler jid=49628727a7164ad1b6b0603d INFO: delete_by_digest(uniquejobs:8fe5f80c85ceba42d90599495fb6405a) completed in 0ms

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.375Z pid=71153 tid=12wh class=Scheduler::SuspendedUserCleanupScheduler jid=49628727a7164ad1b6b0603d elapsed=0.012 INFO: fail

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.376Z pid=71153 tid=12wh WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"scheduler","lock":"until_executed","lock_ttl":86400,"class":"Scheduler::SuspendedUserCleanupScheduler","args":[],"jid":"49628727a7164ad1b6b0603d","created_at":1700651045.3617628,"lock_timeout":0,"lock_prefix":"uniquejobs","lock_args":[],"lock_digest":"uniquejobs:8fe5f80c85ceba42d90599495fb6405a","enqueued_at":1700651045.362964}}

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.376Z pid=71153 tid=12wh WARN: ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory

Nov 22 11:04:05 mark bundle[71153]: Is the server running locally and accepting connections on that socket?

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.376Z pid=71153 tid=12wh WARN: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'

Nov 22 11:04:05 mark bundle[71153]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'

Nov 22 11:04:05 mark bundle[71153]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.375Z pid=71153 tid=12zx class=Scheduler::AccountsStatusesCleanupScheduler jid=dbe3bd832acbe5e4fe36cec2 INFO: Adding dead Scheduler::AccountsStatusesCleanupScheduler job dbe3bd832acbe5e4fe36cec2

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.377Z pid=71153 tid=12zx class=Scheduler::AccountsStatusesCleanupScheduler jid=dbe3bd832acbe5e4fe36cec2 INFO: delete_by_digest(uniquejobs:02ace3fe540de140d5da7abcdd9dc40a) completed in 0ms

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.378Z pid=71153 tid=12zx class=Scheduler::AccountsStatusesCleanupScheduler jid=dbe3bd832acbe5e4fe36cec2 elapsed=0.017 INFO: fail

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.378Z pid=71153 tid=12zx WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"scheduler","lock":"until_executed","lock_ttl":86400,"class":"Scheduler::AccountsStatusesCleanupScheduler","args":[],"jid":"dbe3bd832acbe5e4fe36cec2","created_at":1700651045.3593261,"lock_timeout":0,"lock_prefix":"uniquejobs","lock_args":[],"lock_digest":"uniquejobs:02ace3fe540de140d5da7abcdd9dc40a","enqueued_at":1700651045.3602445}}

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.379Z pid=71153 tid=12zx WARN: ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory

Nov 22 11:04:05 mark bundle[71153]: Is the server running locally and accepting connections on that socket?

Nov 22 11:04:05 mark bundle[71153]: 2023-11-22T11:04:05.379Z pid=71153 tid=12zx WARN: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:87:in `rescue in new_client'

Nov 22 11:04:05 mark bundle[71153]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'

Nov 22 11:04:05 mark bundle[71153]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/activerecord-7.0.8/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'

Nov 22 11:04:07 mark bundle[71153]: 2023-11-22T11:04:07.741Z pid=71153 tid=1hh1 INFO: Shutting down

Nov 22 11:04:07 mark bundle[71153]: 2023-11-22T11:04:07.742Z pid=71153 tid=1hh1 INFO: Terminating quiet threads

Nov 22 11:04:07 mark bundle[71153]: 2023-11-22T11:04:07.765Z pid=71153 tid=13dt INFO: Scheduler exiting...

Nov 22 11:04:07 mark bundle[71153]: 2023-11-22T11:04:07.768Z pid=71153 tid=1hh1 uniquejobs=reaper INFO: Stopping Reaper

Nov 22 11:04:08 mark bundle[71153]: 2023-11-22T11:04:08.270Z pid=71153 tid=1hh1 INFO: Pausing to allow jobs to finish...

Nov 22 11:04:09 mark bundle[71153]: 2023-11-22T11:04:09.774Z pid=71153 tid=1hh1 INFO: Bye!

Nov 22 11:04:22 mark bundle[71156]: [71156] === puma shutdown: 2023-11-22 11:04:22 +0000 ===

Nov 22 11:04:22 mark bundle[71156]: [71156] - Goodbye!

Nov 22 11:04:22 mark bundle[71156]: [71156] - Gracefully shutting down workers...

-- Boot 52191477369542f99557050e6566b251 --

Nov 25 12:49:04 mark node[7565]: WARN Streaming API now listening on [127.0.0.1:4000](https://127.0.0.1:4000/)

### Mastodon instance

guild.combinehonnete.com

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Node.js version: v20.5.1
- Database: psql (16.1 (Ubuntu 16.1-1.pgdg22.04+1))
We are NOT using docker.
The server runs Ubuntu 22.04 x64, has 2048.00 MB, 2 vCPUs, and is not doing much else. I checked free and there is plenty of mem.

**Comment by vmstan** [comment]
```
WARN: ActiveRecord::ConnectionNotEstablished: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory
```

Would indicate issues connecting to Postgres.

**Comment by MarkMicallef** [comment]
Hi vmstan. Thanks for the response. I've been trying to debug this issue for a while. I logged into postgres using psql and the production database is there. It was created by the installation script. I can connect from the command line no trouble at all as the mastodon user using psql [name of my production db]. There are a bunch of tables in it (checked with \dt).

I also checked the .env.production file and it seems to have the correct settings:

DB_HOST=/var/run/postgresql

DB_PORT=5432

DB_NAME=[name of my production db]

DB_USER=mastodon

This is the first time I've used postgresql so my apologies if I've missed something obvious.

**Comment by vmstan** [comment]
I would switch the DB_HOST to localhost.

**Comment by MarkMicallef** [comment]
Switched it like this:

#DB_HOST=/var/run/postgresql
DB_HOST=localhost

Unfortunately makes no difference.

Does Mastoon have a log file where it would be logging its errors? Is there a way to directly test if it can connect to the DB like a test script? Sorry for all the questions but I've been trying to troubleshoot this for a while now and I appreciate the help. :-)

**Comment by MarkMicallef** [comment]
Hi Claire. Thanks so much for your response. I ran the script that you provided and it worked fine. I got a table with a bunch of "up" statuses for my database. Am I right in thinking that this means that mastodon can see the database?

Assuming it is, I think the issue is looking more and more like nginx not being able to talk to some essential mastodon service. What do you think?

**Comment by ClearlyClaire** [comment]
That sounds like it. You may want to double-check how these services are started. Are they started in the same host and with the same environment? Could they be running as a different user, or have environment variables overriding your config?
