### ISSUE TITLE
Docker Mastodon Web Server Image (ghcr.io/mastodon/mastodon:nightly) Requires Writable /opt/mastodon/tmp Directory

### ISSUE THREAD

**Issue by arazilsongweaver** [mastodon/mastodon#28134]
### Steps to reproduce the problem

1. Run Mastodon Nightly with Docker Compose via ```docker compose up -d --force-recreate```
2. Check start up status via ```docker compose logs mastodon-web```

### Expected behaviour

Mastodon web services should start without error.

### Actual behaviour

Server crashes with error: /usr/local/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir': Permission denied @ dir_s_mkdir - /opt/mastodon/tmp/pids (Errno::EACCES)

### Detailed description

This appears to be related to the following pull that made ```/opt/mastodon/``` into a read only directory:  #26850
Abridged Docker Compose Fragment:
```
  mastodon-web:
    image: ghcr.io/mastodon/mastodon:nightly
    container_name: mastodon-web
    restart: unless-stopped
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000"
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
# The following will fix the /opt/mastodon/tmp read only issue:
#    volumes:
#      - ./mastodon_tmp:/opt/mastodon/tmp
    env_file: mastodon-global.env
```
Docker Startup Log:
```
mastodon-web  | => Booting Puma
mastodon-web  | => Rails 7.1.2 application starting in production 
mastodon-web  | => Run `bin/rails server --help` for more startup options
mastodon-web  | Exiting
mastodon-web  | /usr/local/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir': Permission denied @ dir_s_mkdir - /opt/mastodon/tmp/pids (Errno::EACCES)
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:374:in `each'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:71:in `block in create_tmp_directories'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:70:in `each'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:70:in `create_tmp_directories'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:34:in `start'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
mastodon-web  |         from <internal:kernel>:90:in `tap'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
mastodon-web  |         from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
mastodon-web  |         from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
mastodon-web  |         from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
mastodon-web  |         from bin/rails:4:in `<main>'
```
I was able to work around this problem by bind mounting ```/opt/mastodon/tmp``` to a directory that is writable by  mastodon:mastodon (991:991).

### Mastodon instance

social.arazil.net

### Mastodon version

4.3.0-nightly.2023-11-30

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.2.2p53 +YJIT
- Node.js version: N/A (no longer included in the main Docker image per #26850)

**Comment by arazilsongweaver** [comment]
I modified the ```compose.yml``` file to: ```command: bundle exec rails s -p 3000``` and we're still having issues:
```
mastodon-web  | => Booting Puma
mastodon-web  | => Rails 7.1.2 application starting in production 
mastodon-web  | => Run `bin/rails server --help` for more startup options
mastodon-web  | Exiting
mastodon-web  | /usr/local/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir': Permission denied @ dir_s_mkdir - /opt/mastodon/tmp/pids (Errno::EACCES)
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:374:in `each'
mastodon-web  |         from /usr/local/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:71:in `block in create_tmp_directories'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:70:in `each'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:70:in `create_tmp_directories'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:34:in `start'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
mastodon-web  |         from <internal:kernel>:90:in `tap'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands/server/server_command.rb:136:in `perform'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor/command.rb:28:in `run'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor/invocation.rb:127:in `invoke_command'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:178:in `invoke_command'
mastodon-web  |         from /usr/local/bundle/gems/thor-1.3.0/lib/thor.rb:527:in `dispatch'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command/base.rb:73:in `perform'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:71:in `block in invoke'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:149:in `with_argv'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/command.rb:69:in `invoke'
mastodon-web  |         from /usr/local/bundle/gems/railties-7.1.2/lib/rails/commands.rb:18:in `<main>'
mastodon-web  |         from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
mastodon-web  |         from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
mastodon-web  |         from /usr/local/bundle/gems/bootsnap-1.17.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
mastodon-web  |         from bin/rails:4:in `<main>'
```
Thanks for the housekeeping advice.

**Comment by vmstan** [comment]
Does it do the same with the other startup command? That is what is used in other areas like the systemd, Helm charts, etc.

I am going to modify the Dockerfile to set tmp as writable in the meantime, but I want to get a startup command that works and fix the docker-compose.yml as well.

**Comment by vmstan** [comment]
Yeah doing some research that pid removal was added back in like 2018 to workaround the issue this startup method doesn't have that problem and is much cleaner.
