### ISSUE TITLE
`class java.lang.Boolean cannot be cast to class java.util.Map` during `tootctl search deploy`

### ISSUE THREAD

**Issue by drboone** [mastodon/mastodon#28673]
### Steps to reproduce the problem

Trying to add opensearch to a running mastodon instance.

Install:
Opensearch 2.11.0
Openjdk 17.0.9

Start opensearch service.

Run `tootctl search deploy`.

### Expected behaviour

Create indices and load documents.

### Actual behaviour

Java error

### Detailed description

```
[mastodon@company ~/live]$ RAILS_ENV=production bin/tootctl search deploy
WARNING: could not load hiredis extension, using (slower) pure Ruby implementation.
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error': [500] {"error":{"root_cause":[{"type":"class_cast_exception","reason":"class java.lang.Boolean cannot be cast to class java.util.Map (java.lang.Boolean and java.util.Map are in module java.base of loader 'bootstrap')"}],"type":"class_cast_exception","reason":"class java.lang.Boolean cannot be cast to class java.util.Map (java.lang.Boolean and java.util.Map are in module java.base of loader 'bootstrap')"},"status":500} (Elasticsearch::Transport::Transport::Errors::InternalServerError)
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/base.rb:347:in `perform_request'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/transport/http/faraday.rb:37:in `perform_request'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-transport-7.13.3/lib/elasticsearch/transport/client.rb:192:in `perform_request'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/namespace/common.rb:38:in `perform_request'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/elasticsearch-api-7.13.3/lib/elasticsearch/api/actions/indices/create.rb:48:in `create'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/index/actions.rb:62:in `create!'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/index/actions.rb:34:in `create'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/index/actions.rb:116:in `purge'
        from /opt/mastodon/live/lib/mastodon/cli/search.rb:53:in `block in deploy'
        from /opt/mastodon/live/lib/mastodon/cli/search.rb:51:in `each'
        from /opt/mastodon/live/lib/mastodon/cli/search.rb:51:in `deploy'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
        from bin/tootctl:9:in `block in <main>'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from bin/tootctl:8:in `<main>'
```

### Mastodon instance

h-net.social

### Mastodon version

v4.2.1

### Technical details

- Ruby version: ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-solaris2.11]
- Node.js version: v16.20.2

**Comment by mjankowski** [comment]
Are you able to start/run the search service on it's own (ie, not using the tootctl launch script?)

**Comment by drboone** [comment]
Opensearch was running when this happened.

**Comment by mjankowski** [comment]
Are you pretty confident that the env vars configuring the host/port/password/etc for chewy/ES are correct?

**Comment by drboone** [comment]
Ah, I see.  Wrong hostname.

That's a hell of an obscure way to spell "check your hostname", though.

**Comment by mjankowski** [comment]
Closing this on assumption that it was a config issue like described.

The linked PR should make this easier to catch in future release.
