### ISSUE TITLE
Sidekiq IndexingScheduler IDN::Idna::IdnaError: String preparation failed (1)

### ISSUE THREAD

**Issue by smiba** [mastodon/mastodon#28998]
### Steps to reproduce the problem

1. Run a troubled indexingScheduler job

### Expected behaviour

Job completing successfully

### Actual behaviour

Job failing with a string preparation failed error

### Detailed description

```
WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"scheduler","lock":"until_executed","lock_ttl":1800,"class":"Scheduler::IndexingScheduler","args":[],"jid":"7ab0c97539c5d50d2beab6df","created_at":1706443486.0743136,"lock_timeout":0,"lock_prefix":"uniquejobs","lock_args":[],"lock_digest":"uniquejobs:7466699daaed66759f16ae7e0ce32764","enqueued_at":1706450435.2276158,"error_message":"String preparation failed (1)","error_class":"IDN::Idna::IdnaError","failed_at":1706443487.0539262,"retry_count":-1,"retried_at":1706450346.3887196}}
WARN: IDN::Idna::IdnaError: String preparation failed (1)
WARN: /home/mastodon/sidekiq/vendor/bundle/ruby/3.0.0/gems/addressable-2.8.1/lib/addressable/idna/native.rb:39:in `toASCII'
/home/mastodon/sidekiq/vendor/bundle/ruby/3.0.0/gems/addressable-2.8.1/lib/addressable/idna/native.rb:39:in `block in to_ascii'
/home/mastodon/sidekiq/vendor/bundle/ruby/3.0.0/gems/addressable-2.8.1/lib/addressable/idna/native.rb:37:in `map'
```

In the debug log the last line is:
```
Account Load (0.2ms)  SELECT "accounts"."id", "accounts"."username", "accounts"."domain", "accounts"."private_key", "accounts"."public_key", "accounts"."created_at", "accounts"."updated_at", "accounts"."note", "accounts"."display_name", "accounts"."uri", "accounts"."url", "accounts"."avatar_file_name", "accounts"."avatar_content_type", "accounts"."avatar_file_size", "accounts"."avatar_updated_at", "accounts"."header_file_name", "accounts"."header_content_type", "accounts"."header_file_size", "accounts"."header_updated_at", "accounts"."avatar_remote_url", "accounts"."locked", "accounts"."header_remote_url", "accounts"."last_webfingered_at", "accounts"."inbox_url", "accounts"."outbox_url", "accounts"."shared_inbox_url", "accounts"."followers_url", "accounts"."protocol", "accounts"."memorial", "accounts"."moved_to_account_id", "accounts"."featured_collection_url", "accounts"."fields", "accounts"."actor_type", "accounts"."discoverable", "accounts"."also_known_as", "accounts"."silenced_at", "accounts"."suspended_at", "accounts"."hide_collections", "accounts"."avatar_storage_schema_version", "accounts"."header_storage_schema_version", "accounts"."devices_url", "accounts"."suspension_origin", "accounts"."sensitized_at", "accounts"."trendable", "accounts"."reviewed_at", "accounts"."requested_review_at" FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 109820757616630339], ["LIMIT", 1]]
INFO: Adding dead Scheduler::IndexingScheduler job 7ab0c97539c5d50d2beab6df
```

However considering the Indexing_Scheduler is batched, I'm not sure if this account is the one at fault? Checking the result manually reveals a normal account without anything odd that would cause this job to fail.
What would the best course of action be? Any way to enable debug so that it would be easier to trace the result causing the error? 

### Mastodon instance

woof.tech

### Mastodon version

v4.1.12-woof

### Technical details

Ruby 3.0.4p208
Node.js v16.20.2

**Comment by smiba** [comment]
Running the IndexingScheduler with a batch size of 1 shows the following:
For debugging reasons, I've made Addressable output the requests that pass through to_ascii:

```
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: 2024-01-28T19:15:17.587Z pid=2535967 tid=1jgdj class=Scheduler::IndexingScheduler jid=7b56f06b258fddbf34c751c1 INFO: start
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN to_ascii: bsky.app
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN segment: bsky
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN segment: app
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN to_ascii: midnightmakers.ca
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN segment: midnightmakers
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: IDN segment: ca
Jan 28 19:15:17 woof-tech-mastodon-prod bundle[2535967]: 2024-01-28T19:15:17.666Z pid=2535967 tid=1jgdj class=Scheduler::IndexingScheduler jid=7b56f06b258fddbf34c751c1 INFO: Adding dead Scheduler::IndexingScheduler job 7b56f06b258fddbf34c751c1
```

To me this looks entirely sensible and I don't understand why "ca" is what it fails on.

**Comment by smiba** [comment]
Figured it out why it errors, just can't figure out how to resolve it though. Unfortunately my Ruby is not that strong

In the original post, the URL is formatted as `https://midnightmakers.caÃ¢Â%C2%80Â¬`

The post in question is: https://cubhub.social/@spotty/111825489792064754
**(CW: SFW Kink content!)**

The issue seems to have been corrected in an edit 6 seconds later, but this is still causing the indexer to fail on my side
