### ISSUE TITLE
tootctl media remove failing

### ISSUE THREAD

**Issue by vengefulpunk** [mastodon/mastodon#29067]
### Steps to reproduce the problem

1. run command tootctl media remove

### Expected behaviour

should remove media cache

### Actual behaviour

error

### Detailed description

If I manually try to use tootctl I receive the error below
This only started after upgrading Mastodon to 4.2.5

mastodon@thundra:~/live$ ./bin/tootctl media remove
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack/msgpack.so (LoadError)
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack.rb:7:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/config/boot.rb:11:in `<top (required)>'
        from ./bin/tootctl:4:in `require_relative'
        from ./bin/tootctl:4:in `<main>'
<internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block - /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack/msgpack.so (LoadError)
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/msgpack-1.7.1/lib/msgpack.rb:7:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/explicit_require.rb:42:in `with_gems'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap.rb:5:in `<top (required)>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `require_relative'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/setup.rb:3:in `<top (required)>'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from <internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
        from /home/mastodon/live/config/boot.rb:11:in `<top (required)>'
        from ./bin/tootctl:4:in `require_relative'
        from ./bin/tootctl:4:in `<main>'

### Mastodon instance

darktundra.xyz

### Mastodon version

v4.2.5

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
- Node.js version: v16.20.2

**Comment by Zeitverschreib** [comment]
Not sure whether it's connected, but I get the same message "internal:/home/mastodon/.rbenv/versions/3.2.3/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb:38:in require': /lib/x86_64-linux-gnu/libjemalloc.so.2: cannot allocate memory in static TLS block"... when trying to rebuild the app on Yunohost after increasing the max_toot_char value.

This was never a problem up 'til 4.2.0.

**Comment by vranki** [comment]
Getting the same here on 4.2.5 on sauna.social. 

I think this is quite high priority issue. At least we are running out of disk space on our instance and there's no way to regain it.

ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
node v16.20.2

**Comment by ThisIsMissEm** [comment]
Try removing `vendor/bundler`

**Comment by jlopp** [comment]
I hit the same issue after upgrading from 4.2.0 to 4.2.5 and updating ruby from 3.2.0 to 3.2.3

I resolved by removing the ```vendor/bundle``` directory and reinstalling.

**Comment by vranki** [comment]
Removing it from where? This is a simple Mastodon management command that fails. As a instance admin you shouldn't need to touch the ruby/node layer.

**Comment by ThisIsMissEm** [comment]
> Removing it from where? This is a simple Mastodon management command that fails. As a instance admin you shouldn't need to touch the ruby/node layer.

From wherever the mastodon source code is on your server. The issue is that you were using ruby 3.2.0 with a certain version of openssl, then likely did an update of system packages giving a newer openssl, and then installed ruby 3.2.3, but the vendor'd code from bundler referenced ruby 3.2.0 which was compiled against openssl that's no longer on your system with the same binary API, so the low level compiler linking fails.

So removing the vendor directory have bundler recreate it linking against the correct version of ruby and openssl.

(for node.js, they actually side step this by compiling openssl into the node binary, ruby doesn't do this, it links against the system openssl)

**Comment by sznowicki** [comment]
Had the same but only `bundle install --force` worked.
