### ISSUE TITLE
User Data Backup fails with files hosted on S3, crashing Sidekiq entirely

### ISSUE THREAD

**Issue by theCapypara** [mastodon/mastodon#29186]
### Steps to reproduce the problem

Unknown.

### Expected behaviour

Sidekiq does not crash. The user backup finishes OR if there's an error the user or admin gets notified

### Actual behaviour

Sidekiq crashes. It fails (without notification or retry), timing out after 7 days

### Detailed description

One of the users on my Mastodon server is unable to export their data. The job for exporting the backup crashes the Sidekiq server, the sidekiq job is lost.
This only happens for one particular user. We use S3-compatible storage, from the trace it seems related.

My guess is, some media file is corrupted on the S3 server and/or the server sends an invalid response for it. The backup process and especially sidekiq probably shouldn't crash because of this.

S3 provider is Wasabi.

### Mastodon instance

guild.pmdcollab.org

### Mastodon version

v4.25

### Technical details

The sidekiq log for this job shows the following (I tried to strip log lines I knew were not relevant but kept the ones I was not sure about):

```
Feb 13 13:42:21 guild bundle[3313592]: 2024-02-13T12:42:21.722Z pid=3313592 tid=208wc class=BackupWorker jid=03d344d56f21248a6bd0259c INFO: start
Feb 13 13:42:33 guild bundle[3313592]: I, [2024-02-13T13:42:33.146815 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/4fb1186d15fbfed6.png to local file /tmp/b3fe777b292d56c8dec392458a06616520240213-3313592-lhoy65.png
Feb 13 13:42:33 guild bundle[3313592]: I, [2024-02-13T13:42:33.768987 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/fedc9131cbec0215.png to local file /tmp/7f7ae15e193f9d25baf9b98ddeb8d41720240213-3313592-tauh7g.png
Feb 13 13:42:33 guild bundle[3313592]: I, [2024-02-13T13:42:33.897717 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/1ac6ad0205583ebe.png to local file /tmp/a570b1db961df22c0174887ff7d23cb620240213-3313592-mym6xf.png
Feb 13 13:42:34 guild bundle[3313592]: I, [2024-02-13T13:42:34.035910 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/c7abe2ecf74a6f2e.png to local file /tmp/295c5db3ce63f9453cf8525d867e0d0220240213-3313592-48aebh.png
Feb 13 13:42:34 guild bundle[3313592]: I, [2024-02-13T13:42:34.268449 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/d23a5fccfbb41a1a.jpg to local file /tmp/0f1017cc816b131e569bd2e11d46c30d20240213-3313592-t6e1gy.jpg
Feb 13 13:42:34 guild bundle[3313592]: I, [2024-02-13T13:42:34.409284 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/d55e16ec01aa3588.jpg to local file /tmp/b500f690597b189b062f20c34d1baf8820240213-3313592-n5skxi.jpg
Feb 13 13:42:34 guild bundle[3313592]: I, [2024-02-13T13:42:34.567136 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/original/53828e393431a432.mp4 to local file /tmp/8779f18f1c2c1c052ca161909505761520240213-3313592-5fuvr9.mp4
Feb 13 13:42:35 guild bundle[3313592]: I, [2024-02-13T13:42:35.049644 #3313592]  INFO -- : [paperclip] copying media_attachments/files/<stripped for privacy>/92be8b490c8235b5.mp4 to local file /tmp/510f8d0508251193ca086245f4ad579b20240213-3313592-exk0oi.mp4
Feb 13 13:42:36 guild bundle[3313592]: #<Thread:0x00007fda9d9a6968 /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:171 run> terminated with exception (report_on_exception is true):
Feb 13 13:42:36 guild bundle[3313592]: #<Thread:0x00007fda9d9a6620 /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:171 run> terminated with exception (report_on_exception is true):
Feb 13 13:42:36 guild bundle[3313592]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:200:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Feb 13 13:42:36 guild bundle[3313592]:         range, _ = resp.content_range.split(' ').last.split('/')
Feb 13 13:42:36 guild bundle[3313592]:                                      ^^^^^^
Feb 13 13:42:36 guild bundle[3313592]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:181:in `block (2 levels) in download_in_threads'
Feb 13 13:42:36 guild bundle[3313592]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:200:in `write': undefined method `split' for nil:NilClass (NoMethodError)
Feb 13 13:42:36 guild bundle[3313592]:         range, _ = resp.content_range.split(' ').last.split('/')
Feb 13 13:42:36 guild bundle[3313592]:                                      ^^^^^^
Feb 13 13:42:36 guild bundle[3313592]:         from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:181:in `block (2 levels) in download_in_threads'
Feb 13 13:42:36 guild bundle[3313592]: log writing failed. undefined method `split' for nil:NilClass
Feb 13 13:42:36 guild bundle[3313592]: 2024-02-13T12:42:36.249Z pid=3313592 tid=1z1sw WARN: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:200:in `write'
Feb 13 13:42:36 guild bundle[3313592]: /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/file_downloader.rb:181:in `block (2 levels) in download_in_threads'
Feb 13 13:42:36 guild systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=1/FAILURE
Feb 13 13:42:36 guild systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
Feb 13 13:42:36 guild systemd[1]: mastodon-sidekiq.service: Consumed 19min 25.671s CPU time.
```

**Comment by christianp** [comment]
I have the same problem, also using nginx as a proxy to Wasabi.

I think that this might be related to [this post on the nginx forum](https://forum.nginx.org/read.php?2,8958,8958) where someone says that nginx returns the full file in a 200 response if the file wasn't already cached. That would mean that the Content-Range header wouldn't be set, I think.

I'm trying to reproduce this myself to see if that's what the problem really is.

**Comment by pageuppagedown** [comment]
Hello. I'm running into this same problem. My backend is Linode's S3-compatible object storage, and I'm using Nginx to proxy it. I'm having this on Mastodon 4.4.2 and nginx/1.22.1 on Debian GNU/Linux 12 (bookworm).

**Comment by brookmiles** [comment]
I was able to solve this issue in my Wasabi S3 setup by enabling (the [undocumented](https://docs.joinmastodon.org/admin/config/#s3_force_single_request)) `S3_FORCE_SINGLE_REQUEST=true` in `.env.production`

I believe this is also applicable with OVH's S3 storage, the reason I wasn't seeing the issue there was that I already had this flag enabled and had forgotten about it.

**Comment by pageuppagedown** [comment]
> I was able to solve this issue in my Wasabi S3 setup by enabling (the [undocumented](https://docs.joinmastodon.org/admin/config/#s3_force_single_request)) `S3_FORCE_SINGLE_REQUEST=true` in `.env.production`
> 
> I believe this is also applicable with OVH's S3 storage, the reason I wasn't seeing the issue there was that I already had this flag enabled and had forgotten about it.

THANK YOU! This solved my problem. I've got an archive building now.

**Comment by christianp** [comment]
Just another comment to say that `S3_FORCE_SINGLE_REQUEST=true` made it work. Could that be added to the documentation?
