### ISSUE TITLE
upgrading from nightly 2024-02-25 to 2024-04-28 crashes due to missing encryption keys

### ISSUE THREAD

**Issue by untitaker** [mastodon/mastodon#30100]
### Steps to reproduce the problem

Upgrade mastodon by changing the docker image tag from `nightly.2024-02-25` to `nightly.2024-04-28`.

### Expected behaviour

No crashes of web worker

### Actual behaviour

Web worker does not start at all

### Detailed description

<details><summary><strong>click for stacktrace</strong></summary>

```
web_1             | The ActiveRecord encryption feature requires that these variables are set:
web_1             |
web_1             |   - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
web_1             |   - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
web_1             |   - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
web_1             |
web_1             | Run `bin/rails db:encryption:init` to generate values and then assign the environment variables.
web_1             |
web_1             |     from /opt/mastodon/config/initializers/active_record_encryption.rb:8:in `fetch'
web_1             |     from /opt/mastodon/config/initializers/active_record_encryption.rb:8:in `block in <main>'
web_1             |     from /opt/mastodon/config/initializers/active_record_encryption.rb:7:in `each'
web_1             |     from /opt/mastodon/config/initializers/active_record_encryption.rb:7:in `<main>'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:690:in `load'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:690:in `block in load_config_initializer'
web_1             |     from /usr/local/bundle/gems/activesupport-7.1.3.2/lib/active_support/notifications.rb:208:in `instrument'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:689:in `load_config_initializer'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:643:in `block (2 levels) in <class:Engine>'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:642:in `each'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/engine.rb:642:in `block in <class:Engine>'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `instance_exec'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:32:in `run'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:61:in `block in run_initializers'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:228:in `block in tsort_each'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:431:in `each_strongly_connected_component_from'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:50:in `each'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:50:in `tsort_each_child'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `call'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:415:in `each_strongly_connected_component_from'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:349:in `block in each_strongly_connected_component'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `call'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:347:in `each_strongly_connected_component'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:226:in `tsort_each'
web_1             |     from /usr/local/lib/ruby/3.2.0/tsort.rb:205:in `tsort_each'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/initializable.rb:60:in `run_initializers'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/application.rb:426:in `initialize!'
web_1             |     from /opt/mastodon/config/environment.rb:7:in `<main>'
web_1             |     from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
web_1             |     from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
web_1             |     from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1             |     from /usr/local/bundle/gems/zeitwerk-2.6.13/lib/zeitwerk/kernel.rb:34:in `require'
web_1             |     from config.ru:5:in `block in <main>'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `eval'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:116:in `new_from_string'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:105:in `load_file'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/builder.rb:66:in `parse_file'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:349:in `build_app_and_options_from_config'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:249:in `app'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:422:in `wrapped_app'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:312:in `block in start'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:379:in `handle_profiling'
web_1             |     from /usr/local/bundle/gems/rack-2.2.9/lib/rack/server.rb:311:in `start'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/commands/server/server_command.rb:38:in `start'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/commands/server/server_command.rb:145:in `block in perform'
web_1             |     from <internal:kernel>:90:in `tap'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/commands/server/server_command.rb:136:in `perform'
web_1             |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
web_1             |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command/base.rb:178:in `invoke_command'
web_1             |     from /usr/local/bundle/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command/base.rb:73:in `perform'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command.rb:71:in `block in invoke'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command.rb:149:in `with_argv'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/command.rb:69:in `invoke'
web_1             |     from /usr/local/bundle/gems/railties-7.1.3.2/lib/rails/commands.rb:18:in `<main>'
web_1             |     from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
web_1             |     from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
web_1             |     from /usr/local/bundle/gems/bootsnap-1.18.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
web_1             |     from bin/rails:4:in `<main>'
```

</details>

### Mastodon instance

woodland.cafe

### Mastodon version

nightly-2024-04-28

### Technical details

I use the docker image.

**Comment by shleeable** [comment]
This is documented https://docs.joinmastodon.org/admin/config/#db-encryption-support

the error contains the fix `Run `bin/rails db:encryption:init` to generate values and then assign the environment variables.`

**Comment by untitaker** [comment]
I see, I expected this to be visible in changelog

**Comment by fullStackRacc** [comment]
I have ran this and it refuses to generate any values it just tells me that it now requires these values

**Comment by cairobraga** [comment]
> This is documented https://docs.joinmastodon.org/admin/config/#db-encryption-support
> 
> the error contains the fix
> 
> Run `bin/rails db:encryption:init` to generate values and then assign the environment variables.

it's badly documented, because it only indicates the variables and why they're there, but not a single indication in how to obtain them. it would be nice to properly document it, since it's not mentioned in the changelog and will get many server admins by surprise.

**Comment by rursache** [comment]
@rahilarious thanks for this, woke up today with a broken mastodon instance. 
how hard is to highlight these breaking changes in the changelog...? or actually generate these keys automatically and never bother the user?

**Comment by untitaker** [comment]
it's definitely highlighted in the 4.3.0 release notes as a breaking change.

**Comment by Monokel777** [comment]
Thank you for this posts. It worked!

but now my Instance has no content.
how could I get this back?
on my left bottom site there are some "500" as notifications.

`2024-10-22 18:12:20.580 UTC [48] ERROR:  relation "notification_policies" does not exist at character 523

2024-10-22 18:12:20.580 UTC [48] STATEMENT:  SELECT a.attname, format_type(a.atttypid, a.atttypmod),

	       pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod,

	       c.collname, col_description(a.attrelid, a.attnum) AS comment,

	       attidentity AS identity,

	       attgenerated as attgenerated

	  FROM pg_attribute a

	  LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum

	  LEFT JOIN pg_type t ON a.atttypid = t.oid

	  LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation

	 WHERE a.attrelid = '"notification_policies"'::regclass

	   AND a.attnum > 0 AND NOT a.attisdropped

	 ORDER BY a.attnum

	`
