### ISSUE TITLE
webpack-cli throws an error on fresh new install on Docker/MacOS 

### ISSUE THREAD

**Issue by BrunoFenzl** [mastodon/mastodon#30213]
### Steps to reproduce the problem

1. Clone the repository on MacOS and follow the steps to get the Docker virtualization running
2. Execute `docker-compose -f .devcontainer/docker-compose.yml exec -w /workspaces/mastodon app .devcontainer/post-create.sh` as described [here](https://github.com/mastodon/mastodon/discussions/27843#discussioncomment-7872344) to fix the issue in that link.

### Expected behaviour

Webpack compilation should complete successfully

### Actual behaviour

Webpack fails

### Detailed description

Webpacker starts compiling the frontend assets and will stop with the following error: (excerpt)

```log
...
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
[Webpacker] Everything's up-to-date. Nothing to do
  Rendered layout layouts/error.html.haml (Duration: 1529.2ms | Allocations: 582036)
Compiling...
Compilation failed:
/workspaces/mastodon/node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^

TypeError: Cannot read properties of undefined (reading 'compress')
    at Object.<anonymous> (/workspaces/mastodon/config/webpack/development.js:32:35)
    at Module._compile (/workspaces/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (/workspaces/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/workspaces/mastodon/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (/workspaces/mastodon/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at /workspaces/mastodon/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (/workspaces/mastodon/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at /workspaces/mastodon/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (/workspaces/mastodon/node_modules/yargs/yargs.js:576:18)
    at /workspaces/mastodon/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/workspaces/mastodon/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/workspaces/mastodon/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49

Node.js v20.12.2
```

It seems to me that the configuration in `config/webpacker.yml` is not being read. Anyone facing this error?
Thanks in advance!

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: v3.2.4
- Node.js version: v20.12.2
- MacOS 14.4.1 on Apple Silicon M3
- Docker version 25.0.3

**Comment by BrunoFenzl** [comment]
How are developers on newer macs supposed to develop? As of now, Vagrant virtualization does not work with Virtualbox and Docker is broken. Installing the setup on bare metal is not an option at work. 
Any hints or some guidance are greatly appreciated! Thanks in advance!

**Comment by daudix** [comment]
It's also an issue on Linux, not just macOS

**Comment by BrunoFenzl** [comment]
Thanks for the fix @renchap! I can confirm it works.
