### ISSUE TITLE
Upgrading from v4.2.8 to v4.2.9: TypeError: URL.canParse is not a function

### ISSUE THREAD

**Issue by memo-567** [mastodon/mastodon#30489]
### Steps to reproduce the problem

Upgrading from v4.2.8 to v4.2.9

1. git fetch && git checkout v4.2.9
2. bundle install
3. yarn install --frozen-lockfile

`Error: TypeError: URL.canParse is not a function`

### Expected behaviour

Mastodon instance should upgrage

### Actual behaviour

Error message

### Detailed description

```
/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22892
  return !URL.canParse(descriptor.range);
              ^

TypeError: URL.canParse is not a function
    at isSupportedPackageManagerDescriptor (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:22892:15)
    at Engine.resolveDescriptor (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:23552:10)
    at Engine.findProjectSpec (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:23496:41)
    at async Engine.executePackageManagerRequest (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:23542:24)
    at async Object.runMain (/usr/lib/node_modules/corepack/dist/lib/corepack.cjs:24235:5)
```

### Mastodon instance

mstdn.mv2k.com

### Mastodon version

v4.2.8 to  v4.2.9:

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version:  3.2.3
- Node.js version: 16.20.1

**Comment by memo-567** [comment]
I don't know why, but

```
corepack enable
yarn set version classic
```

Worked. Everything is fine now.
