### ISSUE TITLE
Release 4.2.9 breaks our reverse proxy setup with nginx

### ISSUE THREAD

**Issue by loxK** [mastodon/mastodon#30554]
### Steps to reproduce the problem

1. upgrade to 4.2.9
2. restart mastodon

### Expected behaviour

Should show the UI

### Actual behaviour

Show the mastodon 500 error page

### Detailed description

Here is our nginx config that was working on 4.2.8 :

<details>
  <summary>Nginx config</summary>

```
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

upstream backend {
    server 127.0.0.1:3000 fail_timeout=0;
}

upstream streaming {
    server 127.0.0.1:4000 fail_timeout=0;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=CACHE:10m inactive=7d max_size=1g;

server {
  listen 80 default_server;
  listen [::]:80 default_server;
  server_name [redacted];
  root /home/mastodon/live/public;
  location /.well-known/acme-challenge/ { allow all; }

  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 80m;

  set_real_ip_from [redacted];
  real_ip_header    X-Forwarded-For;
  real_ip_recursive on;
  
  gzip on;
  gzip_disable "msie6";
  gzip_vary on;
  gzip_proxied any;
  gzip_comp_level 6;
  gzip_buffers 16 8k;
  gzip_http_version 1.1;
  gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml image/x-icon;

  # brotli
  brotli on;
  brotli_comp_level 6;
  brotli_types text/xml image/svg+xml application/x-font-ttf image/vnd.microsoft.icon application/x-font-opentype application/json font/eot application/vnd.ms-fontobject application/javascript font/otf application/xml application/xhtml+xml text/javascript  application/x-javascript text/plain application/x-font-truetype application/xml+rss image/x-icon font/opentype text/css image/x-win-bitmap;

  location / {
    try_files $uri @proxy;
  }

  # If Docker is used for deployment and Rails serves static files,
  # then needed must replace line `try_files $uri =404;` with `try_files $uri @proxy;`.
  location = /sw.js {
    add_header Cache-Control "public, max-age=604800, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/assets/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/avatars/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/emoji/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/headers/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/packs/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/shortcuts/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/sounds/ {
    add_header Cache-Control "public, max-age=2419200, must-revalidate";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    try_files $uri =404;
  }

  location ~ ^/system/ {
    add_header Cache-Control "public, max-age=2419200, immutable";
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "default-src 'none'; form-action 'none'";
    try_files $uri =404;
  }

  location ^~ /api/v1/streaming {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";

    proxy_pass http://streaming;
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_pass_header Server;
    # add_header Strict-Transport-Security "max-age=63072000; includeSubDomains";

    tcp_nodelay on;
  }

  location @proxy {
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header Proxy "";
    proxy_pass_header Server;

    proxy_pass http://backend;
    proxy_buffering on;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;

    proxy_cache CACHE;
    proxy_cache_valid 200 7d;
    proxy_cache_valid 410 24h;
    proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
    add_header X-Cached $upstream_cache_status;

    tcp_nodelay on;
  }

  error_page 404 500 501 502 503 504 /500.html;
}
```

</details>

mastodon-web service shows this error :

```
[[15~juin 05 10:53:02 toot.gaiac.io bundle[1553]: F, [2024-06-05T10:53:02.130111 #1553] FATAL -- : [70be90b0-6982-445b-a202-f7b51ecb63dd]
juin 05 10:53:02 toot.gaiac.io bundle[1553]: [70be90b0-6982-445b-a202-f7b51ecb63dd] ActionDispatch::RemoteIp::IpSpoofAttackError (IP spoofing attack?! client 127.0.0.1 is not a trusted proxy HTTP_CLIENT_IP=nil HTTP_X_FORWARDED_FOR="10.0.4.90, 10.0.4.90"):
juin 05 10:53:02 toot.gaiac.io bundle[1553]: [70be90b0-6982-445b-a202-f7b51ecb63dd]
juin 05 10:53:02 toot.gaiac.io bundle[1553]: [70be90b0-6982-445b-a202-f7b51ecb63dd] lib/action_dispatch/remote_ip_extensions.rb:49:in `calculate_ip'
juin 05 10:53:02 toot.gaiac.io bundle[1553]: [70be90b0-6982-445b-a202-f7b51ecb63dd] config/initializers/rack_attack.rb:17:in `remote_ip'
juin 05 10:53:02 toot.gaiac.io bundle[1553]: [70be90b0-6982-445b-a202-f7b51ecb63dd] config/initializers/rack_attack.rb:66:in `block in <class:Attack>'
```

### Mastodon instance

too.gaiac.io

### Mastodon version

v4.2.9

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [x86_64-linux]
- Node.js version: v16.20.2

**Comment by loxK** [comment]
I added 127.0.0.1 to TRUSTED_PROXY_IP in .env.production

Solved.
