### ISSUE TITLE
Unmaintained-since-2020 charlock_holmes gem fails to build under gcc10

### ISSUE THREAD

**Issue by drboone** [mastodon/mastodon#30866]
### Steps to reproduce the problem

`bundle exec gem pristine charlock_holmes`
`bundle install`

### Expected behaviour

Successful replacement of charlock_holmes gem

### Actual behaviour

Compiler errors, log in description

### Detailed description

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/opt/local/bin/ruby32 extconf.rb
checking for -licui18n... yes
checking for unicode/ucnv.h... yes
checking for -lz... yes
checking for -licuuc... yes
checking for -licudata... yes
creating Makefile

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240627-34056-u6eba4
sitelibdir\=./.gem.20240627-34056-u6eba4 clean

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240627-34056-u6eba4
sitelibdir\=./.gem.20240627-34056-u6eba4
compiling converter.c
compiling encoding_detector.c
compiling ext.c
compiling transliterator.cpp
<command-line>: warning: "_XOPEN_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
In file included from /opt/local/include/unicode/unistr.h:39,
                 from /opt/local/include/unicode/translit.h:27,
                 from transliterator.cpp:5:
/opt/local/include/unicode/stringpiece.h:133:29: error: 'enable_if_t' in
namespace 'std' does not name a template type
  133 |             typename = std::enable_if_t<
      |                             ^~~~~~~~~~~
/opt/local/include/unicode/stringpiece.h:133:24: note: 'std::enable_if_t' is
only available from C++14 onwards
  133 |             typename = std::enable_if_t<
      |                        ^~~
/opt/local/include/unicode/stringpiece.h:133:40: error: expected '>' before '<'
token
  133 |             typename = std::enable_if_t<
      |                                        ^
In file included from /opt/local/include/unicode/uenum.h:25,
                 from /opt/local/include/unicode/utrans.h:22,
                 from /opt/local/include/unicode/translit.h:29,
                 from transliterator.cpp:5:
/opt/local/include/unicode/localpointer.h:561:26: error: parameter declared
'auto'
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/opt/local/include/unicode/localpointer.h:573:76: error: template argument 2 is
invalid
573 |     explicit LocalOpenPointer(std::unique_ptr<Type,
decltype(closeFunction)> &&p)
|                                                                         
^
/opt/local/include/unicode/localpointer.h:583:78: error: template argument 2 is
invalid
583 |     LocalOpenPointer &operator=(std::unique_ptr<Type,
decltype(closeFunction)> &&p) {
|                                                                         
^
/opt/local/include/unicode/localpointer.h:599:59: error: template argument 2 is
invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/opt/local/include/unicode/uenum.h:69:1: note: invalid template non-type
parameter
69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration,
uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/uset.h:358:1: note: invalid template non-type
parameter
  358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/utrans.h:258:1: note: invalid template non-type
parameter
258 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUTransliteratorPointer,
UTransliterator, utrans_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:241: transliterator.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7 for
inspection.
Results logged to
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/extensions/x86_64-solaris-2.11/3.2.0/charlock_holmes-0.7.7/gem_make.out

  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:119:in `run'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:53:in `block in make'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `each'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:45:in `make'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:187:in `build_extension'
/opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:221:in `block in
build_extensions'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `each'
  /opt/local/lib/ruby/3.2.0/rubygems/ext/builder.rb:218:in `build_extensions'
  /opt/local/lib/ruby/3.2.0/rubygems/installer.rb:855:in `build_extensions'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/rubygems_gem_installer.rb:72:in
`build_extensions'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/source/rubygems.rb:198:in
`install'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/installer/gem_installer.rb:54:in
`install'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/installer/parallel_installer.rb:156:in
`do_install'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/installer/parallel_installer.rb:147:in
`block in worker_pool'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/worker.rb:62:in
`apply_func'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/worker.rb:57:in
`block in process_queue'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/worker.rb:54:in
`loop'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/worker.rb:54:in
`process_queue'
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.13/lib/bundler/worker.rb:90:in
`block (2 levels) in create_threads'

An error occurred while installing charlock_holmes (0.7.7), and Bundler
cannot continue.

In Gemfile:
  charlock_holmes
```

### Mastodon instance

h-net.social

### Mastodon version

v4.2.9

### Browser name and version

Chromium 124.0.6367.207 

### Operating system

FreeBSD 14.0 RELEASE

**Comment by drboone** [comment]
Note that our instance is pretty much down because of this.  I've tried restoring charlock_holmes related files from backup, but asset prebuild claims it can't load the gem.

**Comment by ClearlyClaire** [comment]
Try building with `BUNDLE_BUILD__CHARLOCK_HOLMES="--with-cxxflags='#'"`

**Comment by drboone** [comment]
The cxxflags do get updated in the makefile.  The compiler errors change.  Still errors out.
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
/opt/local/bin/ruby32 extconf.rb --with-cxxflags\=\#
checking for -licui18n... yes
checking for unicode/ucnv.h... yes
checking for -lz... yes
checking for -licuuc... yes
checking for -licudata... yes
creating Makefile

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240628-452512-q0ivfi
sitelibdir\=./.gem.20240628-452512-q0ivfi clean

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.7/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240628-452512-q0ivfi
sitelibdir\=./.gem.20240628-452512-q0ivfi
compiling converter.c
compiling encoding_detector.c
compiling ext.c
compiling transliterator.cpp
<command-line>: warning: "_XOPEN_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
In file included from /opt/local/include/unicode/unistr.h:39,
                 from /opt/local/include/unicode/translit.h:27,
                 from transliterator.cpp:5:
/opt/local/include/unicode/stringpiece.h:134:23: error: 'is_same_v' is not a
member of 'std'; did you mean 'is_same'?
  134 |                 (std::is_same_v<decltype(T().data()), const char*>
      |                       ^~~~~~~~~
      |                       is_same
/opt/local/include/unicode/stringpiece.h:134:66: error: template argument 1 is
invalid
  134 |                 (std::is_same_v<decltype(T().data()), const char*>
      |                                                                  ^
/opt/local/include/unicode/stringpiece.h:138:17: error: expected '>' before ')'
token
  138 |                 ) &&
      |                 ^
/opt/local/include/unicode/stringpiece.h:138:17: error: expected unqualified-id
before ')' token
In file included from /opt/local/include/unicode/uenum.h:25,
                 from /opt/local/include/unicode/utrans.h:22,
                 from /opt/local/include/unicode/translit.h:29,
                 from transliterator.cpp:5:
/opt/local/include/unicode/localpointer.h:561:26: error: 'auto' parameter not
permitted in this context
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/opt/local/include/unicode/localpointer.h:573:76: error: template argument 2 is
invalid
573 |     explicit LocalOpenPointer(std::unique_ptr<Type,
decltype(closeFunction)> &&p)
|                                                                         
^
/opt/local/include/unicode/localpointer.h:583:78: error: template argument 2 is
invalid
583 |     LocalOpenPointer &operator=(std::unique_ptr<Type,
decltype(closeFunction)> &&p) {
|                                                                         
^
/opt/local/include/unicode/localpointer.h:599:59: error: template argument 2 is
invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/opt/local/include/unicode/uenum.h:69:1: note: invalid template non-type
parameter
69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration,
uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/uset.h:358:1: note: invalid template non-type
parameter
  358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/utrans.h:258:1: note: invalid template non-type
parameter
258 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUTransliteratorPointer,
UTransliterator, utrans_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:241: transliterator.o] Error 1

make failed, exit code 2
```

**Comment by ClearlyClaire** [comment]
Hm, I'm afraid I don't know how to address this issue :/

**Comment by ThisIsMissEm** [comment]
Could this actually be due to a change in libicu? The other issue was, iirc, a change in ruby interfaces

**Comment by ClearlyClaire** [comment]
Both have to do with libicu, gcc 10, and compiler flags, not with ruby interfaces. But I hadn't seen the second issue before, and I'm not sure how to solve it.

**Comment by ClearlyClaire** [comment]
A new version of `charlock_holmes` has just been released, supposedly fixing the issue.

Can you apply the following patch and see if it solves the issue for you?
```patch
diff --git a/Gemfile.lock b/Gemfile.lock
index 891566e1ae..1172fc6a7b 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -192,7 +192,7 @@ GEM
     case_transform (0.2)
       activesupport
     cbor (0.5.9.6)
-    charlock_holmes (0.7.7)
+    charlock_holmes (0.7.8)
     chewy (7.3.4)
       activesupport (>= 5.2)
       elasticsearch (>= 7.12.0, < 7.14.0)
```

And do `bundle install`, without setting `BUNDLE_BUILD__CHARLOCK_HOLMES`?

**Comment by drboone** [comment]
Not much different:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.8/ext/charlock_holmes
/opt/local/bin/ruby32 extconf.rb
checking for -licui18n... yes
checking for unicode/ucnv.h... yes
checking for -lz... yes
checking for -licuuc... yes
checking for -licudata... yes
creating Makefile

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.8/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240628-916306-y6wfht
sitelibdir\=./.gem.20240628-916306-y6wfht clean

current directory:
/opt/mastodon/live/vendor/bundle/ruby/3.2.0/gems/charlock_holmes-0.7.8/ext/charlock_holmes
make DESTDIR\= sitearchdir\=./.gem.20240628-916306-y6wfht
sitelibdir\=./.gem.20240628-916306-y6wfht
compiling converter.c
compiling encoding_detector.c
compiling ext.c
compiling transliterator.cpp
<command-line>: warning: "_XOPEN_SOURCE" redefined
<built-in>: note: this is the location of the previous definition
In file included from /opt/local/include/unicode/unistr.h:39,
                 from /opt/local/include/unicode/translit.h:27,
                 from transliterator.cpp:5:
/opt/local/include/unicode/stringpiece.h:134:23: error: 'is_same_v' is not a
member of 'std'; did you mean 'is_same'?
  134 |                 (std::is_same_v<decltype(T().data()), const char*>
      |                       ^~~~~~~~~
      |                       is_same
/opt/local/include/unicode/stringpiece.h:134:66: error: template argument 1 is
invalid
  134 |                 (std::is_same_v<decltype(T().data()), const char*>
      |                                                                  ^
/opt/local/include/unicode/stringpiece.h:138:17: error: expected '>' before ')'
token
  138 |                 ) &&
      |                 ^
/opt/local/include/unicode/stringpiece.h:138:17: error: expected unqualified-id
before ')' token
In file included from /opt/local/include/unicode/uenum.h:25,
                 from /opt/local/include/unicode/utrans.h:22,
                 from /opt/local/include/unicode/translit.h:29,
                 from transliterator.cpp:5:
/opt/local/include/unicode/localpointer.h:561:26: error: 'auto' parameter not
permitted in this context
  561 | template <typename Type, auto closeFunction>
      |                          ^~~~
/opt/local/include/unicode/localpointer.h:573:76: error: template argument 2 is
invalid
573 |     explicit LocalOpenPointer(std::unique_ptr<Type,
decltype(closeFunction)> &&p)
|                                                                         
^
/opt/local/include/unicode/localpointer.h:583:78: error: template argument 2 is
invalid
583 |     LocalOpenPointer &operator=(std::unique_ptr<Type,
decltype(closeFunction)> &&p) {
|                                                                         
^
/opt/local/include/unicode/localpointer.h:599:59: error: template argument 2 is
invalid
  599 |     operator std::unique_ptr<Type, decltype(closeFunction)> () && {
      |                                                           ^
/opt/local/include/unicode/uenum.h:69:1: note: invalid template non-type
parameter
69 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUEnumerationPointer, UEnumeration,
uenum_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/uset.h:358:1: note: invalid template non-type
parameter
  358 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUSetPointer, USet, uset_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/local/include/unicode/utrans.h:258:1: note: invalid template non-type
parameter
258 | U_DEFINE_LOCAL_OPEN_POINTER(LocalUTransliteratorPointer,
UTransliterator, utrans_close);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:241: transliterator.o] Error 1

make failed, exit code 2
```
The available and installed icu package is `icu-75.1`.

**Comment by ClearlyClaire** [comment]
Can you try with `BUNDLE_BUILD__CHARLOCK_HOLMES="--with-cxxflags=-std=c++17"`?

**Comment by drboone** [comment]
Success!  Both the diff and the build option seem to be necessary.

**Comment by drboone** [comment]
Thanks, folks, for the quick response!

**Comment by adamniedzielski** [comment]
Shall this issue be closed as "resolved"?

**Comment by drboone** [comment]
Is the updated charlock_holmes actually installable, and mastodon calls for the correct version now?

**Comment by ThisIsMissEm** [comment]
> Is the updated charlock_holmes actually installable, and mastodon calls for the correct version now?

Should be

**Comment by drboone** [comment]
Seems closable then.  Thanks again!

**Comment by ClearlyClaire** [comment]
You still need the build option (as documented in the release notes) but at least you don't need any additional patch or dependency change.
