### ISSUE TITLE
Batch of NoMethodError's and similar errors from sidekiq

### ISSUE THREAD

**Issue by shleeable** [mastodon/mastodon#31153]
### Pitch

```
WARN: {"context":"Job raised exception","job":{"retry":16,"queue":"push","dead":false,"class":"ActivityPub::DeliveryWorker","args":["{\"@context\":[\"https://www.w3.org/ns/activitystreams\",{\"ostatus\":\"http://ostatus.org#\",\"atomUri\":\"ostatus:atomUri\",\"inReplyToAtomUri\":\"ostatus:inReplyToAtomUri\",\"conversation\":\"ostatus:conversation\",\"sensitive\":\"as:sensitive\",\"toot\":\"http://joinmastodon.org/ns#\",\"votersCount\":\"toot:votersCount\"}],\"id\":\"https://aus.social/users/dgar/statuses/112840039696728772/activity\",\"type\":\"Create\",\"actor\":\"https://aus.social/users/dgar\",\"published\":\"2024-07-24T06:26:03Z\",\"to\":[\"https://aus.social/users/dgar/followers\"],\"cc\":[\"https://www.w3.org/ns/activitystreams#Public\",\"https://old.mermaid.town/users/futzle\"],\"object\":{\"id\":\"https://aus.social/users/dgar/statuses/112840039696728772\",\"type\":\"Note\",\"summary\":null,\"inReplyTo\":\"https://old.mermaid.town/users/futzle/statuses/112839994130100179\",\"published\":\"2024-07-24T06:26:03Z\",\"url\":\"https://aus.social/@dgar/112840039696728772\",\"attributedTo\":\"https://aus.social/users/dgar\",\"to\":[\"https://aus.social/users/dgar/followers\"],\"cc\":[\"https://www.w3.org/ns/activitystreams#Public\",\"https://old.mermaid.town/users/futzle\"],\"sensitive\":false,\"atomUri\":\"https://aus.social/users/dgar/statuses/112840039696728772\",\"inReplyToAtomUri\":\"https://old.mermaid.town/users/futzle/statuses/112839994130100179\",\"conversation\":\"tag:aus.social,2024-07-24:objectId=152957027:objectType=Conversation\",\"content\":\"\\u003cp\\u003e\\u003cspan class=\\\"h-card\\\" translate=\\\"no\\\"\\u003e\\u003ca href=\\\"https://old.mermaid.town/@futzle\\\" class=\\\"u-url mention\\\"\\u003e@\\u003cspan\\u003efutzle\\u003c/span\\u003e\\u003c/a\\u003e\\u003c/span\\u003e … vaguely rings a bell…\\u003c/p\\u003e\",\"contentMap\":{\"en\":\"\\u003cp\\u003e\\u003cspan class=\\\"h-card\\\" translate=\\\"no\\\"\\u003e\\u003ca href=\\\"https://old.mermaid.town/@futzle\\\" class=\\\"u-url mention\\\"\\u003e@\\u003cspan\\u003efutzle\\u003c/span\\u003e\\u003c/a\\u003e\\u003c/span\\u003e … vaguely rings a bell…\\u003c/p\\u003e\"},\"attachment\":[],\"tag\":[{\"type\":\"Mention\",\"href\":\"https://old.mermaid.town/users/futzle\",\"name\":\"@futzle@old.mermaid.town\"}],\"replies\":{\"id\":\"https://aus.social/users/dgar/statuses/112840039696728772/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"next\":\"https://aus.social/users/dgar/statuses/112840039696728772/replies?only_other_accounts=true\\u0026page=true\",\"partOf\":\"https://aus.social/users/dgar/statuses/112840039696728772/replies\",\"items\":[]}}},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://aus.social/users/dgar#main-key\",\"created\":\"2024-07-24T06:26:03Z\",\"signatureValue\":\"eIwAzr6Kq2zP9eXMign/nwlpvEOou5fZqiJinnkSzKchyOqTSI3tEXP1g7IJ6tyWk+QfXGLvj4JwTeFONPD8MO1nqr9oO5KpEhMczg43XWHmY7LA4NN4XL0tHqHf/XY73edOAOeFOG15yb4Yx+aNuZgkgBPky6lgYOZtGTdcBRIM7ElT87R8q6GsLgne/3d2+THI64dBA4RcDSFFPV1br1sWw28f5Mo9GnlRoOgwjMHm9QvR99CRSmssKTRTmcuSjv2wXD4HHgZHwGjTUytCPAthuZbJYaQAp+gSlpGAIK7VJ/nyCKqpQTMn1RLvLi1fNNJ0h8Ad/Bd0qhwI01ZKnw==\"}}",109432497774090692,"https://pl.nudie.social/inbox",{"synchronize_followers":false}],"jid":"50b1eddebca05bfaa0cfd24c","created_at":1721802363.8419402,"enqueued_at":1721953658.809028,"error_message":"https://pl.nudie.social/inbox","error_class":"Stoplight::Error::RedLight","failed_at":1721802365.1981168,"retry_count":13,"retried_at":1721948116.9540164}}
WARN: Stoplight::Error::RedLight: https://pl.nudie.social/inbox
WARN: /usr/local/bundle/gems/stoplight-4.1.0/lib/stoplight/light/runnable.rb:70:in `run_red'
WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"pull","class":"LinkCrawlWorker","args":[112740566418776817],"jid":"7dd3f1b55c7926280263b7c4","created_at":1720284521.778055,"enqueued_at":1721953650.7105236,"error_message":"undefined method `match' for an instance of Array","error_class":"NoMethodError","failed_at":1720284564.6333208,"retry_count":-1,"retried_at":1721915871.805101}}
WARN: NoMethodError: undefined method `match' for an instance of Array
WARN: /opt/mastodon/lib/paperclip/response_with_limit_adapter.rb:55:in `filename_from_content_disposition'
```

```
WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"ingress","backtrace":true,"args":[109877177845109898,"{\"@context\":\"https://www.w3.org/ns/activitystreams\",\"id\":\"https://app.wafrn.net/fediverse/post/12a4a73b-b934-4dd1-be45-9d80fa7fa014\",\"type\":\"Announce\",\"actor\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"published\":\"2024-07-16T07:57:04.000Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"cc\":[\"https://app.wafrn.net/fediverse/blog/gabboman\",\"https://app.wafrn.net/fediverse/blog/gabboman/followers\"],\"object\":null,\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"domain\":\"app.wafrn.net\",\"nonce\":\"f82dd19022e92ee0d1595bf5c913f16a\",\"created\":\"2024-07-16T07:57:04.000Z\",\"signatureValue\":\"dr6NgioeRQcwGlT2b7gu7ptBcq5+oic7bTrbQM6MTYu0udfuvwZiFCG1p92Fj/9wgudnFsCo5DOVIxFjLSt53VMBfWah5Mvtchx8ccxd9RHGH16gan0AqMxizoOhQ1J/h0KSf1Wft7qX6hJnJvUlwCvVKrW0TorKJhqyWeK4xdXNWBar0akcfshDhyvv6UtoJmb0jGOs1SwOkMtusP+ZrEgSY4tbVAXeCy4StiMGrmkd7ecE1HkYzZ5QaCXPB+XLd/fKJzMvjVrKXU/aD5lEijSU++Xaw3xeK6e0hz951diZuLSbMG82tziWF1G6JNocveY3mloU6hxRYgCgMoAsmjgNlwg0m/q3C1c23PJ66+j5Nqp1KZkek4OqCGKfz184ZYPQL0k+ougJfnJPVCfUuhtMIsy+3dElsAjlWDMXBnZYeGuvjdsbORP9tvYTHabjQnfJWGv3MiQvq3URgT69mnYi4NLvfsFVuH4PO/42dMP7VZXGK3/Ry+UGguutiEafPwcCBhwuTWpOXh44OWG7MoF+OWh6mOMYSEdav/4tQpbD1nZlgZn6hcFCaTGPbFk6QInWfReWJka5Sokhe7Uau0raLDhF8kxuuvwU58Kyer/YWR1Hnb/lA+Gn/hQZqC/RX6D64KhhgliatWfMMAUYAYQQrVx4gKb4/5+mzf0LMkM=\"}}",null,"Account"],"class":"ActivityPub::ProcessingWorker","jid":"bcd1ff0765a24793a5559682","created_at":1721116630.8439643,"enqueued_at":1721953650.1529055,"error_message":"undefined method `[]' for nil","error_class":"NoMethodError","failed_at":1721116630.8505385,"retry_count":7,"error_backtrace":"eJzNmNty2jAQhl8lk5u0M8XGNtghN32QTseV7cUoyJIiydC8fXUwYDuQgKPM\n9A6Q9O1qtf+uxK/7kHEVNkgqVjEaIs5DgosQlQrvsHrl7elzIIqnx+QJ07s/\nsuWcCQVVzopnKFWuZ8LPh/sfN+KylcW11Bcwmi+dgwqpVuZrwZqOeBsrRJSy\nlpZgN22RBWHl9k5/4iDWTDTngQ2rgMiwZHqtoDI0i1BBLCeKe6Bv8R2BnZ77\n3TD3WG1yARWWuRm17FYKsxyRsGhpRSCsoZHamsBsZqfOzNRZFMRBZDdyWm+s\nLRbWGipfWixggrfz4bavd1HjqI44ZjTnjJFZHCw6D0cj1szAztuoeLMzd7m2\nQQaQY6pAiJYr3/xBvPzB0y923vGPPp8Vijt8vXyN61YgQ+glyuW14yyznEOa\nrY6LXXLdnqhjwik9p8k9s7x3VS5B7HAJcgDjgumfTIAI6eLbzTPU1FWRwySs\nwB97OUq9vpELAZ1uRWh9Cgk5oPLCeU9nfwVzjYlWS94g7pv8NWFOXKJoPZPz\nzD0TW30C55CY1rkbtsJM32Ty+VohcQVb/DJLg2UQxVYl3U8HMLPAeO46GPyF\nslWQP7PCAzXKLneAbuI0Kw2u9LQ9EhCWG4RdscqyoVYw3bEtXGGgpfilhZne\ns5xlQRQkSd9Y7oZNSGTPsD3QdHignvaxunEf5Qb2r9rzNJi7NmC+h1LpQg61\nvTylXSEXnVRu4FiXllF393LIt9lrph+/HAI3DFb2X8TqVgOPThef4Q4lkZ6v\n6D7QXTp2akv7atPNkyNVvndteceMTn3dgJVwyRC5l4IleHF72Xd76c9tgTCR\n1sRiGPMPktCWX+geLq4iBIvTDQPybkhfdwhDlSvJ4+rzgdautuEqsukkhsid\nsVV8jZ6n7WNxDfqqqCefVPwoTaJ+miz8pcmwEabJ8ZnpRZTxQJSJX1ESVtfd\njcBvsOPlxcbtsZQ8urZUE1b4KSXxSOg+I5wcrobAkfDSCmJ3Zh6zNxq+RTwQ\ns+HjhlEfO++8FC2dBitZw7UnVJ3+w9mbCFas9gCMRpVcojXkaiMAVQ/3v/8B\n2ZjWBg==\n","retried_at":1721915859.872834}}
WARN: NoMethodError: undefined method `[]' for nil
WARN: /opt/mastodon/app/lib/activitypub/activity.rb:83:in `supported_object_type?'
```

### Motivation

bugs

**Comment by shleeable** [comment]
@oneiros

**Comment by shleeable** [comment]
```
WARN: {"context":"Job raised exception","job":{"retry":8,"queue":"ingress","backtrace":true,"args":[110550865959248525,"{\"@context\":[\"https://join-lemmy.org/context.json\",\"https://www.w3.org/ns/activitystreams\"],\"actor\":\"https://programming.dev/c/programming\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\"],\"object\":{\"id\":\"https://feddit.de/activities/like/ef50f6be-bd41-4ea3-a733-2dea8434a616\",\"actor\":\"https://feddit.de/u/sinokon\",\"@context\":[\"https://join-lemmy.org/context.json\",\"https://www.w3.org/ns/activitystreams\"],\"object\":\"https://lemmy.world/comment/11311806\",\"type\":\"Like\",\"audience\":\"https://programming.dev/c/programming\"},\"cc\":[\"https://programming.dev/c/programming/followers\"],\"type\":\"Announce\",\"id\":\"https://programming.dev/activities/announce/like/3ffcf7a9-a031-4009-b6cb-b760b3737e31\"}",null,"Account"],"class":"ActivityPub::ProcessingWorker","jid":"3289519c9b0828878678952f","created_at":1721663330.4793987,"enqueued_at":1721953650.2959366,"error_message":"failed to connect: No address for feddit.de on https://feddit.de/activities/like/ef50f6be-bd41-4ea3-a733-2dea8434a616","error_class":"HTTP::ConnectionError","failed_at":1721663334.2615414,"retry_count":7,"error_backtrace":"eJyLVtLPLyjRz00sLslPyc/TTywo0M/JTNIvSi0sTS0u0StKsjI2MrHKzFNI\nyC9IzVNXigUAx8ERYA==\n","retried_at":1721915850.7136538}}
WARN: HTTP::ConnectionError: failed to connect: No address for feddit.de on https://feddit.de/activities/like/ef50f6be-bd41-4ea3-a733-2dea8434a616
WARN: /opt/mastodon/app/lib/request.rb:324:in `open'
WARN: {"context":"Job raised exception","job":{"retry":0,"queue":"pull","class":"LinkCrawlWorker","args":[112776579050109635],"jid":"2a0af0f38c07b1cda427b2bd","created_at":1720834031.0702124,"enqueued_at":1721953650.054277,"error_message":"PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding \"UTF8\": 0xed 0xa0 0xbd\nCONTEXT:  unnamed portal parameter $3\n","error_class":"ActiveRecord::StatementInvalid","failed_at":1720834058.785555,"retry_count":-1,"retried_at":1721915863.7112637}}
WARN: ActiveRecord::StatementInvalid: PG::CharacterNotInRepertoire: ERROR:  invalid byte sequence for encoding "UTF8": 0xed 0xa0 0xbd
WARN: /usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
```
