### ISSUE TITLE
Aws::S3::Errors::NoSuchKey on tootctl media remove-orphans --fix-permissions

### ISSUE THREAD

**Issue by p37307** [mastodon/mastodon#31181]
### Steps to reproduce the problem

1. run command tootctl media remove-orphans --fix-permissions

### Expected behaviour

Remove orphans and fix ACL permissions

### Actual behaviour

errors out and stops

### Detailed description

Trying to fix acl permissions after moving my object storage. Everything is configured and working, ie new files are public viewable going forward. 

I needed to fix permissions, so I ran `s3cmd setacl s3://BUCKETNAME/ --acl-public --recursive` by itself, and it works but it errors out 404 nosuchkey after a certain point. 

DigitalOcean checked into it one particular file that errored out and found, _Looking at our logs, the file 'redacted' was uploaded and then immediately deleted. This file was uploaded using 'aws-sdk-ruby3/3.181.0' using the Access Key REDACTED_

I ended up running `s3cmd set acl` on individual folders instead of all at once and made some progress getting accounts, avatars, etc permissions set but with the files scattered here and there, it's a tedious operation. 

So, I figured I would run `tootctl media remove-orphans --fix-permissions` and fix acl permission that way.

It errored out also at the  _46634/??_ progress point.

Previous issues https://github.com/mastodon/mastodon/issues/23278 and https://github.com/mastodon/mastodon/issues/22981#issuecomment-1386194288 don't seem to apply to me

### Mastodon version

v4.2.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: v20.8.0
- Debian 11, 
- S3CMD V 2.1.0 (apparently from backports)

screen output:
```
mastodon@server1:~/live$ RAILS_ENV=production bin/tootctl media remove-orphans --fix-permissions
Unrecognized file found: accounts/headers/109/488/640/979/680/621/c327bd1e64c11dde.jpg
Found and removed orphan: cache/accounts/avatars/110/802/675/219/272/895/original/c7b94bd52938f44e.jpg
Unrecognized file found: cache/accounts/avatars/111/432/953/321/882/785/
Found and removed orphan: cache/accounts/avatars/111/432/953/321/882/785/original/3a7d4c61d02a0237.jpg
Unrecognized file found: cache/accounts/avatars/111/432/956/
Unrecognized file found: cache/accounts/avatars/111/432/956/221/
Found and removed orphan: cache/accounts/avatars/111/432/956/221/172/
Unrecognized file found: cache/accounts/avatars/111/432/956/221/172/785/
Unrecognized file found: cache/accounts/avatars/111/432/956/221/172/785/original/
Found and removed orphan: cache/accounts/avatars/111/432/956/221/172/785/original/3a7d4c61d02a0237.jpg
_**Runs awhile removing orphans**_
Found and removed orphan: cache/accounts/headers/112/400/029/545/495/901/original/bb624a413e2f2a19.png
/home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call': Aws::S3::Err                                                ors::NoSuchKey (Aws::S3::Errors::NoSuchKey)
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/dualstack.rb:21:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/plugins/accelerate.rb:43:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/checksum_algorithm.rb:111:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:16:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/request_callback.rb:89:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/seahorse/client/request.rb:72:in `send_request'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/client.rb:13066:in `put_object_acl'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object_acl.rb:322:in `block in put'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.181.0/lib/aws-sdk-core/plugins/user_agent.rb:28:in `feature'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/aws-sdk-s3-1.133.0/lib/aws-sdk-s3/object_acl.rb:321:in `put'
        from /home/mastodon/live/lib/mastodon/cli/media.rb:125:in `block (2 levels) in remove_orphans'
        from /home/mastodon/live/lib/mastodon/cli/media.rb:124:in `each'
        from /home/mastodon/live/lib/mastodon/cli/media.rb:124:in `block in remove_orphans'
        from /home/mastodon/live/lib/mastodon/cli/media.rb:110:in `loop'
        from /home/mastodon/live/lib/mastodon/cli/media.rb:110:in `remove_orphans'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:116:in `invoke'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:338:in `block in subcommand'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/thor-1.3.1/lib/thor/base.rb:584:in `start'
        from bin/tootctl:9:in `block in <main>'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy/strategy.rb:60:in `wrap'
        from /home/mastodon/live/vendor/bundle/ruby/3.2.0/gems/chewy-7.3.4/lib/chewy.rb:154:in `strategy'
        from bin/tootctl:8:in `<main>'
```

**Comment by ThisIsMissEm** [comment]
It looks like we should be catching `Aws::S3::Errors::NoSuchKey` and treating it as a "successfully removed" case.

So we probably need to add a rescue here: https://github.com/mastodon/mastodon/blob/main/lib/mastodon/cli/media.rb#L141-L150

e.g.,

```ruby
            begin
              object.delete unless dry_run?

              reclaimed_bytes += object.size
              removed += 1

              progress.log("Found and removed orphan: #{object.key}")
            rescue Aws::S3::Errors::NoSuchKey
              removed += 1
              progress.log(pastel.yellow("File no longer exists for orphan #{object.key}"))
            rescue => e
              progress.log(pastel.red("Error processing #{object.key}: #{e}"))
            end
```

Though I'm not sure if this should also update the MediaAttachment to delete the record of it?

**Comment by ThisIsMissEm** [comment]
That said, it looks like we also need to begin/rescue on 
```ruby
object.acl.put(acl: s3_permissions) if options[:fix_permissions] && !dry_run?
```
