### ISSUE TITLE
Invalid request leads to printing request body to logs

### ISSUE THREAD

**Issue by knightpp** [mastodon/mastodon#31410]
### Steps to reproduce the problem

I developed an Elixir app, but while testing it, some requests lead to excessive logging. 
When I try to send media(an image or video) to /api/v2/media, my requests fail with status 400 and no body. And the server logs/prints the whole request body.

### Expected behaviour

logs should not print form/multi-part file bodies

### Actual behaviour

I see really long gibberish in logs

### Detailed description

Here's netcat output of the request I make to server. 

```
POST /api/v2/media HTTP/1.1
host: 127.0.0.1:1234
accept-encoding: gzip
authorization: Bearer <token>
content-length: 119103
content-type: multipart/form-data; boundary=ff58db136f38dd3736c9d5a98d79d6c0
user-agent: <Some name>


--ff58db136f38dd3736c9d5a98d79d6c0
content-disposition: form-data; name="file"
--ff58db136f38dd3736c9d5a98d79d6c0--
```

Here's the output of mastodon server
```
redis-1      | 1:M 13 Aug 2024 20:01:46.100 * 100 changes in 300 seconds. Saving...
web-1        | [0dbac559-6c5a-4346-b354-c07b5350fbf3]   
redis-1      | 1:M 13 Aug 2024 20:01:46.104 * Background saving started by pid 449
redis-1      | 449:C 13 Aug 2024 20:01:46.213 * DB saved on disk
redis-1      | 449:C 13 Aug 2024 20:01:46.214 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 0 MB
web-1        | [0dbac559-6c5a-4346-b354-c07b5350fbf3] config/initializers/rack_attack.rb:61:in `paging_request?'
web-1        | [0dbac559-6c5a-4346-b354-c07b5350fbf3] config/initializers/rack_attack.rb:94:in `block in <class:Attack>'
web-1        | [0dbac559-6c5a-4346-b354-c07b5350fbf3] lib/public_file_server_middleware.rb:18:in `call'
redis-1      | 1:M 13 Aug 2024 20:01:46.318 * Background saving terminated with 
# see here
web-1        | F, [2024-08-13T19:53:54.116156 #21] FATAL -- : [807be4c0-12cb-4d1d-b4a8-a4bb2a8c3780]   
web-1        | [807be4c0-12cb-4d1d-b4a8-a4bb2a8c3780] ActionController::BadRequest (Invalid request parameters: Invalid encoding for parameter: ����
web-1        | 8k9������=����f�t�S��y��g�~C$�H:N���d�	$5��'?F��sx{��K���j�����y�����-��c�\;�-Q��*��E*ڨ�Zz���T�J���U��ⲫ&Yz�-=T�d^�J�J��p�ٓ;��Bd�n�����F���6P+.��	�P�dӦ@� t�;;I!�M$�$�$�$�:���'@��$�&��i�"�q�y��W=�uj-3
web-1        | �T:��]���Ѣ�(��F�;���Y:u�j��)x�f0,	K���Z!�K�ڵ3�u��̝�I�$	$��ɲt��Uc�4i:�ߟ݃�iF����s�7��Km��un����:3B���I$�I����:�I���2t�:@�@� I I83�$��$�$��q��S꧂Ǖ鰚�#�'H���l��nmw�2t$��I���I���I��$�$�;!$�:pgww@��:�w��ru��J��	}2��oϩ�1�������D��i�2ڣ���q�h�n�D<*2�N����
...
and it continues ...
```

Here's netcat of working curl request
```
POST /api/v2/media HTTP/1.1
Host: 127.0.0.1:1234
User-Agent: curl/8.7.1
Accept: */*
Authorization: Bearer <token>
Content-Length: 119181
Content-Type: multipart/form-data; boundary=------------------------a0eNK0HdV4yaKwRyAH8E2F

--------------------------a0eNK0HdV4yaKwRyAH8E2F
Content-Disposition: form-data; name="file"; filename="thumbnail.jpg"
Content-Type: image/jpeg

--------------------------a0eNK0HdV4yaKwRyAH8E2F--
```

### Mastodon version

v4.2.10

### Technical details

I use official docker image: v4.2.10
- Rails 7.0.8.4
- ruby 3.2.3-p157

**Comment by knightpp** [comment]
Further testing revealed that sending a request to media api with `filename` succeeds.

So it is the absence of `filename` in content disposition, that leads to the mentioned issue.

**Comment by mjankowski** [comment]
Thanks for following up your own thing. I'm going to close this on the assumption there's not actually anything to resolve here?

**Comment by knightpp** [comment]
If it's still not fixed, anyone registered on a server can spam the instance's logs by making this request. But OK, whatever 🤷
