### ISSUE TITLE
11111

### ISSUE THREAD

**Issue by qiancsff** [mastodon/mastodon#31660]
### Steps to reproduce the problem

1.
2.
3.
...
1

### Expected behaviour

1

### Actual behaviour

1

### Detailed description

1

### Mastodon instance

1

### Mastodon version

1

### Browser name and version

1

### Operating system

1

### Technical details

1

**Comment by qiancsff** [comment]
Do you want to create an admin user straight away? Yes
Username: admin
E-mail: qiancsf@gmail.com
rake aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email" (ActiveRecord::RecordNotUnique)
DETAIL:  Key (email)=(qiancsf@gmail.com) already exists.
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `block in exec_no_cache'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:153:in `exec_insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:83:in `exec_insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:191:in `insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:25:in `insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:588:in `_insert_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1252:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/counter_cache.rb:187:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/locking/optimistic.rb:84:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/encryption/encryptable_record.rb:184:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/attribute_methods/dirty.rb:240:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:445:in `block in _create_record'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:110:in `run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:445:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:114:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1221:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/autosave_association.rb:375:in `around_save_collection_association'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:125:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:718:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:49:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:309:in `block in save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:309:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:52:in `save'
/opt/mastodon/lib/tasks/mastodon.rake:555:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'

Caused by:
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_email" (PG::UniqueViolation)
DETAIL:  Key (email)=(qiancsf@gmail.com) already exists.
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1028:in `block in with_raw_connection'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1000:in `with_raw_connection'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:893:in `block in exec_no_cache'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/notifications/instrumenter.rb:58:in `instrument'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract_adapter.rb:1143:in `log'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:892:in `exec_no_cache'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql_adapter.rb:872:in `execute_and_clear'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:64:in `internal_exec_query'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:153:in `exec_insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:83:in `exec_insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:191:in `insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/query_cache.rb:25:in `insert'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:588:in `_insert_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1252:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/counter_cache.rb:187:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/locking/optimistic.rb:84:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/encryption/encryptable_record.rb:184:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/attribute_methods/dirty.rb:240:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:445:in `block in _create_record'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:110:in `run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_create_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:445:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:114:in `_create_record'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:1221:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `block in create_or_update'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/autosave_association.rb:375:in `around_save_collection_association'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:130:in `block in run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:141:in `run_callbacks'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/callbacks.rb:952:in `_run_save_callbacks'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/callbacks.rb:441:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/timestamp.rb:125:in `create_or_update'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/persistence.rb:718:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/validations.rb:49:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:309:in `block in save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:365:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/bundle/gems/activesupport-7.1.3.4/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/transactions.rb:309:in `save'
/usr/local/bundle/gems/activerecord-7.1.3.4/lib/active_record/suppressor.rb:52:in `save'
/opt/mastodon/lib/tasks/mastodon.rake:555:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:25:in `load'
/usr/local/bin/bundle:25:in `<main>'
Tasks: TOP => mastodon:setup
(See full trace by running task with --trace)

**Comment by collex100** [comment]
I get the same result when I use the installation from the source.  
https://docs.joinmastodon.org/admin/install/

And I can't even run docker-compose.
https://github.com/mastodon/mastodon/discussions/31678

Please share which startup instruction you use for docker-compose. Thanks!

**Comment by vmstan** [comment]
@qiancsff  Is this still an issue for you?
