### ISSUE TITLE
Received statuses without blurhash fail to process with error: `NoMethodError: undefined method `RangeError' for an instance of Paperclip::BlurhashTranscoder1st

### ISSUE THREAD

**Issue by rrgeorge** [mastodon/mastodon#32096]
### Steps to reproduce the problem

1. Receive status that has an attachment, but doesn't have a blurhash
2. Check sidekiq morgue
3. Find failed job with error: NoMethodError: undefined method `RangeError' for an instance of Paperclip::BlurhashTranscoder

### Expected behaviour

The status should be processed

### Actual behaviour

It is not processed

### Detailed description

Example job:
Job: `ActivityPub::ProcessingWorker`
Arguments:
```
109885469574931519, "{\"@context\":[\"https://www.w3.org/ns/activitystreams\",\"https://app.wafrn.net/contexts/litepub-0.1.jsonld\"],\"id\":\"https://app.wafrn.net/fediverse/activity/post/2937ac3b-c245-4c44-83a2-e4eb53d23919\",\"type\":\"Create\",\"actor\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"published\":\"2024-09-25T13:35:21.000Z\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\",\"https://app.wafrn.net/fediverse/blog/gabboman/followers\"],\"cc\":[],\"object\":{\"id\":\"https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919\",\"actor\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"type\":\"Note\",\"published\":\"2024-09-25T13:35:21.000Z\",\"url\":\"https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919\",\"attributedTo\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"to\":[\"https://www.w3.org/ns/activitystreams#Public\",\"https://app.wafrn.net/fediverse/blog/gabboman/followers\"],\"cc\":[],\"atomUri\":\"https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919\",\"attachment\":[{\"type\":\"Document\",\"mediaType\":\"image/avif\",\"url\":\"https://media.wafrn.net/1727271309078_a9d33cf06db803e254bec2e5f2ca9bd5c0cbf9d6_processed.webp\",\"sensitive\":false,\"name\":\"burning text: IT'S PRACTICALY HALLOWEEN\"}],\"tag\":[],\"replies\":{\"id\":\"https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919/replies\",\"type\":\"Collection\",\"first\":{\"type\":\"CollectionPage\",\"partOf\":\"https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919/replies\",\"items\":[]}}},\"signature\":{\"type\":\"RsaSignature2017\",\"creator\":\"https://app.wafrn.net/fediverse/blog/gabboman\",\"domain\":\"app.wafrn.net\",\"nonce\":\"bb1d284dd88be15a866cc46413e6d705\",\"created\":\"2024-09-25T13:35:21.000Z\",\"signatureValue\":\"G/+P65XqUPw/Ow5EHQZHtnf1cXeaGvxl6w7r2MXZfrWXw3bOSNQPuR18oTwpu9Imq9A0yewoA1Nle1+Dogs9gnjVdYF0izqA7wlXxKDG7q7nfTtbfHkAcRwVpRGhrtl8usKJXl1kzI4kelkpeE/nxgOmuVVZ5AczwvLh2LmOkVN6MIh8FMKN3tHive8y75SxrpYfjZ2ILPSYgMFxk99wiuOtd5lVE1z7h+SktEV6qcQMPj2NA02+81N/6tRBbWAATdc59YWlIzJMxTKNUtzIeAEH1nxBdm3DGxz8LWus/2ifm5tHDGg1KqAPH4wfjlwcyFYlWW2UMCBfJuK4nRZ6Wg+uSAmO/9HFANLnKp1+VjGx99YGyU85d8IJCH12JFya76W9jWGUc9ClmtNs6gMwJiG1HLqw1uvEgbel9Y76mc6eiCda04QNbCekWBOWYZgyoFVFRzc8jeb2Bnfd/gACL7RB4U5ZAK2NJE+4Z7xfshg7xjWVUKSDNW/kYaW1vt+YFHdKmnekaQgi1zEJ405dSySSkaYPCahwPl+psvYKnwfg0OamsI/DfpO9kGrPwzYuWAG9qEx/W1wWXTvfio4C0brmSU2SlMHcke0p3I8s89Kbk3uOY5IulXL1ITs6zg5LV0y+oKExD4lyiL+c+X2oyTOuAcArN49646w2j8iTYfU=\"}}", nil, "Account"
```
Stack trace:
```
/home/mastodon/live/lib/paperclip/blurhash_transcoder.rb:10:in `make'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/kt-paperclip-7.2.2/lib/paperclip/processor.rb:33:in `make'
/home/mastodon/live/lib/paperclip/attachment_extensions.rb:21:in `block in post_process_style'
```

### Mastodon instance

raphus.social

### Mastodon version

v4.3.0-beta2

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- Node.js version: v20.5.1

**Comment by ClearlyClaire** [comment]
I am unable to reproduce. Can you reproduce it with the same status (`https://app.wafrn.net/fediverse/post/2937ac3b-c245-4c44-83a2-e4eb53d23919`)? Are you using libvips or ImageMagick?

**Comment by ClearlyClaire** [comment]
Quoting the OP from another channel:
> I am still using imagemagick.

Upon investigation, the media attachment from that post is an animated WEBP, which goes through our processing pipeline as if it were a static image. In that situation, the call to ImageMagick for computing blurhash raises more pixels that there is in the first frame of the image alone.

**Comment by hoshinolina** [comment]
FWIW, trying to do a media refresh on vt.social, a significant fraction of the remaining failing attachments are hitting this.
