### ISSUE TITLE
sidekiq: failed to set redis sentinel username and connect to sentinel

### ISSUE THREAD

**Issue by delgh1** [mastodon/mastodon#32264]
### Steps to reproduce the problem

1. set up redis sentinel instances
2. configure mastodon to use redis sentinel with user specified

### Expected behaviour

connect to redis sentinel successfully

### Actual behaviour

error when starting sidekiq, cannot connect to sentinel

### Detailed description

redis sentinel config:

```
...
sentinel monitor redis 192.168.0.191 6379 3
sentinel monitor sidekiq 192.168.0.191 6479 3
sentinel monitor cache 192.168.0.191 6579 3
...
```

mastodon config:

```
REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
REDIS_SENTINEL_MASTER=redis
REDIS_SENTINEL_USER=mastodon
REDIS_SENTINEL_PASSWORD=secret
SIDEKIQ_REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
SIDEKIQ_REDIS_SENTINEL_MASTER=sidekiq
SIDEKIQ_REDIS_SENTINEL_USER=mastodon 
SIDEKIQ_REDIS_SENTINEL_PASSWORD=secret
CACHE_REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
CACHE_REDIS_SENTINEL_MASTER=cache
CACHE_REDIS_SENTINEL_USER=mastodon
CACHE_REDIS_SENTINEL_PASSWORD=secret
```

sidekiq error in systemd-journald:

```
Oct 05 20:22:35 mastodon1 bundle[3111986]: 2024-10-05T11:22:35.401Z pid=3111986 tid=1ujy6 INFO: Booting Sidekiq 6.5.12 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://sidekiq/0", :driver=>:hiredis, :name=>"sidekiq", :sentinels=>[{:host=>"192.168.0.191", :port=>26379}, {:host=>"192.168.0.192", :port=>26379}, {:host=>"192.168.0.193", :port=>26379}], :sentinel_username=>nil, :sentinel_password=>"secret", :namespace=>nil}
Oct 05 20:22:37 mastodon1 bundle[3111986]: 2024-10-05T11:22:37.568Z pid=3111986 tid=1ujy6 INFO: Booted Rails 7.1.4 application in production environment
Oct 05 20:22:37 mastodon1 bundle[3111986]: 2024-10-05T11:22:37.568Z pid=3111986 tid=1ujy6 INFO: Running in ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
Oct 05 20:22:37 mastodon1 bundle[3111986]: 2024-10-05T11:22:37.568Z pid=3111986 tid=1ujy6 INFO: See LICENSE and the LGPL-3.0 for licensing details.
Oct 05 20:22:37 mastodon1 bundle[3111986]: 2024-10-05T11:22:37.571Z pid=3111986 tid=1ujy6 WARN: Redis::CommandError: NOAUTH Authentication required.
Oct 05 20:22:37 mastodon1 bundle[3111986]: 2024-10-05T11:22:37.571Z pid=3111986 tid=1ujy6 WARN: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:162:in `call'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:630:in `block in resolve_master'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:612:in `block in sentinel_detect'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:602:in `each'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:602:in `sentinel_detect'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:629:in `resolve_master'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:591:in `resolve'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:380:in `establish_connection'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:115:in `block in connect'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:344:in `with_reconnect'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:114:in `connect'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:409:in `ensure_connected'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:269:in `block in process'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:356:in `logging'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:268:in `process'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/client.rb:161:in `call'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis.rb:270:in `block in send_command'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis.rb:269:in `synchronize'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis.rb:269:in `send_command'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/redis-4.8.1/lib/redis/commands/server.rb:90:in `info'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/lib/sidekiq.rb:188:in `block in redis_info'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/lib/sidekiq.rb:164:in `block in redis'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:110:in `block (2 levels) in with'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `handle_interrupt'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:109:in `block in with'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `handle_interrupt'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/connection_pool-2.4.1/lib/connection_pool.rb:106:in `with'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/lib/sidekiq.rb:161:in `redis'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/lib/sidekiq.rb:182:in `redis_info'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/lib/sidekiq/cli.rb:86:in `run'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/sidekiq-6.5.12/bin/sidekiq:31:in `<top (required)>'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/bin/sidekiq:25:in `load'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/bin/sidekiq:25:in `<top (required)>'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/.rbenv/versions/3.3.5/bin/bundle:25:in `load'
Oct 05 20:22:37 mastodon1 bundle[3111986]: /home/mastodon/.rbenv/versions/3.3.5/bin/bundle:25:in `<main>'
Oct 05 20:22:37 mastodon1 systemd[1]: mastodon-sidekiq.service: Main process exited, code=exited, status=1/FAILURE
Oct 05 20:22:37 mastodon1 systemd[1]: mastodon-sidekiq.service: Failed with result 'exit-code'.
Oct 05 20:22:37 mastodon1 systemd[1]: mastodon-sidekiq.service: Consumed 4.909s CPU time, 230.9M memory peak.
```

highlight: `sentinel_username=>nil`, but the issue doesn't seem to be limited to sidekiq.

### Mastodon instance

https://mastodon.jing.lgbt

### Mastodon version

v4.3.0-rc1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- Node.js version: v20.17.0

(debian testing)

**Comment by oneiros** [comment]
Thanks for reporting this (and thanks for trying out this brand new feature - we have not had much feedback on this yet and could not yet make use of it in a full-fledged production setting ourselves).

I am very sorry to say that you encountered a typo in our docs. The environment variables to set the username all actually end on `_USERNAME` and not just `_USER`.

I tried to fix this here https://github.com/mastodon/documentation/pull/1540

**Comment by oneiros** [comment]
So the ruby side of things works now, but you still get the error from the streaming server?

**Comment by delgh1** [comment]
> So the ruby side of things works now, but you still get the error from the streaming server?

Ah no, not working, but `sentinel_username=>nil` became `sentinel_username=>mastodon`, I still got `Redis::CommandError: NOAUTH Authentication required.`

**Comment by oneiros** [comment]
Closing this in favor of #32265 as that has more details.
