### ISSUE TITLE
streaming api: failed to connect to redis sentinel

### ISSUE THREAD

**Issue by delgh1** [mastodon/mastodon#32265]
### Steps to reproduce the problem

1. set up redis sentinel instances
2. configure mastodon to use redis sentinel with user specified

### Expected behaviour

connect to redis sentinel successfully

### Actual behaviour

error when starting streaming api services, cannot connect to sentinel

### Detailed description

redis sentinel config (default user is off):

```
...
sentinel monitor redis 192.168.0.191 6379 3
sentinel monitor sidekiq 192.168.0.191 6479 3
sentinel monitor cache 192.168.0.191 6579 3
...
```

redis sentinel info:

```
# Sentinel
sentinel_masters:3
sentinel_tilt:0
sentinel_tilt_since_seconds:-1
sentinel_running_scripts:0
sentinel_scripts_queue_length:0
sentinel_simulate_failure_flags:0
master0:name=cache,status=ok,address=192.168.0.191:6579,slaves=7,sentinels=4
master1:name=sidekiq,status=ok,address=192.168.0.191:6479,slaves=7,sentinels=4
master2:name=redis,status=ok,address=192.168.0.191:6379,slaves=7,sentinels=4
```

mastodon config:

```
REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
REDIS_SENTINEL_MASTER=redis
REDIS_SENTINEL_USER=mastodon
REDIS_SENTINEL_PASSWORD=secret
SIDEKIQ_REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
SIDEKIQ_REDIS_SENTINEL_MASTER=sidekiq
SIDEKIQ_REDIS_SENTINEL_USER=mastodon 
SIDEKIQ_REDIS_SENTINEL_PASSWORD=secret
CACHE_REDIS_SENTINELS=192.168.0.191,192.168.0.192,192.168.0.193
CACHE_REDIS_SENTINEL_MASTER=cache
CACHE_REDIS_SENTINEL_USER=mastodon
CACHE_REDIS_SENTINEL_PASSWORD=secret
```

`journalctl -eu mastodon-streaming@4000`:

```
...
Oct 05 20:29:18 mastodon1 node[3112978]: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
Oct 05 20:29:18 mastodon1 node[3112978]: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
Oct 05 20:29:18 mastodon1 node[3112978]: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
Oct 05 20:29:18 mastodon1 node[3112978]: [WARN] This Redis server's `default` user does not require a password, but a password was supplied
Oct 05 20:29:18 mastodon1 node[3112978]: {"level":"error","time":1728127758801,"pid":3112978,"hostname":"mastodon1","name":"streaming","err":{"type":"Error","message":"All sentinels are unreachable. Retrying from scratch after 580ms. Last error: ERR No such master with that name","stack":"Error: All sentinels are unreachable. Retrying from scratch after 580ms. Last error: ERR No such master with that name\n    at connectToNext (/home/mastodon/live/node_modules/ioredis/built/connectors/SentinelConnector/index.js:64:31)\n    at connectToNext (/home/mastodon/live/node_modules/ioredis/built/connectors/SentinelConnector/index.js:117:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"},"msg":"Redis Client Error!"}
```

I have no idea why it says `ERR No such master with that name`.

### Mastodon instance

https://mastodon.jing.lgbt

### Mastodon version

v4.3.0-rc1

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
- Node.js version: v20.17.0

(debian testing)

**Comment by oneiros** [comment]
I am not 100% sure. It kind of looks like it could be a different issue but could you try if the solution to #32264 fixes this here as well?

**Comment by delgh1** [comment]
Hi, yes now it's a different error:

`journalctl -ue mastodon-streaming@4000`

```
Oct 07 21:17:44 mastodon2 node[52619]: {"level":"error","time":1728303464234,"pid":52619,"hostname":"mastodon2","name":"streaming","err":{"type":"ReplyError","message":"NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"info","args":[]}},"msg":"Redis Client Error!"}
...
...and we have "All sentinels are unreachable."
```

`journalctl -ue mastodon-sidekiq`

```
Oct 07 21:17:10 mastodon2 bundle[52772]: 2024-10-07T12:17:10.886Z pid=52772 tid=15rc INFO: Booting Sidekiq 6.5.12 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://mastodon:REDACTED@sidekiq/0", :driver=>:hiredis,
... (this time we have correct username)
Oct 07 21:17:12 mastodon2 bundle[52772]: 2024-10-07T12:17:12.899Z pid=52772 tid=15rc WARN: Redis::CommandError: NOAUTH Authentication required.
(traceback)
```

It seems that I need to set both `*REDIS_SENTINEL_USERNAME` and `*REDIS_USER`, both `*REDIS_SENTINEL_PASSWORD` and `*REDIS_PASSWORD`, so I did. Also I carefully checked redis acl and sentinel's acl. redis acl looks like this:

```
user mastodon +@all -@admin -@dangerous +info ~* &* on >secret
```

then sentinel's acl looks like this:

```
user mastodon -@all +auth +command +hello +ping +sentinel|get-master-addr-by-name +sentinel|master +sentinel|masters +sentinel|replicas +sentinel|sentinels +sentinel|is-master-down-by-addr on >secret
```

If I use the redis-cli I can auth/login as `mastodon` and do things. But apparently not for mastodon-sidekiq or mastodon-streaming.

I also checked `ACL LOG` on redis and sentinel instances, but I didn't find anything related.

**Comment by oneiros** [comment]
I fear there is a lot to unpack here (and I am not a redis expert either, sorry).

Both redis and sentinel can be used without any form of authentication (of course that is not recommended on a non-private network). Both can be used with authentication (password-only or username and password in newer versions). In that case, both could have the same credentials, but they could also use different ones.

This also means you could have a mixed setup where e.g. the sentinels require authentication and redis itself does not. Or the other way around.

(To make matters worse (?) if you specify `REDIS_USER` and `REDIS_PASSWORD` we assume those as defaults for `REDIS_SENTINEL_USERNAME` and `REDIS_SENTINEL_PASSWORD`. Not sure if that is really sensible, but I guess we should not make using no authentication in a distributed setup easy.)

So please have another look at the provided usernames and passwords and make sure you can access the sentinels with the sentinel credentials and the redis instances with the redis credentials.

Or are they identical in your setup?

**Comment by delgh1** [comment]
> Not sure if that is really sensible

I'll leave the design choice to you :) I don't do NOAUTH.

> So please have another look at the provided usernames and passwords and make sure you can access the sentinels with the sentinel credentials and the redis instances with the redis credentials.
> 
> Or are they identical in your setup?

They are identical for the username and password. The difference is only in what commands the user can execute.

Very quickly checked with the supplied username and password in `.env.production`, yes I can access everything on the commandline. I wonder if anyone else can reproduce this.

**Comment by delgh1** [comment]
UPDATE: I trippled checked all redis instances (21) and sentinel instances (7), successfully logged in with the same credentials in `.env.production`. I'm only a little disappointed to see that v4.3.0 was released (an hour ago) before this issue is solved :(

I hope someone in the dev team can reproduce this, should not be hard.

**Comment by oneiros** [comment]
> I'm only a little disappointed to see that v4.3.0 was released (an hour ago) before this issue is solved

I can see how this can be frustrating. On the other hand we need to release this feature at some point, so people can start testing it. The more people try to use it the higher our chances of ironing out the remaining problems. If we manage to fix them, rest assured that these fixes will be in v4.3.1.

> I hope someone in the dev team can reproduce this, should not be hard.

I am sorry to say that I cannot :frowning_face: 

I was able to validate that our current implementation works fine with _some_ setups, but there are too many permutations to be sure we support all of them properly.

Please note that I am not giving up, but I am not sure when I will be able to build a larger test setup (only tested with several sentinels and redis instances running on the same server until now).

In the meantime, if you feel up to it, you might try to start from a simpler setup (e.g. 3 sentinels, 2 redis instances and only use `REDIS_*` variables so all our different use cases use the same settings), see if you can get this working (you should!) and gradually build from there to see when the failure is introduced.

Sorry, that is all I can think of for now.

**Comment by delgh1** [comment]
> > I'm only a little disappointed to see that v4.3.0 was released (an hour ago) before this issue is solved
> 
> I can see how this can be frustrating. On the other hand we need to release this feature at some point, so people can start testing it. The more people try to use it the higher our chances of ironing out the remaining problems. If we manage to fix them, rest assured that these fixes will be in v4.3.1.

True dat

> In the meantime, if you feel up to it, you might try to start from a simpler setup (e.g. 3 sentinels, 2 redis instances and only use `REDIS_*` variables so all our different use cases use the same settings), see if you can get this working (you should!) and gradually build from there to see when the failure is introduced.

Hmm, I might do this over the weekend. I'll let you know. On the other hand I'm also terrified if it turns out to be a skill issue...oh well

> Sorry, that is all I can think of for now.

No, no need to say sorry! You've been very helpful.

**Comment by delgh1** [comment]
hi: this is what I found on my test rig:

unfortunately there seems to be two separately bugs. one is that streaming service will fail to connect to redis with or without sentinel, which I opened another #32467 ; another thing is that at least sidekiq can connect to the redis and sentinel without `REDIS_SENTINEL_MASTER=mymaster`, when the sentinels are monitoring only one master redis. If I put `REDIS_SENTINEL_MASTER=mymaster` there, sidekiq fails to connect to redis.

the test rig setup is written here #32467

**Comment by delgh1** [comment]
with #32467 fixed, here's the config that both sidekiq and streaming work:

```
REDIS_SENTINELS=127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579
REDIS_SENTINEL_USERNAME=mastodon
REDIS_SENTINEL_PASSWORD=mastodon
# so these two are also needed...
REDIS_USER=mastodon
REDIS_PASSWORD=mastodon
```

the config when neither sidekiq nor streaming work:

```
REDIS_SENTINELS=127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579
REDIS_SENTINEL_USERNAME=mastodon
REDIS_SENTINEL_PASSWORD=mastodon
REDIS_SENTINEL_MASTER=mymaster          # -----------------------------> highlight
REDIS_USER=mastodon
REDIS_PASSWORD=mastodon
```

sidekiq error:

```
Oct 15 21:38:49 mastt bundle[3378]: 2024-10-15T12:38:49.019Z pid=3378 tid=39a INFO: Booting Sidekiq 6.5.12 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://mastodon:REDACTED@mymaster/0", :driver=>:hiredis, :name=>"mymaster", :sentinels=>[{:host=>"127.0.0.1", :port=>26379}, {:host=>"127.0.0.1", :port=>26479}, {:host=>"127.0.0.1", :port=>26579}], :sentinel_username=>"mastodon", :sentinel_password=>"mastodon", :namespace=>nil}
Oct 15 21:38:51 mastt bundle[3378]: 2024-10-15T12:38:51.621Z pid=3378 tid=39a INFO: Booted Rails 7.1.4 application in production environment
Oct 15 21:38:51 mastt bundle[3378]: 2024-10-15T12:38:51.621Z pid=3378 tid=39a INFO: Running in ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
Oct 15 21:38:51 mastt bundle[3378]: 2024-10-15T12:38:51.621Z pid=3378 tid=39a INFO: See LICENSE and the LGPL-3.0 for licensing details.
Oct 15 21:38:51 mastt bundle[3378]: 2024-10-15T12:38:51.621Z pid=3378 tid=39a INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
Oct 15 21:38:51 mastt bundle[3378]: 2024-10-15T12:38:51.623Z pid=3378 tid=39a WARN: Redis::CommandError: NOAUTH Authentication required.
...
```

streaming error:

```
Oct 15 21:34:08 mastt node[2967]: {"level":"error","time":1728995648273,"pid":2967,"hostname":"mastt","name":"streaming","err":{"type":"ReplyError","message":"NOAUTH Authentication required.","stack":"ReplyError: NOAUTH Authentication required.\n    at parseError (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/home/mastodon/live/node_modules/redis-parser/lib/parser.js:302:14)","command":{"name":"info","args":[]}},"msg":"Redis Client Error!"}
```

**Comment by adhisimon** [comment]
I confirmed this issue still exists on 4.5.2
