### ISSUE TITLE
NoMethodError (undefined method `attribution_domains=' for an instance of Account):

### ISSUE THREAD

**Issue by r3pek** [mastodon/mastodon#32308]
### Steps to reproduce the problem

Not really sure where it comes from but I have several of this error messages on my server log (just updated to 4.3.0 so I'm not really sure if it's 4.3.0 specific)

```
[8dfec997-7e73-4365-9ddd-bf13f305623c] NoMethodError (undefined method `attribution_domains' for an instance of Account):
[8dfec997-7e73-4365-9ddd-bf13f305623c]   
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/serializers/activitypub/actor_serializer.rb:27:in `block in <class:ActorSerializer>'
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/lib/activitypub/serializer.rb:36:in `serializable_hash'
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/lib/activitypub/adapter.rb:19:in `serializable_hash'
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/controllers/concerns/cache_concern.rb:44:in `render_with_cache'
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/controllers/accounts_controller.rb:33:in `block (2 levels) in show'
[8dfec997-7e73-4365-9ddd-bf13f305623c] app/controllers/accounts_controller.rb:18:in `show'
[8dfec997-7e73-4365-9ddd-bf13f305623c] lib/mastodon/rack_middleware.rb:9:in `call'
[8dfec997-7e73-4365-9ddd-bf13f305623c] lib/public_file_server_middleware.rb:18:in `call'
```
```
[bb5834b8-0092-4414-a11a-6d0597d760af] NoMethodError (undefined method `attribution_domains' for an instance of Account):
[bb5834b8-0092-4414-a11a-6d0597d760af]   
[bb5834b8-0092-4414-a11a-6d0597d760af] app/serializers/activitypub/actor_serializer.rb:27:in `block in <class:ActorSerializer>'
[bb5834b8-0092-4414-a11a-6d0597d760af] app/lib/activitypub/serializer.rb:36:in `serializable_hash'
[bb5834b8-0092-4414-a11a-6d0597d760af] app/lib/activitypub/adapter.rb:19:in `serializable_hash'
[bb5834b8-0092-4414-a11a-6d0597d760af] app/controllers/instance_actors_controller.rb:16:in `show'
[bb5834b8-0092-4414-a11a-6d0597d760af] lib/mastodon/rack_middleware.rb:9:in `call'
[bb5834b8-0092-4414-a11a-6d0597d760af] lib/public_file_server_middleware.rb:18:in `call'
```
```
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] NoMethodError (undefined method `attribution_domains=' for an instance of Account):
[9f9a9bdc-8277-4012-b376-82cd4c6a900b]   
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/process_account_service.rb:119:in `set_immediate_attributes!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/process_account_service.rb:92:in `update_account'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/process_account_service.rb:46:in `block in call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/lib/redis_connection.rb:10:in `with'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/redisable.rb:9:in `with_redis'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:9:in `with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/process_account_service.rb:27:in `call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/fetch_remote_actor_service.rb:38:in `call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/activitypub/fetch_remote_account_service.rb:6:in `call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/resolve_account_service.rb:109:in `block in fetch_account!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:12:in `block (2 levels) in with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:10:in `block in with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/lib/redis_connection.rb:10:in `with'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/redisable.rb:9:in `with_redis'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/concerns/lockable.rb:9:in `with_redis_lock'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/resolve_account_service.rb:108:in `fetch_account!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/services/resolve_account_service.rb:54:in `call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/models/account.rb:243:in `refresh!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/controllers/concerns/signature_verification.rb:250:in `actor_refresh_key!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/controllers/concerns/signature_verification.rb:69:in `block in signed_request_actor'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/controllers/concerns/signature_verification.rb:69:in `signed_request_actor'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] app/controllers/concerns/signature_verification.rb:20:in `require_actor_signature!'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] lib/mastodon/rack_middleware.rb:9:in `call'
[9f9a9bdc-8277-4012-b376-82cd4c6a900b] lib/public_file_server_middleware.rb:18:in `call'
```

Just a few example with different stack traces

### Expected behaviour

No errors on the log

### Actual behaviour

Error messages show

### Mastodon instance

mastodon.r3pek.org

### Mastodon version

v4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]

- Node.js version: v20.18.0

**Comment by Gargron** [comment]
Have you followed instructions for running database migrations?

**Comment by r3pek** [comment]
Yep.... something went wrong with them?

**Comment by r3pek** [comment]
```
I, [2024-10-08T14:16:56.289202 #4]  INFO -- : Migrating to AddURLToPreviewCardsStatuses (20231006183200)
== 20231006183200 AddURLToPreviewCardsStatuses: migrating =====================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:preview_cards_statuses, :url, :string)
   -> 0.0776s
== 20231006183200 AddURLToPreviewCardsStatuses: migrated (0.0801s) ============

I, [2024-10-08T14:16:56.445880 #4]  INFO -- : Migrating to AddIndexToWebauthnCredentialsUserIdNickname (20231018192110)
== 20231018192110 AddIndexToWebauthnCredentialsUserIdNickname: migrating ======
[strong_migrations] DANGER: No lock timeout set
-- add_index(:webauthn_credentials, [:user_id, :nickname], {:unique=>true, :algorithm=>:concurrently, :name=>"index_webauthn_credentials_on_user_id_and_nickname"})
   -> 0.3972s
== 20231018192110 AddIndexToWebauthnCredentialsUserIdNickname: migrated (0.3984s) 

I, [2024-10-08T14:16:56.921441 #4]  INFO -- : Migrating to AddIndexToAccountAliasUriAccountId (20231018193209)
== 20231018193209 AddIndexToAccountAliasUriAccountId: migrating ===============
[strong_migrations] DANGER: No lock timeout set
-- add_index(:account_aliases, [:account_id, :uri], {:unique=>true, :algorithm=>:concurrently, :name=>"index_account_aliases_on_account_id_and_uri"})
   -> 0.2554s
== 20231018193209 AddIndexToAccountAliasUriAccountId: migrated (0.2567s) ======

I, [2024-10-08T14:16:57.291111 #4]  INFO -- : Migrating to AddIndexToCustomFilterStatusesStatusCustomFilter (20231018193355)
== 20231018193355 AddIndexToCustomFilterStatusesStatusCustomFilter: migrating =
[strong_migrations] DANGER: No lock timeout set
-- add_index(:custom_filter_statuses, [:status_id, :custom_filter_id], {:unique=>true, :algorithm=>:concurrently, :name=>"index_custom_filter_statuses_on_status_id_and_custom_filter_id"})
   -> 0.3537s
== 20231018193355 AddIndexToCustomFilterStatusesStatusCustomFilter: migrated (0.3550s) 

I, [2024-10-08T14:16:57.721917 #4]  INFO -- : Migrating to AddIndexToIdentitiesUidProvider (20231018193659)
== 20231018193659 AddIndexToIdentitiesUidProvider: migrating ==================
[strong_migrations] DANGER: No lock timeout set
-- add_index(:identities, [:uid, :provider], {:unique=>true, :algorithm=>:concurrently, :name=>"index_identities_on_uid_and_provider"})
   -> 0.3225s
== 20231018193659 AddIndexToIdentitiesUidProvider: migrated (0.3239s) =========

I, [2024-10-08T14:16:58.097130 #4]  INFO -- : Migrating to AddOtpSecretToUser (20231210154528)
== 20231210154528 AddOtpSecretToUser: migrating ===============================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:users, :otp_secret, :string)
   -> 0.0010s
== 20231210154528 AddOtpSecretToUser: migrated (0.0024s) ======================

I, [2024-10-08T14:16:58.147062 #4]  INFO -- : Migrating to CreateFollowRecommendationMutes (20231211234923)
== 20231211234923 CreateFollowRecommendationMutes: migrating ==================
[strong_migrations] DANGER: No lock timeout set
-- create_table(:follow_recommendation_mutes)
command terminated with exit code 137
```

Maybe it didn't go as expected :thinking:

**Comment by renchap** [comment]
I am not sure what your environment is, but error 137 in container environments/k8s can occur when the pod is killed because it goes over the configured memory limit. I suspect thats the issue, and the migration process is killed before it completes successfuly.

**Comment by r3pek** [comment]
@renchap ah damn! :man_facepalming: yes, this is a k8s pod... it might have crashed because of not having the migrations done yet :frowning_face: 
Any way I can redo the missing migrations?

**Comment by renchap** [comment]
You can re-run the same pod/command and it should resume where it left. I suggest that you increase the memory allowed for this pod, as this seems to be a memory issue.

**Comment by r3pek** [comment]
Doesn't run any thing (maybe the "post-deployment" migrations fixed it?)
Also, `bundle exec rails db:migrate:status` shows everything up

**Comment by r3pek** [comment]
OK, I'm gonna close this as "fixed" because a restart fixed it. Maybe I just forgot to do the last restart after the post-deployment db:migrate :-/

Thanks all

**Comment by renchap** [comment]
Yes, if the post-install migrations ran successfully, it also executed any missing pre-install migrations.

The most likely explanation based on the information you provided is that k8s killed your migration pod due to memory limits.
