### ISSUE TITLE
Error running pre-deployment database migrations to v4.3.0 using PostgreSQL 14.2

### ISSUE THREAD

**Issue by aldatsa** [mastodon/mastodon#32309]
### Steps to reproduce the problem

We were trying to update our Mastodon instance from v4.2.13 to v4.3.0 following the upgrade notes using Docker:
1. git fetch && git checkout v4.3.0
2. docker-compose run --rm web bin/rails db:encryption:init
3. Copy the generated secrets to .env.production
4. docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate
5. An error happened while running the "20231018192110 AddIndexToWebauthnCredentialsUserIdNickname" migration. See details in the detailed description.

### Expected behaviour

The pre-deployment database migrations should run without problems

### Actual behaviour

An error happened when running the pre-deployment database migrations

### Detailed description

> docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web bundle exec rails db:migrate
Starting live_db_1    ... 
Starting live_db_1    ... done
I, [2024-10-08T14:03:17.398710 #7]  INFO -- : Migrating to AddURLToPreviewCardsStatuses (20231006183200)
== 20231006183200 AddURLToPreviewCardsStatuses: migrating =====================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:preview_cards_statuses, :url, :string)
   -> 0.0520s
== 20231006183200 AddURLToPreviewCardsStatuses: migrated (0.0545s) ============
I, [2024-10-08T14:03:17.471864 #7]  INFO -- : Migrating to AddIndexToWebauthnCredentialsUserIdNickname (20231018192110)
== 20231018192110 AddIndexToWebauthnCredentialsUserIdNickname: migrating ======
[strong_migrations] DANGER: No lock timeout set
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)
=== Dangerous operation detected #strong_migrations ===
Adding an index concurrently can cause silent data corruption in Postgres 14.0 to 14.3.
Upgrade Postgres before adding new indexes, or wrap this step in a safety_assured { ... } block
to accept the risk.
/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:31:in `add_index_to_table'
/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:7:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

### Mastodon instance

mastodon.eus

### Mastodon version

v4.2.13

### Technical details

Mastodon installed using Docker, currently running v4.2.13.

postgres -V
postgres (PostgreSQL) 14.2

Should we upgrade to PostgreSQL >= 14.4 before running the migration?

**Comment by aldatsa** [comment]
We upgraded PostgreSQL to 14.13.0, and then the pre-deployment database migrations and everything else went flawlessly. Thank you both for your help @renchap and @roobre!
