### ISSUE TITLE
4.3.0 DB Migrations fail on PostgreSQL 14.3

### ISSUE THREAD

**Issue by hardillb** [mastodon/mastodon#32334]
### Steps to reproduce the problem

1. Run upgrade with PostgreSQL v14.3
```
kubectl -n mastodon logs mastodon-db-migrate-qjlsp
I, [2024-10-08T22:13:18.132471 #1]  INFO -- : Migrating to AddURLToPreviewCardsStatuses (20231006183200)
== 20231006183200 AddURLToPreviewCardsStatuses: migrating =====================
[strong_migrations] DANGER: No lock timeout set
-- add_column(:preview_cards_statuses, :url, :string)
   -> 0.0656s
== 20231006183200 AddURLToPreviewCardsStatuses: migrated (0.0739s) ============

I, [2024-10-08T22:13:18.239826 #1]  INFO -- : Migrating to AddIndexToWebauthnCredentialsUserIdNickname (20231018192110)
== 20231018192110 AddIndexToWebauthnCredentialsUserIdNickname: migrating ======
[strong_migrations] DANGER: No lock timeout set
rake aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

=== Dangerous operation detected #strong_migrations ===

Adding an index concurrently can cause silent data corruption in Postgres 14.0 to 14.3.
Upgrade Postgres before adding new indexes, or wrap this step in a safety_assured { ... } block
to accept the risk.

/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:31:in `add_index_to_table'
/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:7:in `up'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

### Expected behaviour

DB Migrations to pass on supported PostgreSQL version

### Actual behaviour

```

### Detailed description

_No response_

### Mastodon instance

_No response_

### Mastodon version

_No response_

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: (from `ruby --version`, eg. v3.1.2)
- Node.js version: (from `node --version`, eg. v18.16.0)

**Comment by Dbroqua** [comment]
Same error with docker environment :

```bash
docker-compose run --rm -e SKIP_POST_DEPLOYMENT_MIGRATIONS=true web rails db:migrate
Creating live_web_run ... done

I, [2024-10-09T06:09:56.929684 #7]  INFO -- : Migrating to AddIndexToWebauthnCredentialsUserIdNickname (20231018192110)
== 20231018192110 AddIndexToWebauthnCredentialsUserIdNickname: migrating ======
[strong_migrations] DANGER: No lock timeout set
bin/rails aborted!
StandardError: An error has occurred, all later migrations canceled: (StandardError)

=== Dangerous operation detected #strong_migrations ===

Adding an index concurrently can cause silent data corruption in Postgres 14.0 to 14.3.
Upgrade Postgres before adding new indexes, or wrap this step in a safety_assured { ... } block
to accept the risk.

/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:31:in `add_index_to_table'
/opt/mastodon/db/migrate/20231018192110_add_index_to_webauthn_credentials_user_id_nickname.rb:7:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
ERROR: 1
```

**Comment by renchap** [comment]
One of the dependencies we use to handle migrations has a check that rejects PostgreSQL 14.0 to 14.3, as those versions contain a data corruption bug. We missed this in the changelog, we will update it.

You should upgrade your postgres version to the latest patch release for PostgreSQL 14 (version 14.13). You can do that by simply updating your package / container image. PostgreSQL minor versions do not require any data migration, so as long as you stay with PG 14, you do not need to migrate / upgrade PostgreSQL data. If you want to upgrade to a more recent PostgreSQL major version (PG 15, 16 or the latest 17), then you need to [follow their documentation](https://www.postgresql.org/docs/17/upgrading.html)

**Comment by Dbroqua** [comment]
Thanks @renchap,

However I can't update the db version via `docker-compose build`.

I get this message `db uses an image, skipping` and it moves on.

Is there a solution to force the update? 

Thanks

**Comment by renchap** [comment]
You need to run `docker compose pull postgresql` to force Compose to download the latest available pg image for this tag (probably `14-alpine` if you use our provided compose file), then restart the pg container (`docker compose restart postgresql`)

**Comment by Dbroqua** [comment]
That wasn't enough, so I had to `docker compose up -d --no-deps --build db` and now it's ok.

Thanks for all 👌 .

**Comment by renchap** [comment]
Yes, `restart` probably down not work, you need `docker compose down db && docker compose pull db && docker compose up -d db`

**Comment by vmstan** [comment]
@hardillb  Is this still an issue for you?

**Comment by hardillb** [comment]
@vmstan This is closely linked to https://github.com/mastodon/chart/issues/156

Both should be closed together, once the docs (and the helm chart) and all updated to ensure it's not possible to install the unsupported versions.

**Comment by thecoolestcoderrushil** [comment]
DB migrations that fail because a dependency rejects PostgreSQL 14.0 to 14.3 is a painful upgrade blocker, since a supported Postgres version cannot complete the migration. Rehearsing the migration on a production-shaped twin first would surface the version problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
