### ISSUE TITLE
Missing Webpacker template for email message

### ISSUE THREAD

**Issue by alsutton** [mastodon/mastodon#32345]
### Steps to reproduce the problem

1. Examine `journalctl -u mastodon-sidekiq` after emails have been sent

### Expected behaviour

No errors about missing templates

### Actual behaviour

Error found in logs

### Detailed description

```
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: 2024-10-09T06:35:53.380Z pid=41086 tid=1tre WARN: ActionView::Template::Error: Webpacker can't find media/images/mailer-new/heading/user.png in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "mailer": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:           "/packs/css/mailer-47e61cac.chunk.css"
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:           "/packs/js/mailer-1f6eeb2de0f4973f1e9e.chunk.js"
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:           "/packs/css/mailer-47e61cac.chunk.css.map"
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:           "/packs/js/mailer-1f6eeb2de0f4973f1e9e.chunk.js.map"
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "mailer.css": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/css/mailer-47e61cac.chunk.css",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "mailer.css.map": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/css/mailer-47e61cac.chunk.css.map",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "mailer.js": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/js/mailer-1f6eeb2de0f4973f1e9e.chunk.js",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "mailer.js.map": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/js/mailer-1f6eeb2de0f4973f1e9e.chunk.js.map",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/icons/icon_email.svg": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/icons/icon_email-185c94df8b200b5513adfd2cb2c90cf2.svg",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_cached.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_cached-d82304cbd965343f5f6a5631d68e8a15.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_done.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_done-f49dc0b65c99f2edce1b99ee696f0b8d.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_email.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_email-07eaf000249a54dae76b2937a834c3ae.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_file_download.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_file_download-fb5f9be9fd8e11726c3b3a1d47e72717.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_flag.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_flag-fb052043db6f17c4f79c21fccff09700.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_grade.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_grade-15655c70b6fe2ca2f8547db15929187a.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_lock_open.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_lock_open-8e5ae4f888e6ea016e3046b607314d02.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_person_add.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_person_add-a9759d23d1662ab87c2f255c8906107b.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/icon_reply.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/icon_reply-05e7be76b12b1b5529bd003bbe17bcf2.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/logo.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/logo-50cfb97cbce11d4974c71481a924b69c.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:   "media/images/mailer/wordmark.png": {
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]:     "src": "/packs/media/images/mailer/wordmark-8a93a992d2c8ac64361a1bc2c1664250.png",
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/app/views/notification_mailer/follow.html.haml:2:in `block in _app_views_notification_mailer_follow_html_haml__71368559434459381_148620'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/app/views/notification_mailer/follow.html.haml:1:in `_app_views_notification_mailer_follow_html_haml__71368559434459381_148620'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:1004:in `block in collect_responses_from_templates'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:1001:in `each'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:1001:in `each'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:1001:in `map'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:1001:in `collect_responses_from_templates'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:979:in `collect_responses'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:887:in `mail'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/app/mailers/notification_mailer.rb:32:in `block in follow'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/app/mailers/application_mailer.rb:15:in `locale_for_account'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/app/mailers/notification_mailer.rb:31:in `follow'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/rescuable.rb:29:in `block in process'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/rescuable.rb:21:in `handle_exceptions'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/rescuable.rb:28:in `process'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:658:in `block in process'
Oct 09 06:35:53 ip-172-30-2-31 bundle[41086]: /home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/actionmailer-7.1.4/lib/action_mailer/base.rb:657:in `process'
```

### Mastodon instance

snapp.social

### Mastodon version

v4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [aarch64-linux]
- Node.js version: v18.19.0

**Comment by renchap** [comment]
This is because the assets have not been build on this server. You need to run the `assets:precompile` step on every server, including sidekiq servers, because Sidekiq is used to send emails, and the assets are needed for emails.

Alternatively, you can generate assets on one server, then copy `public/assets` and `public/packs` to the other servers.

**Comment by renchap** [comment]
Are you using multiple servers for your deployment?

**Comment by alsutton** [comment]
One sidekiq server (running only sidekiq jobs), Two webservers (running the web front end and streamer), all in AWS EC2.

I've tried erasing `public/assets` and `public/packs` and re-running `RAILS_ENV=production bundle exec rails assets:precompile`, and I'll run another log sweep in a few hours to see if a complete rebuild has fixed the issue.

**Comment by renchap** [comment]
You can try to remove `public/packs` and `tmp/webpacker`, and then `assets:precompile` again. Once this is done, you will need to restart all the Ruby (web + sidekiq) processes on this server so they load the new manifest. And you need to do this on all 3 servers.

**Comment by vmstan** [comment]
@alsutton  Is this still an issue for you?

**Comment by alsutton** [comment]
The steps recommended by @renchap solved the issue.
