### ISSUE TITLE
"ip_block.rb Blocked?" after update from 4.2.13 to 4.3.0

### ISSUE THREAD

**Issue by AndresJ551** [mastodon/mastodon#32446]
### Steps to reproduce the problem

1. Follow instructions on https://github.com/mastodon/mastodon/releases/tag/v4.3.0
2. Restart docker containers using provided docker-compose.
3. Front and backend return 500.

### Expected behaviour

Upgrade from 4.2.13 to 4.3.0

### Actual behaviour

Error 500 with backend logs on "app/models/ip_block.rb:39:in blocked?"

### Detailed description

These are the logs I'm getting at the moment from mastodon_website_1:

[a952dc27-7180-4502-b5ca-ff9367959f91] app/models/ip_block.rb:39:in `blocked?'
[a952dc27-7180-4502-b5ca-ff9367959f91] config/initializers/rack_attack.rb:66:in `block in <class:Attack>'
[b6b75ca1-23f9-41d6-b6f2-127118858396] RuntimeError (Temporary failure in name resolution):
E, [2024-10-13T16:32:58.750015 #35] ERROR -- : [b6b75ca1-23f9-41d6-b6f2-127118858396]   

### Mastodon instance

mastodon.hardcoredevs.com

### Mastodon version

4.3.0

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: latest from Docker-Compose
- Node.js version: latest from Docker-Compose

**Comment by AndresJ551** [comment]
The containers couldn't reach each other, adding "hostname" to the docker compose fixed the issue.
