### ISSUE TITLE
Regression: Sidekiq in docker-compose cannot run as non-root

### ISSUE THREAD

**Issue by Mubelotix** [mastodon/mastodon#32767]
### Steps to reproduce the problem

1. Edit your docker-compose to run sidekiq under a specific user id
2. Launch your docker compose

### Expected behaviour

Sidekiq should run fine as it did in all versions prior 4.3

### Actual behaviour

Sidekiq stops after a few seconds and restarts

### Detailed description

<details>
<summary>Docker logs</summary>

```
2024-11-04T14:20:15.456Z pid=7 tid=5sb WARN: Errno::EACCES: Permission denied @ rb_sysopen - /opt/mastodon/tmp/sidekiq_process_has_started_and_will_begin_processing_jobs
2024-11-04T14:20:15.456Z pid=7 tid=5sb WARN: /usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in initialize'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in open'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in rescue in block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2015:in block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in each'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in touch'
/opt/mastodon/config/initializers/sidekiq.rb:17:in block (2 levels) in <main>'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:57:in block in fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in each'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/cli.rb:116:in run'
/usr/local/bundle/gems/sidekiq-6.5.12/bin/sidekiq:31:in <top (required)>'
/usr/local/bundle/bin/sidekiq:25:in load'
/usr/local/bundle/bin/sidekiq:25:in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in kernel_load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in exec'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in invoke_command'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in start'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in start'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in <top (required)>'
/usr/local/bundle/bin/bundle:25:in load'
/usr/local/bundle/bin/bundle:25:in <main>'
```
</details>

### Mastodon instance

mastodon.insa.lol

### Mastodon version

v4.3.0 and v4.3.1

**Comment by renchap** [comment]
What user are you trying to run Sidekiq with?

Our `Dockerfile` has Sidekiq write into `/opt/mastodon/tmp/sidekiq_process_has_started_and_will_begin_processing_jobs` (see https://github.com/mastodon/mastodon/blob/main/Dockerfile#L72)

You can see how its done here: https://github.com/renchap/mastodon/blob/main/config/initializers/sidekiq.rb

As an alternative, you should either disable this feature by setting the environment variable to an empty string, or change it to a path that your user can write to.

Also note that our processes do not run as root in the containers, but as `mastodon`: https://github.com/mastodon/mastodon/blob/main/Dockerfile#L406

**Comment by claudiodekker** [comment]
Started seeing this identical issue:

```
 sidekiq:
    #build: .
    image: ghcr.io/mastodon/mastodon:v4.3.1
    restart: always
    env_file: stack.env
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - /volume1/docker/mastodon/public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    security_opt:
      - no-new-privileges:true
    user: 1026:100
```

```
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
2025-01-12T17:44:44.292Z pid=7 tid=5sb INFO: Booting Sidekiq 6.5.12 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://redis:6379/0", :driver=>:hiredis, :namespace=>nil}
2025-01-12T17:44:57.207Z pid=7 tid=5sb INFO: Booted Rails 7.1.4.1 application in production environment
2025-01-12T17:44:57.207Z pid=7 tid=5sb INFO: Running in ruby 3.3.5 (2024-09-03 revision ef084cc8f4) +YJIT [x86_64-linux]
2025-01-12T17:44:57.207Z pid=7 tid=5sb INFO: See LICENSE and the LGPL-3.0 for licensing details.
2025-01-12T17:44:57.207Z pid=7 tid=5sb INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org
2025-01-12T17:44:57.259Z pid=7 tid=5sb INFO: Loading Schedule
2025-01-12T17:44:57.259Z pid=7 tid=5sb INFO: Scheduling scheduled_statuses_scheduler {"every"=>"5m", "class"=>"Scheduler::ScheduledStatusesScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.265Z pid=7 tid=5sb INFO: Scheduling trends_refresh_scheduler {"every"=>"5m", "class"=>"Scheduler::Trends::RefreshScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.267Z pid=7 tid=5sb INFO: Scheduling trends_review_notifications_scheduler {"every"=>"6h", "class"=>"Scheduler::Trends::ReviewNotificationsScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.270Z pid=7 tid=5sb INFO: Scheduling indexing_scheduler {"interval"=>"1 minute", "class"=>"Scheduler::IndexingScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.281Z pid=7 tid=5sb INFO: Scheduling vacuum_scheduler {"cron"=>"53 3 * * *", "class"=>"Scheduler::VacuumScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.325Z pid=7 tid=5sb INFO: Scheduling follow_recommendations_scheduler {"cron"=>"0 7 * * *", "class"=>"Scheduler::FollowRecommendationsScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.337Z pid=7 tid=5sb INFO: Scheduling user_cleanup_scheduler {"cron"=>"38 6 * * *", "class"=>"Scheduler::UserCleanupScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.363Z pid=7 tid=5sb INFO: Scheduling ip_cleanup_scheduler {"cron"=>"51 5 * * *", "class"=>"Scheduler::IpCleanupScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.373Z pid=7 tid=5sb INFO: Scheduling pghero_scheduler {"cron"=>"0 0 * * *", "class"=>"Scheduler::PgheroScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.381Z pid=7 tid=5sb INFO: Scheduling instance_refresh_scheduler {"cron"=>"0 * * * *", "class"=>"Scheduler::InstanceRefreshScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.392Z pid=7 tid=5sb INFO: Scheduling accounts_statuses_cleanup_scheduler {"interval"=>"1 minute", "class"=>"Scheduler::AccountsStatusesCleanupScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.402Z pid=7 tid=5sb INFO: Scheduling suspended_user_cleanup_scheduler {"interval"=>"1 minute", "class"=>"Scheduler::SuspendedUserCleanupScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.406Z pid=7 tid=5sb INFO: Scheduling software_update_check_scheduler {"interval"=>"30 minutes", "class"=>"Scheduler::SoftwareUpdateCheckScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.409Z pid=7 tid=5sb INFO: Scheduling auto_close_registrations_scheduler {"interval"=>"1 hour", "class"=>"Scheduler::AutoCloseRegistrationsScheduler", "queue"=>"scheduler"}
2025-01-12T17:44:57.415Z pid=7 tid=5sb INFO: Schedules Loaded
2025-01-12T17:44:57.416Z pid=7 tid=5sb WARN: {"context":"Exception during Sidekiq lifecycle event.","event":"startup"}
2025-01-12T17:44:57.416Z pid=7 tid=5sb WARN: Errno::EACCES: Permission denied @ rb_sysopen - /opt/mastodon/tmp/sidekiq_process_has_started_and_will_begin_processing_jobs
2025-01-12T17:44:57.417Z pid=7 tid=5sb WARN: /usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `initialize'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `open'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `rescue in block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2015:in `block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in `each'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in `touch'
/opt/mastodon/config/initializers/sidekiq.rb:17:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:57:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in `each'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in `fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/cli.rb:116:in `run'
/usr/local/bundle/gems/sidekiq-6.5.12/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
2025-01-12T17:44:57.417Z pid=7 tid=5sb WARN: Errno::EACCES: Permission denied @ rb_sysopen - /opt/mastodon/tmp/sidekiq_process_has_started_and_will_begin_processing_jobs
2025-01-12T17:44:57.417Z pid=7 tid=5sb WARN: /usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `initialize'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `open'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2019:in `rescue in block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2015:in `block in touch'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in `each'
/usr/local/lib/ruby/3.3.0/fileutils.rb:2013:in `touch'
/opt/mastodon/config/initializers/sidekiq.rb:17:in `block (2 levels) in <main>'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:57:in `block in fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in `each'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:56:in `fire_event'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/cli.rb:116:in `run'
/usr/local/bundle/gems/sidekiq-6.5.12/bin/sidekiq:31:in `<top (required)>'
/usr/local/bundle/bin/sidekiq:25:in `load'
/usr/local/bundle/bin/sidekiq:25:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:455:in `exec'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:35:in `dispatch'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/cli.rb:29:in `start'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:28:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.5.18/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.5.18/exe/bundle:20:in `<top (required)>'
/usr/local/bundle/bin/bundle:25:in `load'
/usr/local/bundle/bin/bundle:25:in `<main>'
2025-01-12T17:45:17.930Z pid=8 tid=5s4 INFO: Booting Sidekiq 6.5.12 with Sidekiq::RedisConnection::RedisAdapter options {:url=>"redis://redis:6379/0", :driver=>:hiredis, :namespace=>nil}
```

**Comment by claudiodekker** [comment]
Hacky workaround fix for this issue:

```
sidekiq:
    #build: .
    image: ghcr.io/mastodon/mastodon:v4.3
    restart: always
    env_file: stack.env
    #command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - /volume1/docker/mastodon/public/system:/mastodon/public/system
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
    security_opt:
      - no-new-privileges:true
    #user: 1026:100
    user: root
    command:  sh -c "getent passwd mycustomuser >/dev/null 2>&1 || useradd -u 1026 -g 100 -M -d /nonexistent -s /bin/bash mycustomuser; chown -R mycustomuser:mastodon /opt/mastodon/tmp; exec su mycustomuser -c \"bundle exec sidekiq\""
```

The flags that have changed are `command` and `user`.

Instead of running as my custom user, I now run the container as `root`, add a `mycustomuser` user (if it doesn't exist yet, which is necessary to prevent errors in case of restarts, where the container's volume is already modified by us) that matches the user id / group id that I need, followed by changing the ownership of `/opt/mastodon/tmp` to that user, followed by booting sidekiq as that user (to make sure it isn't actually booting as root).

**Comment by Mubelotix** [comment]
> you should either disable this feature by setting the environment variable to an empty string

This is just wrong

> or change it to a path that your user can write to

That's actually the issue. The user can write to the location but apparently the docker is misconfigured 

This issue is very real and should be reopened. My server has millions of failed jobs due suboptimal workarrounds. I might just quit the network if Mastodon isn't running smoothly

**Comment by Mubelotix** [comment]
This malfunction is causing an increasing number of other issues on my instance. Jobs are failing everywhere, features break like dominos. This is **killing** my instance.

**Comment by Mubelotix** [comment]
I'll try fixing the bug and making a PR

**Comment by Mubelotix** [comment]
I found a workaround. Add the tml volume bind in the docker-compose for sidekiq

```yaml
  sidekiq:
    #build: .
    image: ghcr.io/mastodon/mastodon:v4.3.4
    user: "{{user_id}}:{{group_id}}"
    restart: unless-stopped
    mem_limit: 1.2G
    mem_reservation: 800M
    env_file: .env.production
    command: bundle exec sidekiq
    depends_on:
      - db
      - redis
    networks:
      - external_network
      - internal_network
    volumes:
      - /data/mastodon/public/system:/mastodon/public/system
      - /tmp/mastodon:/opt/mastodon/tmp/sidekiq_process_has_started_and_will_begin_processing_jobs
    healthcheck:
      test: ['CMD-SHELL', "ps aux | grep '[s]idekiq\ 6' || false"]
```

**Comment by Mubelotix** [comment]
Workaround wasn't enough. My instance defederated from the network completely and the install is so fucked up I am forced to shut it down permanently. Mastodon lost 3 million users due to instance going dark, just in the last few weeks, because of bugs like this. Just mine on this single issue resulted in a loss of 1200 MAU. It's never going to make it
