### ISSUE TITLE
tootctl error "uninitialized constant HttpLog" when trying to use the tool

### ISSUE THREAD

**Issue by cadusilva** [mastodon/mastodon#32790]
### Steps to reproduce the problem

1. Try to run some `tootctl` command
2. An error `uninitialized constant HttpLog` appears after a few seconds

### Expected behaviour

The tootctl command to sucessfully run

### Actual behaviour

The `uninitialized constant HttpLog` error appears and halts the command

### Detailed description

Every `tootctl` command I try to run end up like this:

``` bash
$ live/bin/tootctl cache clear
/home/mastodon/live/lib/mastodon/cli/progress_helper.rb:8:in `<main>': uninitialized constant HttpLog (NameError)

HttpLog.configuration.logger = dev_null
^^^^^^^
Did you mean?  HTTPClient
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `<main>'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `<main>'
	from live/bin/tootctl:5:in `require_relative'
	from live/bin/tootctl:5:in `<main>'



$ live/bin/tootctl --version
/home/mastodon/live/lib/mastodon/cli/progress_helper.rb:8:in `<main>': uninitialized constant HttpLog (NameError)

HttpLog.configuration.logger = dev_null
^^^^^^^
Did you mean?  HTTPClient
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `<main>'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `<main>'
	from live/bin/tootctl:5:in `require_relative'
	from live/bin/tootctl:5:in `<main>'



$ live/bin/tootctl media usage
/home/mastodon/live/lib/mastodon/cli/progress_helper.rb:8:in `<main>': uninitialized constant HttpLog (NameError)

HttpLog.configuration.logger = dev_null
^^^^^^^
Did you mean?  HTTPClient
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `<main>'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `<main>'
	from live/bin/tootctl:5:in `require_relative'
	from live/bin/tootctl:5:in `<main>'



$ live/bin/tootctl search deploy --clean
/home/mastodon/live/lib/mastodon/cli/progress_helper.rb:8:in `<main>': uninitialized constant HttpLog (NameError)

HttpLog.configuration.logger = dev_null
^^^^^^^
Did you mean?  HTTPClient
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/base.rb:8:in `<main>'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `require_relative'
	from /home/mastodon/live/lib/mastodon/cli/main.rb:3:in `<main>'
	from live/bin/tootctl:5:in `require_relative'
	from live/bin/tootctl:5:in `<main>'
```

When I edit the file `progress_helper.rb` and comment the line 8, the error disappears, and the command runs without a glitch.

It didn't happen at least until `v4.4.0-alpha.1-0a1b5df`.

### Mastodon instance

bolha.one, ursal.zone

### Mastodon version

v4.4.0-alpha.1-d482211

### Technical details

If this is happening on your own Mastodon server, please fill out those:
- Ruby version: `ruby 3.3.6 (2024-11-05 revision 75015d4c1f) [x86_64-linux]`
- Node.js version: `v20.18.0`

**Comment by mjankowski** [comment]
Probably related - https://github.com/mastodon/mastodon/pull/32776

**Comment by vmstan** [comment]
Just ran into this a little bit ago myself. Confirmed.
