### ISSUE TITLE
compiling assets on main on node.js v20 hangs, but v22 succeeds

### ISSUE THREAD

**Issue by NicoBerlo1** [mastodon/mastodon#32866]
### Steps to reproduce the problem

bundle exec rails yarn:install assets:precompile

### Expected behaviour

asset precompiling as I did daily

### Actual behaviour

compiling hanged

### Detailed description

This started on monday night after a pull on main.
Compiling assets would hang, despite having lots of ram.
It even made some kernel tasks unresponsive that showed up on console.

It finally was fixed by using node.js v22 instead of v20.
I tried with ruby 3.3.5 instead of 3.3.6 but it didn't change anything.

### Mastodon instance

lepoulsdumonde.com

### Mastodon version

v4.4.0-alpha.1 main pull

### Environment

Please at least include those informations:
- Operating system: debian 12
- Ruby version: 3.3.6 and 3.3.5
- Node.js version: v20.8.0

### Technical details

 bundle exec rails --trace yarn:install assets:precompile
** Invoke yarn:install (first_time)
** Execute yarn:install
➤ YN0000: · Yarn 4.5.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 320ms
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ eslint is listed by your project with version 8.57.1 (p05eff), which doesn't satisfy what eslint-plugin-formatjs and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react is listed by your project with version 18.3.1 (p68bdc), which doesn't satisfy what emoji-mart-lazyload and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-dom is listed by your project with version 18.3.1 (p9d1ad), which doesn't satisfy what react-router-scroll-4 and other dependencies request (but they have non-overlapping ranges!).
➤ YN0060: │ react-router-dom is listed by your project with version 5.3.4 (p7a2e6), which doesn't satisfy what react-router-scroll-4 requests (^4.0.0).
➤ YN0002: │ @mastodon/mastodon@workspace:. doesn't provide redux (p7bebf), requested by react-redux-loading-bar and other dependencies.
➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 0s 681ms
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed in 0s 527ms
➤ YN0000: · Done with warnings in 1s 860ms
** Invoke assets:precompile (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute assets:precompile
** Invoke webpacker:compile (first_time)
** Invoke webpacker:verify_install (first_time)
** Invoke webpacker:check_node (first_time)
** Execute webpacker:check_node
** Invoke webpacker:check_yarn (first_time)
** Invoke environment 
** Execute webpacker:check_yarn
** Invoke webpacker:check_binstubs (first_time)
** Execute webpacker:check_binstubs
** Execute webpacker:verify_install
** Invoke environment 
** Execute webpacker:compile
Compiling...
^C#<Thread:0x00007f078a96e9c8 /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:664 run> terminated with exception (report_on_exception is true):
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:664:in `read': stream closed in another thread (IOError)
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:664:in `block (2 levels) in capture3'
#<Thread:0x00007f078a96e888 /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:665 run> terminated with exception (report_on_exception is true):
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:665:in `read': stream closed in another thread (IOError)
        from /home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:665:in `block (2 levels) in capture3'
^Cbin/rails aborted!
Interrupt: Interrupt
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:543:in `join'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:543:in `ensure in popen_run'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:543:in `popen_run'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:235:in `popen3'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/open3.rb:658:in `capture3'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker/compiler.rb:70:in `run_webpack'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker/compiler.rb:23:in `compile'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker/commands.rb:51:in `compile'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker.rb:35:in `compile'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/tasks/webpacker/compile.rake:23:in `block (4 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker.rb:28:in `ensure_log_goes_to_stdout'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/tasks/webpacker/compile.rake:22:in `block (3 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/webpacker.rb:20:in `with_node_env'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/tasks/webpacker/compile.rake:21:in `block (2 levels) in <main>'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/webpacker-5.4.4/lib/tasks/webpacker/compile.rake:14:in `block in enhance_assets_precompile'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `block in execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:281:in `execute'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `synchronize'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/task.rb:188:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:188:in `invoke_task'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block (2 levels) in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `each'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:138:in `block in top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:147:in `run_with_threads'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:132:in `top_level'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:27:in `block (2 levels) in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:27:in `block in perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:44:in `block in with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:156:in `invoke_rake'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:73:in `block in invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:149:in `with_argv'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:69:in `invoke'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands.rb:18:in `<main>'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `require'
/home/mastodon/.rbenv/versions/3.3.5/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
/home/mastodon/live/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'

**Comment by ThisIsMissEm** [comment]
I was involved in trying to get asset compiling working here on a matrix chat & suggested opening an issue in case there's been a weird regression.

**Comment by renchap** [comment]
Can you try to directly invoke Webpacker, with `RAILS_ENV=production NODE_ENV=production ./bin/webpacker`?

**Comment by Y0ngg4n** [comment]
We have the same problem with the Update to v4.3.1
The `./bin/webpacker` does not exist in our Installation. Do you mean `./bin/webpack`?
If i call `RAILS_ENV=production NODE_ENV=production ./bin/webpack` it also just hangs indefinitely.

**Comment by mjankowski** [comment]
@Y0ngg4n - can you confirm your ruby/node versions? (and maybe general system env/specs)?

**Comment by Y0ngg4n** [comment]
@mjankowski The ruby version is 3.3.5 running on a standard debian install.

**Comment by nemobis** [comment]
I have the same issue on Debian 12, installed with the [usual instructions](https://docs.joinmastodon.org/admin/install/). I previously tried yarnpkg 4.0.2 from Debian 13

```
$ node --version
v18.19.0
...
==> Installed ruby-3.3.5 to /home/mastodon/.rbenv/versions/3.3.5
Bundle complete! 147 Gemfile dependencies, 279 gems now installed.
Gems in the groups 'development' and 'test' were not installed.
Bundled gems are installed into `./vendor/bundle`
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0000: └ Completed
➤ YN0000: · Done in 0s 128ms

Jan 18 14:40:13 scw-musing-yonath systemd-journald[245]: [🡕] Suppressed 61918 messages from mastodon-web.service
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: E, [2025-01-18T14:40:13.811774 #3719] ERROR -- : [4b1f6eaf-1723-4ca6-b603-b049c60e1b90]
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: [4b1f6eaf-1723-4ca6-b603-b049c60e1b90] ActionView::Template::Error (Webpacker can't find inert.css in /home/mastodon/live/public/packs/manifest.json. Possible causes:
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: 1. You want to set webpacker.yml value of compile to true for your environment
Jan 18 14:40:13 scw-musing-yonath bundle[3719]:    unless you are using the `webpack -w` or the webpack-dev-server.
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: 2. webpack has not yet re-run to reflect updates.
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: 3. You have misconfigured Webpacker's config/webpacker.yml file.
Jan 18 14:40:13 scw-musing-yonath bundle[3719]: 4. Your webpack configuration is not creating a manifest.


$ RAILS_ENV=production NODE_ENV=production ./bin/webpack
Usage Error: Couldn't find a script named "webpack".

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] [--require #0] <scriptName> ...
```
