### ISSUE TITLE
"We're sorry, but something went wrong on our end." when signing in to web

### ISSUE THREAD

**Issue by cipriani14** [mastodon/mastodon#33001]
### Steps to reproduce the problem

1. Visit my personal Mastodon instance on a new device/incognito tab
2. Attempt to log in, entering email, password, 2FA code
3. View error message

### Expected behaviour

Should be able to access my Mastodon account

### Actual behaviour

Can't log in

### Mastodon instance

mrcippy.xyz

### Mastodon version

v4.3.1

### Environment

Please at least include those informations:
- Docker container on Synology NAS (image: lscr.io/linuxserver/mastodon:latest)
- Docker compose: https://gitlab.com/thinkonezero/mastodon-docker-standup
- Ruby version: v3.3.6
- Node.js version: 20.15.1

### Technical details

I _think_ this is the relevant error in my logs? Let me know if you nee more. 

`2024-11-20T19:59:18.572Z pid=253 tid=34z09 class=ActivityPub::ProcessingWorker jid=9e0b15c4c008e91e6cf8c28d elapsed=0.006 INFO: done
I, [2024-11-20T12:59:18.605264 #398]  INFO -- : [bfeb7013-e67d-4a68-8104-91d31749039f] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=200 allocations=21821 duration=2295.20 view=648.70 db=217.76
I, [2024-11-20T12:59:19.060317 #388]  INFO -- : [efab1d44-7bbc-4218-905b-ce32246adb8d] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=500 allocations=1688 duration=94.07 view=0.00 db=0.99
E, [2024-11-20T12:59:19.073439 #388] ERROR -- : [efab1d44-7bbc-4218-905b-ce32246adb8d]   
[efab1d44-7bbc-4218-905b-ce32246adb8d] ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):
[efab1d44-7bbc-4218-905b-ce32246adb8d]   
[efab1d44-7bbc-4218-905b-ce32246adb8d] app/controllers/concerns/auth/two_factor_authentication_concern.rb:32:in `valid_otp_attempt?'
[efab1d44-7bbc-4218-905b-ce32246adb8d] app/controllers/concerns/auth/two_factor_authentication_concern.rb:74:in `authenticate_with_two_factor_via_otp'
[efab1d44-7bbc-4218-905b-ce32246adb8d] app/controllers/concerns/auth/two_factor_authentication_concern.rb:51:in `authenticate_with_two_factor'
[efab1d44-7bbc-4218-905b-ce32246adb8d] lib/mastodon/rack_middleware.rb:9:in `call'
I, [2024-11-20T12:59:19.455805 #388]  INFO -- : [8cae3826-41c4-418b-9931-d47ae83ef378] method=GET path=/favicon.ico format=html controller=ApplicationController action=raise_not_found status=404 allocations=3140 duration=2.87 view=0.79 db=0.00`

**Comment by ClearlyClaire** [comment]
This looks like you changed the values of `ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT` or `ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY` some time after the upgrade. If you still have a backup of those, you could revert it (provided that no other user has enabled 2FA in-between).

You can learn more in https://github.com/mastodon/mastodon/issues/32375

**Comment by ClearlyClaire** [comment]
You can look at https://github.com/mastodon/mastodon/issues/32375#issuecomment-2410957427

**Comment by cipriani14** [comment]
Thank you. I'm not sure how to run the unset script, but I'll report back once I figure it out. 

I've been using Portainer to manage my setup and slowly trying to learn how to manage it via CLI. Baby steps. 

Appreciate the help!

**Comment by cipriani14** [comment]
@ClearlyClaire I was able to get this fixed. Thanks again.
