### ISSUE TITLE
settings.thing_type column removed (accidentally?)

### ISSUE THREAD

**Issue by xrobau** [mastodon/mastodon#33346]
https://github.com/mastodon/mastodon/blob/main/db/post_migrate/20241205135925_remove_legacy_user_settings_columns.rb

This drops the 'thing_type' column, which is still is referenced in app/models/settings.rb

This is visible in the logs as:
```

Dec 18 06:03:17 f2 bundle[29999]: /home/mastodon/dev/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
Dec 18 06:03:17 f2 bundle[29999]: /home/mastodon/dev/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/abstract_adapter.rb:1027:in `block in with_raw_connection'
Dec 18 06:03:17 f2 bundle[29999]: 2024-12-18T06:03:17.798Z pid=29999 tid=28w7 WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"default","args":[113672309816606909],"class":"DistributionWorker","jid":"66fbf9b309e55f5a8ffd9f5e","created_at":1734501797.7742586,"enqueued_at":1734501797.774319}}
Dec 18 06:03:17 f2 bundle[29999]: 2024-12-18T06:03:17.798Z pid=29999 tid=28w7 WARN: ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column settings.thing_type does not exist
Dec 18 06:03:17 f2 bundle[29999]: LINE 1: SELECT "settings".* FROM "settings" WHERE "settings"."thing_...
Dec 18 06:03:17 f2 bundle[29999]:                                                   ^
Dec 18 06:03:17 f2 bundle[29999]: 2024-12-18T06:03:17.798Z pid=29999 tid=28w7 WARN: /home/mastodon/dev/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.4.1/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `exec_params'

```

**Comment by xrobau** [comment]
Sorry, PEBKAC issue - that was 'mastodon/*dev*/...' - which was still running partially updated code. Closing.
