### ISSUE TITLE
Error processing mentions rejects toot

### ISSUE THREAD

**Issue by ClearlyClaire** [mastodon/mastodon#3703]
If an error occurs when fetching details from mentionned users, the whole job will fail.

```
juin 11 22:30:17 neiro bundle[15174]: 2017-06-11T20:30:17.515Z 15174 TID-njlac WARN: HTTP::TimeoutError: Read timed out after 10 seconds
[…]
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/fetch_atom_service.rb:9:in `call'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/fetch_remote_account_service.rb:8:in `call'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:212:in `account_from_href'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:195:in `block in mentions_from_xml'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:190:in `block in each'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `upto'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.0/lib/nokogiri/xml/node_set.rb:189:in `each'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:192:in `mentions_from_xml'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:161:in `status_from_xml'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:60:in `block in create_status'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `block in transaction'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:194:in `block in within_new_transaction'
juin 11 22:30:17 neiro bundle[15174]: /usr/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/transaction.rb:191:in `within_new_transaction'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/connection_adapters/abstract/database_statements.rb:225:in `transaction'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/transactions.rb:210:in `transaction'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:59:in `create_status'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:33:in `call'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:19:in `block in process_entries'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:19:in `reverse_each'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:19:in `each'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:19:in `map'
juin 11 22:30:17 neiro bundle[15174]: /home/mastodon/live/app/services/process_feed_service.rb:19:in `process_entries'
```

I am not completely sure what should be done with mentions that fail processing because of such errors, but I don't think it should abort the whole job.

**Comment by Gargron** [comment]
The job will be retried though, right?

What's the alternative - if we need FetchRemoteAccountService in the first place, it means information about a mentioned user is missing. So ignoring this failure would result in a toot with missing metadata.

**Comment by ThibG** [comment]
Yeah, but imagine the following situation: users bob@example.org knows alice@somedomain.org and mentions her in a toot that isn't directly directed to her. However, somedomain.org happens to be unavailable for an extended period of time: bob's followers will get his toots only if their instance already knows alice.

**Comment by clworld** [comment]
FYI:
There is IPv6 only instances which is always unreachable from IPv4 only instances.
They are small and maybe testing purpose instances but exists. for example: https://mastodon.home.js4.in, https://v6.waraiotoko.net
Dual-Stacked instances can reply to/boosting IPv6 only instances' toots but I heard it causes problematic behavior.
(I don't know how can we solve this...)

**Comment by ThibG** [comment]
@clworld ah, didn't think about that. So, yes, connectivity to a remote instance cannot be assumed to be the same for any two instances.

I think we should process as much as we can, and display the status even if its missing some mentions. Maybe there could be a service that process as much unresolved mentions as possible from a remote toot, and spawn a worker if it hasn't resolved everything. The worker would just use this service, trying to resolve any mention that hasn't been resolved yet.

**Comment by clworld** [comment]
> connectivity to a remote instance cannot be assumed to be the same for any two instances.

Yes. Even does not thinking IPv6, China has GFW and UK has IWF/Cleenfeed which did block some Wikipedia pages. As I know.

**Comment by Solyasonya** [comment]
Ggg
