### ISSUE TITLE
Sidekiq deadlocks on multi-threaded and development env

### ISSUE THREAD

**Issue by unarist** [mastodon/mastodon#3996]
It works when `:concurrency: 1`, but 2 or more concurrency causes deadlock.

![image](https://user-images.githubusercontent.com/705555/27688232-d881be50-5d14-11e7-8a64-874e647af8b4.png)

Setting `config.allow_concurrency = false` on `config/environments/development.rb` seems to fix this, but I don't know whether it's appropriate solution or not.

sidekiq.yml

```yml
---
:concurrency: 2
:queues:
  - default
  - push
  - pull
  - mailers
:schedule:
  subscriptions_scheduler:
    cron: '0 5 * * *'
    class: Scheduler::SubscriptionsScheduler
  media_cleanup_scheduler:
    cron: '5 4 * * *'
    class: Scheduler::MediaCleanupScheduler
  feed_cleanup_scheduler:
    cron: '0 0 * * *'
    class: Scheduler::FeedCleanupScheduler
  doorkeeper_cleanup_scheduler:
    cron: '1 1 * * 0'
    class: Scheduler::DoorkeeperCleanupScheduler
```

<details>
<summary>Stack trace generated with ActionDispatch::DebugLocks</summary>

```
Attaching to mastodon_sidekiq_1
[36msidekiq_1    |[0m Thread 0 [0x2ab701f71e34 sleep]  No lock (yielded share)
[36msidekiq_1    |[0m   Waiting in start_exclusive to "load"
[36msidekiq_1    |[0m   may be pre-empted for: "load"
[36msidekiq_1    |[0m   blocked by: 1
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:111:in `sleep'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:111:in `wait'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:111:in `wait'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:123:in `wait_while'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:219:in `wait_for'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:81:in `block (2 levels) in start_exclusive'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:80:in `block in start_exclusive'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:75:in `start_exclusive'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/concurrency/share_lock.rb:147:in `exclusive'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies/interlock.rb:11:in `loading'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:36:in `load_interlock'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:357:in `require_or_load'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:510:in `load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:202:in `const_missing'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:542:in `load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `block in load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:6:in `with_bootsnap_fallback'
[36msidekiq_1    |[0m /usr/local/bundle/gems/bootsnap-1.0.0/lib/bootsnap/load_path_cache/core_ext/active_support.rb:53:in `load_missing_constant'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:202:in `const_missing'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:101:in `filter_from_home?'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:16:in `filter?'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:59:in `block (2 levels) in merge_into_timeline'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:39:in `each'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activerecord-5.1.2/lib/active_record/relation/delegation.rb:39:in `each'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:58:in `block in merge_into_timeline'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2257:in `block in pipelined'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `block in synchronize'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:2254:in `pipelined'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:57:in `merge_into_timeline'
[36msidekiq_1    |[0m /mastodon/app/workers/merge_worker.rb:9:in `perform'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:199:in `execute_job'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:169:in `block in process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_retry.rb:97:in `local'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/rails.rb:42:in `block in call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/rails.rb:41:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:215:in `stats'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_logger.rb:7:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_retry.rb:72:in `global'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:129:in `block in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/logging.rb:44:in `with_context'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:128:in `dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:168:in `process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:85:in `process_one'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:73:in `run'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/util.rb:16:in `watchdog'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m ---
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m Thread 1 [0x2ab701f71d30 sleep]  Sharing
[36msidekiq_1    |[0m   blocking: 0
[36msidekiq_1    |[0m 
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:187:in `lock'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:187:in `mon_enter'
[36msidekiq_1    |[0m /usr/local/lib/ruby/2.4.0/monitor.rb:212:in `mon_synchronize'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:58:in `synchronize'
[36msidekiq_1    |[0m /usr/local/bundle/gems/redis-3.3.3/lib/redis.rb:1474:in `zcard'
[36msidekiq_1    |[0m /mastodon/app/lib/feed_manager.rb:52:in `merge_into_timeline'
[36msidekiq_1    |[0m /mastodon/app/workers/merge_worker.rb:9:in `perform'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:199:in `execute_job'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-unique-jobs-5.0.8/lib/sidekiq_unique_jobs/server/middleware.rb:17:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/middleware/chain.rb:133:in `invoke'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:169:in `block in process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:141:in `block (6 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_retry.rb:97:in `local'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:140:in `block (5 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/rails.rb:42:in `block in call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/reloader.rb:68:in `block in wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/execution_wrapper.rb:85:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/activesupport-5.1.2/lib/active_support/reloader.rb:67:in `wrap'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/rails.rb:41:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:136:in `block (4 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:215:in `stats'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:131:in `block (3 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_logger.rb:7:in `call'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:130:in `block (2 levels) in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/job_retry.rb:72:in `global'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:129:in `block in dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/logging.rb:44:in `with_context'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/logging.rb:38:in `with_job_hash_context'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:128:in `dispatch'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:168:in `process'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:85:in `process_one'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/processor.rb:73:in `run'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/util.rb:16:in `watchdog'
[36msidekiq_1    |[0m /usr/local/bundle/gems/sidekiq-5.0.2/lib/sidekiq/util.rb:25:in `block in safe_thread'
```
</details>

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by fjyaniez** [comment]
Hi @unarist, we are facing a similar problem. Do you have any news about this?

Thanks!
