### ISSUE TITLE
Syntax error wasm-edit/lib/apply.js

### ISSUE THREAD

**Issue by jeena** [mastodon/mastodon#9882]
### Expected behaviour

`RAILS_ENV=production bundle exec rails assets:precompile` runs without errors

### Actual behaviour

```
jeena@debian-512mThomasb-fra1-01:~/mastodon$ RAILS_ENV=production bundle exec rails assets:precompile
yarn install v1.13.0
[1/6] Validating package.json...
[2/6] Resolving packages...
success Already up-to-date.
Done in 1.95s.
Webpacker is installed 🎉 🍰
Using /home/jeena/mastodon/config/webpacker.yml file for setting up webpack paths
Compiling…
Compilation failed:
/home/jeena/mastodon/node_modules/@webassemblyjs/wasm-edit/lib/apply.js:252
    /**
    ^^^

SyntaxError: Invalid or unexpected token
    at NativeCompileCache._moduleCompile (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
    at Module._compile (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/jeena/mastodon/node_modules/@webassemblyjs/wasm-edit/lib/index.js:21:14)
    at Module._compile (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/jeena/mastodon/node_modules/webpack/lib/wasm/WebAssemblyGenerator.js:12:37)
    at Module._compile (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/jeena/mastodon/node_modules/webpack/lib/wasm/WebAssemblyModulesPlugin.js:9:30)
    at Module._compile (/home/jeena/mastodon/node_modules/v8-compile-cache/v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

```

### Steps to reproduce the problem

I was updating from 2.6.5 to 2.7.0 without docker. I was following the instructions on https://github.com/tootsuite/mastodon/releases/tag/v2.7.0 and once I got to the precompile assets, I got that error.

### Specifications

I have ruby 2.5.3 running and that is what I set .ruby_version to also, but this seems not to be connected because it's a node error.

**Comment by jeena** [comment]
jeena@debian-512mThomasb-fra1-01:~/mastodon$ node -v
v8.11.2

**Comment by jeena** [comment]
After an upgrade to v8.15.0 I still have the same problem.
